### ISSUE TITLE
/beacon/committees endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1197]
/beacon/committees

Get the shuffling for an epoch.

**Comment by rolfyone** [comment]
prysm: https://api.prylabs.net/#/BeaconChain/ListBeaconCommittees
lighthouse: https://lighthouse-book.sigmaprime.io/http_beacon.html#beaconcommittees
eth2-spec: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#get_beacon_committee (not quite the same)

similar but different to BeaconStateUtil.get_committee_count_at_slot (this just returns the count, we need the validator indicies.

 - New endpoint, new implementation (might be worth splitting out)
 - needs to be able to pass query parameters.
