### ISSUE TITLE
Make data directory configurable

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1216]
Currently, teku's data directory is created in the current working directory: https://github.com/PegaSysEng/artemis/blob/6bb628647bcfc1382d45018045f14a987f1ab33c/storage/src/main/java/tech/pegasys/artemis/storage/ChainStorageServer.java#L40

We should make the data directory location configurable, and probably put the actually db data in a subdirectory at <data-dir>/db

**Comment by ajsutton** [comment]
Note that this ties into an existing epic of work: https://pegasys1.atlassian.net/browse/BC-53 In particular, we should ensure that we record a clear version for the database format to make future migrations easier.  We don't need to maintain backwards compatibility for this change though.

**Comment by macfarla** [comment]
see ArtemisConfiguration
add a configuration item for data directory - Besu uses "--data-path"
move db into a subdirectory /db
need to add some tests

**Comment by rolfyone** [comment]
there's a bit of scope creep, but also its easier than thought in a way.

 - we don't actually have command line arguments to play with
 - we do need to write a database version file, and throw a runtime exception if the version doesn't match

i'm confident enough that its more of a 1 than a 3, so changed the estimate.
