### ISSUE TITLE
add a configuration option to be able to disable swagger-ui

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#1227]
As a DevOps engineer,
I want to be able to disable swagger-ui in Teku
So that there are less resources being consumed, and i have one less endpoint to secure.

**Comment by rolfyone** [comment]
add a configuration option, link it to adding the swagger-ui endpoint, but not the swagger-docs.

**Comment by rolfyone** [comment]
there wasn't a general consensus whether swagger-docs is needed, so i removed that too.
In config.toml
```
[beaconrestapi]
portNumber = 5051
enableSwagger = true
```
enableSwagger is true by default, but when set to false, swagger-ui, swagger-docs will no longer be exported, and will just be invalid routes.

**Comment by macfarla** [comment]
To demo:
edit this file:
`scripts/demo/node_0/config.toml`
`enableSwagger = false`
and run teku from there
`cd scripts/demo/node_0; bin/teku --config=config/config.toml`
