### ISSUE TITLE
POW module not recognized by project

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#123]
### Description
The POW module is not recognized by the project; thus BeaconChainService and PowchainService do not build due to an import error.

**Comment by jrhea** [comment]
@schroedingerscode what lines  did you comment out?

**Comment by schroedingerscode** [comment]
This was one of a handful of issues that I ported over manually from the repo firedrill, so the original comments weren't necessarily mine. That said, I believe this issue has been resolved. If one more person can confirm, we'll close this. @jrhea @akhila-raju @dangerousfood

**Comment by jrhea** [comment]
This issue is resolved
