### ISSUE TITLE
/beacon/state_root endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1257]
Add a /beacon/state_root endpoint

Returns the state root for the given slot in the canonical chain. If there is a re-org, the same slot may return a different root.

Lighthouse: https://lighthouse-book.sigmaprime.io/http_beacon.html#beaconstate_root

**Comment by rolfyone** [comment]
- query by slot
 - canonical chain
 - get the block and return the state_root
