### ISSUE TITLE
Bump web3j Version to 4.1.0

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#127]
### Description
Bump web3j version from 3.6.0 to 4.1.0 to resolve transitive dependency licensing issue.

### Acceptance Criteria
 - Web3j version should be increased to 4.1.0 and all regression scenarios continue to function
 - Web3j v4.1.0 should pull transitive dependency jnr-posix v3.0.47, which is tri-licensed under LGPL, GPL2, and EPL2.
 - gradle task checkLicenses should not contain any errors

### Versions
This will happen on all versions until jnr-posix v3.0.47 is pulled by changing web3j to v4.1.0

### Additional Information
Gradle Check License Plugin (hierynomus/license-gradle-plugin) does not gracefully handle maven artifacts licensed under more than one license, so for projects which fall under this scenario, unless ALL licenses are in the acceptedLicenses list, the developer must explicitly declare which license the dependency is being used under. This is done using either the fully qualified group, id, AND version, or using the group only. Neither of these solutions are ideal, because:
   - many different projects under different licenses share the same group name
   - maintainability becomes a factor having to bump the transitive dependency version number every time the direct dependency bumps their own internal dependency.
    
The lesser of 2 evils at the moment is the second option, however I have suggested that the plugin supports filtering by groupId and artifactId at https://github.com/hierynomus/license-gradle-plugin/issues/168.

**Comment by schroedingerscode** [comment]
@dangerousfood This might be best left for you given your recent experience generating the Java types.

**Comment by schroedingerscode** [comment]
Bumping for awareness. @dangerousfood - could you regen the autogenerated Java contract classes with web3j 4.1 pls?

**Comment by jrhea** [comment]
closed by #344
