### ISSUE TITLE
Support for keystore cipher function aes-gcm

### ISSUE THREAD

**Issue by usmansaleem** [Consensys-Incorporated/teku#1271]
### Description
As an teku administrator, 
I want validator encrypted keystore to support aes-gcm cipher function 
so that stronger encryption can be applied on BLS Keys. 

### Acceptance Criteria
* Ability to read and write keystores with aes-gcm cipher function parameters
* related unit test cases

### Additional Information
Following is the section from keystore where support for aes-gcm should be provided:
~~~
"cipher": {
      "function": "aes-128-ctr",
      "params": {
        "iv": "264daa3f303d7259501c93d997d84fe6"
      },
      "message": "a9249e0ca7315836356e4c7440361ff22b9fe71e2e2ed34fc1eb03976924ed48"
    }
~~~
The `aes-gcm` takes additional parameter SALT. Also, the size of iv is not limited to 16 as in ctr (iv size >= 96 with tag size 128)

The key sizes are AES 128/192/256 ... so it might make sense to provide `aes-128-gcm`, `aes-192-gcm` cipher functions and apply `kdf.dklen` restrictions. 

As per the EIP-2335 spec, the dklen should be the double of the AES key size. AES-128 -> 128/8 -> 16
Hence 16+16 = 32 should be the size of dklen.

Similarly, if AES-192 is specified, the dklen must be 24 + 24 = 48

References:
- https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2335.md
- https://github.com/Quicksign/kafka-encryption/blob/master/samples/kafkastream-with-keyrepo-sample/src/main/java/io/quicksign/kafka/crypto/samples/stream/keyrepo/AesGcmNoPaddingCryptoAlgorithm.java#L75

**Comment by usmansaleem** [comment]
The key sizes are AES-128/192/256 ... so it might make sense to provide `aes-128-gcm` so on so forth and dklen restrictions.

**Comment by arash009** [comment]
Closing this for now until a specific requirement for `aes-128-gcm` is raised
