### ISSUE TITLE
GET /validator/block endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1355]
GET /validator/block endpoint
Produce a new block, without a signature.

Lighthouse: https://lighthouse-book.sigmaprime.io/http_validator.html#validatorblock
Prysm: https://api.prylabs.net/#/BeaconNodeValidator/GetBlock

**Comment by rolfyone** [comment]
talk to Centaur about whether creation of an unsigned block is possible at the moment.

**Comment by rolfyone** [comment]
From Adrian:

> BlockProposalUtil is basically what you’re looking for - just need to extract a method from createNewBlock that returns before the last couple of lines (then work out the randao issue).
> The randao reveal is just the epoch number signed by the block producer.  So the beacon chain client can’t know it because it requires the validator private key. 

the request information includes randao_reveal, and slot the block is for.
The root state is from the requested slot -1 (ie. the slot before the one requested)
