### ISSUE TITLE
Initial Slot Processing Logic

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#136]
### Description
Implement the slot processing logic as described in this section of the [beacon chain spec](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#per-slot-processing)

> Note: Not all the logic in the spec is finalized.  Follow Danny Ryan's recommendation by implementing the logic that is well defined.  See pseudo code below.

***pseudo code:***
```
# per-slot processing
state.slot += 1
update_proposer_randao_skips(state)
update_recent_block_hashes(state)
```

### Acceptance Criteria
* Add the logic to the slotProcessor method in StateTransition.java - see [here](https://github.com/PegaSysEng/artemis/blob/bdae8d870851d15f8a7f46c2ff4a67741398aab7/artemis/src/main/java/tech/pegasys/artemis/services/beaconchain/StateTransition.java#L51)
* Add appropriate tests

**Comment by jrhea** [comment]
~Blocked by #145~

**Comment by jrhea** [comment]
@cemozerr you are working this issue, correct?

**Comment by cemozerr** [comment]
Yep!
