### ISSUE TITLE
Use an external signing service to sign blocks and attestations

### ISSUE THREAD

**Issue by jframe** [Consensys-Incorporated/teku#1382]
### Description
As a Teku administrator, I want to use an external signing service so that my validator keys can be kept secure. 

### Acceptance Criteria
* CLI options for the signing service url, the public keys of the validator keys that will be used for signing with the external service
* Sign blocks and attestations for the validator keys configured to use external signing

### Additional Information
Eth2Signer is an example of an external signing service and has the following API:

POST
/signer/block
{"publicKey": <HEXVALUE>, "signingRoot": <HEXVALUE\>}

/signer/attestation
{"publicKey": <HEXVALUE>, "signingRoot": <HEXVALUE\>}

/signer/randao_reveal
{"publicKey": <HEXVALUE>, "signingRoot": <HEXVALUE\>}

And an example of the request body:
{"publicKey":"0x989d34725a2bfc3f15105f3f5fc8741f436c25ee1ee4f948e425d6bcb8c56bce6e06c269635b7e985a7ffa639e2409bf","signingRoot":"0x48656c6c6f2c20776f726c6421"}

**Comment by arash009** [comment]
> the public keys of the validator keys that will be used for signing with the external service

To clarify, why would you need to specify the public keys. Wouldnt the assumption be that any keys you have are stored in the signer and therefore go there for ANY key?

**Comment by jframe** [comment]
Teku needs to know what validator keys it is acting as validator for so that when it receives a block it can check to see if it is the proposer and create the block if necessary and use Eth2Signer. Similarly for attestations.
Also maybe we don't want all the validator keys to be in Eth2Signer?
