### ISSUE TITLE
Update Teku default storage directory

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1411]
As a user of Teku, 
I want the storage directory to default to a known location depending on my OS that I'm using, 
so that I can find it easily and allows it to be stored separately to where the client is, and can be upgraded easily.

- Typical application default storage directories to be used for OSX (~/Library/Teku), Windows (~/AppData/Teku), Linux

**Comment by rolfyone** [comment]
@arash009 can we have more context on this?

**Comment by rolfyone** [comment]
@arash009 waiting for context, added by blocked by research flag.

**Comment by rolfyone** [comment]
Update ArtemisConfiguration class to default storage based on operating system.
Unix/Linux - `~/.teku`
Mac - `~/Library/teku`
Windows - `%localappdata%/teku`

Once the defaults are in place, the config file should be updated to remove the default storage path.

**Comment by rolfyone** [comment]
In each case, we end up with a 'data' and a 'logs' folder under the top level teku folder.  The location of that teku folder changes depending on operating system.
_WINDOWS_
`%LOCALAPPDATA%/teku`
_MAC_
`~/Library/teku`
_XDG_DATA_PATH defined_
`$XDG_DATA_PATH/teku`
_Otherwise_
`~/.local/share/teku`
