### ISSUE TITLE
Store ETH1 deposit event

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1412]
As a user of Teku, 
I want the ETH1 deposit events to be written to disk, 
so that I can reload from disk instead of reprocessing it every time Teku starts, as it is more efficient.

- Write the Merkle Tree and latest block processed number to disk

**Comment by rolfyone** [comment]
> Adrian Sutton:flag-au:  8:36 AM
> We pull all the deposit events from the eth1 chain and they are gradually fed into the state, but as we process them we have to build up the merkle tree for them so we can provide the deposit count and deposit root when creating new blocks.
> 8:37
> Right now, everytime we startup we have to scan the entire eth1 chain for deposit events to reconstruct that merkle tree again.
> 
> Paul Harris:flag-au:  8:37 AM
> ah wow ok
> 
> Adrian Sutton:flag-au:  8:37 AM
> We want to store deposits in a way that makes rebuilding that merkle tree efficient on startup even as the number of deposits becomes extremely large.  That may mean storing the whole merkle tree.
> Paul Harris:flag-au:  8:38 AM
> and keeping it separate from the state...
> 8:38
> so how would it be accessed? is that a silly question?
> 8:38
> like can you access it at slot X or is that not a concept?
> 
> Adrian Sutton:flag-au:  8:38 AM
> No you’d literally be loading the whole thing at startup.
> 
> Paul Harris:flag-au:  8:39 AM
> but at a given point in time i cant effectively rewind, its just 'current' state
> 
> Adrian Sutton:flag-au:  8:39 AM
> So I think what you need to store is the merkle tree in some form, the list of deposits not yet included in finalized state and the eth1 block number that we have already retrieved deposits up to.
> 8:40
> Correct you can’t go backwards but you never need to.
> 
> Paul Harris:flag-au:  8:40 AM
> ok cool, and we've got the merkle tree now in memory?
> 
> Adrian Sutton:flag-au:  8:40 AM
> Well, that’s not entirely true.  Our merkle tree implementation is capable of calculating the root and proofs as if only a certain number of deposits are in the tree (so if we need to verify the root at deposit 100, but we already have up to deposit 200, we can do that efficiently).
> 8:41
> Yes, MerkleTree is the class that holds them.
> 8:42
> DepositProvider I think is the class you’d want to be able to store and re-hydrate.  It has the deposit merkle tree and the deposits which haven’t yet been included in a finalized state.
> 
> Adrian Sutton:flag-au:  8:44 AM
> We may also need to store and re-hydrate Eth1DataCache - it can rebuild itself from the eth1 chain fairly efficiently now but I think it requires more state history than most nodes store so may need to be reworked.
> 8:45
> I would probably ignore Eth1DataCache for now and get DepositProvider sorted then we can work it out.  Cem is the most knowledgable person in this area.

**Comment by rolfyone** [comment]
need to condense comment.

**Comment by rolfyone** [comment]
- currently, every time teku starts, the entire eth1 chain is scanned for deposit events, to reconstruct the merkle tree
- DepositProvider should be stored and re-hyrdated, it has the tree, and deposits which haven't been included in a finalized state
- May also need to store and re-hydrate Eth1DataCache, it can rebuild itself from eth1 chain fairly efficiently, but probably currently requires more state history than most nodes will be storing, so may require rework.
- Cem is the most knowledgable in this area (potentially eth1DataCache specifically, unsure)
