### ISSUE TITLE
/beacon endpoints unresponsive on AWS

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#1430]
As I was running Teku on AWS, trying to sync to Lighthouse Testnet 5, I noticed that /network endpoints worked perfectly, however, I did not get any responses from the /beacon endpoints. However, when I run locally, both endpoints work. The 

Node's public IP:
http://ec2-18-209-46-236.compute-1.amazonaws.com/

Rest API port number: 
5051

Here are the inbound rules for the instance's security group on AWS:
![Screen Shot 2020-03-20 at 5 44 13 PM](https://user-images.githubusercontent.com/16581242/77208607-9133f800-6ad2-11ea-9340-255b23e2b184.png)

**Comment by macfarla** [comment]
run up AWS instance to test this - talk to Yeti

**Comment by macfarla** [comment]
waiting on https://github.com/PegaSysEng/systems-tools/pull/52

**Comment by macfarla** [comment]
[][ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/network/peers
[][ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/network/peer_count
0[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/chainhead
{"head_slot":9824,"head_epoch":1228,"head_block_root":"0x3cfbe7e5041afef01eba9730980c4600268badd60b7ffb1f278321a84cd2d42d","finalized_slot":9816,"finalized_epoch":1227,"finalized_block_root":"0xda687f190baf14f32497186cbcdeafaabc71c055b5799ac22eaf255da0d6985d","justified_slot":9824,"justified_epoch":1228,"justified_block_root":"0x3cfbe7e5041afef01eba9730980c4600268badd60b7ffb1f278321a84cd2d42d","previous_justified_slot":9816,"previous_justified_epoch":1227,"previous_justified_block_root":"0xda687f190baf14f32497186cbcdeafaabc71c055b5799ac22eaf255da0d6985d"}[ec2-user@ip-192-168-25-174 ~]$

**Comment by macfarla** [comment]
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=2
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=5
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=99
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=1228
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=1229
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=1230
[ec2-user@ip-192-168-25-174 ~]$ curl http://localhost:5051/beacon/committees?epoch=1232
[{"slot":9848,"index":0,"committee":[32,5,22,7]},{"slot":9848,"index":1,"committee":[38,9,37,49]},{"slot":9849,"index":0,"committee":[0,18,21,20]},{"slot":9849,"index":1,"committee":[51,45,1,57]},{"slot":9850,"index":0,"committee":[36,39,13,15]},{"slot":9850,"index":1,"committee":[2,14,35,41]},{"slot":9851,"index":0,"committee":[27,40,42,24]},{"slot":9851,"index":1,"committee":[56,8,43,29]},{"slot":9852,"index":0,"committee":[26,34,30,28]},{"slot":9852,"index":1,"committee":[58,25,54,3]},{"slot":9853,"index":0,"committee":[62,16,10,52]},{"slot":9853,"index":1,"committee":[53,11,19,63]},{"slot":9854,"index":0,"committee":[59,44,60,33]},{"slot":9854,"index":1,"committee":[4,12,6,50]},{"slot":9855,"index":0,"committee":[61,46,55,31]},{"slot":9855,"index":1,"committee":[47,17,48,23]}][ec2-user@ip-192-168-25-174 ~]$

**Comment by macfarla** [comment]
get no response from some queries eg the committees for past slots - this is expected behaviour but may be confusing

**Comment by macfarla** [comment]
[ec2-user@ip-192-168-25-174 ~]$ curl -i  http://localhost:5051/beacon/committees?epoch=1228
HTTP/1.1 410 Gone
Date: Wed, 01 Apr 2020 23:43:09 GMT
Server: Javalin
Content-Type: application/json
Cache-Control: max-age=31556952
Content-Length: 0

[ec2-user@ip-192-168-25-174 ~]$ curl -i  http://localhost:5051/beacon/committees?epoch=1928
HTTP/1.1 404 Not Found
Date: Wed, 01 Apr 2020 23:43:19 GMT
Server: Javalin
Content-Type: application/json
Cache-Control: max-age=0
Content-Length: 0

[ec2-user@ip-192-168-25-174 ~]$

**Comment by macfarla** [comment]
Hi Cem,

Couple of questions 
- when you say you got "no response" do you mean that it returned quickly with nothing, or did it hang and not respond?
- did you by any chance use `curl -i` to get the status code which can be 404 not found (future slots) or 401 gone (past slots) when there is no content returned

There is also an issue with the way the REST APIs get committees which we are fixing as we speak - needs to get effective slot #1473

**Comment by cemozerr** [comment]
I was accessing the API's through my browser, and when I make the request:

`http://ec2-3-81-229-71.compute-1.amazonaws.com:5051/network/peer_count`

it would immediately return the peer count, however, it would not return anything when I made the call:

`http://ec2-3-81-229-71.compute-1.amazonaws.com:5051/beacon/head`

However, it seems like the issue has been resolved because when I ran again with the new updates today, I was unable to reproduce it. So closing this issue.
