### ISSUE TITLE
Logging config overriding custom config file

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1481]
### Description
When running Teku with a custom Log4J config file, the internal logging configuration is still running and causing additional log output.

Specifically I wind up with:
```
2020-03-26 13:22:49.468+10:00 | TimeTickChannel-1 | INFO  | teku-event-log | ******* Slot Event *******
13:22:49.468 [INFO ] - Node slot:                             97
2020-03-26 13:22:49.468+10:00 | TimeTickChannel-1 | INFO  | teku-event-log | Node slot:                             97
13:22:49.469 [INFO ] - Head block slot:                       97
2020-03-26 13:22:49.469+10:00 | TimeTickChannel-1 | INFO  | teku-event-log | Head block slot:                       97
13:22:49.469 [INFO ] - Justified epoch:                       11
2020-03-26 13:22:49.469+10:00 | TimeTickChannel-1 | INFO  | teku-event-log | Justified epoch:                       11
13:22:49.469 [INFO ] - Finalized epoch:                       10
2020-03-26 13:22:49.469+10:00 | TimeTickChannel-1 | INFO  | teku-event-log | Finalized epoch:                       10
```

when using the logging config:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="DEBUG" monitorInterval="5">
    <Appenders>
        <Console name="console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg%n" />
        </Console>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="console"/>
        </Root>
    </Loggers>
</Configuration>
```

There are no logging options specified in the config file so Teku should not be adjusting the logging config.

**Comment by CjHare** [comment]
The default value for logging is actually `both`, meaning console output and log file output for the `STATUS_LOG` and `EVENT_LOG` but only log file output for everything else.

The configuration is added to programmatically during the Teku startup.

**Comment by ajsutton** [comment]
We ultimately need it to be like Besu - if you don't specifically set any logging options, it won't override your custom logging.  If you also don't have a custom logging setup the defaulting to the "both" mode makes sense.  That's pretty simple to achieve with the XML-based config since it gets replaced by any custom logging config, but programmatically augmenting the config makes it more challenging.  Not really sure what can be done - the simplest option would be that if the `log4j.configurationFile` system property is set, don't change any logging properties.  Hopefully there's a better way of doing it though as Log4J has a few places it looks for custom logging configs and we'd ideally want to pick up them all (or at least the most common ones).

**Comment by CjHare** [comment]
> if you don't specifically set any logging options, it won't override your custom logging.

Sounds like decent requirements.

Alright, I'll take a look at the various System/Environment config options Log4j allows users to set custom logging and figure out whether there is custom logging and not apply the default programmatic logging when there is custom logging.

**Comment by CjHare** [comment]
Fun fact about Log4j custom config files, it supports two different variables (one legacy, one newish) , which can be either System or Environment variables, meaning to tell if a custom config was used the code looks like this:
```
  private static final String LOG4J_ENVIRONMENTAL_CONFIG_FILE_KEY = "LOG4J_CONFIGURATION_FILE";
  private static final String LOG4J_ENVIRONMENTAL_LEGACY_CONFIG_FILE_KEY = "log4j.configurationFile";

  private static boolean isProgrammaticLoggingNeeded() {
    return System.getenv(LOG4J_ENVIRONMENTAL_LEGACY_CONFIG_FILE_KEY) == null
        && System.getenv(LOG4J_ENVIRONMENTAL_CONFIG_FILE_KEY) == null
        && System.getProperty(LOG4J_ENVIRONMENTAL_LEGACY_CONFIG_FILE_KEY) == null
        && System.getProperty(LOG4J_ENVIRONMENTAL_CONFIG_FILE_KEY) == null
  }
```

Think I'm going to embrace having the destination as an optional in the Teku config and use that as a semaphore for whether the user wants the programmatic logging.

**Comment by CjHare** [comment]
Issue addressed by https://github.com/PegaSysEng/teku/pull/1502

**Comment by CjHare** [comment]
@ajsutton do you still experience this issue with the head of the master branch or have the various commits resolved the issue?

**Comment by ajsutton** [comment]
Yes this is working for me now.

**Comment by CjHare** [comment]
Awesome, in that case I'll close off this issue
