### ISSUE TITLE
Adhere to Java Naming Conventions

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#1575]
### Description
As an implementor, I want namings in Teku to conform to Java Naming Conventions, so that the code is more legible and cohesive. Here are Java naming conventions: https://www.geeksforgeeks.org/java-naming-conventions/

**Comment by stringray55** [comment]
hey @cemozerr  is this issue still open, would like to pick this.

**Comment by ajsutton** [comment]
@stingray55 This is still relevant, though many of the places it's an issue are being fixed as they move into the `spec` module. I'd ignore anything that's already marked as `@Deprecated` as it will have a new version that should be named correctly already and the old version will be removed as we migrate the code anyway.

But there are a bunch of methods in places like `BeaconState` which are still an issue and would be great to fix.

My suggestion would be to put up a number of small PRs to minimise the number of conflicts - so a PR that renamed the methods in `BeaconState` would be a great start, then look for another class to fix up and so on.  The smaller the PRs the quicker we can review and merge them and the less likely we'll have a difficult merge to deal with.

**Comment by seroze** [comment]
@ajsutton  is this task still open. 

as I see in `BeaconState` abstract class the method names are adhering to Java naming conventions, but the variables are not, should i format those instance variables ? 

```java

public abstract class BeaconState implements State {
  @Schema(type = "string", format = "uint64")
  public final UInt64 genesis_time;

  public final Bytes32 genesis_validators_root;

  @Schema(type = "string", format = "uint64")
  public final UInt64 slot;

  public final Fork fork;
  public final BeaconBlockHeader latest_block_header;

  @ArraySchema(
      schema = @Schema(type = "string", format = "byte", description = DESCRIPTION_BYTES32))
  public final List<Bytes32> block_roots;

  @ArraySchema(
      schema = @Schema(type = "string", format = "byte", description = DESCRIPTION_BYTES32))
  public final List<Bytes32> state_roots;

  @ArraySchema(
      schema = @Schema(type = "string", format = "byte", description = DESCRIPTION_BYTES32))
  public final List<Bytes32> historical_roots;

  public final Eth1Data eth1_data;
  public final List<Eth1Data> eth1_data_votes;

  @Schema(type = "string", format = "uint64")
  public final UInt64 eth1_deposit_index;

  public final List<Validator> validators;

  @ArraySchema(schema = @Schema(type = "string", format = "uint64"))
  public final List<UInt64> balances;

  @ArraySchema(
      schema = @Schema(type = "string", format = "byte", description = DESCRIPTION_BYTES32))
  public final List<Bytes32> randao_mixes;

  @ArraySchema(schema = @Schema(type = "string", format = "uint64"))
  public final List<UInt64> slashings;

  @Schema(type = "string", format = "byte", description = DESCRIPTION_BYTES_SSZ)
  public final SszBitvector justification_bits;

  public final Checkpoint previous_justified_checkpoint;
  public final Checkpoint current_justified_checkpoint;
  public final Checkpoint finalized_checkpoint;
  
  ```
  
  for eg: I will change the `latest_block_header` variable name to `latestBlockHeader`

**Comment by ajsutton** [comment]
@seroze Yes we've made some progress on it but there's still a bunch of places we're using snake case in various classes (`Attestation` has a few too I think).  The `BeaconState` class you're looking at there is actually part of the REST API definition. We can probably leave those as-is - if we renamed them we'd have to use an annotation to tell the JSON serialiser to use the snake-case version so we don't break the API.  There's a separate `BeaconState` interface in the spec module which is the internal representation and its the internal names we're most keen to fix up.

**Comment by seroze** [comment]
@ajsutton  i have a raised a PR for Attestation class, will refactor more classes once we identify them. (is there an automatic way to identify them)

one dumb doubt. why is spotlessJava plugin not complaining about the use of snake case for method names.
