### ISSUE TITLE
Multiple `Hash` Classes Causes Confusion

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#161]
### Description
Artemis currently implements 2 `Hash.java` classes: `tech.pegasys.artemis.crypto.Hash`, and `tech.pegasys.artemis.ethereum.core.Hash`, the former of which is only used for static access to the `keccak256` method by 2 classes, one of which is `tech.pegasys.artemis.ethereum.core.Hash`. This adds a confusing dependency, and it seemingly makes more sense to just move the keccak256 logic into `tech.pegasys.artemis.ethereum.core.Hash`.

### Acceptance Criteria
*  The confusing naming should be resolved, or analysis should be done and consensus reached on why both are necessary.

**Comment by atoulme** [comment]
Fixed with #207
