### ISSUE TITLE
--rest-api-enabled shouldn't require an argument

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1616]
### Description
The `--rest-api-enabled` CLI value should be optional.  So `--rest-api-enabled` means the same as `--rest-api-enabled=true`.  Currently `--rest-api-enabled` results in an error.

**Comment by rolfyone** [comment]
```
--rest-api-docs-enabled
--rest-api-enabled
--Xinterop-enabled (hidden)
--metrics-enabled
--p2p-enabled
--p2p-discovery-enabled
```
all the above can now be specified and fallback to true if no value is specified
