### ISSUE TITLE
log destination CLI option - use enum

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1641]
Use enum for the allowable values and add them to the help output

**Comment by rolfyone** [comment]
now, when you specify an invalid value:

```
Invalid value for option '--log-destination': expected one of [BOTH, CONSOLE, DEFAULT_BOTH, FILE] (case-insensitive) but was 'booth'
```

usage:
```
      --log-destination=<LOG_DESTINATION>
                             Whether a logger is added for the console, the log
                               file, or both (Valid values: BOTH, CONSOLE,
                               DEFAULT_BOTH, FILE)
                               Default: DEFAULT_BOTH
```

**Comment by ajsutton** [comment]
One option is to simply ignore the --log-destination regardless of it's value if a custom log4j config is detected.  That may well be less confusing than having a weird mix of your custom log4j and Teku programatically changing stuff on you.
