### ISSUE TITLE
Display a shorter version of help by default

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#1651]
Currently we get the long version of help by default. Can we display a short version, including how to display the full version, along with any error messages

**Comment by ajsutton** [comment]
I believe @jakehaugen was doing up a spec on how to report errors well and one of the elements of it was ommitting the help entirely for a lot of cases since it's not useful and obscures what the problem is.

**Comment by macfarla** [comment]
Yep that's where this idea came from - https://docs.google.com/document/d/1T4C6r28mw2aeNp4580_HQRLaulkMpWx4RXgjc7VqMJg/edit#heading=h.4uzb11dl2edw

#1655 makes any error messages come after the help not before so they won't be obscured.
