### ISSUE TITLE
Fix intermittently failing tests

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#1658]
### Description
Integration test: shouldFetchUnknownAncestorsOfPropagatedBlock() and the acceptance test: shouldCreateTheSameGenesisState() fails intermittently, making it hard to understand if the problem is related to the current PR or something we've had previously.

**Comment by Nashatyrev** [comment]
May be related to https://github.com/libp2p/jvm-libp2p/issues/94

**Comment by Nashatyrev** [comment]
This issue is distinct from https://github.com/libp2p/jvm-libp2p/issues/94
