### ISSUE TITLE
Many Utils and DataStructures in Artemis Sub-Module Use snake_case

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#166]
### Description
Many classes in `tech.pegasys.artemis.datastructures` and `tech.pegasys.artemis.state` use `snake_case` for method and field naming as opposed to `camelCase`.

**Expected behavior:** . 
Code should follow `camelCase` naming conventions per https://google.github.io/styleguide/javaguide.html#s5-naming.

**Actual behavior:** . 
Many methods and fields use `snake_case` for naming.

**Comment by schroedingerscode** [comment]
This _should_ be addressed by #163.

**Comment by schroedingerscode** [comment]
Looks like google-java-format draws the line at actually renaming methods, so this was not automatically fixed by spotless and will have be addressed manually.

This would be a good issue for someone to pick up as an excuse to familiarize themselves with the code.

**Update:** It has been decided that this issue should not be worked while naming changes are occurring in the spec. snake_case makes it easy to search and replace spec related name changes during this time.

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue? I see there's a "won't fix" label.

**Comment by schroedingerscode** [comment]
I don't really care enough either way to leave this open. In fact snake_case, however unnatural, is a good way to distinguish between our helpers and spec methods.
