### ISSUE TITLE
[feature] teku `pretty` print subcommand

### ISSUE THREAD

**Issue by pventuzelo** [Consensys-Incorporated/teku#1714]
### Description

In (under development) new beacon-fuzz tooling, we are using client tools like `zcli`, `lcli`, `ncli`, ... and we compared the result/return value between all tools.

I would to have a `teku` subcommand to preform `pretty` print on most common type, like those ones:
- Attestation
- BeaconBlock
- BlockHeader
- Deposit
- ProposerSlashing
- SignedBeaconBlock
- SignedBlockHeader
- SignedVoluntaryExit
- BeaconState
- VoluntaryExit

That will allow us to have an easy way to test SSZ decoding and parsing between `teku` and other clients. We consider `zcli` as the reference spectest tool.

**Comment by ajsutton** [comment]
Is the aim here to actually have the pretty output that you're then parsing to determine if the parsed result matches or just to see if we consider the input valid or not?

**Comment by pventuzelo** [comment]
Both ;) but main goal is to compared parsing result since output will be a JSON.
