### ISSUE TITLE
Teku REST API reference documentation linked in the README is 404ing

### ISSUE THREAD

**Issue by skmgoldin** [Consensys-Incorporated/teku#1723]
The Teku REST API reference documentation linked in the README is 404ing.

https://pegasyseng.github.io/teku/latest/

**Comment by skmgoldin** [comment]
assigned to @cemozerr 

🤠

**Comment by ajsutton** [comment]
https://pegasyseng.github.io/teku/#latest appears to be the new URL.  @NicolasMassart can you confirm what the URL should be? It would be great if we could keep it stable to support the API standardisation work.

**Comment by NicolasMassart** [comment]
Yes it is except that you can even omit the #latest part as it's the default.
I obviously did a non efficient search when looked at the places where this url was used.
It should remain stable now. The generated specs are available also directly in the root folder in the form `https://pegasyseng.github.io/teku/{version}.json` (example: https://pegasyseng.github.io/teku/latest.json )
