### ISSUE TITLE
Enforce hosts whitelist on REST API

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1738]
### Description
To mitigate DNS rebinding attacks, the REST API should validate the `Host` header matches one of the whitelisted hostnames.

This should be similar to the Besu `--host-whitelist`: https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/API/#host-whitelist although I don't believe we need to support the special "all" or "none" magic values `--rest-api-host-whitelist=` would be the equivalent of "none" and just use `*` as the only value for `all`.

**Comment by bgravenorst** [comment]
This documentation is now available here:
https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#rest-api-host-whitelist

**Comment by Magicking** [comment]
Posting here as a minor request but supporting netmask as well such as 192.168.42.0/24 could be useful.
