### ISSUE TITLE
Specify units for `--validators-external-signer-timeout` option

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#1747]
### Description
As a user, I want the units for `--validators-external-signer-timeout` to be shown when I do `--help` so that I know what number to put there. 

The default is 1000, and I assume it means milliseconds, but who knows `¯\_(ツ)_/¯`

### Acceptance Criteria
* Correct units are shown for `--validators-external-signer-timeout` when I do `teku --help`.

### Versions (Add all that apply)
* Software version: [`teku --version`]
  - teku/v0.11.0-dev-3949f7e2/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

**Comment by macfarla** [comment]
milliseconds as per https://github.com/PegaSysEng/teku/blob/e60fa13f61ccab5923a22cde79e57e557ab95803/validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/ValidatorLoader.java#L72

**Comment by bgravenorst** [comment]
Documentation is already up to date. See:
https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#validators-external-signer-timeout
