### ISSUE TITLE
Ability to set Graffiti per validator

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#1750]
As a validator, I want to be able to set the `graffiti` field in blocks that I propose. 

The graffiti field is an optional feature allowing validators to set arbitrary data in block proposals. Teku currently has it [hardcoded to all zeros](https://github.com/PegaSysEng/teku/blob/81deceb0070d240768fe3a43fa833fbb3604e9e2/ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/blocks/BeaconBlockBody.java#L75).

It would be a nice feature to be able to set this per validator from the command line on start up. A stretch goal would be to allow this to be changed via the API in a running validator.

As a very minimum it should default to the current version of Teku if not set by the user.

**Comment by ajsutton** [comment]
Now defaults to the Teku version but is not yet user configurable.

**Comment by macfarla** [comment]
Nothing in the standard API at the moment that allows you to set the graffiti. 

Need to do some investigation, split into separate tickets, and also need to follow the design for #2003

eg directory containing:
graffiti_<short_key>

**Comment by ajsutton** [comment]
We should consider if it's worth the complexity of setting graffiti per validator or just using one graffiti for all validators.  Worth looking at Prysm's options for this as they're the only client that currently supports custom graffiti.

**Comment by rolfyone** [comment]
At some stage it'd be ideal to be able to set per validator, but after talking with Ben, he's happy to have graffiti passed in via command line or config file.

In Prysm it takes any string, so our command line should probably take any string data, and convert that to byte data for the graffiti.

We will accept a UTF-8 string, and byte encode it to produce the graffiti.

concrete example:
`teku --graffiti="The quick brown fox"`

failure example (too long):
`teku --graffiti="The quick brown fox jumps over the lazy dog"`

**Comment by bgravenorst** [comment]
Documented here:

https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#validators-graffiti
