### ISSUE TITLE
Provide a clear indication of which validators are being run

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1762]
### Description
So that I know I have configured the node correctly prior to my validator being scheduled to perform duties, print the list of validators being run in the validator client at startup.

If the number of validators is quite large, print the total number, not the full list.

**Comment by mark-terry** [comment]
Validator info = index + truncated pubkey.
Output to logs.
Always print number of validators.
Config item to specify whether to print list of validators.

**Comment by bgravenorst** [comment]
No documentation required since this is visible in the logs
