### ISSUE TITLE
OpenAPI documentation for some value types is inaccurate

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#1765]
### Description
The OpenAPI documentation for the `/beacon/head` endpoint displays the expected result format as:

```
{
  "slot": { },
  "block_root": {
    "zero": true,
    "empty": true
  },
  "state_root": {
    "zero": true,
    "empty": true
  }
}
```

We should make sure that `Bytes32`, `UnsignedLong` and other value types are displaying correctly.

**Comment by rolfyone** [comment]
The output above is basically what's shown in the 'Example value' tab of the response, but the schema tab has relatively good information, showing the types like 'UnsignedLong', 'Bytes32'.

Making code generators happy, all the output will basically say 'string' as the type, and there's no good way to add descriptive text, which will leave us with a gap to fill, basically documentation would need to fill in the missing portions.

For now, it's possible but does make things a little messy, and we're not sure how commonly used code generators are, and whether it's a big issue.

When we march towards a conforming API, presumably there will be reference spec's we can rely on, which will allow us to lose this information without much of a degradation over all, but for now we might hold off and see if there's much more feedback on needing code generators to work before we invest a lot of time...

**Comment by skmgoldin** [comment]
Is it possible to generate `format` properties for your types with the tooling you use?

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types

> to support documentation needs, the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification. 

For example, the additional type data in these docs are generated using `format` properties: https://redocly.github.io/redoc/?#operation/placeOrder

**Comment by rolfyone** [comment]
It's probably a good place to link a ticket from javalin - https://github.com/tipsy/javalin/issues/877#issuecomment-587328161

Basically all the Byte types, and UnsignedLong we'd need to wrap with an object, and make it look like what we want.  These are really fundamental types, and I think it's going to really obfuscate some of what we're doing, so it's concerning that it's the offered solution, especially when i can change a couple of object types in the swagger docs in about 5 minutes and get it all the way i want it to be ...
