### ISSUE TITLE
Validator keys option should give better error message

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1774]
When setting the following options:

- validators-key-file
- validators-key-password-files

I get a generic error message which doesn't tell me what the actual problem is. It would be good to know if the file cannot be found (wrong path), data is invalid (correct path but wrong keyfile or password) or something else.

Current response is:
`Invalid configuration. The size of validator.validatorsKeystoreFiles [0] and validator.validatorsKeystorePasswordFiles [1] must match`

**Comment by macfarla** [comment]
check options are specified together
validators-key-files (note plural) AND validators-key-password-files
then check lengths match
