### ISSUE TITLE
Null pointer exception when missing options

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1777]
You need both `validators-key-file` and `validators-key-password-files` specified.

If I only provide the key file and don't use the password file option I get a Null pointer error. I should receive a meaningful error telling me what's missing

_UPDATE_
The NPE is being caused by the YAML loader attempting to load incomplete keys, due to invalid validator key YAML files being supplied.  The NPE is not directly related to this specific CLI option combination. The loading / parsing code should be improved to provide better handling of this case.

**Comment by macfarla** [comment]
provide an error when you don't use validators-key-file properly.

NOT included: rename this option to be called "unencrypted" since it's confusing
