### ISSUE TITLE
Gradle version is incompatible with Java 14

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#1788]
### Description
As an developer, I want to build Teku with openjdk-14 so that I don't need to downgrade to 13.

### Acceptance Criteria
* Clean build with openjdk-14

### Steps to Reproduce (Bug)
Try to build with Java 14. 

On Ubuntu:

```
update-alternatives: using /usr/lib/jvm/java-14-openjdk-amd64/bin/java to provide /usr/bin/java (java) in manual mode
ben@metalalbert:~/teku$ ./gradlew installDist
Starting a Gradle Daemon (subsequent builds will be faster)
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
```

Advice from Danno is that updating to Gradle 6.3 or higher will fix this.

It seems to be more complex than simply updating the gradle version in `gradle/wrapper/gradle-wrapper.properties` - on one of my machines this works fine; on another it leads to a failure in errorprone (`Task :errorprone-checks:compileJava FAILED`) which does not occur under Java 13.

**Comment by usmansaleem** [comment]
Fixed by #1907
