### ISSUE TITLE
Mysterious response for input on POST `/beacon/validators`

### ISSUE THREAD

**Issue by skmgoldin** [Consensys-Incorporated/teku#1790]
This request:
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"epoch": "0", "pubkeys": ["0x1b66ac1fb663c9bc59509846d6ec05345bd908eda73e670af888da41af178bb2305b26a285fa2737f175668d0dff91cc"]}' localhost:5051/beacon/validators
```

Produces this response:
```
{"status":400,"message":"The serialized input does not have the C flag set. (through reference chain: tech.pegasys.teku.api.schema.ValidatorsRequest[\"pubkeys\"]->java.util.ArrayList[0])"}
```

Which is rather mysterious.

**Comment by rolfyone** [comment]
it looks like this is not a valid key because G1Point is raising an error about not having the 'c flag' set, but i think we need to wrap this message and report back that the public key supplied is not valid.

**Comment by skmgoldin** [comment]
You're right, that pubkey was no good. Using a different one works.

**Comment by macfarla** [comment]
error message should include key that was bad

**Comment by macfarla** [comment]
error message includes **index** of key that was bad
