### ISSUE TITLE
 java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by MDionSijan** [Consensys-Incorporated/teku#1792]
### Description
As a developer, I want to sync to Schlesi.

### Acceptance Criteria
*Sync to Schlesi without the exception

### Steps to Reproduce (Bug)
With docker image
1. Attempt to sync to Schlesi
2. Hit Out Of Memory error
3. Restart Teku
4. Hit exception

**Expected behavior:** 
No exception is thrown.

**Actual behavior:** 
`java.util.NoSuchElementException: No value present` exception is thrown.

**Frequency:**
Happened once.

### Versions (Add all that apply)
* Software version: `351b6c2c89b3`
* OS Name & Version: Windows 10, Docker w/ linux container
* Docker Version: [`19.03.8, build afacb8b`]

### Additional Information

Logged Exception

`
23:58:37.545 INFO  - Sync Event *** Current slot: 126593, Head slot: 19524, Connected peers: 6                          23:58:52.839 INFO  - Sync Event *** Current slot: 126594, Head slot: 19529, Connected peers: 6                          23:59:13.962 INFO  - Sync Event *** Current slot: 126595, Head slot: 19535, Connected peers: 6                          23:59:13.973 INFO  - Sync Event *** Current slot: 126596, Head slot: 19535, Connected peers: 7                          23:59:24.368 INFO  - Sync Event *** Current slot: 126597, Head slot: 19537, Connected peers: 8                          Exception in thread "Thread-14281" java.util.NoSuchElementException: No value present                                           at java.base/java.util.Optional.orElseThrow(Optional.java:382)                                                          at org.ethereum.beacon.discovery.storage.NodeTableImpl$ClosestNodeIterator.loadNextBatch(NodeTableImpl.java:186)        at org.ethereum.beacon.discovery.storage.NodeTableImpl$ClosestNodeIterator.hasNext(NodeTableImpl.java:145)              at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)                              at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)                           at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)                            at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)                                      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)                               at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)                              at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)                        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                      at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)                                     at org.ethereum.beacon.discovery.task.RecursiveLookupTask.sendRequests(RecursiveLookupTask.java:60)                     at org.ethereum.beacon.discovery.task.RecursiveLookupTask.execute(RecursiveLookupTask.java:42)                          at org.ethereum.beacon.discovery.task.DiscoveryTaskManager.searchForNewPeers(DiscoveryTaskManager.java:234)             at org.ethereum.beacon.discovery.DiscoverySystem.searchForNewPeers(DiscoverySystem.java:99)                             at tech.pegasys.teku.networking.p2p.discovery.discv5.DiscV5Service.searchForPeers(DiscV5Service.java:78)                at tech.pegasys.teku.networking.p2p.connection.ConnectionManager.searchForPeers(ConnectionManager.java:86)              at tech.pegasys.teku.util.async.DelayedExecutorAsyncRunner.lambda$runAsync$1(DelayedExecutorAsyncRunner.java:57)        at java.base/java.lang.Thread.run(Thread.java:834)                                                              23:59:37.935 INFO  - Sync Event *** Current slot: 126598, Head slot: 19542, Connected peers: 6                          23:59:55.482 INFO  - Sync Event *** Current slot: 126599, Head slot: 19544, Connected peers: 6                          00:00:04.377 INFO  - Sync Event *** Current slot: 126600, Head slot: 19545, Connected peers: 6                          00:00:19.518 INFO  - Sync Event *** Current slot: 126601, Head slot: 19548, Connected peers: 6    `

**Comment by ajsutton** [comment]
Thanks for this report.   The exception stems from the discv5 library so I've implemented a fix there.  Apart from the noise in the logs the only impact is that the current round of discovery fails but peer search happens periodically so it will carry on next time.

**Comment by ajsutton** [comment]
Pulled in latest discovery dependency that includes the fix for this.
