### ISSUE TITLE
/beacon/chainhead reports wrong block root

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1798]
The `/beacon/chainhead` endpoint is reporting the body root of the latest block header as the head block root but these are completely different hashes.

As a result, the head block root reported by /beacon/chainhead differs from that reported by /beacon/head

**Comment by macfarla** [comment]
related: https://pegasys1.atlassian.net/browse/BC-440

**Comment by macfarla** [comment]
see: https://consensys.slack.com/archives/GU7V1QLG4/p1589751536094600
