### ISSUE TITLE
BeaconStateHelperFunctions.bytes3ToInt typo?

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#180]
Sorry for dismissing your issue template. 
In this [code](https://github.com/PegaSysEng/artemis/blob/master/artemis/src/main/java/tech/pegasys/artemis/state/BeaconState.java#L636): 
```java
    static int bytes3ToInt(Hash src, int pos) {
      checkArgument(pos >= 0, "Expected positive pos but got %s", pos);
      return ((src.extractArray()[pos] & 0xF) << 16) |
          ((src.extractArray()[pos + 1] & 0xFF) << 8) |
          (src.extractArray()[pos + 2] & 0xFF);
    }
```
`src.extractArray()[pos] & 0xF` should be `src.extractArray()[pos] & 0xFF` or am I missing anything?

**Comment by schroedingerscode** [comment]
Good catch, this is certainly a bug. A Java int is 4 bytes, so this unnecessarily truncates valid integers that are outside of the range -2^19 <-> 2^19-1, whereas it should be expected a bytes3 can occupy from -2^23 <-> 2^23-1. This implementation also fails to properly convert a 2s complement bytes3 to a signed int, treating the bytes3 as unsigned instead, which is not Java's default int or byte behavior.

@akhila-raju I know you put the most thought and work into this, so I'll let you make the changes unless you're alright with me doing it. Also I'll let it be your call whether or not bytes3 -> int conversion should be a signed conversion, or if it's appropriate to leave it unsigned as currently implemented.

If we do go the signed route, I suggest we add some additional boundary tests in `BeaconStateTest.java` which confirm that:
 - `BeaconState.bytes3ToInt(BytesValue.wrap(new byte[] {(byte) 128, (byte) 0, (byte) 0})) == -8388608` (the min value a signed Bytes3 should be expected to hold)
 - `...new byte[] {(byte) 127, (byte) 255, (byte) 255}... == 8388607` (the max value a signed Bytes3 should be expected to hold)
 - `...new byte[] {(byte) 255, (byte) 255, (byte) 255}... == -1`

In addition, to avoid confusion, I'd suggest changing the current implementation of `hashSrc` in `BeaconStateTest.java` from `...new byte[] {(byte) 1, (byte) 256, (byte) 65656}...` to the equivalent `...new byte[]{(byte) 1, (byte) 0, (byte) 120}...`. Not having to do the truncation mentally makes it a little bit easier for the programmer to quickly see what's going on from a maintainability perspective.

**Comment by schroedingerscode** [comment]
Also @Nashatyrev, if you're interested in making this fix please feel free. We'll discuss amongst ourselves whether a bytes3 should be unsigned (0 <-> 2^24-1) or signed (-2^23 <-> 2^23-1) and open another issue if we wish to change that behavior. 

If you do submit a PR for this, would you mind adding some additional unsigned (current behavior) boundary tests for the bytes3 -> int conversion? We're currently testing properly converting just one number: 817593. I think it would be beneficial to validate 0, 2^8-1, 2^8, 2^16-1, 2^16, and 2^24-1 are all properly converted.

**Comment by akhila-raju** [comment]
Thank you for catching @Nashatyrev - it should be `0xFF`. Happy to fix this or pass it on to you if you'd like to pick it up.
