### ISSUE TITLE
Allow configuration of public listening endpoint

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1854]
From https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/p2p-interface.md#interop:

```
All listening endpoints must be publicly dialable, and thus not rely on libp2p circuit relay, AutoNAT, or AutoRelay facilities.

Nodes operating behind a NAT, or otherwise undialable by default (e.g. container runtime, firewall, etc.), MUST have their infrastructure configured to enable inbound traffic on the announced public listening endpoint.
```

See TODO in code:  https://github.com/PegaSysEng/artemis/blob/154d6ecc558e1bb48fe1ab69a0246e559b4451ff/networking/p2p/src/main/java/tech/pegasys/artemis/networking/p2p/JvmLibP2PNetwork.java#L96-L99

**Comment by ajsutton** [comment]
Should have been closed by #2656.
