### ISSUE TITLE
Handle peers that disconnect without sending error response

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1868]
If peers fail to decode a req/resp request we send, they should send a response chunk with an error status code and message, but they may just disconnect immediately.  This looks like the response completed successfully with no responses (e.g. no matching blocks).

Need to understand what the right behaviour is in this case.

**Comment by macfarla** [comment]
should there be a success acknowledgement as part of the protocol?
if so are we not looking for them?

**Comment by ajsutton** [comment]
The success code comes as the first byte of each response chunk.  But you only have a response chunk if there is a response to give.  There's no signal for "I have no data" other than the stream being closed.

Peers are expected to return an error chunk if there's an error.  Suspect this needs to get tied into an expanded reputation management system.

**Comment by ajsutton** [comment]
The only requests where this doesn't result in a timeout are when blocks are returned and an empty response is taken to mean no matching blocks.  So we're handling the response correctly and can just close this.
