### ISSUE TITLE
Slashing support

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1881]
### Description
As an [Actor], I want [feature] so that [why]. 

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by benjaminion** [comment]
As long as there is a single altruistic slashing detector (slasher) on the network, then all clients are on an equal footing. The evidence so far is that when slashers detect a violation they very swiftly broadcast it to the network, and whoever is the next block proposer, irrespective of the client, can include it and receive the reward. There is no specific reward for running a slasher, and lack of a slashing detector does not affect Teku's profitability in any way.

If we get to the point when nobody is running an altruistic slasher, we might consider implementing one I guess. Or we could just run one of the available ones. I don't see any client diversity angle here.

In future there will be more slashable offences defined, and we might revisit this, but it's not a priority for now.
