### ISSUE TITLE
Gradle build fails when Jenkins passes in non-ASCII env vars.

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#189]
### Description
Gradle build fails when Jenkins passes in non-ASCII env vars to gradle daemon.

### Steps to Reproduce (Bug)
1. Create a PR with a non-ASCII char in the title, or have a non-ASCII char in your git author name.
2. Allow Jenkins to build the PR.

**Expected behavior:**
Gradle build is kicked off and runs as expected.

**Actual behavior:**
Gradle build never starts. Fails 4-5s in due to "gradle daemon disappeared".

**Frequency:**
100%

### Workaround
When indicating a PR is in a Work In Progress status, prepend `[WIP]` to the title instead of 🚧. You can still continue to use 🚧 in the PR description, as that is not sent to gradle in the env vars.

### Additional Information
See https://github.com/gradle/gradle/issues/3117

**Comment by schroedingerscode** [comment]
Have tried a couple of quick fixes based on the referenced issue in the Additional Information which have not worked. Next I am going to recreate this environment locally so I can experiment a bit more readily without the overhead of creating unnecessary PRs.

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?

**Comment by jrhea** [comment]
closing this bc i don't think it is worth fixing
