### ISSUE TITLE
When a block is rejected, include the block root in the message and a clear reason why (preferably avoid stack traces)

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1892]

**Comment by macfarla** [comment]
Q is there ways that a locally validated block can be submitted and then rejected by the network?

clean up any messages already there (local to beacon node)

**Comment by rolfyone** [comment]
this is an @ajsutton thing... putting back to centaur, its a bigger problem than it appears and needs refactoring.

**Comment by ajsutton** [comment]
Closing this. Our reporting seems reasonable now.
