### ISSUE TITLE
Advertise localhost instead of all 0s if no specific advertised IP was provided

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#1899]
Libp2pNetwork has a method to get that and do the right conversion from all zeros to actual IP if no specific advertised IP was provided.

https://github.com/PegaSysEng/teku/blob/e226b78260d27f41c600f98b7d8d8adc5d4f681f/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/LibP2PNetwork.java#L213

**Comment by ajsutton** [comment]
duplicate of #1896
