### ISSUE TITLE
Support WebSocket ETH1 connections

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#1901]
Infura only supports the `eth_newBlockFilter` method over web socket connections, not HTTP.  However Teku is hard coded to create a Web3J `HttpService` instance.  We should detect `ws` and `wss` URLs and automatically use the websocket service.

Supporting IPC and WindowsIPC services would also be useful.

**Comment by rolfyone** [comment]
talked to adrian, and closing based on that.
