### ISSUE TITLE
Rename --validators-key-file

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1905]
The current CLI option of `--validators-key-file` is to specify an unencrypted key file, but is very similar to the option of `--validators-key-files` (note the plural files) which is used for encrypted keystore files. We should rename the unencrypted version to make it clear what the option is:

Rename option to `--validators-unencrypted-key-file`

**Comment by bgravenorst** [comment]
Content is available here:

https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#validators-unencrypted-key-file
