### ISSUE TITLE
Discovery: Handle unexpected WHOAREYOU

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1922]
When communicating with peers, we may receive a WHOAREYOU at any time and should handle it cleanly.  Currently we only expect it when we sent a random packet or are authenticated.  However, it’s possible that they are trying to connect to us at the same time we are connecting to them, resulting in both sides sending WHOAREYOU to each other. We need to handle that case cleanly somehow.

**Comment by ajsutton** [comment]
Moved to https://github.com/PegaSysEng/discovery/issues/48
