### ISSUE TITLE
JDK SecureRandom may hang on Linux

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1925]
`SecureRandom may` hang on generating next random on Linux. The issue may potentially affect `SecureRandomProvider` clients. The problem was reproduced on Ubuntu 18. Here are more details: https://github.com/PegaSysEng/teku/pull/1632#discussion_r415689340

**Comment by ajsutton** [comment]
Closing as doesn't appear to be an issue even in cloud hosts where entropy is typically limited. JDK offers options to change source of entropy if needed.
