### ISSUE TITLE
Examine use of UnsignedLong.longValue() in datastructures.main

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1933]
* create tickets for any use of UnsignedLong.longValue() that is inappropriate

**Comment by macfarla** [comment]
this is more complicated than it looks so has gone to the betting table.

**Comment by macfarla** [comment]
This one is now a separate ticket: SECONDS_PER_ETH1_BLOCK should probably NOT be an UnsignedLong #2105
