### ISSUE TITLE
Utilize ProtoArrayForkChoiceStrategy methods to optimize processes

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1935]
We have multiple methods in ProtoArrayForkChoice strategy that are currently unused, however, Lighthouse uses these methods to optimize a good amount of its processes. We should be utilizing them for similar purposes.

The methods are:

- containsBlock
- blockSlot
- blockSlotAndStateRoot
- latestMessage

**Comment by ajsutton** [comment]
We have the block tree in Store now which is likely more efficient for most queries anyway.
