### ISSUE TITLE
Inefficient Slot Event Publishing

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1941]
Process slot gets called only when store.getTime() is greater than nextSlotStartTime. Since, at least with the current constants, onTick() gets called twice every second, in the worst-case scenario we're losing 500 ms processing time for each slot.

One idea is to have a SlotScheduler class that has its own timer which gets kicked off exactly at genesis. This class could post SlotEvents, BroadcastAttestationEvents and BroadcastAggregateEvents just like the processSlot method here, however, it would post those events way more precisely.

**Comment by ajsutton** [comment]
Closing this.  The validator client now does independent timing.
