### ISSUE TITLE
Look into better deduplication of logic in AttestationGenerator

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1951]
The test utility `AttestationGenerator`, holds a fair bit of logic that is based on [logic in ValidatorCoordinator](https://github.com/PegaSysEng/artemis/blob/1017a82d7a854962992a2e07a3d538caa2782176/validator/coordinator/src/main/java/tech/pegasys/artemis/validator/coordinator/ValidatorCoordinator.java#L173).  We look into reworking the logic that produces attestations in order to DRY up the code.

See: https://github.com/PegaSysEng/artemis/pull/993#discussion_r344756821

**Comment by ajsutton** [comment]
I think we've wound up leveraging the duplicate code to make it possible to create various forms of invalid attestations for tests so closing this as won't fix.
