### ISSUE TITLE
BlocksByRange responses may be inconsistent

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1954]
Currently, our BlocksByRange responses may return inconsistent block results.  We query against our chain data [using a fixed chainhead](https://github.com/PegaSysEng/teku/blob/7359e47da629e1d6723b7074dc680d0f21f9e15f/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/beaconchain/methods/BeaconBlocksByRangeMessageHandler.java#L96).  But the `CombinedChainDataClient` only enforces the chainhead for recent blocks, not historical blocks.  This means its possible that:

- We start responding with recent blocks on a fork

- We're syncing, so we pull in a bunch of blocks and finalize a different fork

- Now we start serving from the finalized, historical blocks which are on a fork that is inconsistent with the blocks we previously served

We should instead just serve blocks that we believe to be canonical and listen for reorgs.  If a reorg occurs that might have affected blocks we've already served, we should stop sending blocks and close the rpc response stream.

**Comment by ajsutton** [comment]
We load a consistent fork to follow from protoarray up front now.
