### ISSUE TITLE
Expose host whitelist options for metrics service

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1959]
We should expose CLI options for the host whitelist for our metrics service.  See: https://github.com/PegaSysEng/teku/blob/8a99b8e3f9c2e6191940c5f5876370008b77f8f0/data/metrics/src/main/java/tech/pegasys/teku/metrics/MetricsEndpoint.java#L70-L75

We should also configure `hostsWhitelist()` here.

**Comment by macfarla** [comment]
we already do this https://github.com/PegaSysEng/teku/blob/6c01e272db4431528d1642dbb3688e46072863bb/data/metrics/src/main/java/tech/pegasys/teku/metrics/MetricsEndpoint.java#L69

      --metrics-host-whitelist[=<hostname>[,<hostname>...]...]
                             Comma separated list of hostnames to whitelist for
                               access, or * to accept any host
                               Default: [127.0.0.1, localhost]

**Comment by OisinKyne** [comment]
Was about to open an issue but found this related closed one. Can this arg be added to the public docs site please? I spent a long while troubleshooting this while trying to get eth2stats docker image scraping metrics from a teku node while running both in docker-compose (using docker dns to address teku, hence I was getting a `host not allowed` type of error).  https://docs.teku.pegasys.tech/en/latest/Reference/CLI/CLI-Syntax/#metrics-port

**Comment by macfarla** [comment]
--metrics-host-whitelist 

Needs to be added to docs @bgravenorst
