### ISSUE TITLE
Update database metadata persistence

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1960]
We should drop v1 and v2 databases, so we don't need to maintain defunct code going forward.    Since v1 and v2 are no longer supported, we should probably reset the remaining version (v3) to “1.0” or “1”.

While we're at it, we should rework version persistence so that:

[db.version](https://github.com/PegaSysEng/teku/blob/24030e8271281e3206af900f7cba64ed079dc607/storage/src/main/java/tech/pegasys/artemis/storage/server/VersionedDatabaseFactory.java#L33) becomes db.metadata

we store structured data in db.metadata to make this file more future-proof (at some point we may want to store db migration status info here, for example).

**Comment by ajsutton** [comment]
We didn't rework db.version to be more complex but we'll now likely need to do it using a db migration as we want to keep compatibility.  v1 and v2 have been dropped.
