### ISSUE TITLE
Persist ENR data so we can restart with consistent ENR info

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1961]
On restart, we should initialize discovery with an ENR record that is consistent with our latest published ENR record (seq >= the latest seq number with matching or updated fields).

**Comment by rolfyone** [comment]
would need to persist public key and sequence number across restart.

As much as anything, we need to look at what other clients are doing WRT ENR.  If they persist, then we probably should too.

It's possible to supply a key, but if you don't the node key gets generated and not stored. In this case, each restart, you would be generating a new key, so your ENR is changing on each restart.

Storing it will mean basically mean you're storing a private key unencrypted in the data folder, should confirm that's ok with @benjaminion 

The sequence number should be stored also. It would be ok for the sequence number to go up, but never down so we need to understand what the previous value of the sequence number was on restart.

**Comment by macfarla** [comment]
Ran up lighthouse (docker image) and it stores network/enr.dat but it's regenerated on restart

enr:-LK4QHG1WjVzGiohzHbWtl67fvtsKrJweaSEV6Wzr5lQ5F6PHipj4BBT2xWmezgmq3BXXVxDqXJFcctfjiPtCk0_lbECh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD2d10HAAABE___________gmlkgnY0gmlwhBsgPVSJc2VjcDI1NmsxoQPV4PRHQ2i2jniVG8Gm8rpKa3FdriLK9m34Z_b8RFV35IN0Y3CCIyiDdWRwguhe

**Comment by ajsutton** [comment]
Just checking, but did it regenerate on start because it always does or because it stored the data to the docker image disk and then the next instance of docker started from scratch again?

**Comment by macfarla** [comment]
Yeah I did wonder about that - next step is build lighthouse from source

**Comment by macfarla** [comment]
Building lighthouse from source and running `lighthouse --http` 
ENR is stored here and does NOT get regenerated on stop/start
~/.lighthouse/beacon/network/enr.dat

**Comment by benjaminion** [comment]
Closing in favour of #2209.

**Comment by protolambda** [comment]
@benjaminion You said "closing" but this issue was not closed? I still really like to see this feature. And not just the private key, but also other details (seq number in particular) should be persisted.

**Comment by benjaminion** [comment]
> You said "closing" but this issue was not closed?

Oops. Well spotted :-)

> not just the private key, but also other details (seq number in particular) should be persisted.

Yes, of course. I'll add a note to the other issue to make sure.

**Comment by Nashatyrev** [comment]
I'd reopen this as I'd like to address #2209 separately
