### ISSUE TITLE
Retry if publish to fanout fails

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1962]
If we attempt to publish an attestation via the fanout, but we don’t actually have any peers connected to the relevant subnet (causing the publish to fail), we should retry.

Ideally, the call to publish to the fanout via libp2p will return a result letting us know if we’re successful or not.  If we’re not successful, we should hold onto the attestation and retry periodically.  We’ll also need to come up with a retry policy that keeps us from retrying forever.

**Comment by ajsutton** [comment]
This may not be required now that flood publishing is enabled (#2717) as we broadcast to all our peers. Need to test it.

**Comment by ajsutton** [comment]
No longer required.
