### ISSUE TITLE
Clean up fork management at the storage layer

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1966]
Currently, when we finalize a block, we don't do any explicit management of hot blocks / states that we now know are no longer descendants of the latest finalized block.  We should probably prune this data when we finalize a new block.

See test around this scenario [here](https://github.com/mbaxter/teku/blob/cde2d2bdb66cfa2ab8fdb348fc4760f5e296bb0c/storage/src/test/java/tech/pegasys/artemis/storage/server/rocksdb/V3RocksDbDatabaseTest.java#L54).
And review comment [here](https://github.com/PegaSysEng/teku/pull/1577#discussion_r408494409).

**Comment by benjaminion** [comment]
Done
