### ISSUE TITLE
Investigate errors in handling incoming rpc requests

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1968]
We're getting occasional `NullPointerException`'s when handling incoming rpc requests.  See: https://github.com/libp2p/jvm-libp2p/issues/94

**Comment by ajsutton** [comment]
I haven't seen this in logs for a long time.  @mbaxter do you know if this is still an issue?

**Comment by mbaxter** [comment]
As far as I know, we never fixed this and the libp2p issue is still open. @Nashatyrev - do you know if this is still an issue?

**Comment by Nashatyrev** [comment]
@mbaxter Oh, no, just remembered that I wanted to fix this in `0.5.0` :(
It's still the issue
