### ISSUE TITLE
Move onChainStarted and onValidatorRegistered from BeaconChainService to StateTreeManager

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#200]
### Description
Beaconchain specific event handling does not belong in service classes.  The event handlers currently in BeaconChainService should be implemented in StateTreeManager.

> Note once #199 is merged this issue can be worked.

### Acceptance Criteria
* onChainStarted moved to StateTreeManager.java
* onValidatorRegistered to StateTreeManager.java

**Comment by stefanmendoza** [comment]
@jrhea I'm going to start looking into this 👍
