### ISSUE TITLE
Improve error message when indexed attestation is invalid

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2017]
### Description
When an attestation failed the `is_valid_indexed_attestation` checks, `ForkChoiceUtil` simply prints `on_attestation: Attestation is not valid` which is completely unhelpful in understanding what went wrong.

Fix the message to include the specific reason the indexed attestation was invalid.

**Comment by cemozerr** [comment]
The is_valid_indexed_attestation method does print the specific reason for the error such as 
> AttestationUtil.is_valid_indexed_attestation: Verify indices are sorted

However, we are printing them at the DEBUG level. Putting up a PR to switch them to WARN.
