### ISSUE TITLE
Default or option to not write withdrawal key pairs to disk

### ISSUE THREAD

**Issue by ethers** [Consensys-Incorporated/teku#2025]
https://github.com/prysmaticlabs/prysm/issues/6078

https://lighthouse-book.sigmaprime.io/key-managment.html#withdrawal-keypairs

>  adopted a strategy where we do not save withdrawal keypairs to disk by default (it is opt-in). Instead, we assert that since the withdrawal keys can be regenerated from a mnemonic, having them lying around on the file-system only presents risk and complexity.
> 
> withdrawal keypairs can be trivially regenerated from the mnemonic via EIP-2333 so they are not saved to disk like the voting keypairs.

**Comment by ajsutton** [comment]
This is an interesting one and something to consider as part of planning for the validator subcommands. 

Possibly a simpler and more secure solution is to support specifying the withdrawal public key as a command line argument so the withdrawal private key is not required for the deposit generation at all. That would support the recommended process of generating the withdrawal key offline and keeping it in cold storage.

Couple of other factors to consider with this issue:
* Note that Teku does not use a mnemonic to generate key pairs - they are randomly generated.  Currently if the generated withdrawal key is not written to disk it will be completely irretrievable.
* Teku can use any validator keys from a BLS12-381 keystore. They do not have to be generated by the Teku subcommands.

**Comment by cemozerr** [comment]
Closing this issue, as we now recommend using the Launchpad or other external tools to generate keys.
