### ISSUE TITLE
Add BLS verify to Cava

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#206]
### Description
We need a well tested, compatibly licensed implementation of the pairing function in order to verify BLS signatures.  

@bkolad suggested using: https://github.com/ConsenSys/mikuli

### Acceptance Criteria
* research the best implementation
* add it to cava
* make the pairing function available to complete:
https://github.com/PegaSysEng/artemis/pull/119

**Comment by jrhea** [comment]
Modified @bkolad's code so that G1 is used for pubkey, G2 is used for hash(m) & sigs. Here is my commit:

https://github.com/jrhea/mikuli/commit/dbe8cc2f10be2f28009f00ae147cd6494a5cb392

All tests pass and benchmark runs.

**Comment by akhila-raju** [comment]
Is this complete @jrhea ?

**Comment by jrhea** [comment]
I added it to cava, but the base type of the Milagro implementation are too small and I need to either add a hack or use Harmony's implementation.
