### ISSUE TITLE
Make list of subcommands available via CLI

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#2071]
If we're not putting subcommands in the docs pages, we need to make it clear on the command line what the subcommands are and how they work. There is currently no way to find subcommands, but you can get the --help for them if you know what they are.

**Comment by macfarla** [comment]
Probably only validator should be doc’d and ideally that would be replaced by the one true tool for making deposits (hopefully that will be EF’s LaunchPad but it doesn’t really exist yet so each client is having to provide their own tools)

**Comment by ajsutton** [comment]
They're included in help.

```
> ./build/install/teku/bin/teku --help
...
Commands:
  help        Displays help information about the specified command
  transition  Manually run state transitions
  peer        Commands for LibP2P PeerID
  validator   Register validators by sending deposit transactions to an
                Ethereum 1 node
  genesis     Commands for generating genesis state
```
