### ISSUE TITLE
update teku validator generate to output to a single level output folder

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#2088]
As a user of teku,
I want to be able to generate validator keys into a structure that allows me to use it directly in subsequent commands,
so that I don't have to move files into an arbitrary structure.

Currently the folder structure we generate looks like:
```
├── validator_814a1a6
│   ├── validator_814a1a6.json
│   └── withdrawal_8b3ad4d.json
├── validator_81ee3ca
│   ├── validator_81ee3ca.json
│   └── withdrawal_8077d79.json
```

to make it easier to use the generator folder when specifying for teku, we need to flatten this without losing the context of which validator goes with which key.
our output folder, rather than containing a folder per validator, will now be:
```
814a1a6_validator.json
814a1a6_withdrawal.json
81ee3ca_validator.json
81ee3ca_withdrawal.json
```

This is to enable #2003 to be more usable, because specifying a folder to load keys from is predicated by those keys all being predictably in a folder.

**Comment by macfarla** [comment]
To DEMO:
# Run besu
besu --rpc-http-enabled=true \
    --genesis-file=path-to-teku/acceptance-tests/src/testFixtures/resources/besu/depositContractGenesis.json \
    --miner-enabled \
    --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73
starts a besu with a test genesis from teku 

teku: after you've run gradle install,
./build/install/teku/bin/teku validator generate \
    --deposit-amount-gwei 32000000000 \
    --eth1-endpoint=http://localhost:8545 \
    --eth1-deposit-contract-address=0xdddddddddddddddddddddddddddddddddddddddd \
    --eth1-private-key=0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3 \
    --encrypted-keystore-enabled=true --number-of-validators=64 --network minimal --keys-output-path ~/out

**Comment by bgravenorst** [comment]
Raised equivalent doc issue:
https://app.zenhub.com/workspaces/pliny-5e33b0c5274adc1d47ff7cc5/issues/pegasyseng/doc.teku/104
