### ISSUE TITLE
Teku not recovering after loosing peer connections

### ISSUE THREAD

**Issue by bgravenorst** [Consensys-Incorporated/teku#2102]
**Version info**: teku/v0.11.4-dev-0182e8da/osx-x86_64/oracle-java-12

My Teku instance lost connection to all Peers after a bunch of the following warnings:

`2020-06-10 07:14:28.853+10:00 | nioEventLoopGroup-3-16 | WARN  | DefaultChannelPipeline | An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException: null`

Teku continued syncing but it did not reconnect to its Peers.

**Comment by benjaminion** [comment]
Closed in favour of #2200.
