### ISSUE TITLE
SECONDS_PER_ETH1_BLOCK should probably NOT be an UnsignedLong

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#2105]
SECONDS_PER_ETH1_BLOCK can change from UnsignedLong to int to avoid use of UnsignedLong.longValue

**Comment by ajsutton** [comment]
It's a lot more readable to have `SECONDS_PER_ETH1_BLOCK` as an `UnsignedLong` and call `.longValue` in a few places than to have to re-wrap it with `UnsignedLong.valueOf`.  There's nothing inherently wrong with calling `longValue` so long as we aren't risking an overflow.
