### ISSUE TITLE
replace "whitelist" with "allowlist"

### ISSUE THREAD

**Issue by macfarla** [Consensys-Incorporated/teku#2113]
https://developers.google.com/style/inclusive-documentation#features-and-users describes this pretty well. Associating "white" with good/allowed and "black" with bad/disallowed cannot be disentangled from systemic racism. In contrast, allowlist and denylist exactly and merely describe the functions of these fields and variables.

This will change CLI options - do we need to support both options for a time or are we ok with a breaking change?
* --metrics-host-whitelist becomes --metrics-host-allowlist
* --rest-api-host-whitelist becomes --rest-api-host-allowlist
* change variable names throughout the code

**Comment by bgravenorst** [comment]
Raised equivalent doc issue:
https://app.zenhub.com/workspaces/pliny-5e33b0c5274adc1d47ff7cc5/issues/pegasyseng/doc.teku/103
