### ISSUE TITLE
POST /beacon/validators implementation does not match documentation

### ISSUE THREAD

**Issue by skmgoldin** [Consensys-Incorporated/teku#2114]
https://pegasyseng.github.io/teku/#operation/postBeaconValidators

`epoch` is an optional key according to the docs, but Teku returns a 500 error if it is omitted in the request.

CC @rolfyone 

🙂

**Comment by rolfyone** [comment]
The intent is definitely for the epoch to default and return meaningful data. I've made a fix, PR is up, I'll merge ASAP.

Thanks for bringing it to my attention.
