### ISSUE TITLE
Integrate v0.12.1 fork choice tests

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2162]
### Description
Had to revert https://github.com/PegaSysEng/teku/pull/2154 on the 0.12.1-integration branch because those are the 0.11.1 fork choice tests.  We need to get the v0.12 fork choice tests and integrate them.  

Need to also fix the way they're integrated as they're being run as a separate test, not actually picked up by the reference test runner because they're under `src/test/java` instead of `src/test/resources` with the rest of the reference tests.

**Comment by cemozerr** [comment]
After offline discussion with @ericsson49, we're waiting for the v0.12.2 release in order to update the tests and later incorporate them back into Teku tests.
