### ISSUE TITLE
Implement efficient aggregation strategies

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2192]
### Description
As a staker, I want aggregations to be efficiently packed in blocks so that I can maximise my rewards. 

### Acceptance Criteria
* Teku proposer rewards over time better or not significantly worse than other clients' rewards.

**Comment by mbaxter** [comment]
A simple idea for selecting higher priority `MatchingDataAttestationGroup`'s would be to keep a `Bitlist` that holds the superset of all aggregation bits in each group.  We could then take this bitlist, unset any [`seenAggregationBits`](https://github.com/mbaxter/teku/blob/0f5def611e2c42d878c7ffcf6f82a440dde8ae3e/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/attestation/MatchingDataAttestationGroup.java#L54), and count the remaining set bits to get the number of unique validators in each group.   We could then prioritize groups with higher counts for unique validators.

**Comment by ajsutton** [comment]
Useful reference: https://lighthouse-blog.sigmaprime.io/optimising-attestation-packing.html

**Comment by benjaminion** [comment]
Closing as there is no evidence that Teku's current packing strategy is poor. Teku produces a disproportionate number of blocks for operators who use Vouch, suggesting that Teku's attestation packing is at least as good as others'.
