### ISSUE TITLE
use a NoOpRocksDbProvider when in Prune mode using v4 database.

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#2197]
from #2195, 

>Probably not for this PR, but I wonder if when storage mode is PRUNE we should skip loading or creating the archive db entirely and just pass in a StubRocksDbAccessor here. Then it would automatically discard archive state and we avoid the overhead of opening a second RocksDB instance that we never actually use.

As an operator of validator clients,
I want to never store finalized data,
because it is not an overhead i require when I'm just operating validator clients.

part of #1965

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. [Step 1]
2. [Step 2]
3. [Step ...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by ajsutton** [comment]
Actually in hindsight this was not my best idea.  We still need to record finalised blocks - it's only states we discard so can't use a NoOp database.
