### ISSUE TITLE
Validator client loses sync quickly

### ISSUE THREAD

**Issue by ethers** [Consensys-Incorporated/teku#2215]
Node was in sync, and then suddenly was not?  I stopped the beacon node and then restarted the validator straight away so how could it fall so much behind?

19:06:08.012 INFO  - Slot Event  *** Slot: 77343, Block:    ... empty, Epoch: 2416, Finalized checkpoint: 2392, Finalized root: a0deb0..3b7f, Peers: 0
19:06:14.097 INFO  - Epoch Event *** Epoch: 2417, Justified checkpoint: 2393, Finalized checkpoint: 2392, Finalized root: a0deb0..3b7f
19:06:16.996 INFO  - Slot Event  *** Slot: 77344, Block:    ... empty, Epoch: 2417, Finalized checkpoint: 2392, Finalized root: a0deb0..3b7f, Peers: 0
19:06:29.289 INFO  - Slot Event  *** Slot: 77345, Block:    ... empty, Epoch: 2417, Finalized checkpoint: 2392, Finalized root: a0deb0..3b7f, Peers: 0
19:06:34.385 INFO  - Sync Event  *** Current slot: 77345, Head slot: 76618, Connected peers: 4
19:06:48.838 INFO  - Sync Event  *** Current slot: 77346, Head slot: 76618, Connected peers: 5
19:06:50.889 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChannel-0 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length (See log file for full stack trace)
19:07:21.257 INFO  - Sync Event  *** Current slot: 77347, Head slot: 76618, Connected peers: 7
19:07:55.645 INFO  - Sync Event  *** Current slot: 77348, Head slot: 76636, Connected peers: 7
^

**Comment by cemozerr** [comment]
There seems to be a race condition between our new block processing and fork choice head updating transactions that is causing this issue and others that you have brought up: https://github.com/PegaSysEng/teku/issues/2208, https://github.com/PegaSysEng/teku/issues/2224. We're working on resolving this as soon as possible.

**Comment by cemozerr** [comment]
We've reverted the PRs that caused this issue so we shouldn't see this issue again.
