### ISSUE TITLE
Slot Event changing to Sync Event and beacon node never syncs

### ISSUE THREAD

**Issue by ethers** [Consensys-Incorporated/teku#2224]
What is a Slot Event?
What is a Sync Event?
Why is there a transition?

The following is from running beacon node only (not validator client, which is #2215.  Because of 2215, just running beacon node itself to sync the chain. But it is unable to sync and is always behind).

01:25:04.561 INFO  - Slot Event  *** Slot: 79238, Block:    ... empty, Epoch: 2476, Finalized checkpoint: 2465, Finalized root: a664f9..0b74, Peers: 17
01:25:16.521 INFO  - Slot Event  *** Slot: 79239, Block:    ... empty, Epoch: 2476, Finalized checkpoint: 2465, Finalized root: a664f9..0b74, Peers: 17
01:25:28.647 INFO  - Slot Event  *** Slot: 79240, Block:    ... empty, Epoch: 2476, Finalized checkpoint: 2465, Finalized root: a664f9..0b74, Peers: 17
01:25:40.837 INFO  - Slot Event  *** Slot: 79241, Block:    ... empty, Epoch: 2476, Finalized checkpoint: 2465, Finalized root: a664f9..0b74, Peers: 17
01:25:52.525 INFO  - Slot Event  *** Slot: 79242, Block:    ... empty, Epoch: 2476, Finalized checkpoint: 2465, Finalized root: a664f9..0b74, Peers: 17
01:26:04.073 INFO  - Sync Event  *** Current slot: 79243, Head slot: 78947, Connected peers: 18
01:26:18.918 INFO  - Sync Event  *** Current slot: 79244, Head slot: 78947, Connected peers: 18
01:26:20.611 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChannel-0 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length (See log file for full stack trace)
01:26:55.042 INFO  - Sync Event  *** Current slot: 79245, Head slot: 78947, Connected peers: 18
01:26:56.110 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChannel-0 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length (See log file for full stack trace)
01:27:33.546 INFO  - Sync Event  *** Current slot: 79246, Head slot: 78947, Connected peers: 18

The beacon node is always behind:
01:30:51.381 INFO  - Sync Event  *** Current slot: 79252, Head slot: 79053, Connected peers: 18
01:31:22.481 INFO  - Sync Event  *** Current slot: 79253, Head slot: 79065, Connected peers: 18
01:31:52.320 INFO  - Sync Event  *** Current slot: 79254, Head slot: 79078, Connected peers: 18
01:31:53.769 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChannel-0 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length (See log file for full stack trace)
01:32:44.345 INFO  - Sync Event  *** Current slot: 79255, Head slot: 79078, Connected peers: 18
01:35:19.230 INFO  - Sync Event  *** Current slot: 79256, Head slot: 79105, Connected peers: 18
01:35:26.707 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for StorageUpdateChannel-0 java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: ProtoArray: Invalid delta length (See log file for full stack trace)
01:37:39.461 INFO  - Sync Event  *** Current slot: 79257, Head slot: 79105, Connected peers: 18

**Comment by cemozerr** [comment]
We've reverted the PRs that caused this issue so we shouldn't see this issue again.
