### ISSUE TITLE
RocksDB Produces fatal error on shutdown

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2241]
### Description
When shutting down teku, the following error occurred:
```
Teku is shutting down
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000136e6c988, pid=6007, tid=46595
#
# JRE version: Java(TM) SE Runtime Environment (11.0.3+12) (build 11.0.3+12-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.3+12-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [librocksdbjni11922200677829895721.jnilib+0x5d988]  rocksdb::GetColumnFamilyID(rocksdb::ColumnFamilyHandle*)+0x8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/mbaxter/code/consensys/teku/build/hs_err_pid6007.log
[thread 115975 also had an error]
[thread 64003 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Error report: [hs_err_pid6007.log](https://github.com/PegaSysEng/teku/files/4840769/hs_err_pid6007.log)

Teku restarted fine after this error.

**Comment by rolfyone** [comment]
one easy way to reproduce:
 - start syncing onyx, on v4 db with 2048 slot storage.
 - once its got more than a couple of hundred slots, do a fetch of /beacon/state at around 300.
 - you'll have several seconds to then CTRL+C the teku process and a SEGV will happen.

**Comment by mbaxter** [comment]
Running into a similar error again on shutdown.  I think we need a similar fix in [methods that modify rocksdb `Transaction`'s](https://github.com/PegaSysEng/teku/blob/0dbd974afe0a164d5da0f1a5bf2d29e820a9049e/storage/src/main/java/tech/pegasys/teku/storage/server/rocksdb/core/RocksDbInstance.java#L196-L197).

Error log: [hs_err_pid32789.log](https://github.com/PegaSysEng/teku/files/4853835/hs_err_pid32789.log)
