### ISSUE TITLE
Incorrect Genesis when calculated in "real time"

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2243]
This was observed for Altona network genesis. When tracking the deposit contract "in real time" we got the following at the moment that `is_valid_genesis_state()` was first true (`GENESIS_DELAY - ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK` seconds before `MIN_GENESIS_TIME`):

```
2020-06-27 16:46:14.274+00:00 | Eth1EventsChannel-2 | INFO  | teku-event-log | ^[[36mGenesis Event *** Initial state root: 0x692e5b2e01a21f46ca232cae86ae29c72e0e0ce18fc528d5de9f2f4b93e43f1f, Genesis block root: 0x980238061b46a5a79ba00f395daded137d529bae944d3ecaf43c0208fc4b9582^[[0m
```

This differed from Prysm.

Deleting the DB (yep, should have saved it, but I nuked it) and re-running Teku after this time obtained different genesis data, which matches Prysm's:

```
2020-06-27 17:43:26.069+00:00 | Eth1EventsChannel-2 | INFO  | teku-event-log | ^[[36mGenesis Event *** Initial state root: 0x939d98077986a9f6eccae33614e2da1008a2f300f1aac36bc65ef710550eec4a, Genesis block root: 0x9e2ffe8ab9316e03e45409eaaffab10cf02e1b60e609276113e07240d4a31b7a^[[0m
```

In both cases, the genesis time was correctly set to 1593433805, and 685 validators were registered.

```
$ ./build/install/teku/bin/teku --version
teku/v0.12.0-dev-50fa4ed6/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13
```

This may relate to a deposit ordering issue first discussed [on Discord](https://discord.com/channels/476244492043812875/619926417970429962/721131014314786827).

The definitive data from @protolambda:
```
state hash-tree-root: 939d98077986a9f6eccae33614e2da1008a2f300f1aac36bc65ef710550eec4a
genesis latest header root: eade62f0457b2fdf48e7d3fc4b60736688286be7c7a3ac4c9a16a5e0600bd9e4
genesis latest header root (with updated state root): 9e2ffe8ab9316e03e45409eaaffab10cf02e1b60e609276113e07240d4a31b7a
validator reg root: 1b244843b4aa8d14d59a3e397f0a02318eefa229ae68209de78418b2fc07f794
validator count: 685
eth1 data: Eth1Data(Container)
    deposit_root: Root = 0x14ad54cce180f0bc3c31a59c37c38125ab9120b1eae83946de906228a937f249
    deposit_count: uint64 = 1078
    block_hash: SpecialByteVectorView = 0x1b75ab3e138be05eb83d084ac54c4887e9ba6b83fa5c73d8b73a30ffdcd75faa
dep index: 1078
```

**Comment by ajsutton** [comment]
I've uploaded good and bad databases and JSON dumps of the generated genesis to https://github.com/ajsutton/eth2-states/tree/master/altona-genesis

Notably this is different from previous issues because all deposits were processed in the correct order (good and bad databases have exactly the same sequence of deposits) yet somehow the states different.

**Comment by ajsutton** [comment]
Looks like we included one extra deposit?

```
zcli diff state bad/genesis.ssz good/genesis.ssz
BeaconState objects A and B are different:
modified bytes: .Eth1State.Eth1Data.DepositRoot
from = 4a436ecff1ec3184772644e0d1bd7d17dd2eb49f606a4ef8a6259c2adedd8514
  to = 14ad54cce180f0bc3c31a59c37c38125ab9120b1eae83946de906228a937f249
modified: .Eth1State.DepositIndex, from = 0x437; to = 0x436
modified: .Eth1State.Eth1Data.DepositCount, from = 0x437; to = 0x436
modified: .RegistryState.BalancesState.Balances[681], from = 0xee6b28000; to = 0x773594000
```
