### ISSUE TITLE
Memory leak in RpcHandler

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2286]
### Description
In `RpcHandler` 
https://github.com/PegaSysEng/teku/blob/320b66c77e32b9f54b1291edbf2b714029fb19ef/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/rpc/RpcHandler.java#L68 for every request we send to a peer, we register a new handler with the connection closeFuture.  That handler and everything it has a reference to via closure can't be garbage collected until the peer disconnects.

We need to rework it so that a single handler can exceptionally complete any pending futures and avoid registering additional handlers for each request.

**Comment by Nashatyrev** [comment]
Reopen until the next Libp2p release is integrated
