### ISSUE TITLE
Implement the new API specification

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2296]
https://github.com/ethereum/eth2.0-APIs

**Comment by benjaminion** [comment]
Conformance testing tool: https://github.com/INFURA/eth2-comply

**Comment by rolfyone** [comment]
cleanup complete. most of the standard api is implemented, though there are 2 related issues:
#3129 
#3130

These aren't planned prior to initial release for mainnet, so closing epic.
