### ISSUE TITLE
Integrate third-party BLS library

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2300]
Current target candidate is [Blst](https://github.com/supranational/blst/).

We ought to keep the current Milagro/JVM version as well, so recommend implementing the BLS package as interfaces.

**Comment by Nashatyrev** [comment]
The problem with SWIG binding on Windows described here: https://github.com/supranational/blst/issues/4

**Comment by Nashatyrev** [comment]
Hit the problem with high level `verify` function: https://github.com/supranational/blst/issues/5

**Comment by Nashatyrev** [comment]
Relates to #2127
Would probably remove some of public classes/methods when abstracting to interfaces. However particular implementations (Milagro, Blst) may leave their classes/methods public

**Comment by Nashatyrev** [comment]
The only test which fails now is the Infinity Pubkey/Signature. Here is the opened Blst issue : https://github.com/supranational/blst/issues/11
