### ISSUE TITLE
Feature request: detailed reward/penalty metrics

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2302]
### Description
As a staker or staking service, I want to be able to see very granular reward and penalty information so that I can identify any issues and compare with others. 

Currently, validator balances are available via the state object, but that does not give granular insight. If my validator is falling behind, I might like to know whether it is due to delayed inclusion of attestations in blocks, or incorrect votes on the head block, or poor packing of attestations into blocks, etc. This information is not currently accessible.

Teku could log this data on demand, e.g. to a CSV file. Need to decide whether this is done in real time, or via historical API calls (`get_rewards_for_epoch`), or a dedicated mode that can resync the chain and output the data. Also need to decide which validators' data get output. All of them would be a lot of data, so maybe selected by validator index.

Also useful would be to log alongside the data the maximum available reward for perfect performance, for comaprison purposes.

**Comment by ajsutton** [comment]
We now have enough individual metrics to track all the different elements of attestation rewards for the validators running on against a teku beacon node: https://www.symphonious.net/2021/01/10/exploring-eth2-attestation-rewards-and-validator-performance/

Specifically:
```
(
validator_performance_correct_head_block_count - (validator_performance_expected_attestations - validator_performance_correct_head_block_count) +

validator_performance_correct_target_count - (validator_performance_expected_attestations - validator_performance_correct_target_count) +

validator_performance_included_attestations - (validator_performance_expected_attestations - validator_performance_included_attestations) +

(0.875 * validator_performance_included_attestations / validator_performance_inclusion_distance_average)
) / validator_performance_expected_attestations / 3.875
```

We log the individual components each epoch, but not currently the weighted total which I think is probably reasonable. There's already a lot of info in the log message and the individual components are what you can act on and the total when reported epoch by epoch is going to fluctuate a fair bit for low numbers of validators.

I'm going to close this but reopen if you feel we should be reporting the total.
