### ISSUE TITLE
Native memory excessive consumption and native memory leaks

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#2303]
### Description

When running Teku with `-Xmx1G` the `java` process resident memory tend to be of ~`2.5G` which looks like an overhead

When running Teku with e.g. `-Xmx1G`, the total JVM memory consumption is estimated to be around 1.5G (including `ByteBuffers` which are mostly Netty owned). 
It's also expected for `RocksDB` to consume around `200Mb` with the current defaults: 
- 128Mb for write buffer
- 8Mb for block cache 
- Other native structures

Thus we having ~`0.8G` of unknown native memory consumption. 
`RocksDB` is the major native lib used in Teku so it is the primary suspect. 

Here is the process memory consumption over time: 
![изображение](https://user-images.githubusercontent.com/8173857/86351464-f7e9b580-bc6c-11ea-9c3d-5cc715e9e0d1.png)

From the graph it doesn't looks like the memory is leaking

### Acceptance Criteria
Teku process with `-Xmx1G` shouldn't consume more than `2G`

### Steps to Reproduce (Bug)
Run Teku node with `-Xmx1G` on Onyx (or other) testnet for about 2-3 hours 

**Expected behavior:** process consumes < `2Gb`

**Actual behavior:** process consumes `2.5G`

**Frequency:** Always

### Versions (Add all that apply)
```
commit d98d802cb416819a22081be693ffb130c052e425 (HEAD -> master, origin/master, origin/HEAD)
Author: Adrian Sutton <adrian.sutton@consensys.net>
Date:   Wed Jul 1 15:03:46 2020 +1000
```

**Comment by Nashatyrev** [comment]
Here is the information gathered by `jemalloc` with following settings: 
```
> export LD_PRELOAD=/usr/local/lib/libjemalloc.so
> export MALLOC_CONF="prof:true,lg_prof_interval:30,lg_prof_sample:17"
```
```
(pprof) top
Total: 75500943443 B
42991837621  56.9%  56.9% 49218367523  65.2% JVM_RaiseSignal
14543664971  19.3%  76.2% 14543931233  19.3% rocksdb::Arena::AllocateNewBlock
3092307015   4.1%  80.3% 3092307015   4.1% YMap::init
2128888958   2.8%  83.1% 2128888958   2.8% YNodeTree::allocateFreeNode
1978396368   2.6%  85.7% 4883327036   6.5% _init
1310280226   1.7%  87.5% 1310280226   1.7% inflate
1277841606   1.7%  89.2% 1277841606   1.7% YMap::rehash
955604955   1.3%  90.4% 955604955   1.3% CountingSupportBase::getCounterPtrImpl
854434717   1.1%  91.6% 854434717   1.1% std::string::_Rep::_S_create
829081038   1.1%  92.7% 3140881904   4.2% YNodeTree::YNodeTree
597342681   0.8%  93.5% 3924786781   5.2% PlayerEventAdding::createTableRow
(pprof) top --cum
Total: 75500943443 B
       0   0.0%   0.0% 52106014966  69.0% JVM_handle_linux_signal
42991837621  56.9%  56.9% 49218367523  65.2% JVM_RaiseSignal
       0   0.0%  56.9% 33374137573  44.2% 0x00007fa1cb91c96f
       0   0.0%  56.9% 14633438816  19.4% Java_org_rocksdb_Transaction_commit
       0   0.0%  56.9% 14633438816  19.4% rocksdb::PessimisticTransaction::Commit
       0   0.0%  56.9% 14625888452  19.4% rocksdb::DBImpl::WriteImpl
       0   0.0%  56.9% 14625888452  19.4% rocksdb::WriteCommittedTxn::CommitWithoutPrepareInternal
14543664971  19.3%  76.2% 14543931233  19.3% rocksdb::Arena::AllocateNewBlock
  131120   0.0%  76.2% 14369816624  19.0% rocksdb::SkipListFactory::CreateMemTableRep
       0   0.0%  76.2% 14369685504  19.0% rocksdb::ConcurrentArena::AllocateAligned
       0   0.0%  76.2% 14369685504  19.0% rocksdb::MemTable::Add
```

Though I'm not sure how to interpret those numbers correctly it appears that no one besides `RocksDB` is in duty for memory consumption

**Comment by Nashatyrev** [comment]
Here is the usual JVM Native memory layout for Teku with `-Xmx1G`: 

(Note that `Other` part includes allocated `ByteBuffers` which are 99% owned by Netty (Libp2p)

```
> jcmd 20485 VM.native_memory
20485:

Native Memory Tracking:

Total: reserved=2851785KB, committed=1524893KB
-                 Java Heap (reserved=1048576KB, committed=1048576KB)
                            (mmap: reserved=1048576KB, committed=1048576KB)

-                     Class (reserved=1123823KB, committed=81439KB)
                            (classes #11294)
                            (  instance classes #10641, array classes #653)
                            (malloc=3567KB #54769)
                            (mmap: reserved=1120256KB, committed=77872KB)
                            (  Metadata:   )
                            (    reserved=71680KB, committed=70064KB)
                            (    used=68772KB)
                            (    free=1292KB)
                            (    waste=0KB =0.00%)
                            (  Class space:)
                            (    reserved=1048576KB, committed=7808KB)
                            (    used=6959KB)
                            (    free=849KB)
                            (    waste=0KB =0.00%)

-                    Thread (reserved=110554KB, committed=11166KB)
                            (thread #107)
                            (stack: reserved=109944KB, committed=10556KB)
                            (malloc=383KB #644)
                            (arena=227KB #213)

-                      Code (reserved=250952KB, committed=65832KB)
                            (malloc=3264KB #7984)
                            (mmap: reserved=247688KB, committed=62568KB)

-                        GC (reserved=106664KB, committed=106664KB)
                            (malloc=34844KB #145736)
                            (mmap: reserved=71820KB, committed=71820KB)

-                  Compiler (reserved=981KB, committed=981KB)
                            (malloc=951KB #1068)
                            (arena=30KB #5)

-                  Internal (reserved=40024KB, committed=40024KB)
                            (malloc=39992KB #53696)
                            (mmap: reserved=32KB, committed=32KB)

-                     Other (reserved=131309KB, committed=131309KB)
                            (malloc=131309KB #40)

-                    Symbol (reserved=12100KB, committed=12100KB)
                            (malloc=10462KB #128405)
                            (arena=1638KB #1)

-    Native Memory Tracking (reserved=6250KB, committed=6250KB)
                            (malloc=29KB #395)
                            (tracking overhead=6220KB)

-        Shared class space (reserved=17024KB, committed=17024KB)
                            (mmap: reserved=17024KB, committed=17024KB)

-               Arena Chunk (reserved=2939KB, committed=2939KB)
                            (malloc=2939KB)

-                   Logging (reserved=4KB, committed=4KB)
                            (malloc=4KB #191)

-                 Arguments (reserved=41KB, committed=41KB)
                            (malloc=41KB #495)

-                    Module (reserved=279KB, committed=279KB)
                            (malloc=279KB #2133)

-              Synchronizer (reserved=258KB, committed=258KB)
                            (malloc=258KB #2159)

-                 Safepoint (reserved=8KB, committed=8KB)
                            (mmap: reserved=8KB, committed=8KB)

```

**Comment by Nashatyrev** [comment]
Here is also a chat with Besu team member on RocksDB versions: 
>Anton Nashatyrev  1 day ago
Hey team! I'm trying to investigate native memory leaks in Teku and the main suspect is RocksDB.
I'd love to consult with someone from Besu who may have any RocksDB tuning experience (edited) 

Danno Ferrin:besu:  21 hours ago
The only serious work I’ve done was to play with rocksdb versions.  6.4.6 which is what teku currently runs is what we had for 1.4.x versions of besu.  We just updated to 6.8.1 as part of 1.5.0 library version updates.  Prior versions were 6.2.4 and 5.15.10.  We rolled back to 5.15.10 because of severe leaks in 5.17.2. (edited) 

Anton Nashatyrev  21 hours ago
So you generally didn't experience any memory problems with 6.4.6 ?

Danno Ferrin:besu:  21 hours ago
I think we did, it just never caused OOMs within 2 weeks for our production nodes.

Danno Ferrin:besu:  21 hours ago
A classic full sync did die after 3 weeks.

Anton Nashatyrev  21 hours ago
Do you know what was the approximate process mem size comparing to max heap size ?

Danno Ferrin:besu:  21 hours ago
not really.  Havent dug that deeply.

Anton Nashatyrev  21 hours ago
Is the 6.8.1 version better in that respect?

Danno Ferrin:besu:  21 hours ago
It’s the newest.  During our quarterly minor version RCs we update all versions to newest and see if anything breaks.  Mostly doing it to keep ahead of security advisories.

**Comment by Nashatyrev** [comment]
Looks like we have light native memory leak. This is the process memory usage for ~100 hours:
![изображение](https://user-images.githubusercontent.com/8173857/86599868-e9223c00-bfa7-11ea-858d-31710d49c0e2.png)

**Comment by benjaminion** [comment]
Upped to P2 now that we've seen a couple of OOMs.

**Comment by Nashatyrev** [comment]
Run the node without `RocksDB` and with `-XX:MaxDirectMemorySize=128M`
HEAD: 59f58aa70f90826c660c29ae6c8822c05aa9f8ca
Here is the difference between Process committed memory and VM native memory committed: 

(don't pay too much attention to those spikes. These are just two metrics measurement time shifts)

![изображение](https://user-images.githubusercontent.com/8173857/88277179-f437d480-cce8-11ea-8fb6-eb14603d5067.png)


Looks like leaking ~750Kb/hour

**Comment by benjaminion** [comment]
Limiting RocksDB open files seems to be having a very good effect on my system.

![Annotation 2020-07-24 061804](https://user-images.githubusercontent.com/20796281/88374416-a2975480-cd91-11ea-9dac-fc9e0e6707e6.png)

The chart covers 6 days of total process memory. The left hand side is the previous behaviour: observe the inexorable upwards slope everywhere. For the last 2 days I constrained RocksDB open files (I set 100, but I already had ~253. It has not reduced the FDs, but has also not increased them as it did previously). Note that the upwards sloping trend is now almost flat.

The memory profile now looks like a smoothed version of the heap usage plus a constant about 1.5GB. I have `Xmx2g`, which could be reduced, and I don't think I have the latest reduction in ByteBuffer usage applied, so there's definitely scope to reduce RSS more. I'm just happy that it has stopped growing unboundedly, which is the main thing.

Caveats: needs another day or so to be sure. I'm keen then to do a resync so that I can see if the open files can really be kept within our new limits. YMMV - we may have different memory issues on different systems. I don't know what bad effect this may have, if any, on RocksDB performance.

**Comment by benjaminion** [comment]
Seems to be under control for now. Closing.

**Comment by Nashatyrev** [comment]
Here is the pure native memory consuption (`process committed - jvm committed`) for 5 days (version: 05cea37ad80fa0210e5a3f6b1d7ae2134af41ee7): 
![изображение](https://user-images.githubusercontent.com/8173857/88806298-e8508480-d1b8-11ea-8ff7-2f80ed0a37a1.png)

Looks pretty stable but extra 1.3G for unknown purposes looks slightly excessive 🤔 

Just 21 `SST` files are opened, and totally 41 handle to the data dir

**Comment by Nashatyrev** [comment]
Here is the fresh data from attack-net Teku nodes with validators: 
![изображение](https://user-images.githubusercontent.com/8173857/94054314-2d252000-fde4-11ea-9200-9a84602c6f7b.png)

With 2Gb heap allocated the process committed memory approaching to 3.5Gb and keeps growing.

**Comment by Nashatyrev** [comment]
![изображение](https://user-images.githubusercontent.com/8173857/94122236-fb02d500-fe5a-11ea-9884-0567ae633e20.png)
One node down. Didn't find any anomalies on all other node metrics besides this one.

**Comment by kcharbo3** [comment]
I'm new here, but thought I might take a stab at this issue. I see that it was opened and closed, so I'm uncertain how much this issue has changed from when it was first opened. A couple of quick questions: Are the steps to reproduce the native memory leak the same? (Run Teku node with -Xmx1G on Onyx (or other) testnet for about 2-3 hours)  Is RocksDB still the main suspect?

**Comment by ajsutton** [comment]
@kcharbo3 Lots and lots of unknowns about what's going on but very similar situation.  We're seeing issues when running Teku in a docker container with 4Gb of RAM and -Xmx2G.  Medalla is a bigger network so will need more than 1G but should run comfortably with -Xmx2g but seems to struggle at some points (but not always).  At the same time, we're seeing total process resident memory gradually increase to the point where with a 4g system memory limit the system out of memory killer kills Teku.

So there's two issues - one with on-heap memory being higher than we'd like at times, the second with native memory usage growing.  RocksDB is the key suspect for the native memory usage growth but we're definitely open to any theories.  

@Nashatyrev can probably provide more detail but he's in Russian timezones so won't be awake for a while yet.

**Comment by kcharbo3** [comment]
Makes sense, thanks for the explanation. I'll update if I find anything!

**Comment by Nashatyrev** [comment]
Hey @kcharbo3 ! I'm working on this at the moment. Unfortunately no new findings yet :/

**Comment by kcharbo3** [comment]
Ahh okay thanks for the update, I'll reach out to you if I find anything that I think can help!

**Comment by tzapu** [comment]
we re seeing a slow but steady memory increase on mainnet to the point where teku gets killed, so it s reaching 11-12gb+, graph is of `container_memory_working_set_bytes`
special flags we used are 
```
        env:
          - name: JAVA_OPTS
            value: -Xmx4g -XX:-HeapDumpOnOutOfMemoryError
```
![image](https://user-images.githubusercontent.com/2983312/107217188-7fbf4b80-6a16-11eb-91d6-98e49bbd53b8.png)

is there anything we can do/set to stop the slow leak? how can we limit the max mem it uses so it doesn't grow large enough to get killed?
what other data can i provide?
thank you very much, love teku :D

**Comment by benjaminion** [comment]
@tzapu This is most like related to https://github.com/ConsenSys/teku/issues/3495 - (excessive memory consumption by RocksDB). We are actively looking at alternative DBs at the moment, and will hopefully have news soon. It would definitely be good to resolve this!

**Comment by benjaminion** [comment]
Note that, on Linux, setting the environment variable `MALLOC_ARENA_MAX=1` has a good effect for me. It reduces process memory growth on my own node from about 300MB/day to about 100MB/day over the long term. I've been testing this for a couple of months, and all seems fine. There is no detectable affect on performance/CPU usage. This is with RocksDB.

**Comment by hoangong** [comment]
Hi, I see that the PR to fix this issue (using levelDB) has been merged. But I still have the same issue. memory usage is very high  after about 1hr running (more than 20G). I'm using version 21.5.0. This is the command I used:
```
JAVA_OPTS="-Xmx3G" bin/./teku \
  --eth1-endpoints="$ETH1_NODE,$ETH1_BACKUP" \
  --data-path=$ETH2_DATA/teku
```

**Comment by ajsutton** [comment]
@1mdc Are you using an existing database or creating a new one? The change to leveldb so far is only for newly created database - existing databases will continue to use RocksDB.

20Gb is way more than I've ever seen even with RocksDB though.

**Comment by hoangong** [comment]
@ajsutton I have same problem with both old DB and completely new database (i.e. pointing data path to a new location)

I tried to debug in JDK Mission Control. I find that recorded memory is quite low in this profiler (1-3Gb), i'm not sure where it the rest comes from. may be some another sub-process? 

These are screenshots actual memory usage from activity monitor (it shows 5Gb but it keep growing to 20Gb or 30Gb) and from JDK Mission Control:
<img width="828" alt="Screenshot 2021-06-08 at 14 53 53" src="https://user-images.githubusercontent.com/5703525/121197829-8c8b6900-c869-11eb-8738-a2e7edb01133.png">

<img width="1007" alt="Screenshot 2021-06-08 at 14 54 19" src="https://user-images.githubusercontent.com/5703525/121197818-88f7e200-c869-11eb-91b5-dd7481424614.png">

**Comment by ajsutton** [comment]
> I tried to debug in JDK Mission Control. I find that recorded memory is quite low in this profiler (1-3Gb), i'm not sure where it the rest comes from. may be some another sub-process?

JDK Mission Control only looks at the on-heap memory that's actually used.  Activity monitor will report the amount of heap that's allocated (whether it's currently used or not) plus native memory use.  I'm not entirely sure what MacOS reports in that memory column - if it includes memory mapped files then it will grow to be very large but that doesn't necessarily mean that memory isn't available to other processes if needed.

How much memory does your system have available? Are you seeing any actual problems like slow performance etc?

**Comment by hoangong** [comment]
My system has 40Gb memory. I can notice the system be slow down when teku takes > 20Gb (e.g. switching between chrome tab very slow)

**Comment by ajsutton** [comment]
> My system has 40Gb memory. I can notice the system be slow down when teku takes > 20Gb (e.g. switching between chrome tab very slow)

So probably the next thing to check is that Teku is actually using leveldb rather than RocksDB.  If you look in the director you're using for `--data-path` there will be a `beacon/db.version` file.  If it's using leveldb it should contain `leveldb2`. If it's just a number like `5` then it's still using RocksDB.

**Comment by hoangong** [comment]
it is `leveldb2` in db.version file.

This screenshot shows that the app took 31Gb after about 30 minutes running and my machine is slowing down. 

<img width="853" alt="Screenshot 2021-06-10 at 11 12 26" src="https://user-images.githubusercontent.com/5703525/121508046-1c9def80-c9dd-11eb-80e6-bc7336af26b0.png">

**Comment by ajsutton** [comment]
@1mdc This may be easier to work through on discord rather than this issue: https://discord.gg/7hPv2T6 in the #teku channel.

But I think the next thing to check is the metrics around memory to see what's actually being used.  Prometheus and grafana are the ideal and the memory graph in https://grafana.com/grafana/dashboards/13457 gives a very good overview.  If you don't have those setup though, you could run Teku with `--metrics-enabled`, give it time for the memory usage to become an issue and then run `curl http://localhost:8008/metrics | grep memory` to get a single snapshot of the memory metrics. Mac OS X doesn't provide some of the metrics around native memory usage I'd really like but we can at least confirm what the JVM itself is actually using.

**Comment by Nashatyrev** [comment]
Another thing I would try is the newer leveldb version. 
The version Teku is using is pretty old. Bintray had been shut down, so I'm attaching the artifact I have here. It's not the latest leveldb version though. 
 [leveldbjni-all-1.18.3.zip](https://github.com/ConsenSys/teku/files/6703505/leveldbjni-all-1.18.3.zip)

**Comment by Nashatyrev** [comment]
Not sure if it's binary compatible with `1.8` so probably you would need to delete the old db dir and sync from scratch

**Comment by hoangong** [comment]
I have not really found the root cause but I finally fixed it by switching to a different JVM implementation. From openj9 to hotspot. Explicitly, it is from `AdoptOpenJDK 11.0.11.j9-adpt` to `AdoptOpenJDK 11.0.11.hs-adpt`

**Comment by ajsutton** [comment]
Ah great to hear you've found the issue.  j9 isn't particularly common and IBM tends to focus on big iron server deployments of it so I'm not entirely surprised it winds up using a lot of memory. Likely it could be controlled by setting the right options but it may not be setting defaults as intelligently as Hotspot.
