### ISSUE TITLE
Incorrect time to genesis reported

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2323]
### Description
Teku seems to get timezones confused when reporting the time until genesis.  When I run `run.sh` it prints:
```
10:36:36.835 INFO  - 10:00:06 until genesis time is reached                                                           │10:36:36.578 INFO  - 10:00:06 until genesis time is reached
```

I'm in UTC+1000 and genesis is actually in 6 seconds time.  It kicks off correctly, just the info message that's wrong.

**Comment by cemozerr** [comment]
Can you give more detail on how you use the `run.sh` script? When I run it, it errors and exits pretty quickly.

**Comment by ajsutton** [comment]
Run `./gradlew distTar && cd scripts && ./run.sh`

But I suspect any genesis event will do it, we seem to be comparing the genesis time in UTC to the local time in the user's time zone.
