### ISSUE TITLE
Possible MetaData Issue with Lighthouse

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#2344]
I was looking through a recent Lighthouse peerstore dump from Altona and found 14 teku nodes in the peerstore.   All 14 had a reputation of 0 & metadata = null.  I'm wondering if there is a possible issue with the MetaData req/resp method.  🤷‍♂️

Here is an example of a teku entry:

```json
  {
    "peer_id": "16Uiu2HAmRaVfypo834Kovh4mQErjTzigyAnri4618wpEke3bXftD",
    "peer_info": {
      "_status": "Healthy",
      "reputation": 0,
      "client": {
        "kind": "Teku",
        "version": "v0.12.0-dev-5380e888",
        "os_version": "linux-x86_64",
        "protocol_version": "ipfs/0.1.0",
        "agent_string": "teku/teku/v0.12.0-dev-5380e888/linux-x86_64/oracle_openjdk-java-11"
      },
      "connection_status": {
        "Connected": {
          "in": 0,
          "out": 1
        }
      },
      "listening_addresses": [
        "/ip4/xx.x.x.xxx/tcp/9000/p2p/16Uiu2HAmRaVfypo834Kovh4mQErjTzigyAnri4618wpEke3bXftD"
      ],
      "sync_status": {
        "Synced": {
          "info": {
            "status_head_slot": 65255,
            "status_head_root": "0xf9aa4c155d92640eae4ff6f9262625e9ccd092f328cb84284bc558a915f3ec1d",
            "status_finalized_epoch": 2013,
            "status_finalized_root": "0x7d5a7d2ee690fa2fd50cf0c18e4c28d674e5c33b2d184cbe36cec135219b6891"
          }
        }
      },
      "meta_data": null
    }
  }
```

 For comparison, here is an example of a Prysm node:

```json
 {
    "peer_id": "16Uiu2HAmLvREVVcPJGbpRmvEMxV8AJy1s8fn9LRPXVB9FBo9xYaW",
    "peer_info": {
      "_status": "Healthy",
      "reputation": 50,
      "client": {
        "kind": "Unknown",
        "version": "unknown",
        "os_version": "unknown",
        "protocol_version": "ipfs/0.1.0",
        "agent_string": "Prysm/v1.0.0-alpha.13/a9bbbae19abac0c3c8cf7c4213b949172f97cf57"
      },
      "connection_status": {
        "Connected": {
          "in": 0,
          "out": 1
        }
      },
      "listening_addresses": [
        "/ip4/xx.xxx..x.xx/tcp/13000"
      ],
      "sync_status": {
        "Synced": {
          "info": {
            "status_head_slot": 65254,
            "status_head_root": "0x69d4de78fc15e0e04763d66f826fe345b3cd703724d5e4e6bdf4cc0fef2275af",
            "status_finalized_epoch": 2013,
            "status_finalized_root": "0x7d5a7d2ee690fa2fd50cf0c18e4c28d674e5c33b2d184cbe36cec135219b6891"
          }
        }
      },
      "meta_data": {
        "seq_number": 1,
        "attnets": "0xbfafd576ffffb3d7"
      }
    }
  }
```

Here is a Nimbus node:

```json
 {
    "peer_id": "16Uiu2HAmUZgER8SkBxfyf8RaH8As7AmU5ZgYqSmhmuvYTZbSjgdg",
    "peer_info": {
      "_status": "Healthy",
      "reputation": 50,
      "client": {
        "kind": "Nimbus",
        "version": "0.0.1",
        "os_version": "unknown",
        "protocol_version": "ipfs/0.1.0",
        "agent_string": "nim-libp2p/0.0.1"
      },
      "connection_status": {
        "Connected": {
          "in": 0,
          "out": 1
        }
      },
      "listening_addresses": [
        "/ip4/x.x.x.x/tcp/9000"
      ],
      "sync_status": {
        "Synced": {
          "info": {
            "status_head_slot": 65242,
            "status_head_root": "0xf10aaf360ba51620202fd1d9753cb1738f24102c84eaefb47ac2cea4ae8d1bb6",
            "status_finalized_epoch": 2013,
            "status_finalized_root": "0x7d5a7d2ee690fa2fd50cf0c18e4c28d674e5c33b2d184cbe36cec135219b6891"
          }
        }
      },
      "meta_data": {
        "seq_number": 0,
        "attnets": "0xffffffffffffffff"
      }
    }
  },
```

**Comment by Nashatyrev** [comment]
Hey @jrhea I believe we fixed the metadata issue with #2254 (~ 15 days ago) 
Do you think this is more recent behavior?

**Comment by jrhea** [comment]
I believe the peerstore dump is from July 8th.  I got it from proto and noticed the issue when looking through it.  i'll message you guys on tg with the data.

**Comment by Nashatyrev** [comment]
Yep, we still experiencing the similar problem as was solved #2254

**Comment by Nashatyrev** [comment]
Hm, this time we have another reason: the remote peer doesn't close his write side of stream 'after empty request'

**Comment by Nashatyrev** [comment]
See other successful requests, likely from other clients. So this is probably just Lighthouse related

**Comment by jrhea** [comment]
> Hm, this time we have another reason: the remote peer doesn't close his write side of stream 'after empty request'

You are sending an empty metadata request?

**Comment by Nashatyrev** [comment]
The `getMetadata` request _should_ be empty. In fact the requester should immediately close his write side of a Stream. That means the end of empty request. We are sending response right after the request stream side is closed. Bit it is not in our case.

**Comment by jrhea** [comment]
> The `getMetadata` request _should_ be empty. In fact the requester should immediately close his write side of a Stream. That means the end of empty request. We are sending response right after the request stream side is closed. Bit it is not in our case.

Oops...you're right.  For some reason, I thought the spec told us to request it by sending your current Metadata.  I swear I saw that in the spec just a few weeks ago...my bad.  Thanks for the clarification.

**Comment by jrhea** [comment]
> Hm, this time we have another reason: the remote peer doesn't close his write side of stream 'after empty request'
> See other successful requests, likely from other clients. So this is probably just Lighthouse related

I have been running an agent on the Altona network for the past 5 days masquerading as a lighthouse node.  It's possible that it is my agent isn't closing the stream properly...DId you see multiple lighthouse nodes with this issue or just one?  Do you have the peerid?

**Comment by Nashatyrev** [comment]
It's hard to say from logs which client I'm talking with. I think it would be simpler to get any Lighthouse node address, connect directly and see how is it going

**Comment by Nashatyrev** [comment]
The issue fixed on the Lighthouse side https://github.com/sigp/lighthouse/pull/1369
