### ISSUE TITLE
Improve teku output when fork-choice is "stuck" on a stale branch during sync

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2353]
### Description
While syncing during long periods of non-finalization, our the fork-choice chainhead can get stuck on a dead-end block making teku appear to have stalled.  We should add logs / metrics that make it easier to see what's happening in this case.  

For example:  the following chart displaying `beacon_head_slot` vs `beacon_slot` makes it appear that teku is stuck.  It may be helpful to add another metric that tracks the latest block synced: ![Screen Shot 2020-07-14 at 4.59.54 PM.png](https://images.zenhubusercontent.com/5b2bbbcb8f620008aaa30877/449bd117-c575-4f9e-a1f6-94f1ee2775a8)

For notes on reproducing, see description from #2157: https://github.com/PegaSysEng/teku/issues/2157#issuecomment-657725103

**Comment by mbaxter** [comment]
Note:  An alternative fix would be to find a way of processing attestations during sync (see attestation validation logic [here](https://github.com/PegaSysEng/teku/blob/d9fdf128e70b7cc4d5d0b556f1bea20f17b7bf22/ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java#L413-L416)).  This should prevent fork-choice from getting stuck.

**Comment by ajsutton** [comment]
We now process attestations during sync so this is no longer an issue.
