### ISSUE TITLE
--logging option should be case insensitive

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2367]
### Description
`teku --logging debug` should work to set the log level to debug, but it has to be `teku --logging DEBUG`.  We should match case insensitively.

**Comment by rolfyone** [comment]
the option is still case insensitive, but the debug command is confusing the processing of the command line.

to fix, we will:
 - rename the debug subcommand to `debug-tools`

also noticed that the error level was not present in the log levels, so i'll have a look at that too.
