### ISSUE TITLE
Use RocksDB setDbPaths to support spreading data across multiple directories

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2380]
### Description
We currently use multiple RocksDB instances to split data across directories but could use `DBOptions.setDbPaths` to allow RocksDB to automatically spread data across multiple directories, including supporting target sizes for each directory.

We may still want to use separate hot and finalised DBs but allowing the finalised DB to be spread across multiple drives would be potentially useful.  Alternatively this may be a better options than having two DBs.

**Comment by rolfyone** [comment]
closing - seem to be ok on space currently.
