### ISSUE TITLE
TODO: don't join, create synchronous API for synchronous blockProvider in RocksDbDatabase

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2397]
This comment appears in _RocksDbDatabase.java_. It should be done or the comment removed and manage it via the backlog.

```
// TODO - don't join, create synchronous API for synchronous blockProvider
```

**Comment by ajsutton** [comment]
I deleted the TODO....  The `BlockProvider` is guaranteed to return a completed future because of the way its constructed so fine with using a join in that case.
