### ISSUE TITLE
Re-enable Fips reference tests for HashToG2

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2409]
The following appears in HashToG2 _ReferenceTests.java_:

```
  @Disabled // TODO re-enable once test vectors for draft 07 are available
```

As of 21/7/20, these are not yet available. The original test source was https://github.com/algorand/bls_sigs_ref/tree/master/test-vectors/hash_g2

**Comment by ajsutton** [comment]
@benjaminion is this still something we should do? Are the ref tests available now?
