### ISSUE TITLE
Implement light client friendliness

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#248]
Implement the changes in https://github.com/ethereum/eth2.0-specs/pull/476

Addresses some of #235, namely
* remove `validator_registry_delta_chain_tip`
* add `latest_index_roots`

**Comment by cemozerr** [comment]
In progress

**Comment by schroedingerscode** [comment]
@cemozerr @benjaminion Should this have been closed? I see it was closed manually but no PR referenced it.

**Comment by cemozerr** [comment]
Yeah I should have referenced it. Here is the PR that closed it #258
