### ISSUE TITLE
Use different default databases for different networks

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2493]
### Description
As a node operator, when I supply the `--network=` flag, I want Teku to use a different database so that I am not trying to work with invalid data. This could also apply for the default logging location.

If users specify their own database path, we assume they know what they are doing. This should ony change the defaults.

### Acceptance Criteria
* Each variant of the `--network` flag defaults to a different database directory, such as `data_medalla`, `data_altona`, but ony if a specific database location is not otherwise provided.
* Also applies to default logs if the log path is not supplied: `logs_altona`, `logs_medalla`, etc.

**Comment by benjaminion** [comment]
Better idea. Write some network characteristics into the DB (or metadata) such as the contract address, genesis fork version, and check these data on start up. Refuse to start (with a nice message!) if they do not match.

This is better since it can be made backward compatible (just skip the check if the data is not present). Also, it does not need to apply only to the default DB, or to nodes started with `--network==`.

Probably doesn't apply so well for log files, but they are not so critical.

**Comment by rolfyone** [comment]
@benjaminion can we have this put into a milestone? we couldnt decide...

**Comment by rolfyone** [comment]
```
fork_version: 
deposit_contract: (nullable)
```
