### ISSUE TITLE
Remove support for validators-key-file

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2497]
### Description
Remove support for loading validator keys from an unencrypted file via `validators-key-file` option. This is insecure and causes confusion for users.

**Comment by rolfyone** [comment]
is the intent that it becomes an X option? i'm assuming this is referring to `--validators-unencrypted-key-file`?

**Comment by ajsutton** [comment]
No, just remove it outright. It shouldn't be used anywhere and if it is those places could just be converted to use encrypted keystores instead.

Probably also remove the ability to generate unencrypted keystores from the validator subcommands.
