### ISSUE TITLE
Feature Request: Detailed logs for validator performance

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#2510]
Teku logs only show beaconchain events and do not show validator events. En enhanced log and interface similar to Nimbus could be helpful for validators troubleshooting their setup.

Teku CLI UI:
<img width="744" alt="Screen Shot 2020-08-05 at 9 22 48 AM" src="https://user-images.githubusercontent.com/4099038/89428647-3f4ae200-d702-11ea-893e-d64fbe658e95.png">

Nimbus CLI UI:
<img width="744" alt="Screen Shot 2020-08-05 at 9 22 50 AM" src="https://user-images.githubusercontent.com/4099038/89428757-5c7fb080-d702-11ea-87cb-acbbfcbca456.png">

**Comment by mbaxter** [comment]
We do have a flag to enable more verbose validator-related logging: `--log-include-validator-duties-enabled`.  This enables logging for attestation, aggregation and block production.
