### ISSUE TITLE
Teku client missing almost all attestations on Medalla

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#2520]
### Description
Deposited 100 validators on Goerli, which got activated last night (not included in genesis). Running a teku client with all 100 of them, almost none of them are attesting, ever (each validator has made ~1 attestations in total). See here for performance: https://medalla.beaconcha.in/dashboard?validators=21288,21289,21290,21291,21292,21293,21294,21295,21296,21297,21298,21299,21300,21301,21302,21303,21304,21305,21306,21307,21308,21309,21310,21311,21312,21313,21314,21315,21316,21317,21319,21320,21321,21323,21324,21325,21326,21327,21328,21329,21330,21331,21332,21333,21334,21335,21336,21337,21338,21339,21340,21341,21342,21343,21344,21345,21346,21347,21348,21349,21350,21351,21352,21353,21354,21355,21356,21357,21358,21359,21360,21361,21362,21363,21364,21365,21366,21367,21368,21369,21370,21371,21372,21373,21374,21375,21376,21377,21378,21379,21380,21381,21382,21383,21384,21385,21386,21387,21388,21389

### Acceptance Criteria
I expect all validators to make 99%+ of their attestations.

### Versions (Add all that apply)
* Software version: teku/v0.12.3-dev-a170f84a/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

* OS Name & Version: Ubuntu 20.04 LTS
* Kernel Version: Linux pascal 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Teku command line:
```
bin/teku -n medalla --validators-key-files=`echo ~/test/eth2.0-deposit-cli/validator_keys/keystore-m_12381_3600_* | tr " " ","` --validators-key-password-files=`echo ~/test/eth2.0-deposit-cli/passwords/* | tr " " ","` --p2p-port=9001 --rest-api-enabled=true --rest-api-docs-enabled=true --metrics-enabled --validators-graffiti="Dankrad/teku" --rest-api-port=5151 --eth1-endpoint=http://localhost:8545
```

Looking at the logs it looks like the client is creating attestations and has peers. So either attestations are incorrect or not sent to peers:
[teku.log](https://github.com/PegaSysEng/teku/files/5034321/teku.log)

**Comment by mbaxter** [comment]
We recently reverted a change that caused issues with our attestations production:  https://github.com/PegaSysEng/teku/pull/2519

Try pulling the latest from master and see if this clears up your issue.

**Comment by dankrad** [comment]
Yes, that seems to have fixed it. Would be good to find the root cause of that issue.

Also, performance is ok now, but not great: Validators are still missing significant (one-digit) percentage of attestations. Would be great to see an improvement on that.

**Comment by mbaxter** [comment]
Agreed - we are currently investigating to see exactly how that merge broke attestation production.  You can follow: https://github.com/PegaSysEng/teku/issues/2334 for updates.

I know that there have been some issues at the gossip layer across all clients, which could be causing some percentage of attestations to be missed.  That's something we'll be looking into as well.

Closing this issue for now since it seems the immediate problem has been fixed.
