### ISSUE TITLE
possible to mutation attack? on BLSConstants.VERIFICATION_DISABLED 

### ISSUE THREAD

**Issue by kevzettler** [Consensys-Incorporated/teku#2527]
A security scan hit on 

https://github.com/PegaSysEng/teku/blob/master/bls/src/main/java/tech/pegasys/teku/bls/BLSConstants.java#L30

> A mutable static field could be changed by malicious code or by accident. The field could be made package protected to avoid this vulnerability.

Not sure if this is real issue or false positive

**Comment by ajsutton** [comment]
Thanks for raising this but I would say that's a false positive. The only code running in the Teku process is Teku's code so there's no malicious code (or there's only malicious code if everything has been completely compromised already).  Additionally making the variable package private won't have any benefit as the Java reflection APIs could still be used to change it: **https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/AccessibleObject.html#setAccessible(boolean)**

We have multiple tests in place to ensure the value isn't accidentally changed.
