### ISSUE TITLE
Publishing IHAVE gossips messages with no topic hash

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2528]
### Description
Age Manning reports seeing Teku publishing IHAVE gossipsub messages with no topic hash:

Adrian, [6 Aug 2020 at 1:09:05 pm]:
Hey guys, in the process of doing some debugging, it looks like Teku is sending "IHAVE" gossipsub messages with no topic hash to peers

Adrian Sutton, [6 Aug 2020 at 1:10:08 pm]:
Is it all of them or just some of them?

Adrian, [6 Aug 2020 at 1:11:17 pm]:
I can't really tell from the logs I've seen. If it were all teku nodes, I'd expect to have seen a lot more logs. So I'd say just some of them
One of them is:
v0.12.3-dev-fd2f3cf1

We explicitly check for the case where we have no message IDs (https://github.com/libp2p/jvm-libp2p/blob/6753c3f06d2c9e89a76c7dd8b13f26c117c128fc/src/main/kotlin/io/libp2p/pubsub/gossip/GossipRouter.kt#L410) so not sure how this is happening.  Have requested whatever logs are available.

**Comment by Nashatyrev** [comment]
May be it makes sense to close this for now? A lot of stuff changed in Gossip from the issue creation time.

**Comment by benjaminion** [comment]
Closing, per @Nashatyrev's suggestion.
