### ISSUE TITLE
Constants represented as different types

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#253]
### Description
Sometimes I want, for example, a constant to be returned as a long and sometimes as UnsignedLong.  Would be nice to break up the constants into sep classes (Sig domains, initial values, time params, etc) and create methods to return as long, or UnsignedLong (depending on the type).

### Acceptance Criteria
* toLong()
* toUnsignedLong()
* toInt()?

**Comment by akhila-raju** [comment]
@jrhea, has this been completed or is it still an open issue? I believe it is since we have these methods?
