### ISSUE TITLE
ProtoNode: Delta to be subtracted is greater than node weight.

### ISSUE THREAD

**Issue by J2R5M3** [Consensys-Incorporated/teku#2562]
### Description
The error below was displayed many times while teku seemed to run normally, however the only attestation submitted before restart and after these errors was missed , upon restart I want to note that the errors did not show up again within nearly 2 hours of operation. Additionally few of the published attestations actually succeeded.
```
15:16:00.407 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController' java.util.concurrent.CompletionException: java.lang.RuntimeException: ProtoNode: Delta to be subtracted is greater than node weight. (See log file for full stack trace)
```

### Versions
* Software version: [teku/v0.12.3-dev-f8453a95/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11]

* Java version: [
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)]

* OS Name & Version: [VERSION="20.04.1 LTS (Focal Fossa)"] running on windows subsystem for linux (wsl)
* Windows Version:[Version 10.0.18362.535]
* Kernel Version: [Linux L-0614 4.4.0-18362-Microsoft 476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux]

### Additional Information
[teku.log](https://github.com/PegaSysEng/teku/files/5059895/teku.log)

**Comment by J2R5M3** [comment]
Ran debug-tools with the provided build(https://github.com/PegaSysEng/teku/pull/2561) on discord the resulting forkChoice.yaml is below.
Been continuing to run the client as an experiment and the error has yet to come up again , however all of the published attestations are being missed.
[forkChoice.tar.gz](https://github.com/PegaSysEng/teku/files/5060282/forkChoice.tar.gz)

**Comment by mbaxter** [comment]
Fork choice processing logic was recently reworked here: https://github.com/PegaSysEng/teku/pull/2511. Worth looking into this to see if a bug was introduced.
