### ISSUE TITLE
Remove assertions from non test code

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#259]
### Description
I think these assertions were added as a result of translating the spec literally, but we should visit each case and decide how to handle this.  do we throw and exception?  do we return null, 0, flag?

### Acceptance Criteria
* replace all assertions with appropriate logic

**Comment by akhila-raju** [comment]
Where are the assertions? Without looking deeply into it I'd suggest flags over exceptions.

**Comment by jrhea** [comment]
It's all over the code. Search for assert. You will see a bunch of uses in non test code.
