### ISSUE TITLE
Optimize checkpoint processing

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2609]
### Description

When [regenerating checkpoint states](https://github.com/PegaSysEng/teku/blob/39bfecad0bff96e5ab31aaca970929f45b61b94d/storage/src/main/java/tech/pegasys/teku/storage/store/Store.java#L495), we should be able to reduce the required work by looking for existing checkpoint states rooted at the same block in our checkpoint cache.  For example, if we need to generate a checkpoint at block A, epoch 3, we can regenerate using an existing checkpoint state at block A, epoch 2.

**Comment by ajsutton** [comment]
Stealing this one as it will be addressed as part of deduplicating checkpoint processing. Hopefully not stepping on toes...
