### ISSUE TITLE
RocksDB exception on restart

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2633]
### Description
We've got a user reporting a rocksdb issue after shutting down teku and restarting:
```
08:09:15.531 INFO  - Teku version: teku/v0.12.4-dev-1bbea6b0/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
08:09:15.828 INFO  - Loading 1 validator keys...
08:09:19.157 INFO  - Loaded 1 Validators: b5d7418
08:09:19.476 INFO  - Using data path: /home/user/.local/share/teku/data
Teku failed to start.

Caused by: tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to open database at path: ~/.local/share/teku/data/db

Caused by: org.rocksdb.RocksDBException: SST file is ahead of WALs
```

The user reports that they used `ctrl-c` to stop teku before restarting.  

Problematic data directory is available [here](https://www.dropbox.com/s/drly52998t9sx8x/data.zip).

### Versions
* Software version: v0.12.4-dev-1bbea6b0
* Java version: java 11

**Comment by ajsutton** [comment]
There was a RocksDB issue a while back: https://github.com/facebook/rocksdb/pull/5412 which occurred when the db crashed - and a user later reported seeing this error after running out of disk space.  That PR was merged and should be included in the current RocksDB release we're using, but there is a later release of RocksDB available.

I can't see anything relevant in the changelog or open issues.

**Comment by rolfyone** [comment]
consider adding an arg to the metadata file so people can continue on after this failure...

**Comment by ajsutton** [comment]
Unfortunately I don't think we have access to the required settings to ignore WAL errors via jni, so won't be able to ignore the error and continue.
