### ISSUE TITLE
Teku stops synchronising at headslot 83460.

### ISSUE THREAD

**Issue by D-A-Lake** [Consensys-Incorporated/teku#2642]
### Description
As a user, I want to use Teku as its intended so that I can contribute to the medalla testnet  without having to use the majority-used validators, Prysm and Lighthouse.  Using various validators benefits the network more.

### Acceptance Criteria
*N/A

### Steps to Reproduce (Bug)
1. I booted teku with the the flags shown in the attached log file and no database or log files.
2. I let it synchronise with the network up until headslot 83460.
3. It won't synch past headslot 83460. Left it for over an hour but no luck.

**Expected behavior:** Teku to continue synchronising the headslot until the latest so it can start validating.

**Actual behavior:** Stops at headslot 83460.

**Frequency:** 100% in my case.

### Versions (Add all that apply)
* Software version: [`teku --0.12.3`]
* Java version: [`java -14`]
* OS Name & Version: [`Windows 10 | Build 19041.450 | Version 2004`]

[teku.log](https://github.com/PegaSysEng/teku/files/5114655/teku.log)

**Comment by Yoldark34** [comment]
Hello, I'm stuck as well.

teku/v0.12.4-dev-84673770/linux-x86_64/-privatebuild-openjdk64bitservervm-java-14
Kubuntu 20.04, 32 Gb ram, i5, HDD (no SSD yet).
no validators enabled.

**Comment by ajsutton** [comment]
Doing some syncs to attempt to reproduce this now.  When we've seen similar behaviour in the past the sync was actually continuing but the head block wasn't being updated as we skip updating the fork choice data while syncing finalised slots since there should only be one chain to follow.  However, it is possible to get blocks from the wrong chain which would result in a fork being imported and then Teku switching back to the right chain to continue importing.  Because the fork choice data isn't being filled out though, we won't actually update the head block until we get to or close to chain head making it look like it's stuck.

I'm also looking into whether we can efficiently update those fork choice structures during a sync to avoid the problem entirely.

**Comment by ajsutton** [comment]
Depending on the exact issue you were encountering, #2643 may be needed or potentially #2644 which has just been merged in might be enough.

**Comment by benjaminion** [comment]
Reopening due to a new occurence of this in the wild. See [the report](https://discord.com/channels/697535391594446898/697539289042649190/751051916129206312)  from `@jgm` (@mcdee):

> Trying to sync from clean and it seems to stick at slot 83460:

```
12:07:56.148 INFO  - Sync Event  *** Current slot: 215739, Head slot: 81220, Connected peers: 72
12:08:08.209 INFO  - Sync Event  *** Current slot: 215740, Head slot: 81998, Connected peers: 72
12:08:20.029 INFO  - Sync Event  *** Current slot: 215741, Head slot: 82734, Connected peers: 72
12:08:33.680 INFO  - Sync Event  *** Current slot: 215742, Head slot: 83460, Connected peers: 73
12:08:44.020 INFO  - Sync Event  *** Current slot: 215743, Head slot: 83460, Connected peers: 74
12:08:44.511 INFO  - Epoch Event *** Epoch: 6742, Justified checkpoint: 2290, Finalized checkpoint: 2289, Finalized root: d0ea42..255b
12:08:56.020 INFO  - Sync Event  *** Current slot: 215744, Head slot: 83460, Connected peers: 74
12:09:08.019 INFO  - Sync Event  *** Current slot: 215745, Head slot: 83460, Connected peers: 74
12:09:20.021 INFO  - Sync Event  *** Current slot: 215746, Head slot: 83460, Connected peers: 74
12:09:32.020 INFO  - Sync Event  *** Current slot: 215747, Head slot: 83460, Connected peers: 74
```

> This is the second time I've tried syncing; first time it stuck at this slot for over a day before I killed it.
>
> This is running from master.  Any ideas?

**Comment by D-A-Lake** [comment]
Was this from the pre-compiled binaries or self-compiled? Not sure if the pre-compiled are the latest...

**Comment by mcdee** [comment]
@Dallion3K this is self-compiled from master:

```
$ git rev-parse HEAD
50cfa70b4ad694151014ddf063a32ac7e9aa7709
```

**Comment by D-A-Lake** [comment]
@mcdee TY

**Comment by ajsutton** [comment]
I got a log privately from @mcdee. Copying comment from Discord so we have a more permanent record:

So the node appears to be making progress in a way but is in the long period of non-finalization on Medalla.  It looks like at some point it sync'd up to block 83460 and then for some reason got interrupted with its sync.  In the log you sent it's then started again back at the finalized checkpoint and is gradually following a new peer's chain back up but hasn't reached where it was up to yet.  The Teku version seems to be quite out of date (`teku/v0.12.4-dev-df300e3b`) so it doesn't include most of the fixes for dealing with the Medalla incident, in particular we now try to find a closer common ancestor to restart sync from which should get it making visible process much faster.
The key logs I'm looking at are from the `PeerSync` class:
```
2020-09-03 21:38:48.036+00:00 | beaconchain-async-5 | DEBUG | PeerSync | Request 200 blocks starting at 81363 from peer 16Uiu2HAmS3GGdznKQ6TYfnCW2q5LuKpmsHFq35BQu3fDM5fXXPNy
```

which show what blocks it's actually requesting.

**Comment by benjaminion** [comment]
Closing again. @mcdee has confirmed that there were some out of date JAR files in use, and sync is making progress after being updated to the latest.

**Comment by alexfisher** [comment]
FWIW, I just started a sync today and am running into this issue, too.  Not going past Head slot 83460.  Running with docker image pegasyseng/teku:develop

**Comment by ajsutton** [comment]
@alexfisher Can you check you've actually pulled the latest docker image (`docker pull pegasyseng/teku:develop`) and attach the logs here so I can take a look please?

**Comment by alexfisher** [comment]
Thanks for the fast response @ajsutton -- I just updated and can confirm I was able to pull a newer version.  Started it back up and will see how it does!

![image](https://user-images.githubusercontent.com/176891/92593972-09080180-f270-11ea-9258-64b4788f4a53.png)
