### ISSUE TITLE
Deduplicate gossip messages in validation queue

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2647]
### Description
When the same data is received from multiple gossip messages simultaneously, it's possible that we will spend time validating both of them, only for one of them to be eventually rejected as a duplicate after validation when it is actually recorded in received messages and find the other message there.

The window for this is fairly small as we check if the message is a duplicate before any validation occurs, but we can't record the result at that point because the message isn't yet valid.  We should investigate a system similar to `CacheableTaskQueue` (or possibly just use it) which supports deduplicating messages even prior to validation.

**Comment by Nashatyrev** [comment]
Hm, if that's a really observed case then it should be a Gossip bug. As we have content based message IDs then Gossip router shouldn't propagate the same message to the application even if it's still in process of validation

**Comment by Nashatyrev** [comment]
Seems it's not the case. Closing
