### ISSUE TITLE
Teku periodically dropping out of sync

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2661]
### Description
We're getting reports of teku nodes periodically falling out of sync.  Seeing a series of slot events with empty blocks (dozens):
```
Slot Event  *** Slot: 158093, Block:    ... empty, Epoch: 4940, Finalized checkpoint: 4938, Finalized root: 73a437..be07, Peers: 74
```

Eventually teku initiates a PeerSync and catches up.  But then falls behind again.  Anecdotally it seems like: 
> "once it gets behind it’s stuck behind until it gets about ~50 slots behind and decides to sync the ~100 latest blocks"

### Versions (Add all that apply)
* Software version: teku/v0.12.5-295d0f67

**Comment by mbaxter** [comment]
I noticed that our own validator nodes started producing more empty slot events after an update on Aug 23 with the following changes: https://github.com/PegaSysEng/teku/compare/edde317223aa0578209ae588eaf435ca06a9ab17...1dc9801674819f2445d4d595209d3d893c2a96a2

See logs [here](https://kibana-logs-ohio.ops.pegasys.tech/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2020-08-04T00:00:00.000Z',to:'2020-08-26T12:00:00.000Z'))&_a=(columns:!(message,instance),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8edd65d0-a9f4-11ea-9961-599210e124ad',key:service,negate:!f,params:(query:teku),type:phrase),query:(match_phrase:(service:teku))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8edd65d0-a9f4-11ea-9961-599210e124ad',key:instance,negate:!f,params:!(dev-teku-ohio-medalla-1,dev-teku-ohio-medalla-2,dev-teku-ohio-medalla-3,dev-teku-ohio-medalla-4),type:phrases,value:'dev-teku-ohio-medalla-1,%20dev-teku-ohio-medalla-2,%20dev-teku-ohio-medalla-3,%20dev-teku-ohio-medalla-4'),query:(bool:(minimum_should_match:1,should:!((match_phrase:(instance:dev-teku-ohio-medalla-1)),(match_phrase:(instance:dev-teku-ohio-medalla-2)),(match_phrase:(instance:dev-teku-ohio-medalla-3)),(match_phrase:(instance:dev-teku-ohio-medalla-4))))))),index:'8edd65d0-a9f4-11ea-9961-599210e124ad',interval:auto,query:(language:kuery,query:'%22Block:%20%20%20%20...%20empty%22'),sort:!(!('@timestamp',desc)))).

**Comment by ajsutton** [comment]
Got a case of this with trace level logging for `BlockImporter` which is quite revealing. I've added some notes in brackets at the end based on what beaconcha.in reports:

```
Slot Event  *** Slot: 161983, Block: 3773dc..ca54, Epoch: 5061, Finalized checkpoint: 5059, Finalized root: b2e0ac..53ed, Peers: 74  (Correct Block)
Epoch Event *** Epoch: 5062, Justified checkpoint: 5060, Finalized checkpoint: 5059, Finalized root: b2e0ac..53ed
Slot Event  *** Slot: 161984, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5059, Finalized root: b2e0ac..53ed, Peers: 74  (Block existed)
                Chain reorg from 0x3773dc509d364ad8eee5b8a8415ebf0c60b385a77ac488a756c697f1b187ca54 (161984) to 0x043034f0d9ae9d6b6e6b46621021a257f8f2ff8a7868c83fefe0c3aab6223b65 (161984) (Reorg from empty slot to correct block)
                Successfully imported block 043034..3b65 (161984)                                                                    (Correct Block)
                Failed to import block for reason UNKNOWN_PARENT: ed2476..a8c1 (161985)                                              (Correct Block - parent is 043034..3b65 which we do have)
Slot Event  *** Slot: 161985, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5060, Finalized root: edc40a..5c99, Peers: 74
                Failed to import block for reason UNKNOWN_PARENT: 15ee3d..ee12 (161986)
Slot Event  *** Slot: 161986, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5060, Finalized root: edc40a..5c99, Peers: 73
Slot Event  *** Slot: 161987, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5060, Finalized root: edc40a..5c99, Peers: 72
Slot Event  *** Slot: 161988, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5060, Finalized root: edc40a..5c99, Peers: 72
                Failed to import block for reason UNKNOWN_PARENT: 545348..397f (161989)
Slot Event  *** Slot: 161989, Block:    ... empty, Epoch: 5062, Finalized checkpoint: 5060, Finalized root: edc40a..5c99, Peers: 73
```

So we received all the blocks we needed, but for some reason failed importing 161985 because we didn't find the parent. We would have added it to the pending queue but because we did have the parent, it would never have been triggered to retry the import as that would normally happen once the parent is imported. Eventually it switched to sync mode again and caught up then carried on tracking head without an issue (but will fall behind again when this issue next occurs).

**Comment by ajsutton** [comment]
Ah, there's a race condition with importing blocks - we've wound up receiving 161984 and 161985 close together such that we haven't finished importing 161984 before we start gathering the data for 161985 so 161985 fails to find it's parent state.  All of that's ok (161985 could have been from a different fork so able to import in parallel).  The race condition is in `BlockManager` tracking pending blocks.  The sequence would be something like:

1. `BlockManager.importBlock` Start importing 161984
2. `BlockManager.importBlock` Start importing 161985
3. `BlockManager.onBlockImported` Receives notification that 161984 finished imported. No pending blocks are waiting.
4. `BlockManager.importBlock` receives `UNKNOWN_PARENT` response for 161985 and adds it to the pending block pool.  But this is too late to get the notification that 161984 has already completed.
