### ISSUE TITLE
Can't set metrics-host-allowlist to an IP address via a config file

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2687]
Setting an address in `--metrics-host-allowlist` via the command line works, but not via a config file.

### Command line

Both of these work for accessing from the remote IP 192.168.1.253.

```
teku --config-file=tmp/test.yaml --metrics-host-allowlist='*'
teku --config-file=tmp/test.yaml --metrics-host-allowlist=192.168.1.203
```

[Update: however, see user report below of it not working from the commandline either]

### Config file

However, I can get only `*` to work via the config file, not an address.

This works:
```
metrics-host-allowlist: "*"
```

These fail with `Host not authorized.`:
```
metrics-host-allowlist: "192.168.1.253"
metrics-host-allowlist: ["192.168.1.253"]
metrics-host-allowlist: [192.168.1.253]
```

(The second one is as per [the docs](https://docs.teku.pegasys.tech/Reference/CLI/CLI-Syntax/#metrics-host-allowlist).)

Here is the full (non-working) metrics config I am using:
```
metrics-enabled: true
metrics-interface: "0.0.0.0"
metrics-port: 8009
metrics-host-allowlist: ["192.168.1.253"]
```

**Comment by benjaminion** [comment]
Update from user `tjc_` on [Teku discord](https://discord.com/channels/697535391594446898/697539289042649190/748900007159267359):

I continued to get `Host not authorized` from the command line. Here is what I ran:

```
teku --data-path="/var/eth/teku" --network="medalla" --eth1-endpoint="http://127.0.0.1:8545/" --validator-keys="/var/eth/teku/validators/keystore-m_12381_3600_0_0_0-1598582155.json:/var/eth/teku/validators/password.txt" --p2p-port=9001 --log-destination=CONSOLE --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port=8008 --metrics-host-allowlist=ws2 --rest-api-enabled=true --rest-api-docs-enabled=true
```

Even though this machine can resolve `ws2` :

```
[teku@eth1 trevor]$ ping ws2
PING ws2.XXX.XX (10.0.0.243) 56(84) bytes of data.
64 bytes from ws2.XXX.XX (10.0.0.243): icmp_seq=1 ttl=64 time=0.344 ms
64 bytes from ws2.XXX.XX (10.0.0.243): icmp_seq=2 ttl=64 time=0.329 ms
```

I did try using the IP address also:

```
teku --data-path="/var/eth/teku" --network="medalla" --eth1-endpoint="http://127.0.0.1:8545/" --validator-keys="/var/eth/teku/validators/keystore-m_12381_3600_0_0_0-1598582155.json:/var/eth/teku/validators/password.txt" --p2p-port=9001 --log-destination=CONSOLE --metrics-enabled=true --metrics-interface=0.0.0.0 --metrics-port=8008 --metrics-host-allowlist=10.0.0.243 --rest-api-enabled=true --rest-api-docs-enabled=true
```

With the same result. From the command-line it worked when I set the allowlist to `"*"`

**Comment by ajsutton** [comment]
Discussed this on discord as well but for the historical record...

The `--metrics-host-allowlist` specifies which hosts are allowed in the http `Host` header to prevent DNS rebinding attacks. So it restricts the target host, not the source.  If you allow `192.168.1.253` then calling `http://192.168.1.253/metrics` will be allowed from any source. 

https://en.wikipedia.org/wiki/DNS_rebinding has some info on DNS Rebinding Attacks. Anything you can access on your local network without dns rebinding protection can be accessed to some extent from any webpage you visit which is why we enable this protection by default in Teku.
