### ISSUE TITLE
ForkChoiceTest.onBlock_shouldNotProcessAttestationsForBlocksThatDoNotYetExist fails intermittently 

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#2699]
### Description

The test `ForkChoiceTest.onBlock_shouldNotProcessAttestationsForBlocksThatDoNotYetExist` [failed](https://app.circleci.com/pipelines/github/PegaSysEng/teku/6619/workflows/87605ae5-8091-4bc5-85d9-bbdaa633a758/jobs/41587) on one run and then [passed](https://app.circleci.com/pipelines/github/PegaSysEng/teku/6619/workflows/f84e6f6e-932a-4670-bf13-5b9bafbf9ac3/jobs/41590) after just CI task restart

### Additional Information

Stacktrace: 
```
java.lang.IllegalStateException: Failed to create attestation for block 0xe22e97a922f8c534348cf141e997b5fd0257f2bb0120dec7c74be72413493fd0 
genesis root: 0x6746e70ca3650fde87a039db48f9d1ff3877798112e2bd940f8987e2f76c9331 
chain head: 0x333b17c60375387b3717ad7f28af2dce295427e00bb0535414dc1e9124ff5d94 
validators: 0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c, 0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b, 0xa3a32b0f8b4ddb83f1a0a853d81dd725dfe577d4f4c3db8ece52ce2b026eca84815c1a7e8e92a4de3d755733bf7e4a9b
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoiceTest.lambda$onBlock_shouldNotProcessAttestationsForBlocksThatDoNotYetExist$2(ForkChoiceTest.java:183)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoiceTest.onBlock_shouldNotProcessAttestationsForBlocksThatDoNotYetExist(ForkChoiceTest.java:170)
```

**Comment by ajsutton** [comment]
I'm struggling to understand why this is failing intermittently.  It's trying to create an attestation and comparing the values in this error to what I get running locally (when it passes) all the values match.  So we're trying to create an attestation for the same block, with the same genesis, same validators and building on the same chain head but somehow we intermittently can't create a valid attestation.

There shouldn't be any other source of randomness...
