### ISSUE TITLE
Make 'bls' module Eth2 agnostic. 

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#2716]
### Description

See #2706

> If the bls module is actually used and going to be used outside of Eth2 domain then may be it makes sense to slightly redesign the module API to make it totally DST neutral?

**Comment by Nashatyrev** [comment]
Refactoring BLS should also include test fix to avoid #3175 
Temporary test fix is made in #3203

**Comment by lucassaldanha** [comment]
Closing as not planned.
