### ISSUE TITLE
Bug: Unsigned Long Overrun in EpochProcessorUtil#updateJustification

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#274]
### Description
As an implementor, I want to be sure that unsigned values are not overrun so that program behaves as expected. 

### Acceptance Criteria
- `mod(UnsignedLong.valueOf((long) Math.pow(2, 64)))` in `tech.pegasys.artemis.statetransition.util.EpochProcessorUtil#updateJustification` should be corrected to match values/logic in the [Beacon Chain Spec v0.1 - Justification Section](https://github.com/ethereum/eth2.0-specs/blob/v0.1/specs/core/0_beacon-chain.md#justification).
- Appropriate unit tests should be written to ensure `updateJustification` performs according to the Beacon Chain Spec v0.1.

**Expected behavior:** 
Verify the logic in the snippet mentioned in the above AC, as UnsignedLong.valueOf(2^64) overruns to 0.

**Actual behavior:**
`UnsignedLong.valueOf((long) Math.pow(2, 64))` always results in an UnsignedLong with a value of 0, as 2^64 overruns the upper bound of UnsignedLong, which is 2^63 - 1.

**Comment by vitorpy** [comment]
I believe this was closed by #328

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?

**Comment by schroedingerscode** [comment]
This was closed by #302.
