### ISSUE TITLE
Bounds Checking Should Occur Every Time [De]serialization Reaches a Primitive

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#275]
### Description
As an implementor, I want bounds checking tests any time a primitive type is [de]serialized so that I am sure my client behavior conforms to the spec. 

### Acceptance Criteria
* Bounds tests are written for every class which [de]serializes an arithmetic primitive.

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?
