### ISSUE TITLE
All Serialized Objects Should Be Tested Against Known Good Serialized Bytes Values

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#276]
### Description
As an implementor, I want every serialized class to be serialized from a known value and compared against a known correct bytes value, and deserialized from a known correct bytes value to an expected object value so that I am sure [de]serialization is fully tested, as round trip testing is not sufficient to test against errors that are common to both serializing and deserializing. 

### Acceptance Criteria
- Every class which is [de]serialized should have the following tests:
  - Known Obj Configuration is Serialized into Known Serialized Bytes Value
  - Known Serialized Bytes Value is Deserialized into Known Obj Configuration

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?
