### ISSUE TITLE
Retrieve peer identify info

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2764]
### Description
When peers connect, Teku should use the libp2p identify protocol to request their info and expose that data via a REST API somewhere (/node/peers would be ideal but the standard API doesn't actually include it).

**Comment by ajsutton** [comment]
Would be good to also publish this as metrics.  To limit the number of time series prometheus would create we'd have to have a limited set of known clients + OTHER and use basic matching on the identify to pick the client type but ignore version or other differences etc.  Probably just identify TEKU, LIGHTHOUSE, NIMBUS, PRYSM and OTHER.

**Comment by benjaminion** [comment]
Suggest 'UNKNOWN' rather than 'OTHER'.
