### ISSUE TITLE
load public keys from file or url

### ISSUE THREAD

**Issue by tzapu** [Consensys-Incorporated/teku#2785]
# Description
As a validator, i would like to be able to load a lot of keys from a config file or/and url to use with an external signer.

### Acceptance Criteria
Being able to load multiple keys from a config file and/or url. It would be useful if the url loading would be compatible with the list keys endpoint in web3signer  https://pegasyseng.github.io/web3signer/web3signer-eth2.html#operation/ETH2_SIGN

### Additional Information
I tried to load 2000 keys and was not able, it failed with 
`standard_init_linux.go:211: exec user process caused "argument list too long"`      

thank you very much

**Comment by tzapu** [comment]
the ideal scenario for us being a new cli param to specify the url of the keys, which would be in the web3signer list keys format

**Comment by arash009** [comment]
@tzapu was the error when only when putting the 2000 keys on the CLI? What about using the config file, I assume that works fine?

**Comment by tzapu** [comment]
i didn't think to use a config file at the time and split into 1024 keys
file config would probably work fine, a bit annoying to mount in k8s tho :P 
still rooting for the "load from web3signer url" thing

**Comment by ajsutton** [comment]
`--validators-external-signer-public-keys` now supports loading from a URL (which includes `file:/` URLs).

**Comment by ajsutton** [comment]
That was added in #3463 for the record.
