### ISSUE TITLE
Delete lockfiles in our stop code

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#2793]
We currently delete keystore lockfiles when the VM exits, but in the future, we should be able to support running multiple Teku's in one process, so a better approach would be to hook in a delete call for the lock files in our stop code.

**Comment by cemozerr** [comment]
Seems like it would require too big of a refactor. Putting to icebox for now.

**Comment by ajsutton** [comment]
Current code is working really well as it turns out so just going to leave it as is.
