### ISSUE TITLE
Verify ETH1 chain ID

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2807]
### Description
When the PoWService first connects to the ETH1 node and when sending deposits, check that the chain ID reported by the ETH1 node matches the one in the network config.

**Comment by systemfreund** [comment]
I'd like to tackle this, but I have a question. What do you mean by checking the chain ID?
Should it just do an `ERROR` log in that case, or somehow fail or shutdown?

**Comment by ajsutton** [comment]
Good question.  The ideal case is that the ETH1 node is up at startup, and Teku fails to start with a clear error message if the chain ID doesn't match but the ETH1 chain may not be available at startup and we don't want to delay Teku waiting for it to become available.  So I think we'll just have to have something that tries to query the chain ID - started by `PowchainService.doStart` but that returns immediately and then in the background continues retrying until the ETH1 node is available and we can get it's chain ID.  Then if it doesn't match log a message via the `StatusLogger` at error level.


The sending deposits part of this description doesn't apply anymore as we'll be removing the subcommands that send deposits (we recommend users use other tools like the launchpad).

**Comment by systemfreund** [comment]
Thank you for your input. I still do have a couple of questions :smiley: 

1. Against which chain id value do I have to validate the ETH1 chain id? I couldn't find any mention of a chain id in the existing code. 

1. Regarding the `StatusLogger`... you're not referring to `fatalError` with a following `System.exit`, but to adding a new logging method to `StatusLogger`, right?

**Comment by ajsutton** [comment]
1. The expected chain ID is in the network definition (so for example the MainNet config: https://github.com/PegaSysEng/teku/blob/aa936b9c36607f434a2a412ad63ad693263ef71c/util/src/main/resources/tech/pegasys/teku/util/config/mainnet.yaml#L55) and those definitions will be loaded into the `Constants` class at startup (https://github.com/PegaSysEng/teku/blob/ffc0579ab701df30ac43feb26f500b18215d5e17/util/src/main/java/tech/pegasys/teku/util/config/Constants.java#L124).  So you'd request the chain ID from the ETH1 node and check that it matches `Constants.DEPOSIT_CHAIN_ID`.

Requesting the chain ID from the ETH1 node would be a new method to add to `Eth1Provider` which will wind up calling `web3j.ethChainId()` to do the actual work.

2. Yes, it would be a nw method on StatusLogger.  I'd suggest starting the message with `PLEASE CHECK YOUR ETH1 NODE | ` to match what eth1DepositEventsFailure outputs.

**Comment by systemfreund** [comment]
Just wanted to say that I'm still working on this. I do have a day-job therefore I cannot allocate my time freely to work on teku, that's why it takes a bit longer :)

**Comment by ajsutton** [comment]
@systemfreund Thanks for the update, no problem if it takes time.  Feel free to ask more questions either here or on our Discord (https://discord.gg/7hPv2T6) if there's anything we can do to help.
