### ISSUE TITLE
java.lang.ArithmeticException: uint64 underflow

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#2864]
On Spadina launch, I see this about twice per second:
[tekulog3.zip](https://github.com/PegaSysEng/teku/files/5298769/tekulog3.zip)

13:01:35.148 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController' java.lang.ArithmeticException: uint64 underflow (See log file for full stack trace)

**Comment by cemozerr** [comment]
I believe this issue must have been fixed with the PRs: #2863 and #2865.
