### ISSUE TITLE
Teku can't access (write) to docker volume 

### ISSUE THREAD

**Issue by stefa2k** [Consensys-Incorporated/teku#2869]
### Description
I ran the docker image inside a [docker-compose setup](https://github.com/stefa2k/ethereum2-docker-compose/blob/7596edc55df2ef358fe04646d3c1118b64ff7a9b/docker-compose.yaml#L52) and teku throws an error:
```
Unable to create the path to store database files at /opt/teku/data/db
```

Got it fixed by adding
```
services:
  ...
  teku_node:
    ...
    user: "0:0"
    ...
```

### Acceptance Criteria
* Using docker image without needing to specify `user` via `docker run` or `docker-compose up`

### Steps to Reproduce (Bug)
1. checkout [docker-compose](https://github.com/stefa2k/ethereum2-docker-compose/tree/7596edc55df2ef358fe04646d3c1118b64ff7a9b)
2. run `docker-compose up teku_node`
3. watch the log

**Expected behavior:**
No error, no need to add `user`

**Actual behavior:**
Either error is thrown or need to add `user`

**Frequency:**
Every time

### Versions (Add all that apply)
* OS Name & Version: Ubuntu 20.04
* Kernel Version: Linux eth2-medalla-node-d 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Docker Version:
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by cemozerr** [comment]
Thanks for reporting @stefa2k . We'll look into this and try to fix it as soon as possible.

**Comment by benjaminion** [comment]
Just adding @ajsutton's comments from the Discord here:

> Teku follows best security practice by not running as root, even within the docker container. That can lead to the kind of permissions issue you hit if the user running teku in the container (default UID 501 I think) differs from the user you are using outside the container. The best solution is to explicitly set the UID to use within the docker container so you know what teku is actually running as.

**Comment by ajsutton** [comment]
Going to close this one.  It's security best practice to not run as root even within the docker container.  The downside is that this can create permissions issues for file mounts but specifying the UID to use when running the docker instance manages that and our docs already include a note to that effect.

I would recommend using a non-root UID though and just changing the ownership of the files being mounted to that user.
