### ISSUE TITLE
Remove key generation tools for Mainnet

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2876]
We should discourage use of Teku's built-in key generation convenience tools for mainnet deposits. These built-in tools are not [EIP-2333](https://eips.ethereum.org/EIPS/eip-2333) compatible, do not generate recovery mnemonics, and naively handle the withdrawal keys. In addition, they have not had the required degree of audit scrutiny.

The best way to discourage the use of this functionality would be to remove it (or move it to a separate tool if we wished to keep access for some reason).

We will recommend to stakers that they use fully audited tools such as the [deposit-cli](https://github.com/ethereum/eth2.0-deposit-cli) tool that works with Launchpad, or other specialised 3rd-party key management tools.

**Comment by rolfyone** [comment]
- hide options and change the name

 - update deprecation warning to say 'do not use in production' and caps :)
