### ISSUE TITLE
Review and address audit best practices

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2896]
### Description
Review auditor's comments on best practices and implement appropriate fixes, creating additional tickets as necessary.

**Comment by rolfyone** [comment]
raised #3230 to address one of the teku best practices, but this is the only 'best practice' from the audit related to teku that we agreed with that needed addressing prior to release.

The rest of the best practice list is related to discovery and libp2p.

**Comment by ajsutton** [comment]
Closing this. The on-going maintenance means the codebase has changed a lot since then and these best practices tend to be quite debatable anyway.
