### ISSUE TITLE
Create Signature Type

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#290]
### Description
I would like to have a `Signature` type to abstract away the fact that signatures are represented as a 2 element list of Bytes48? It's a little confusing and possibly error-prone.

### Acceptance Criteria
- new class `BLSSignature`
- two properties: 
  1) private Bytes48 c0;
  2) private Bytes48 c1;
- implements toBytes() SSZ serialization (see other POJOs for reference)

**Comment by benjaminion** [comment]
Closed by #294 .
