### ISSUE TITLE
Key files loading is slow

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/teku#2973]
Take 2 minutes 16 seconds to load 300 key files, on a 6 cores Intel i5 9th gen fast machine.
To make things worse, sync is not parallel, sync won't start until key loading is done. In mainnet, time is money.
cpu consumption is also high during loading.

Compare with two other major clients:
1. prysm loads instantly
2. lighthouse used to be like teku, but now employes key cache. first time loading takes same time as teku, subsequent loading is instant.

Hope your guys can take a page from prysm and lighthouse teams.

**Comment by benjaminion** [comment]
Hi @somuchid  - loading speed largely depends on how your keystores were generated. Many generators use `scrypt` format which is very slow and memory hungry, but (for these exact reasons) the most secure. Personally I use `pbkdf2` format keystores which load instantly, but are less secure (for this exact reason). I generated my `pbkdf2` keystores using the [`ethdo`](https://github.com/wealdtech/ethdo) tool with my mnemonic phrase. Both formats are supported by [EIP 2335](https://eips.ethereum.org/EIPS/eip-2335) and Teku supports both.

Any kind of fast caching could reduce your security. I want security level to be a user choice, so I doubt that we will implement this in Teku. If you want instant loading and are comfortable with the compromise, then I recommend taking a look at converting your keyfiles to `pbkdf2` format.

**Comment by ajsutton** [comment]
Teku is deliberately using the keystore that's supplied to us so that users are in control of the level of security for those files.  It would be good to document a way to re-encode a keystore to use pbkdf2 encryption though if users want them to load faster.

**Comment by benjaminion** [comment]
Fast-loading `pbkdf2` keystores may be generated via the [ethdo](https://github.com/wealdtech/ethdo) tooling. Teku will continue to load keystores in the form in which they are provided -- `scrypt` (slow) or `pbkdf2` (fast) --, as per EIP 2335, so as to give users control over their own security tradeoffs.

**Comment by benjaminion** [comment]
Further to this, I made a script that (ab)uses `ethdo` to convert existing Launchpad scrypt keystores to pbkdf2 keystores: https://gist.github.com/benjaminion/6d24491abe01a40e728c37f0834f5009
