### ISSUE TITLE
integrate stateRootVerification() for 0.1

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#299]
### Description
Implement this section of the spec:

https://github.com/ethereum/eth2.0-specs/blob/v0.1/specs/core/0_beacon-chain.md#state-root-verification

> Note: I am thinking that this check should happen after all slot, block, and epoch processing has completed...here: https://github.com/PegaSysEng/artemis/blob/master/ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateTreeManager.java#L83

### Acceptance Criteria
* target 0.1 spec
* create/update all helpers (that it calls) to ensure it matches 0.1 logic

**Comment by vitorpy** [comment]
What's the expected behavior if the verification fails? Throw and log?

**Comment by jrhea** [comment]
Good question...ya that will work
