### ISSUE TITLE
The latest finalized checkpoint at epoch 221 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>

### ISSUE THREAD

**Issue by lufa23** [Consensys-Incorporated/teku#2999]
I started Teku with `./teku --network=medalla --metrics-enabled --rest-api-enabled --rest-api-docs-enabled --metrics-categories=BEACON,PROCESS,LIBP2P,JVM,NETWORK,PROCESS`
and i get the warning: `The latest finalized checkpoint at epoch 221 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.`
Which BLOCK_ROOT and EPOCH should i use?
<img width="1636" alt="Screenshot 2020-10-16 at 11 50 34" src="https://user-images.githubusercontent.com/67415638/96262126-a79b2700-0fc1-11eb-9e3e-df63e34e1cc1.png">

**Comment by mbaxter** [comment]
Hey @lufa23 - this warning is in place to protect users against potential long-range attacks.  Realistically, you probably don't need to worry about this right now for the medalla testnet.  But if you want to try out the weak-subjectivity protections, you'd need to find a recent checkpoint that you know is on the medalla chain.  We're still working on a way to reliably serve these checkpoints - it's likely that various block explorers will make these checkpoints available in the near future.  Whatever the final mechanism is, it's ultimately up to the user to find a value that they trust and check that value against multiple sources.

**Comment by mbaxter** [comment]
I realize this is not a great answer ^.  This feature is still under active development.  Since we don't have a reliable mechanism to find values for the WS checkpoint at this time, I'm making the logs a bit quieter for now (See: #3029).

**Comment by lufa23** [comment]
thanks!
