### ISSUE TITLE
The latest finalized checkpoint at epoch 15614 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#3005]
Medalla hasn't been finalizing for a long time, and it seems the last finalized epoch has now fallen out of the WS period. Teku just shut itself down with the message

```
06:19:24.396 INFO  - Slot Event  *** Slot: 537696, Block:    ... empty, Epoch: 16803, Finalized checkpoint: 15614, Finalized root: b38064..b440, Peers: 18
06:19:28.001 INFO  - Validator   *** Published aggregate    Count: 1, Slot: 537696, Root: 4f48f4..fd39
06:19:36.053 INFO  - Validator   *** Published attestation  Count: 2, Slot: 537697, Root: 4f48f4..fd39
06:19:36.525 INFO  - Slot Event  *** Slot: 537697, Block:    ... empty, Epoch: 16803, Finalized checkpoint: 15614, Finalized root: b38064..b440, Peers: 17
06:19:40.867 FATAL - The latest finalized checkpoint at epoch 15614 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
Teku is shutting down
```

and is now refusing to start back up (same message on every launch)

[tekulog5.zip](https://github.com/PegaSysEng/teku/files/5398182/tekulog5.zip)

**Comment by ajsutton** [comment]
I'm guessing at some point you did specify a weak subjectivity checkpoint - otherwise it should only be warning.

You can avoid the shutdown with `--Xws-suppress-errors-until-epoch <big number>`.  It's still unclear how long periods of non-finality and the weak subjectivity checks need to interact to ensure safety.

**Comment by dankrad** [comment]
I did specify it, but the client had since fully caught up to the main chain and was signing attestations. So my intuition is that at that point the old checkpoint should be forgotten and the client go back to normal operation.

```--Xws-suppress-errors-until-epoch <big number>``` does seem to be a workaround but shouldn't WS checkpoints be updated by default when the client catches up?

**Comment by ajsutton** [comment]
I'm going to have to defer to @mbaxter on that as she actually knows what she's talking about with WS.  But I think it updates only when there's a new finalized checkpoint so it's struggling with Medalla not finalising.

**Comment by mbaxter** [comment]
Hey @dankrad - it's still a bit unclear how exactly we should be handling this case.  For now, if you've supplied a WS checkpoint, the client runs in a "strict" mode where it will crash if the latest finalized checkpoint falls outside of the WS period.  If you want to run in a more lenient mode (just log warnings), you can clear out the stored WS state with:  `teku admin weak-subjectivity clear-state`.

**Comment by dankrad** [comment]
As I said, workaround is currently ok for me, but I think this needs to be solved so that not all teku validators will suddenly go offline in case there is an extended non-finalized period.
