### ISSUE TITLE
Bug: Converting UnsignedLongs into ints results in a loss of precision.

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#303]
### Description
As a developer, I want to be sure proper bounds checking is performed whenever an UnsignedLong is converted to an int, so that I can be sure there isn't accidental truncation occurring. 

### Acceptance Criteria
* Document and justify each occurrence of `UnsignedLong#intValue()`, changing this to a more appropriately sized datatype if necessary.

### Steps to Reproduce (Bug)
1. Search for occurrences of `UnsignedLong#intValue()` in code.
2. Note that this is often being performed on slots, which will eventually result in loss of precision when slot # is greater than `Integer.MAX_VALUE`.

**Expected behavior:** UnsignedLongs should not be converted into ints without certainty that the UnsignedLong in question is bounded by 0 and `Integer.MAX_VALUE`.

**Actual behavior:** UnsignedLongs are being converted into ints without proper bounds checking.

**Comment by akhila-raju** [comment]
This doesn't include the case where UnsignedLongs are converted to integers for purposes of using them as an index value right?

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?
