### ISSUE TITLE
Increase visibility of weak-subjectivity warnings

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3066]
### Description
Relates to #2273 

Once we have a reliable mechanism for distributing weak subjectivity checkpoint information, we should make our weak subjectivity warnings more visible ([log to console](https://github.com/ConsenSys/teku/blob/be9378d3d67e8fb2bd0cd2cb873b339c24382544/infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/WeakSubjectivityLogger.java#L34-L34), [increase log level](https://github.com/ConsenSys/teku/blob/be9378d3d67e8fb2bd0cd2cb873b339c24382544/ethereum/weaksubjectivity/src/main/java/tech/pegasys/teku/weaksubjectivity/policies/ModerateWeakSubjectivityViolationPolicy.java#L27-L27) to WARN).

See: https://github.com/ConsenSys/teku/pull/3029

**Comment by ajsutton** [comment]
Going to close this. The current levels of warnings seem to be working well given the lack of exits on MainNet.  We can revisit later when long range attacks become a realistic threat.
