### ISSUE TITLE
Check if network validated attestations and blocks can be put into future pools without further processing

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#3114]
### Description
Check if network validated attestations can be put into future and pending pools without further processing. These two comments explain the issue:
- https://github.com/ConsenSys/teku/pull/3106#discussion_r513841244
- https://github.com/ConsenSys/teku/pull/3106#discussion_r513841480

**Comment by cemozerr** [comment]
Turns out this requires a bit of refactoring due to networking validation currently having fewer levels of result granularity than what's needed to differentiate between Pending and Future items.

**Comment by ajsutton** [comment]
I think we've changed the architecture now so that validation and adding to the right pool is handled by BlockManager and AttestationManager so we avoid duplicate processing.
