### ISSUE TITLE
Ability to disable internal slashing protection when using an external signer

### ISSUE THREAD

**Issue by jframe** [Consensys-Incorporated/teku#3122]
### Description
As an validator user using an external signer, I want to disable internal slashing protection in Teku so that external slashing protection rules can be used exclusively.

### Acceptance Criteria
* Should only apply to external signing. When the internal slashing protection is disabled, no slashing protection is done in Teku

**Comment by ajsutton** [comment]
Done in https://github.com/ConsenSys/teku/pull/3202
