### ISSUE TITLE
Refusing to sign attestation

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#3135]
Just updated teku to latest master and am getting messages like this:

```
08:39:48.303 ERROR - Validator   *** Failed to produce attestation  Slot: 653898 tech.pegasys.teku.core.signatures.SlashableConditionException: Refusing to sign attestation at slot 653898 with source epoch 19066 and target epoch 20434 because it may violate a slashing condition (See log file for full stack trace)
```
[tekulog7.zip](https://github.com/ConsenSys/teku/files/5480093/tekulog7.zip)

**Comment by rolfyone** [comment]
Thanks for raising this, we'll investigate what's going on.

**Comment by cemozerr** [comment]
Hi @dankrad,

Looking at the logs, around 2020-11-03 08:31, I see another Teku instance being initialized, potentially with the same keys. That would explain why Teku was refusing to sign the attestation above. 

Where were you running this? I'm curious about how another Teku instance could be spun up. Also had you manually set `--validators-keystore-locking-enabled` option to false by any chance?

**Comment by dankrad** [comment]
I definitely never had more than one instance running on Medalla. I do run a Spadina instance on the same machine, though, and despite specifying a different datadir with ``--data-path``, it seems to be writing its logs to the same file, so the two are getting mixed up. So maybe that's what you're seeing?
There was definitely only one instance on Medalla and with these keys running, I am always running them in the same shell window so no possibility of starting a second one by accident before I exited the previous one.

I have never used the ``--validators-keystore-locking-enabled`` option.

**Comment by cemozerr** [comment]
From the logs, I was unable to gather if this was slashing protection doing its job properly or a failure on our end, but to have a better understanding if a similar issue arises in the future, we now log the reason why slashing protection kicks in: https://github.com/ConsenSys/teku/pull/3217. 

Also, this PR (https://github.com/ConsenSys/teku/pull/3219) sets the default logfile relative to the specified datadir, so specifying different datadirs should result in different log files. 

Closing this issue as we haven't seen it repeat. Feel free to open it back up if you see it again.

**Comment by dankrad** [comment]
OK, good to have more tracking logic in there, but for the record, there is definitely a bug if the beacon node asks the VC client to make a slashable attestation, no matter whats happening (unless you re-synced your beacon node, then it might happen).
