### ISSUE TITLE
Invalid OpenAPI spec output from swagger-ui 

### ISSUE THREAD

**Issue by Magicking** [Consensys-Incorporated/teku#3209]
### Description

The output JSON specification is invalid because of an extra exampleSetFlag element.
Possible duplicate of https://github.com/swagger-api/swagger-core/issues/3702 with explanation at https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287

### Steps to Reproduce (Bug)
```bash
%> openapi-generator validate -i https://consensys.github.io/teku/latest.json
Validating spec (https://consensys.github.io/teku/latest.json)               
Errors:
	- attribute
	  paths.'/eth/v1/beacon/states/{state_id}/committees'(get).parameters.[slot].schemas.exampleSetFlag
	  is unexpected
	- attribute paths.'/eth/v1/events'(get).parameters.[topics].schemas.exampleSetFlag is
	  unexpected
[...]

[error] Spec has 108 errors.
```

**Expected behavior:** [What you expect to happen]

The specification validate.

**Actual behavior:** [What actually happens]

The specification doesn't validate.

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: d6e1ff9ed3ea56e5faf8102fa6af2d1ffcc9b2ac (latest)

**Comment by rolfyone** [comment]
swagger-docs started generating this field after an update. I have looked into it briefly, but I'll take another look and see if i can find a decent solution to the problem...
