### ISSUE TITLE
Slashing protection interchange format v5 not properly implemented

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#3223]
When exporting from Teku, the Interchange database JSON contains the fields `"sourceEpoch"` and `"targetEpoch`". According to the [interchange format spec](https://hackmd.io/@sproul/Bk0Y0qdGD#Complete-Format), these should be named `"source_epoch"` and `"target_epoch"`. This currently prevents them being imported by lighthouse (only client I tried). After substituting the two names, the import completed.

**Comment by rolfyone** [comment]
Wow, that's not changed since version 4, but it definitely doesn't look right. I only removed the metadata field for v.5, I'll check the rest of the output.
