### ISSUE TITLE
Inaccurate "expected_attestations" validator performance metric

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3261]
### Description
We record a single "[expected attestation](https://github.com/ConsenSys/teku/blob/acf069bb022a5590c3c170e57c1a71717a8154d5/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/performance/ValidatorPerformanceMetrics.java#L40-L45)" [when an unsigned attestation is created](https://github.com/ConsenSys/teku/blob/acf069bb022a5590c3c170e57c1a71717a8154d5/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java#L258).  But when [`AttestationProductionDuty.produceAttestationsForCommittee`](https://github.com/ConsenSys/teku/blob/acf069bb022a5590c3c170e57c1a71717a8154d5/validator/client/src/main/java/tech/pegasys/teku/validator/client/duties/AttestationProductionDuty.java#L112-L120) runs, it requests a single unsigned attestation and can then end up creating multiple signed attestations for each validator in the committee.  The end result is that we can end up with metrics for "included_attestations" exceeding the value of "expected_attestations".

**Comment by ajsutton** [comment]
Word of warning - we don’t want to change the validator to create a new attestation data for every validator, that would be a major performance hit when running a lot of validators. Not sure how to fix it otherwise but definitely not that answer. :)

**Comment by cemozerr** [comment]
I was thinking we could add a custom API where the validator client reports to beacon node the result of calling `sendSignedAttestation`

**Comment by ajsutton** [comment]
I'd say we want to stick to the standard API.  Actually we have to call `sendSignedAttestation` once per validator so if we just counted the number of those it would correctly report the number of produced attestations which is a good comparison to the number actually included.

From chat, Ben just mentioned:
> Fyi, my workaround in Grafana is to do sum(validator_performance_included_attestations{instance=~"$system"}) / sum(validator_local_validator_count{instance=~"$system"}) as, except for the first epoch when Teku is starting, the expected number per epoch is the number of attached validators.

That's also a useful approach and we track the number of validators based on their subnet subscriptions (which even include the ID): ActiveValidatorTracker is the class that does it.  That would give us the number of attestations we should have produced in the epoch regardless of whether the validator client failed to produce them (only has to get as far as calculating duties I think).

**Comment by cemozerr** [comment]
I think Ben's approach is the simplest and generally the best approach. A while back as I was investigating this issue, I remember noticing counting the number of `sendSignedAttestation`'s would not work either. I don't exactly remember why, but I think it was due to the fact that `createUnsignedAttestation` itself could fail too, and in that scenario we would not have called `sendSignedAttestation`
