### ISSUE TITLE
Optimise block creation for first slot of epoch

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3262]
### Description
Seeing a higher rate of orphan blocks on Pyrmont for the first slot of the epoch. This will be due to the need to do epoch processing. We should investigate what optimisations are possible.

**Comment by ajsutton** [comment]
With epoch transition now being precomputed we're seeing Teku produce the first block of epochs well inside the 4s cutoff to get votes.  It's still slower than other blocks but seems to be fast enough to be voted for.

**Comment by mcdee** [comment]
What is the process from a validator client's point of view to fetch a block proposal from teku?  Looking at the first slot of the epoch, can the validator client request the block as soon as the epoch starts (as defined by wall time) or is there a delay before teku will have applied the epoch transition and be able to provide a suitable block?

**Comment by ajsutton** [comment]
Teku is able to create a block straight away (and even a few slots before the epoch start to allow for clock skew though obviously you don't want to be creating a new block before the slots before it have had a fair chance to be filled).  The epoch transition precomputing that just went into master runs a couple of seconds before the epoch boundary but if you request before that happens or if a block comes in that invalidates it, either the get duties call or the create block call with recalculate the correct epoch transition as part of the call (and that is then cached).

The one key timing based thing the beacon chain does, which isn't automatically done by the REST API calls a validator would make is it does a "full" fork choice run 4 seconds into the slot which is when it may switch forks.  That's not as critical as it sounds though as if a new block is received that builds on the current chain head we immediately select it as the new head without having to run that "full" fork choice.  So if you requested an attestation before the full fork choice run you might be on the old branch for one more slot than you probably should have been.

That fork choice run at 4 seconds made a lot more sense when it was the start of the validator attestation process but I suspect it should move more towards the end of the slot now so it can more quickly apply the attestations from the slot and have everything ready to create the next block.  Ultimately though, this is just the beacon node doing its job of ensuring it has the right chain for you and the validator ideally shouldn't need to think about it at all.

**Comment by ajsutton** [comment]
One thing we could do, suggested by SigP is to process the next slot as soon as a block is imported.  Probably only do it for the canonical chain and then it would ensure the next block can be applied immediately.

**Comment by ajsutton** [comment]
We're seeing consistently good performance creating blocks now. There's ongoing performance work under other tickets so will close this one.
