### ISSUE TITLE
Unit test per-epoch processing functions and helpers

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#327]
Functions such as:
- updateJustification()
- get_current_epoch_boundary_attesting_balance()
- is_active_validator()
- get_validators_not_present()
- updateCrosslinks()
- crosslinkRewards()
- justificationAndFinalization()

Need to be unit tested.

**Comment by akhila-raju** [comment]
@cemozerr, has this been completed or is it still an open issue?

**Comment by cemozerr** [comment]
Still an open issue.
