### ISSUE TITLE
Add /liveness endpoint

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3283]
### Description
Add a liveness endpoint that returns 200 OK all the time.  This allows checking that the node is up even if it's syncing etc.

**Comment by ajsutton** [comment]
Can just use the metrics server for this which is probably enough but may want to consider a liveness check on the REST API itself.

**Comment by rolfyone** [comment]
wait up, this is just the health endpoint... why do we need another one?

https://ethereum.github.io/eth2.0-APIs/#/Node/getHealth
