### ISSUE TITLE
Optimise validator index lookups

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3294]
### Description
On Pyrmont, running 2048 validators per box with both internal and remote validator client, attestations aren't produced until two epochs after the node starts up.  Previously this was thought to be because the validator indices hadn't been loaded and a fix was put in for that.  Turns out it just takes this long to lookup the validator indices. See first comment for details.

**Comment by ajsutton** [comment]
There was previously a race condition looking up the validator indices which could cause this and a fix was put in. It continued happening on the Pyrmont nodes because the process of looking up 2048 validator indices in a 100k+ validator state was very slow and took about 2 epochs if the beacon node had just restarted.  Because the validator indices are cached, if only the validator client was restarted, the lookup happened quickly and attestations happened immediately.

We should look to optimise the lookup of validator indices. Currently we look up one public key at a time and add its index to the cache which means that first lookup is O(n^2) in the number of validators in the state (hence we see this on Pyrmont).  But since we’re iterating over a lot of keys to get up to the key we’re looking for we could just cache them all as we go and record how far along we got to begin the next search from there.

Updating the title of this issue to reflect the optimisation focus.

**Comment by Nashatyrev** [comment]
This could potentially speed the things up. This is not optimal but at least avoids `BLSPublicKey` creation (inside `validator.getPubkey()`) which is expensive. 

```patch
Index: ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java	(revision e313f44e3ff21041e4e1c87c0362be534263ec1d)
+++ ethereum/datastructures/src/main/java/tech/pegasys/teku/datastructures/util/ValidatorsUtil.java	(date 1603555638980)
@@ -113,8 +113,9 @@
                 key -> {
                   SSZList<Validator> validators = state.getValidators();
                   for (int i = 0; i < validators.size(); i++) {
-                    final Validator validator = validators.get(i);
-                    if (validator.getPubkey().equals(publicKey)) {
+                    Optional<BLSPublicKey> maybePubKey = getValidatorPubKey(state,
+                        UInt64.valueOf(i));
+                    if (maybePubKey.isPresent() && maybePubKey.get().equals(publicKey)) {
                       return i;
                     }
                   }
```
