### ISSUE TITLE
/eth/v1/beacon/pool/attestations not aligned with current spec

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#3302]
https://github.com/ethereum/eth2.0-APIs/pull/102 changed the body type of `/eth/v1/beacon/pool/attestations` from an object to an array, to allow for more efficient submission of attestations.  It appears that Teku does not yet support this.  Will this be implemented prior to mainnet release?

**Comment by rolfyone** [comment]
Thanks for raising this. I'll have a look at it today, our intent would be to support it prior to mainnet release.
