### ISSUE TITLE
Traffic spike at epoch boundaries

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3311]
### Description
There's a spike in traffic between Teku and other clients each epoch.  That shouldn't be necessary.

From Proto:
Ok, I've a theory: Teku is weird with status checks. If it finds a peer status with a finalized epoch that's too old w.r.t its own (very likely when checking just after an epoch transition that finalizes) it will request that block from the peer. So every epoch, there's a reasonable chance Teku nodes are requesting an old block (and maybe even so from multiple peers at once)

https://github.com/ConsenSys/teku/blob/256ec2450310b08bfb25dc2b3aacd2e3dd1594c8/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/peers/PeerChainValidator.java#L165

I've this theory that Teku nodes are sending a whole bunch of block requests every epoch boundary. Teku nodes receive more, while other nodes serve teku. And maybe lighthouse is smart enough to not serve its teku peer, when the peer status says it already has the block.

**Comment by protolambda** [comment]
![image](https://user-images.githubusercontent.com/19571989/100180599-c8b43900-2ed8-11eb-9c88-2805ce720164.png)

20 nodes per client. Lighthouse is unaffected. Nimbus and Prysm transmit more than they receive, every 6.4 minutes (= every epoch), while Teku is the opposite, receiving more.

Edit: Oh, and the high nimbus traffic is improving, that's another bug that got much better with an update (the yellow spike)

**Comment by protolambda** [comment]
![network_weird](https://user-images.githubusercontent.com/19571989/100293112-efc74500-2f82-11eb-8796-1bd5d003856d.png)

**Comment by cemozerr** [comment]
Hey @protolambda!
Any chance you ran these Teku nodes with the `--ws-checkpoint` command set? or are these our nodes on Pyrmont?

**Comment by ajsutton** [comment]
Note that we did a test where the `PeerChainValidator` code was all disabled and were still seeing the traffic spikes.

**Comment by protolambda** [comment]
> --ws-checkpoint command set? 

No, without that flag. This was about my 20 teku nodes on pyrmont. The traffic spikes, and the weird request on epoch boundary, just looked suspicious. And yes, with that code disabled, we were still seeing spikes (although not 100% accurate testing, there were other teku peers on the network)

**Comment by ajsutton** [comment]
Closing this one as we've had it hanging around for ages and haven't been able to find any reason to explain the difference.   There doesn't seem to be any practical implication of this and general network usage seems inline with what we'd expect.
