### ISSUE TITLE
Upgrade block slashing/exit validation by using ProposerSlashingValidator/VoluntaryExitValidator

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#3319]
### Description

When validating a new block or processing it on block transition the following method is used to validate bolck slashings: https://github.com/ConsenSys/teku/blob/fd7ef91e11b6e6bb8992bc5b8354b3406609147c/ethereum/core/src/main/java/tech/pegasys/teku/core/BlockProcessorUtil.java#L260

This method looks less reliable than `ProposerSlashingValidator`, e.g. it doesn't check the slashing proposer index explicitly at least. 

Would be good to use `ProposerSlashingValidator` to validate blocks slashings 

See the comment for original context: https://github.com/ConsenSys/teku/pull/3314#discussion_r530667450

The same issue with `VoluntartyExits`: https://github.com/ConsenSys/teku/pull/3314#discussion_r530667971

**Comment by Nashatyrev** [comment]
can be related to #3385

**Comment by ajsutton** [comment]
Going to close this - while we may be able to share more code, there are different requirements for validation of network gossip and block processing which justifies the two being different.
