### ISSUE TITLE
Optimization: Epoch Transition with precomputed validator status array

### ISSUE THREAD

**Issue by protolambda** [Consensys-Incorporated/teku#3326]
With Pyrmont, optimizations are critical for good validator performance. Running a sample of 20 validating Teku nodes, 250 validators each, we have observed:
- Teku blocks getting orphaned just after epoch transitions
- Gossip output dipping during epoch transitions. Causing significant asymmetrical network traffic: other clients are missing more than they are sending. Teku is still receiving data, but regularly failing to process it on time. And failing to publish data on time.

![image](https://user-images.githubusercontent.com/19571989/100410325-a7855100-306e-11eb-96ac-ce1dfa035253.png)

With some profiling, you can find Teku struggle (relative to other work) on the epoch transition during sync:

The forkchoice and the sync running a costly epoch transition:
![deltas2](https://user-images.githubusercontent.com/19571989/100408396-2b3d3e80-306b-11eb-9de3-13a7a9611858.png)

An example epoch transition:
![deltas](https://user-images.githubusercontent.com/19571989/100408421-3d1ee180-306b-11eb-9d98-a6aa03784925.png)

*(Above profiles were on a slow and memory-limited machine, don't mind the slow processing, it's about relative performance to other parts of Teku)*

Note that the majority of the epoch transition is:
- process rewards and penalties (almost 2/3 of epoch transition)
- process justification and finalization (almost 1/3 of epoch transition)

From there, the same thing happens two or three calls deeper: the pending attestations are iterated, matched against some committee data, and returning some resulting data such as "validator 1, 2, 3 participated with inclusion distance x, y, z and correct performance on target/head, while being unslashed, etc. etc.".

And it does so for 100.000+ validators. And overhead may be more than twice that, due to attestation bitlists: attestations are not perfectly aggregated, there are many more pending attestation bits in the state than validators.

Here is an example of converting some list of attestations to unslashed indices: https://github.com/ConsenSys/teku/blob/d7cdf221cba78718888462fe9b58853215f03796/ethereum/core/src/main/java/tech/pegasys/teku/core/epoch/EpochProcessorUtil.java#L92
It iterates every attestation bit of every attestation, every call of the function. And while doing so, it converts the bitlist (a byte array) to a boolean list with `getAggregation_bits` before then converting it to a list of validator indices. I'm not completely sure about allocations, but just the repeated unnecessary conversion and huge amount of data is already a great optimization target.

This is exactly what other eth2 clients did, and I strongly recommend implementing the same optimization. It works roughly like:
1. Iterate the pending attestations once during the epoch transition
2. Be as efficient as possible with iterating the attestation bits, and looking up the corresponding indices
3. Keep track of a nice summary of relevant per-validator performance (known as the "validator status array" with other implementers):
    - inclusion distance per validator
    - voting mode per validator (flags for attesting at all, attesting to the head, to the target)
    - being slashed or not (repeated state lookups slower, might as well cache being slashed or not here, local with the other validator data)
4. Sum attesting stake totals efficiently from above summary data, avoiding later lookups with the state
5. Pass the stake totals to the `process_justification_and_finalization` function
    - the stake totals are just numbers, much better than going through the whole work of 100.000 validators. Then compare some numbers, and justify/finalize or not.
6. Pass the status array and stake totals to the `process_rewards_and_penalties` function 
   - now all data for rewards/penalties can instantly be looked up from the status array, avoiding slow state access, complicated cache lookups, or painful repeated attestation bits iteration.

Edit: I also recommend pooling the "Validator statuses" array. Then you can avoid GC of it as much as possible, and not re-allocate 100.000 objects each transition.

This validator status optimization was introduced as early as April 2019 in the Eth2 workshop in Sydney, original by Lighthouse, and then developed as the spec evolved.

You can see lighthouse run the optimization here: https://github.com/sigp/lighthouse/blob/c6baa0eed131c5e8ecc5860778ffc7d4a4c18d2d/consensus/state_processing/src/per_epoch_processing.rs#L41

And then other implementations do their version of it here:
- optimized pyspec (readable but optimized, not spec v1.0.0 yet however): https://github.com/protolambda/eth2fastspec/blob/3af03bd89112b58db262da07f12fb3c6f988f6af/eth2fastspec.py#L612
- ZRNT: https://github.com/protolambda/zrnt/blob/6445ee81cda9a36bf4b3139bd74c2ce3f1ea05db/eth2/beacon/epoch.go#L46
- Prysm: https://github.com/prysmaticlabs/prysm/blob/b243665d3ef6ce588c77e16bb694c4ee6c7eb3db/beacon-chain/core/state/transition.go#L590

This should help reduce the epoch processing to something more manageable, and is hopefully enough to make Teku validators perform on-par with the best, even under high load like with Pyrmont.

And then not calling the slowest function repeatedly would also help, https://github.com/ConsenSys/teku/pull/3265 is improving that :clap:

**Comment by ajsutton** [comment]
>Edit: I also recommend pooling the "Validator statuses" array. Then you can avoid GC of it as much as possible, and not re-allocate 100.000 objects each transition.

Counter-intuitively this is generally very bad for performance in Java because it pushes all the objects into the old gen where GC is more expensive.  100k objects is a lot though so we'll have to profile and see what shows up.

**Comment by protolambda** [comment]
@ajsutton I'm not suggesting to pool them as individual objects. But to pool the thing as a whole (an array of objects). If the GC is able to efficiently ignore it as a whole, and Teku is able to consistently re-use it every 6.4 minutes, that sounds like a win to me. I'm not a JVM expert though, profiling and just seeing what works best sounds like a better idea.

**Comment by ajsutton** [comment]
> @ajsutton I'm not suggesting to pool them as individual objects. But to pool the thing as a whole (an array of objects). If the GC is able to efficiently ignore it as a whole, and Teku is able to consistently re-use it every 6.4 minutes, that sounds like a win to me. I'm not a JVM expert though, profiling and just seeing what works best sounds like a better idea.

Each entry in an array would still be its own object which the GC would have to track (not sure how smart the GC is at discarding whole subtrees when doing reference analysis these days).

But it is a unique little corner case where it may wind up being useful. Mostly commented because I wasn't adding it in the initial PR and didn't want to just completely ignore the comment.  

Initial profiling suggests the creation of the validator status is about 5% of the time and dominated by state access so unlikely to need to do caching at this point, but will have to monitor GC logs more carefully in real world scenarios.  Seeing about a 2-2.5x speed up on the old code - just pushed a few extra optimisations based on that profiling.

Next big target is to improve the performance of `PendingAttestation.getAggregation_bits`. If we get a `Bitlist` implementation that works more directly on the underlying SSZ data I suspect we can save almost 10%.

**Comment by protolambda** [comment]
Yep, sounds good. Bit access is known to be really important in this part. Since you access `validator_count * redundanty_attestations_factor`, one function call (and maybe deeper) per bit, each masking bytes and extracting booleans. Especially with boxed uints or byte types, it can get quite slow. In javascript and python we mostly solved it with specialized iterators, that do not call the get-bit method for each byte, but rather iterate over each byte slice, then each byte, then each bit, while streaming the results (via some efficient type of callback). And depending on the language, this can look very different. In JS it's faster to convert to strings than to try do native array access, to name something unexpected.
Even optimizing it a tiny bit amounts to a big overall reduction if it counts `2 * 100.000+` times.
