### ISSUE TITLE
Implement ability to fall back to a secondary Eth1 nodes if the primary node is unavailable .

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3327]
### Description
As a staker, I want to be able to fail-over automatically to a secondary/tertiary Eth1 node so that if the primary Eth1 node is unavailable or incorrect I am able to continue to propose blocks correctly. 

### Acceptance Criteria
* Configuration option to list a sequence of Eth1 nodes
* Nodes are to be tried in the specified order
* If the node I am connected to is unresponsive or incorrect, a different node should be selected. Order of retries is TBD (Start from the top again? Try round-robin?)
* Helpful log warnings are emitted to alert the operator to what is happening

**Comment by benjaminion** [comment]
Related: https://github.com/emeraldpay/dshackle
Also, [nginx](https://www.reddit.com/r/ethstaker/comments/ju08ll/howto_load_balance_your_eth1_provider_with/) can do some of the job (won't detect Eth1 node out of sync, only if it's down).

**Comment by ajsutton** [comment]
I don't seem to be able to assign this to him, but https://github.com/tbenr is looking into this.
