### ISSUE TITLE
/eth/v1/attestation_data returning out-of-date information

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#3328]
### Description

Using Teku 20.11.00.

It appears that Teku is occasionally returning poor information in the attestation data request.  Specifically, it appears to have an old source epoch.

For example, here are some Vouch logs that show it querying both Lighthouse and Teku for attestation data, along with their relevant responses:

```
{"level":"trace","service":"client","impl":"standardv1","id":"441dc588","endpoint":"/eth/v1/validator/attestation_data?slot=77760&committee_index=13","time":"2020-11-29T07:12:11Z","message":"GET request"}
{"level":"trace","service":"client","impl":"standardv1","id":"2763a030","endpoint":"/eth/v1/validator/attestation_data?slot=77760&committee_index=13","time":"2020-11-29T07:12:11Z","message":"GET request"}
{"level":"trace","service":"client","impl":"standardv1","id":"441dc588","response":"{\"data\":{\"slot\":\"77760\",\"index\":\"13\",\"beacon_block_root\":\"0x5b9f5e58dd2a54e6c0cc29d494aa93da2389fd3d2c1b9e07dc03d44a965cbe46\",\"source\":{\"epoch\":\"2429\",\"root\":\"0x1316fb5307d394903183c3ff2eb5b28e792ce2607f5a4311daf122a383957d59\"},\"target\":{\"epoch\":\"2430\",\"root\":\"0x5b9f5e58dd2a54e6c0cc29d494aa93da2389fd3d2c1b9e07dc03d44a965cbe46\"}}}","time":"2020-11-29T07:12:11Z","message":"GET response"}
{"level":"trace","service":"client","impl":"standardv1","id":"2763a030","response":"{\"data\":{\"slot\":\"77760\",\"index\":\"13\",\"beacon_block_root\":\"0xdfa159a0608151629ce1d3c87ab9545af07703b395057b61ffcde82e4ad96b72\",\"source\":{\"epoch\":\"2428\",\"root\":\"0xae00733248d9ef0e1ec0e26b6bb948220edb6c622ff3313923bdda79b84af06e\"},\"target\":{\"epoch\":\"2430\",\"root\":\"0xdfa159a0608151629ce1d3c87ab9545af07703b395057b61ffcde82e4ad96b72\"}}}","time":"2020-11-29T07:12:11Z","message":"GET response"}

```

It can be seen that the data provided by Teku has an older source epoch (2428 for Teku, 2429 for Lighthouse).  Proceeding with this data results in the attestation being dropped by the network.

Checking the timing for this slot, at the time the request was made (2020-11-29T07:12:11, as per the logs) the beacon chain was 4 seconds in to its slot (and epoch; this is on an epoch transition), so I would have expected Teku to be ready to serve the correct data.

The server on which the beacon nodes run is quite highly specced (Ryzen 9 3900, 128GB RAM, NVMe SSDs).  The log does show the block for 77760 coming in after the above calls were made:

```
07:12:07.400 INFO  - Epoch Event *** Epoch: 2430, Justified checkpoint: 2428, Finalized checkpoint: 2427, Finalized root: 800438..1d90
07:12:14.457 INFO  - Slot Event  *** Slot: 77760, Block: 5b9f5e..be46, Epoch: 2430, Finalized checkpoint: 2428, Finalized root: ae0073..f06e, Peers: 73
```

**Comment by rolfyone** [comment]
Possibly related to #3262 - it may be because of epoch boundary processing.

It looks like the API is just passing through to the server, nothing 'unusual' is needed to process the request.

Thanks for raising this, we'll look into it.
