### ISSUE TITLE
Container security tools detect java process execute a /bin/sh -c  'ldd /usr/bin/env | grep -q musl'

### ISSUE THREAD

**Issue by cdivitotawela** [Consensys-Incorporated/teku#3334]
### Description
As an security analyst, I would like to understand why Teku executes the shell sub process  `ldd /usr/bin/env | grep -q musl` within java process. Security monitoring tools reports this and if this is expected behaviour alert can be disabled. This command might not be directly related to Teku but may be executed by any of the libraries used by Teku.

### Acceptance Criteria
* Identifying the command execution is expected

### Steps to Reproduce (Bug)
No specific steps identified to reproduce the issue. However alert has been noticed periodically without any identifiable pattern.

### Versions (Add all that apply)
* Software version: teku/v20.11.0+6-g02f5443/linux-x86_64/oracle_openjdk-java-14
* Java version: openjdk version "14.0.2" 2020-07-14
* OS Name & Version:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
* Kernel Version: Linux teku-beacon-0 5.4.0-1031-azure #32~18.04.1-Ubuntu SMP Tue Oct 6 10:03:22 UTC 2020 x86_64 GNU/Linux

### Additional Information
This is an issue to report back the use of specific command so that security teams can mark the process execution as a known behaviour.

**Comment by ajsutton** [comment]
Confirmed this was done by the RocksDb library. Nothing we can do to stop it, but it is expected behaviour (even if I don't personally like it much).
