### ISSUE TITLE
OutOfMemoryError on Beacon Node - Pyrmont testnet

### ISSUE THREAD

**Issue by AbdelStark** [Consensys-Incorporated/teku#3335]
### Description

After few days of syncing on Pyrmont testnet, I am getting heap space issues on the beacon node. It is still running but this is impossible to query it, even for the validator which gets a bunch of `21:14:45.738 ERROR - Validator   *** Error while connecting to beacon node event stream java.net.SocketTimeoutException: timeout (See log file for full stack trace)`.
I know the AWS instance I am using is quite small but since I don't see any recommendation in terms of hardware requirements I create this issue for record.

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Connector-Scheduler-10f6351e-1"
23:20:07.661 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController' java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
23:20:07.662 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for p2p-async-scheduler-0 java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
23:20:07.665 FATAL - Exiting due to fatal error in p2p-async-145 java.lang.OutOfMemoryError: Java heap space (See log file for full stack trace)
Deserialization error with class: BeaconStateImpl
```

### Steps to Reproduce (Bug)
1. Let Teku run on Pyrmont for few days

**Actual behavior:** [What actually happens]

**Frequency:** Occurred once for the moment.

### Versions (Add all that apply)
* Software version: `teku/v20.11.0+6-g02f5443/linux-x86_64/corretto-java-11`
* Java version: `openjdk version "11.0.9.1" 2020-11-04 LTS`
* OS Name & Version: `centos rhel fedora`
* Kernel Version: `Linux ip-10-0-0-68.us-east-2.compute.internal 4.14.203-156.332.amzn2.x86_64 #1 SMP Fri Oct 30 19:19:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Cloud VM, type, size: `Amazon Web Services t2.medium`

**Comment by rolfyone** [comment]
Thanks for raising this.

Were you specifying '-Xmx' on the command line or in java arguments? Limiting the heap space could be helpful, especially when it's a smaller machine.
On a machine with 8GB memory, you can probably limit it with `-Xmx=5632m`. This limits the heap space, but more memory is required for non heap processes as well, so it will definitely grow above that 5GB or so.

If you have a copy of the stack trace from the logs, it would be helpful if you could attach it to this ticket.

**Comment by rolfyone** [comment]
The outstanding portion of this ticket is to update our documentation, and since there's already a documentation ticket covering that, I'll close this one.
