### ISSUE TITLE
create a CI build for blst

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3350]

**Comment by Nashatyrev** [comment]
I've had a chat with Danno on this topic. Below there are some extracts which might be useful as a starting point:

 Anton Nashatyrev  
> Hey Danno!
I'm now near the final stage of integrating Supranational Blst BLS native library (https://github.com/supranational/blst)
Speaking shortly we would like to build and publish cross-platform Java wrapper maven artifact. This looks pretty similar to besu-native project: https://github.com/hyperledger/besu-native/

Danno Ferrin:
> Since it’s C based the seckp256k1 bindings are the closest - https://github.com/hyperledger/besu-native/blob/master/secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java
secp256k1/src/main/java/org/hyperledger/besu/nativelib/secp256k1/LibSecp256k1.java

>Here is the JNA cheat sheet on type mappings - https://github.com/java-native-access/jna/blob/master/www/Mappings.md
www/Mappings.md

Anton Nashatyrev  
> I think the central topic I'd love to ask about is the building infrastructure, how to better organize the repository and how you do native shared libs packaging? Do you use some tool for the latter or did you do it manually (I mean packing them during build and then extracting them on runtime) ?
 > BTW we are currently not using JNA but stick to SWIG bindings as they are claimed to be supported by the Blst team

Danno Ferrin:
> Swig has java support?

Anton Nashatyrev  
> Yep.

Danno Ferrin:
> For building we do n+1 passes, where n is the number of binaries to produce.  First we run a pass where the native .so/.dll/.dylib is generated, and store that in CircleCI somehow.  Then we run a java step where we gather the binaries and store them in the jar, along with the java code for the wrapper.

> https://github.com/hyperledger/besu-native/blob/master/.circleci/config.yml is the CircleCI config for all
.circleci/config.yml

> we run the final jarring step directly from gradle.

Anton Nashatyrev  
> CircleCI may spin up Win/MacOS environment?

Danno Ferrin:besu:  
> Yes.  Although we haven’t taken the time to make windows builds work yet.
Looks like mac comes with xcode built in.
@ben.burns did most of the CI magic
JNA has support for loading jars from magic resource names, so we follow their pattern on where to put it in a jar.

**Comment by Nashatyrev** [comment]
Submitted the Windows related issue/question to blst team: https://github.com/supranational/blst/issues/53

**Comment by Nashatyrev** [comment]
Also filed an issue to SWIG: https://github.com/swig/swig/issues/1932
