### ISSUE TITLE
AttestationGossipAcceptanceTest intermittently fails

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3354]
### Description
Hit an intermittent test here: shouldFinalizeWithTwoNodes() - https://app.circleci.com/pipelines/github/ConsenSys/teku/9493/workflows/bdbea851-f1ca-4d88-8e19-bb4efdd9cc1a/jobs/60054

**Comment by cemozerr** [comment]
Might be related to the speed changes of the acceptance test configurations. 1 minute seems too short.
