### ISSUE TITLE
Problem on specify data-base-path on Docker image

### ISSUE THREAD

**Issue by kelvinyasu** [Consensys-Incorporated/teku#3360]
Hello...

I am trying to specify the data-base-path , but it seem there is some permission issue while I mount the data-base-path to the file system, can anyone help?

<img width="1766" alt="Screenshot 2020-12-04 at 7 02 08 PM" src="https://user-images.githubusercontent.com/7789291/101157613-5c1e0480-3665-11eb-8406-6140c47cbb8d.png">

**Comment by rolfyone** [comment]
Thanks for raising.

We recently updated the default log path to be under the data path if it's been specified, but it looks like the log-file-name-pattern path hasn't been updated.

As a work-around, you could specify
```
--log-file-name-pattern="/chaindata/logs/teku_%d{yyyy-MM-dd}.log"
```
on the command line and it should get you running again straight away.

**Comment by kelvinyasu** [comment]
Thanks, I also checked some permission issue can be fixed with chown 1000:1000 -R /xxxx which on the host system volume, Thanks.
