### ISSUE TITLE
Optimise SSZ Bitlist view

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3375]
### Description
Reading the aggregation bits from `PendingAttestation` is now one of the biggest bottlenecks for our epoch processing.  We should investigate if its possible to make Bitlist an interface and provide an implementation that reads directly from the backing node efficiently rather than iterating through to create a new Bitlist.

Other ways of optimising may also be possible.

**Comment by Nashatyrev** [comment]
Got the following picture of epoch transition with `ProfilingRun` (32K validators) :
![изображение](https://user-images.githubusercontent.com/8173857/101924091-48344e80-3be1-11eb-8638-8e6839e27998.png)
Looks there is a lot of optimization opportunities in `VectorViewImpl.packChanges()` (inside `commitChanges()`). Could check this next week
