### ISSUE TITLE
Allow external signer public keys to be loaded from url

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3378]
currently, `--validators-external-signer-public-keys` allows us to send in public keys used by an external signer, so that we know the public keys to use for validators.

It'd be nicer if they could be loaded from URL rather than having to get the public keys and then pass them into teku.

i would like to be able to do something like

`--validators-external-signer-public-keys-url http://localhost:9000/api/v1/eth2/publicKeys` 

and have teku load the public keys from http request.

**Comment by ajsutton** [comment]
I'd suggest rather than adding a new argument `--validators-external-signer-public-keys` just detects when its given an URL and loads it.
