### ISSUE TITLE
Path is assumed to be a directory

### ISSUE THREAD

**Issue by hmijail** [Consensys-Incorporated/teku#3397]
A Path is checked to see if it's a directory, and later it's assumed to still be a directory - but it could change, causing a NPE.

https://github.com/ConsenSys/teku/blob/447a7b41c84dc2bbf98849efa2eeef07fd6ccba6/services/serviceutils/src/main/java/tech/pegasys/teku/service/serviceutils/layout/SeparateServiceDataDirLayout.java#L55

**Comment by ajsutton** [comment]
I'm going to close this one as won't fix.  The code in question is part of a migration that's no longer required (https://github.com/ConsenSys/teku/issues/3406), we want to fail fast if the data dir is being concurrently modified and the exception that's raised is caught and handled appropriate (by exiting Teku).
