### ISSUE TITLE
implement hash_tree_root for BeaconState

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#340]
### Description
We need a way to calculate the hash_tree_root for BeaconState.  The spec references this functionality here:
https://github.com/ethereum/eth2.0-specs/blob/v0.1/specs/core/0_beacon-chain.md#state-root-verification

### Acceptance Criteria
* the function is already stubbed out in TreeHashUtil.java.  The method signature is: `hash_tree_root(BeaconState state)`

**Comment by vitorpy** [comment]
@jrhea If you give me some pointers on how to implement this, I'll be glad to help.

**Comment by jrhea** [comment]
@vitorpy sorry for the delay.  If you implement this: https://github.com/PegaSysEng/artemis/issues/353, then it automatically takes care of this.  All the code has been written in the state transition logic that utilizes this.  The last thing left to do is my a `toBytes()` method for BeaconState

**Comment by jrhea** [comment]
closed by #357
