### ISSUE TITLE
hash_tree_root(proof_of_possession_data.toBytes()) error

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#342]
### Description
when `validate_proof_of_posession()` calls `hash_tree_root(proof_of_possession_data.toBytes())` from `get_initial_beacon_state` from the OnChainStarted event, an error is thrown.

### Acceptance Criteria
* hash_tree_root(proof_of_possession_data.toBytes()) doesnt not error out when running Artemis

### Steps to Reproduce (Bug)
1. `./gradlew run`

**Comment by atoulme** [comment]
What is the error?
