### ISSUE TITLE
Replace Grafana dashboard link in docs

### ISSUE THREAD

**Issue by cooganb** [Consensys-Incorporated/teku#3436]
Hi there! Current [Teku Metrics Docs](https://docs.teku.consensys.net/en/latest/HowTo/Monitor/Metrics/#visualize-collected-data) provide this Grafana dashboard as the go-to:

https://grafana.com/grafana/dashboards/12199

Seems as though this is the more up-to-date dashboard, however:

https://grafana.com/grafana/dashboards/12523

**Comment by ajsutton** [comment]
Updating it to point to https://grafana.com/grafana/dashboards/13457 instead - it is designed for a single validator but is a really good starting point for people to get an idea of the key metrics and for solo stakers should be all they need. If you're running a fleet of nodes there's a good chance you'll know how to build your own dashboard targeted at your particular needs and preferences anyway.
