### ISSUE TITLE
[Feature] More helpful error message for Validator Exit Message endpoint

### ISSUE THREAD

**Issue by Magicking** [Consensys-Incorporated/teku#3467]
### Description
As a validator, I want to submit a potentially invalid signed Validator Exit Message(VEM) so that I can exit.

### Acceptance Criteria
A characterized error mentioning why the VEM is invalid.

### Steps to Reproduce (Bug)
`curl -X POST "http://127.0.0.1:5051/eth/v1/beacon/pool/voluntary_exits"  -H "accept: application/json" -d '{"message":{"epoch":"0","validator_index":"111075"},"signature":"0x90321cc3fef91133b96fcbd5620907219dd15db5a33c306cce1a30d5c53dbeb2171e0f6e00bd66ef6cfb550a71fb84d006461398c729d17e45d648180ae75b388efc1a0b36eedb63c433339ddc0851dbf0c49386a00a5a60f46f822a8ae28114"}'`

**Expected behavior:**
{"status":400,"message":"Invalid voluntary exit, the exit epoch is too early"} (this is an example)

**Actual behavior:**
{"status":400,"message":"Invalid voluntary exit, it will never pass validation so it's rejected"}

For all possible error see VEM processing:
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#voluntary-exits

**Comment by rolfyone** [comment]
It's pretty confusing, I agree. It's basically as described by the standard API currently, but we've got scope to give better error messages, just not alter the return code.

Thanks for raising this, we'll put it on the schedule to improve.

**Comment by Magicking** [comment]
Note for the future implementer/fixer, the problem shows up not only on the API but using the CLI commands as well, for example 
`./build/install/teku/bin/teku --network=pyrmont voluntary-exit --validators-external-signer-public-keys=0x964ad3bc2f60dc0523cc5e6626083f0678ac2623896222e6b81f1ce2108486c76be280daa44958e96a4f090ee03b1d62 --validators-external-signer-url=http://127.0.0.1:9100/` result in a valid VEM but invalid because epoch is too early resulting with the same « Invalid voluntary exit, it will never pass validation so it's rejected » so maybe there is also something on the default epoch selection for the CLI.
