### ISSUE TITLE
Implement Doppelganger Detection

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3493]
For discussion.

### Description
As a staker, 
I want my node to ensure that its validators are unique on the network when it starts,
so that I don't get slashed if another instance of the validator is running elsewhere. 

One way this could be accomplished is to wait 2 (say) epochs before starting to attest and watch the network. If any attestations are seen from validators I believe I own, this should trigger the kill-switch.

It should be optional (default, but able to override?) as staking services are unlikely to want to miss epochs.

A small number of instances of slashing on mainnet may have been avoidable with such a mechanism. Current folklore in the staking community is to wait at least two epochs after stopping a node before restarting; this mechanism would effectively automate that.

- [x] Add doppelganger detection activation flag
- [x] Add validators liveness check to Validator API Channel
- [x] Add doppelganger detection to Validator Client Service
- [x] Handle the validators added via the keymanager API
- [x] Add tests

@mehdi-aouadi [notes](https://hackmd.io/St0_OdKwROKSgYzGJhaZMw?view)

**Comment by rolfyone** [comment]
ref. #4453

**Comment by benjaminion** [comment]
Promoting this to "implement doppelganger detection". After discussion with users - in particular Rocket Pool and Allnodes - I'm more convinced of the importance of this. It's time to raise it on the priority list.

Doppelganger detection should be off by default, and enabled by a flag.

**Comment by benjaminion** [comment]
Useful, [Doppelganger Detection: Lessons Learned](https://hackmd.io/Szjk_d1gTrWGuUsLojmoqA)
