### ISSUE TITLE
Add validators without restarting Teku

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3494]
### Description
As a staking service operator, I want to be able to add validators to a running Teku instance without restarting so that I can add new deposits without downtime.

#### How

* Validator keys are specified as usual via config file, cli etc
* Adding validators is done by updating the config file and then sending a SIGHUP to the teku instance.  Note that it's not possible to change CLI args or env vars while the process is running
* Teku will reload the config, including redownloading any URLs provided (eg for external validator public keys).  Any new validators detected will be added and begin performing duties.
* Always log a message when the config is being reloaded even if there are no changes.
* Log public keys of any newly added validators.
* Teku should not exit if a validator key is unable to be loaded when reloading the config, just log the error.
* Teku should not reload keys it already has (the `pubkey` field of the keystore is assumed to be correct for this purpose)
* Teku should never, under any circumstances wind up with the same validator key loaded twice. 
* Removing validators isn't supported in the initial version.  If we can, printing a warning that the validator is not being removed would be good.

Web3Signer changes are out of scope for this ticket (will be handled by Groot).

#### Notes

 - Need to take strong measures to ensure that any changes are intentional. For example calling a "refresh validators" API after installing the new keys.
 - Similar functionality should be made available in Web3Signer, and the Teku side of remote signing should integrate with that.
 - I'm assuming that it is much simpler to only have funcionality to add validators. Removing and moving validators looks tricky in terms of managing slashing data etc.

**Comment by rolfyone** [comment]
- spike:
    - how many ways can we add validators?
    - methods for loading? SIGHUP?
    - is removing included? - no - consider how it might fit with signaling.

specific use case - web3signer, add new validator clients

**Comment by rolfyone** [comment]
web3signer would require a restart to add new validators currently @benjaminion 

this would mean adding a validator using web3signer requires 
 - add keys to right location
 - restart web3signer
 - restart teku

Will initially focus on a spike to solve the teku side, but we should consider whether we put an enhancement in for web3signer.
