### ISSUE TITLE
investigate alternatives to RocksDB

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3495]
RocksDB seems less than ideal for Teku. In particular, it is believed to be causing substantial growth in native memory usage over time, which we have failed to get on top of.

Are there other databases that would be an improvement, such as alternative kv stores like LevelDB, or ones that offer more structured storage?

 - Investigate LevelDB as an alternative to RocksDB - [3 days]
    - is it embedded?
    - is it likely to be a relatively small rewrite, or extensive to get a prototype to play with?
 - Are there fast alternatives to RocksDB other than LevelDB? [1 day]

**Comment by ajsutton** [comment]
LevelDB is clearly a big improvement.  Separate tickets logged to roll it out.
