### ISSUE TITLE
Spike: what mechanisms could be used to add validator keys to teku without a restart [2D]

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3505]
- for example, it is relatively common for 'reload' logic in services in linux to reload configuration while running, without a restart
 - could folder locations be watched, or an admin api added?
 - other possible mechanisms that would avoid a restart?
 - we don't need remove functionality at the moment, but would we be able to fit it in as a similar mechanism?

time box: 2 days

related to #3494

**Comment by ajsutton** [comment]
Updated description of #3494.
