### ISSUE TITLE
Give ViewRead, ViewWrite, ViewType classes better names

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#3539]
### Description

Backing tree view classes were kind of internal behind `BeaconState` and its members until recent refactorings (#3426, #3512). 

Since then they became kind of first class citizens: 
- `ViewType` (and subclasses) refers to a particular SSZ type describing its scheme 
- `ViewRead` (and subclasses) refers to an immutable SSZ instance. 
- `ViewWrite` (and subclasses) refers to a mutable SSZ instance.
- `*ViewWriteRef` refers to a mutable SSZ instance which also may give the reference to a mutable child (see `getByRef()`) and track changes made there.  `*ViewWriteRef` is kind of shortcut and optimized version of: `[get immutable child] + [create its mutable copy] + [update it] + [get a new updated immutable instance] + [set the new instance back to parent]`

Their class names are not so obvious in a new context, so it makes sense to give them better names. 

> https://github.com/ConsenSys/teku/pull/3426#issuecomment-772902993

I personally like these variants suggested by @ajsutton : `SszData`, `SszMutableData` and `SszSchema`

**Comment by Nashatyrev** [comment]
These new names look awesome to me: 
- `SszData` (former `ViewRead`) 
  - `SszList` (former `ListViewRead`) 
  - `SszVector` (former `VectorViewRead`) 
  - `SszContainer` (former `ContainerViewRead`) 
  - `SszComposite` and `SszCollection` intermediate interfaces 
- `SszMutableData` (former `ViewWrite`) 
  - `SszMutableList` (former `ListViewWrite`) 
  - `SszMutableVector` (former `VectorViewWrite`) 
  - `SszMutableContainer` (former `ContainerViewWrite`) 
  - `SszMutableComposite` and `SszMutableCollection` intermediate interfaces 
- `SszSchema` (former `ViewType`) 
  - `SszContainerSchema`, `SszListSchema`, `SszVectorSchema` etc...
  
Not quite sure about current `ViewType` and `SszType` interfaces. They were intended to logically separate serialization related methods (`SszType`) and backing tree view operations, but not sure if this distinction and general idea is so obvious now and probably it's worth to merge them into a single base interface (`SszSchema`)

**Comment by Nashatyrev** [comment]
Also not sure what could be a better name for current `*WriteRef` classes? `SszMutableRef*` ?

Though these interfaces are still hidden behind `BeaconState` so probably no big sense to bother with inventing anything better

**Comment by ajsutton** [comment]
Renaming is pretty cheap really so I'd go with the list you have which seems pretty good.  I'm not sure exactly how the `*WriteRef` classes fit in but `SszMutableRef*` seems to fit the new pattern fairly well.  We don't have to get it perfect the first time so let's just pick something and if we don't like it and think of something better later we can change again.

**Comment by Nashatyrev** [comment]
Additionally: 
- `BasicView` -> `SszPrimitive`
- `ViewUtils` -> `SszUtils`
- `BasicViewType` -> `SszPrimitiveSchema`
