### ISSUE TITLE
Make gossip scoring information visible to users

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3557]
### Description
Following up on #3457, we should make gossip scoring visible in some way.  A few ideas:
* Have a REST API endpoint where we can pull peer info, where each peer has scoring information available
* Look into whether or not there is any way to expose scoring over metrics:
  * Maybe we could have a histogram where we periodically add peer scores?

This will make it easier to test and validate that scoring is working how we expect.

**Comment by BogdanStirbat** [comment]
Hi!

I was thinking about working on this issue. I can see that `GetPeers` class exposes a REST endpoint `/eth/v1/node/peers` for retrieving the list of peers. Perhaps I can add a new similar REST endpoint, `/eth/v1/node/peers/gossip-scoring`, returning a map peerId (String) -> gossipScore (Double).

To use libp2p in order to compute gossip scoring for a peer, I can use something similar to [this](https://github.com/Nashatyrev/jvm-libp2p-minimal/blob/0.8.0/src/test/kotlin/io/libp2p/pubsub/gossip/GossipScoreTest.kt) : 

```
        val peer = mockPeer()

        val peerScoreParams = GossipPeerScoreParams(
            decayInterval = 1.seconds,
            behaviourPenaltyWeight = -1.0,
            behaviourPenaltyDecay = 0.9,
            behaviourPenaltyThreshold = 5.0
        )
        val scoreParams = GossipScoreParams(peerScoreParams)
        val timeController = TimeControllerImpl()
        val executor = ControlledExecutorServiceImpl(timeController)

        val score = GossipScore(scoreParams, executor, { timeController.time })
```

Is this a solid plan?

**Comment by mbaxter** [comment]
Hello @BogdanStirbat! 👋 

I think the first step in getting this implemented will involve actually exposing the [peer scores from jvm-libp2p](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt#L135). 
 One option would be to add a method for getting a peer score by peer id to the [Gossip class](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt#L23) (`GossipScore` being available at `router.score`).

**Comment by BogdanStirbat** [comment]
Hi @mbaxter ,

Thank you for the explanation! I will add a method to get a peer score by `PeerId` in the [Gossip class](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt#L23) . To get a `PeerId` from a `peer`, can I use `new PeerId(peer.peerId.getBytes())`? 

Also, I've noticed that the libp2p version used in Teku is `io.libp2p:jvm-libp2p-minimal:0.8.1-RELEASE`. I should push the changes to [jvm-libp2p](https://github.com/libp2p/jvm-libp2p/), master, so that they will part of next release, right?

**Comment by mbaxter** [comment]
> Thank you for the explanation! I will add a method to get a peer score by `PeerId` in the [Gossip class](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt#L23) . To get a `PeerId` from a `peer`, can I use `new PeerId(peer.peerId.getBytes())`?

Np!  You can just do `peer.peerId`: [example](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/src/main/kotlin/io/libp2p/pubsub/gossip/GossipScore.kt#L146)

> Also, I've noticed that the libp2p version used in Teku is `io.libp2p:jvm-libp2p-minimal:0.8.1-RELEASE`. I should push the changes to [jvm-libp2p](https://github.com/libp2p/jvm-libp2p/), master, so that they will part of next release, right?
 
Yep, that's the right repo.  You'll want to fork that repo, and create a branch of off `develop`.  The changes from `develop` are periodically bundled up and merged to `master` when we do releases.

**Comment by BogdanStirbat** [comment]
I understand. Thank you! I added a [pull request](https://github.com/libp2p/jvm-libp2p/pull/188) for retrieving peer score by peerId. After the changes will reach `master` and next jvm-libp2p version, I will continue working on this issue.

**Comment by mbaxter** [comment]
@BogdanStirbat - thanks for the jvm-libp2p contribution!  If you want to go ahead with the teku implementation without waiting for the jvm-libp2p release, you can run against the jvm-libp2p `develop` branch by following these steps:
* From the jvm-libp2p side:
  * Bump up the jvm-libp2p version [here](https://github.com/libp2p/jvm-libp2p/blob/6cac516d2ea5f75d96dcc4f0167ff0affd94fd6f/build.gradle.kts#L15)
  * Run `./gradlew publishToMavenLocal` to make your local build available to teku
* From teku:
  * Update the jvm-libp2p version to match your local build [here](https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/gradle/versions.gradle#L41)
  * Rebuild teku

Hope that makes sense - let me know if you have any questions!

**Comment by mbaxter** [comment]
> I was thinking about working on this issue. I can see that `GetPeers` class exposes a REST endpoint `/eth/v1/node/peers` for retrieving the list of peers. Perhaps I can add a new similar REST endpoint, `/eth/v1/node/peers/gossip-scoring`, returning a map peerId (String) -> gossipScore (Double).

I'd add the new scoring endpoint as a [teku-specific handler](https://github.com/ConsenSys/teku/tree/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/tekuv1) at something like `/teku/v1/nodes/peer_scores`.  And I'd probably have it return a list of `PeerScores` where each `PeerScore` has a `peer_id` and a `gossip_score`.

**Comment by BogdanStirbat** [comment]
@mbaxter - thank you for reviewing the pull request, and for the explanations, as well!

Yes, I understand how I can go ahead with the teku implementation without waiting for a new jvm-libp2p release.

I understand, I will add a new handler. The list of peers will be retrieved from a `NetworkDataProvider network`, and `NetworkDataProvider network` will be injected via construction injection, like in [GetPeers](https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/node/GetPeers.java) handler, right?

**Comment by mbaxter** [comment]
> I understand, I will add a new handler. The list of peers will be retrieved from a `NetworkDataProvider network`, and `NetworkDataProvider network` will be injected via construction injection, like in [GetPeers](https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/node/GetPeers.java) handler, right?

Yep, sounds right!

**Comment by BogdanStirbat** [comment]
Thank you!

I'm having difficulties injecting [Gossip](https://github.com/libp2p/jvm-libp2p/blob/develop/src/main/kotlin/io/libp2p/pubsub/gossip/Gossip.kt) into a handler (like [GetSszState](https://github.com/ConsenSys/teku/blob/9c0086ca5af0f90eddc26ca437475adfa7afc914/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/tekuv1/beacon/GetSszState.java) for example). Should this be done through a provider?

**Comment by mbaxter** [comment]
The Gossip instance is available [here](https://github.com/ConsenSys/teku/blob/d87b37a47bacea9a72cc1106e822f343988b3304/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/gossip/LibP2PGossipNetwork.java#L159).  I'd suggest exposing a method `getGossipScore()` on the [Peer](https://github.com/ConsenSys/teku/blob/d87b37a47bacea9a72cc1106e822f343988b3304/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/peer/Peer.java#L26) interface.  The lowest level peers are constructed in [`PeerManager`](https://github.com/ConsenSys/teku/blob/d87b37a47bacea9a72cc1106e822f343988b3304/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/libp2p/PeerManager.java#L72).  You should be able to inject that `Gossip` object into `PeerManager`, which will allow you to inject the scoring functionality into `LibP2PPeer`.  Then, you can grab your peers from the `NetworkDataProvider` just like `GetPeers`, and print out the scoring values you get from `peer.getGossipScore()`.  Does that make sense?

**Comment by BogdanStirbat** [comment]
Yes, it does, thank you! I will continue working, and I will inform you if I find other difficulties. I think that it's best to commit after the new version of libp2p is released, so that build will pass.

**Comment by mbaxter** [comment]
Hey @BogdanStirbat - If you wouldn't mind, it would be great if you could put up a draft PR of your work before we do the jvm-libp2p release.  As a general matter of process, that tends to work better so that if we need to make any adjustments on the jvm-libp2p side we don't end up with multiple releases making small tweaks.  

It is unfortunate that CI won't pass for now, but you can just leave a note in the PR description explaining that the work depends on a jvm-libp2p release.  We were just discussing how to improve this process - hopefully we can get this streamlined soon!

**Comment by BogdanStirbat** [comment]
I understand. Sure, no problem!

**Comment by BogdanStirbat** [comment]
I've added a draft PR: https://github.com/ConsenSys/teku/pull/3885

**Comment by mbaxter** [comment]
Thanks @BogdanStirbat - looks great! 🎉 I'll try to do a proper review today and get a jvm-libp2p release out!
