### ISSUE TITLE
move SSZ definitions into spec

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3564]
### Description

Migrate container definitions and datastructures into the new `spec` module.  See https://github.com/ConsenSys/teku/pull/3546

Acceptance Criteria:
* Address all  todos labelled `TODO(#3564)`

**Comment by rolfyone** [comment]
@mbaxter are we talking about basically relocating the teku.ssz module into spec.ssz?

**Comment by mbaxter** [comment]
@rolfyone - No, this is about completing the transition of moving specific `SszSchema` definitions for [eth2 containers](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#containers) (`BeaconState`, etc) to spec-versioned [`SchemaDefinitions`](https://github.com/ConsenSys/teku/blob/66979d8087a8a8e03a51a2baa7f0523aef1c78be/ethereum/spec/src/main/java/tech/pegasys/teku/spec/schemas/SchemaDefinitions.java#L21-L30).  Many of the container schemas reference `SpecConfig` values, and they can all theoretically be versioned.  Right now a lot of the schema definitions are defined statically, [for example](https://github.com/ConsenSys/teku/blob/66979d8087a8a8e03a51a2baa7f0523aef1c78be/ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/operations/IndexedAttestation.java#L52), when they should be instances on a `SchemaDefinitions` object.

**Comment by benjaminion** [comment]
Is this issue still alive, or can we close it now?

**Comment by mbaxter** [comment]
I still see a number of [static SSZ_SCHEMA definitions](https://github.com/ConsenSys/teku/search?q=SSZ_SCHEMA).  For [example](https://github.com/ConsenSys/teku/blob/45b4375239ef26d0f1141a289cfdd60e3285eea8/ethereum/spec/src/main/java/tech/pegasys/teku/spec/datastructures/operations/Deposit.java#L46) :D

**Comment by ajsutton** [comment]
Meredith is going to hate me for this, but I'm going to close this as I don't think we're getting any value from having the issue sitting around. We have the pattern established well enough now and will migrate the remaining things to schema definitions when and if we need to.
