### ISSUE TITLE
"teku failed to start" with no other error information - logs attached

### ISSUE THREAD

**Issue by kyleboddy** [Consensys-Incorporated/teku#3571]
### Description
As a user trying to run teku after depositing 32 ETH, I want to get the client working, but it crashes with no usable information.

### Steps to Reproduce (Bug)
1. Follow the [Consensys first blog post](https://consensys.net/blog/blockchain-explained/my-journey-to-becoming-a-validator-on-ethereum-2-0/) on depositing 32 ETH using Metamask - succeeds.
2. Follow the [Consensys second blog post](https://consensys.net/blog/developers/my-journey-to-becoming-a-validator-on-ethereum-2-0-part-2/) on building the validator machine. Chose to build locally, Ubuntu 20.04 LTS 64-bit, signed up for Infura endpoint, installed Java/Teku, registered non-root user, used systemd services, all of which succeeded.
3. Test to see if port 9000 is being forwarded properly using netcat and it hits the Infura endpoint properly; succeeds. 
4. Run teku using systemd or yaml configuration files; teku fails to start with no further information.

**Expected behavior:** 
Teku runs as written about in the two blog posts cited above.

**Actual behavior:**
Upon running teku and enabling verbose logs, I get errors using the systemd method as well as the yaml configuration file method. I Google them and see no similar errors, likely because there is no information after teku crashes, unlike p2p port 9000 problems or Java stacktrace dumps.

```
validator@ethvalidator:~/teku-21.1.1/bin$ sudo systemctl stop teku
validator@ethvalidator:~/teku-21.1.1/bin$ ./teku --config-file ~/tekuconfig/validatorconfig.yaml --logging=ALL
2021-02-09 22:43:05,597 main INFO Setting logging level to ALL
2021-02-09 22:43:05,844 main INFO Configuring logging for destination: console and file
2021-02-09 22:43:05,844 main INFO Logging file location: ~/tekudata/logs/teku.log
2021-02-09 22:43:05,844 main INFO Logging includes events: true
2021-02-09 22:43:05,844 main INFO Logging includes validator duties: true
2021-02-09 22:43:05,845 main INFO Logging includes color: true
22:43:05.916 INFO  - Teku version: teku/v21.1.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
22:43:05.917 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
22:43:05.997 INFO  - Loading 1 validator keys...
22:43:06.275 INFO  - Storing beacon chain data in: /home/validator/teku-21.1.1/bin/~/tekudata/beacon
22:43:12.992 INFO  - Loading initial state from jar:file:/home/validator/teku-21.1.1/lib/teku-ethereum-networks-21.1.1.jar!/tech/pegasys/teku/networks/pyrmont-genesis.ssz
22:43:14.604 INFO  - Loaded initial state at epoch 0 (state root = 0x2bb257ca66d05a047a65fe43a5f457b674de445d917cca029efb09b3ba4758c4, block root = 0x6a89af5df908893eedbed10ba4c13fc13d5653ce57db637e3bfded73a987bb87, block slot = 0).
22:43:14.623 INFO  - Initializing storage
22:43:16.969 INFO  - Storage initialization complete
22:43:17.251 INFO  - Loading generated p2p private key from: generated-node-key
22:43:18.041 INFO  - PreGenesis Local ENR: enr:-KG4QKD1BNAYmnmGebxNR90JeTsoNC3GmXb_fFAl1im5mgnIXqHKnjrtGGV8J4BMKSNBmhvEPB3C2zLfA8npH-jp8ycFhGV0aDKQ1Uz1lwAAIAn__________4JpZIJ2NIJpcIR_AAEBiXNlY3AyNTZrMaECZFNfRQeWEs3F8gMG9VZiTSqGchH64nkHen8R9ZHEeQ2DdGNwgiMog3VkcIIjKA
22:43:18.468 INFO  - Listening for connections on: /ip4/127.0.1.1/tcp/9000/p2p/16Uiu2HAm2BJV4CefQrMMT1dJ5Tz2KRjYM1F7JyhB3rnQVowJqqoJ
Teku failed to start

To display full help:
teku [COMMAND] --help
```

**Frequency:** 
100 percent of the time.

### Versions 
* Software version: teku/v21.1.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: openjdk version "11.0.9.1" 2020-11-04, OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04), OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
* OS Name & Version: Ubuntu 20.04.2 LTS, Focal Fossa
* Kernel Version: Linux ethvalidator 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thank you for reviewing this.

**Comment by kyleboddy** [comment]
validatorconfig.yaml:


```
# network
network: "pyrmont"

# p2p
p2p-enabled: true
p2p-port: 9000

# validators
validator-keys: REDACTED
validators-graffiti: "Teku Validator"

# Eth 1
eth1-endpoint: REDACTED

# metrics
metrics-enabled: true
metrics-categories: ["BEACON","LIBP2P","NETWORK"]

# database
data-path: "~/tekudata"
data-storage-mode: "archive"

# rest api
rest-api-port: 5051
rest-api-docs-enabled: true
rest-api-enabled: true

# logging
log-include-validator-duties-enabled: true
```

Validator link:

https://mainnet.beaconcha.in/validator/0xb308bde486e893f7825b80579cc083354eaafe7cc55444b97a77afe4b39698687df39b1a642f3cb580bae64e2f5b13ba

**Comment by benjaminion** [comment]
Thanks for the detailed report! Just to note that this looks identical to https://github.com/ConsenSys/teku/issues/3481. You may find pointers to a solution there: it was a permissions issue on the validator key files in that case. The lack of an error message on exit ought to be fixed in the next release (due in the next day or so).

**Comment by kyleboddy** [comment]
Got it. It wasn't a permissions error, it was in fact my own stupidity. I didn't realize there was a different logging option, and upon doing that, I got an "invalid keystore password" error and realized I had the wrong information in my appended text file for the password. Upon fixing that mistake, it's running great!

Discord was super helpful - posting the logs here for the next people up!

![image](https://user-images.githubusercontent.com/746351/107478278-0f0b5280-6b2e-11eb-8403-7133fec49826.png)

The only thing that I would request is the slightly confusing idea that turning logging to ALL didn't dump everything to console and had to be pointed out to me in Discord.
