### ISSUE TITLE
Consider simplifying jvm-libp2p-related config

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3573]
### Description
We currently have a lot of config builders that basically duplicate existing configuration builders in `jvm-libp2p`.  We should consider simplifying this logic and just relying on the jvm-libp2p builders.  See conversation here: https://github.com/ConsenSys/teku/pull/3534#discussion_r572919557

**Comment by ajsutton** [comment]
Closing this as the current code works fine and no real reason to revisit it specifically.  If we find it difficult to work with in the future normal refactoring practices should be used to sort it out.
