### ISSUE TITLE
Update to latest LevelDB

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3587]
### Description
The fuse source LevelDB JNI wrapper hasn't been updated for quite a while.  We should create our own fork and upgrade to the latest LevelDB version.

**Comment by rolfyone** [comment]
It's been reported that the old library will be a problem for anyone on windows, due to the age of the leveldb dll, so we should take this into account when setting priority.

**Comment by benjaminion** [comment]
Closing this venerable issue as a duplicate of #6138
