### ISSUE TITLE
Migrate all spec-related logic into new spec module

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3596]
### Description
Part of #3356 - migrate all spec-related logic (implementations from the [eth2.0-specs repo](https://github.com/ethereum/eth2.0-specs/tree/dev/specs/phase0)) into the new `spec` package, exposing all versioned logic through an instance of `Spec`.

**Comment by ajsutton** [comment]
I think we've managed to move all this stuff now, so closing.
