### ISSUE TITLE
Get node syncing status API is missing the is_syncing field

### ISSUE THREAD

**Issue by jclapis** [Consensys-Incorporated/teku#3634]
### Description
Hi! I'm working with the REST API for Teku. I noticed that in the official documentation for [Get node syncing status](https://consensys.github.io/teku/#operation/getEthV1NodeSyncing), there is a field named `is_syncing` which indicates whether or not the client is still syncing with the beacon chain. However, when I hit this endpoint, the `is_syncing` field is missing:

```
$ curl http://localhost:5052/eth/v1/node/syncing
{"data":{"head_slot":"52","sync_distance":"667925"}}
```

As a workaround, I have to check if `sync_distance` is within some small margin (e.g. less than 3) in order to determine if the client is still syncing or not.

### Steps to Reproduce (Bug)
1. See example shown above

**Expected behavior:** [What you expect to happen]
```
{"data":{"head_slot":"52","sync_distance":"667925","is_syncing":true}}
```

**Actual behavior:** [What actually happens]
```
{"data":{"head_slot":"52","sync_distance":"667925"}}
```

**Frequency:** [What percentage of the time does it occur?]
100%

### Versions (Add all that apply)
* Software version: v21.1.1
* Java version: openjdk 14.0.2 2020-07-14
* OS Name & Version: Ubuntu 20.04.2 LTS
* Kernel Version: Linux dev-pi 5.4.0-1028-raspi #31-Ubuntu SMP PREEMPT Wed Jan 20 11:30:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
* Virtual Machine software & version: N/A
* Docker Version: N/A
* Cloud VM, type, size: N/A

**Comment by akashapool** [comment]
I confirm the absence of the  is_syncing field. In a production fully sync node - the result is
```
curl http://localhost:5051/eth/v1/node/syncing
{"data":{"head_slot":"590150","sync_distance":"0"}}
```

**Comment by ghost** [comment]
Hello, I confirm the above and the absence of the is_syncing field. In a production fully sync node the result is:

```
curl http://localhost:5051/eth/v1/node/syncing
{"data":{"head_slot":"590150","sync_distance":"0"}}
```

**Comment by ajsutton** [comment]
Thanks for reporting this - the `is_syncing` field was only quite recently added to the standard API and to Teku (in #3528) so it hasn't been included in a release yet.  The API docs appear to be defaulting to lastest/master version - there's a toggle at the top of the page to choose the right version, but unfortunately doesn't look like links to a specific method maintain the version, which may well have led to this confusion.

I'll close this one as the field will be there when the next release goes out but have logged https://github.com/ConsenSys/doc.teku/issues/255 and https://github.com/ConsenSys/doc.teku/issues/256 to get the doc links issue fixed.
