### ISSUE TITLE
HF1  - consensus - sync committees

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3648]
https://notes.ethereum.org/@vbuterin/HF1_proposal#Sync-committees

Acceptance Criteria:
* Address todos labelled `TODO(#3648)`

**Comment by rolfyone** [comment]
spec PR has been merged: https://github.com/ethereum/eth2.0-specs/pull/2130

**Comment by ajsutton** [comment]
Going to close this one - the state transition is complete, gossip is handled under #3803 and there are separate tickets for the validator duties.
