### ISSUE TITLE
Feature request: add beacon node version to prometheus metrics

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#3664]
### Description
As a user I would lie to be able to access teku version information via prometheus.

### Acceptance Criteria

A metric in prometheus that provides the version, for example:

```
teku_info{version="21.2.0"} 1
```

would be nice. Additional labels can be added for other items if desired (commit hash or whatever).

**Comment by ajsutton** [comment]
For the record, we generally like this idea but just need to find some time to do it.

**Comment by rolfyone** [comment]
Labels are a little messy.

Prometheus allows basically `[a-zA-Z_][a-zA-Z0-9_]*`, and reserves starting with `_` for internal use.

Our dev version string (complicated example) is `v21.2.0+42-gb443919`, and that would need translation to be consistent with what's allowed in labels. If I replace '.' and '+' with '_', and drop any other invalid characters (the '-') then it would translate to: `v21_2_0_42gb443919`

The far simpler, and probably more 'normal' example is a release version. so `v21.2.0` would become the label `v21_2_0`

If there's any feedback, I'd be very interested to hear.

**Comment by mcdee** [comment]
Is this label names or label values where the restrictions apply?  As far as I can see label values have no restrictions, so a metric

```
teku_info{version="v21.2.0+42-gb443919"} 1
```

would be acceptable, although that's somewhat verbose compared to other implementations and so

```
teku_info{version="21.2.0" release="v21.2.0+42-gb443919"} 1
```

may make more sense, with `release` having the full details and 'version' being the headline value used elsewhere in your release notes _etc_.
