### ISSUE TITLE
Avoid basic authentication credentials from being leaked to log files 

### ISSUE THREAD

**Issue by asanso** [Consensys-Incorporated/teku#3668]
Similarly to https://github.com/ConsenSys/teku/pull/3622 the authentication credentials might end up being leaked in the log files when voluntary exits are performed: 

https://github.com/ConsenSys/teku/blob/f5693d9f83dda4fd4be30702eed12b67e3afa11d/teku/src/main/java/tech/pegasys/teku/cli/subcommand/VoluntaryExitCommand.java#L205

**Comment by rolfyone** [comment]
thanks for logging this, I'll add this to our prioritised list.

**Comment by rolfyone** [comment]
fixed by #3704
