### ISSUE TITLE
Ssz: sharing the same mutable instance - how to handle? 

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#3679]
### Description

Use case: 
`EpochProcessor.processFinalUpdates(MutableBeaconState state):`
```java
    state.setPrevious_epoch_attestations(state.getCurrent_epoch_attestations());
    state.getCurrent_epoch_attestations().clear();
```
Here the `state.getCurrent_epoch_attestations()` is an ssz list which is aimed to be 'moved' from the `current_epoch_attestation` filed to the `previous_epoch_attestation` field. 
The issue is that this is a mutable list acquired 'by reference' and after the first line the same instance is shared by both `current_epoch_attestation` and `previous_epoch_attestation` fields. The second line effectively clears both fields. 

The right code would be either 
```java
    state.setPrevious_epoch_attestations(state.getCurrent_epoch_attestations().commitChanges());
    state.getCurrent_epoch_attestations().clear();
```
or (is not currently allowed but might be fixed): 
```java
    state.setPrevious_epoch_attestations(state.getCurrent_epoch_attestations());
    state.setCurrent_epoch_attestations(
        BeaconState.CURRENT_EPOCH_ATTESTATIONS_FIELD_SCHEMA.get().getDefault());
```

The question is: should we somehow handle or disallow the original case or leave it for the client code to sort out?

**Comment by mbaxter** [comment]
I think it would be nice to disallow this (probably throw an exception), if possible.

**Comment by Nashatyrev** [comment]
I believe I have another solution, will prepare PR shortly ...
