### ISSUE TITLE
Feature: push certain node metrics to remote services

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3682]
There is a proposal for clients to support the ability to regularly push some metrics data to remote services to provide added value for individual stakers.

 - [Design document](https://docs.google.com/document/d/1qPWAVRjPCENlyAjUBwGkHMvz9qLdd_6u9DPZcNxDBpc/edit)
 - [Discussion](https://discord.com/channels/595666850260713488/746343380900118528/816259997678960661) (on the EthStaker Discord)

If we were to implement this, I suggest that
 1. it is off by default, and
 2. users provide the delivery endpoint URL as a parameter.

**Comment by ajsutton** [comment]
This looks to be a duplicate of #3773.
