### ISSUE TITLE
investigate 2853 implementation [1D]

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3709]
- get block by parent root
 - is storage an easy change? (new column, maybe lookup by slot also)

**Comment by rolfyone** [comment]
- would need to add a storage column and index for orphaned blocks
   - potentially an index by parent root as well as proposer slot
 - StoreTransactionUpdatesFactory would write orphaned blocks prior to pruning them from data structures.

 - alter historical fetch to fetch orphaned blocks?

 - potentially implement `/eth/v1/beacon/headers` by parent_root parameter, which would be complicated as no index exists currently for existing blocks, but the value is reduced if only supporting orphaned blocks.

without a parent_root index, the only way to tell its orphaned is to get headers from the following slot and see if any of those blocks have this parent...

estimates:
 - storage - 3d
 - api - 5d

so looking at maybe 1 sprint worth of work as a rough estimate.

**Comment by rolfyone** [comment]
The other point made during discussions at standup was that it will only be for orphaned blocks you've physically seen.

For example, we're several months past the start of mainnet. If we start a sync today we'll miss any of the older orphaned blocks before now, because we wont have received them, we'll only have the canonical chain passed back when we perform a sync, and there isn't any way to get the orphaned historic blocks.

**Comment by ajsutton** [comment]
Closing this as we now support recording orphaned blocks that we've seen.
