### ISSUE TITLE
Vote for random block instead of previous eth1data

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3712]
### Description
When there are no candidate Eth1 data votes, Teku should vote for a random Eth1 block. Currently it votes for the current Eth1Data (https://github.com/ConsenSys/teku/blob/9dbbe4333ab34c4ff802c31dd5857c343128b32a/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/Eth1DataCache.java#L81)

**Comment by rolfyone** [comment]
it does look like the spec is in line with what we're doing, so I haven't made any changes here until we determine what needs to be done.

**Comment by ajsutton** [comment]
Confirmed Teku is following the spec correctly.  We should probably open an issue on the eth2 specs repo with the suggestion that the current eth1 data is not considered a valid vote and only used as the fallback.

That way even if the first proposer has no valid blocks and votes for the current eth1 data block, other proposers would still prefer to vote for data that progresses the eth1 chain rather than just following that vote.  This would also essentially make the current eth1 data vote a replacement for any need to create random votes.

**Comment by ajsutton** [comment]
Proposed spec change being discussed in https://github.com/ethereum/eth2.0-specs/issues/2227

**Comment by ajsutton** [comment]
Teku is following the spec and it doesn't look like we're going to agree on a spec change prior to the merge. Post merge we'll be focussed on removing eth1 voting entirely so going to close this.
