### ISSUE TITLE
Add Javadocs and Cleanup BlockProcessorUtil

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#373]
### Description
As a code maintainer, I want BlockProcessorUtil well documented so that I better understand the operations being performed per-block. 

### Acceptance Criteria
* Code is sufficiently refactored to pass code review and javadoc coverage is near 100% for all public methods.

**Comment by akhila-raju** [comment]
This still requires work.

**Comment by akhila-raju** [comment]
@schroedingerscode are you actively working on this?
