### ISSUE TITLE
Altair parameters prematurely included in /config/spec response

### ISSUE THREAD

**Issue by michaelsproul** [Consensys-Incorporated/teku#3749]
### Description

Some Lighthouse users noticed that their Infura beacon nodes stopped functioning once Infura updated to Teku v12.3.0. The issue is that Lighthouse is very strict about the chain spec parameters returned from the `/eth/v1/config/spec` endpoint, and Teku now includes Altair parameters.

### Possible Solutions

* Change the API spec to be explicit about how specs should be served across hard forks. I haven't thought about this in detail yet, but it's probably the best long-term solution.
* (Temporarily) change Lighthouse's validator client to be less strict (https://github.com/sigp/lighthouse/issues/2274)
* Change Teku to only return phase0/genesis chain specs until Altair is in effect (or closer).

### Steps to Reproduce

```bash
curl -s "https://x:y@eth2-beacon-mainnet.infura.io/eth/v1/node/version"
```

```json
{
  "data": {
    "DEPOSIT_CONTRACT_ADDRESS": "0x00000000219ab540356cBB839Cbe05303d7705Fa",
    "MIN_ATTESTATION_INCLUSION_DELAY": "1",
    "SLOTS_PER_EPOCH": "32",
    "INACTIVITY_SCORE_BIAS": "4",
    "SHUFFLE_ROUND_COUNT": "90",
    "MAX_EFFECTIVE_BALANCE": "32000000000",
    "DOMAIN_BEACON_PROPOSER": "0x00000000",
    "DOMAIN_SYNC_COMMITTEE": "0x07000000",
    "MAX_ATTESTER_SLASHINGS": "2",
    "DOMAIN_SELECTION_PROOF": "0x05000000",
    "INACTIVITY_PENALTY_QUOTIENT": "67108864",
    "LIGHT_CLIENT_UPDATE_TIMEOUT": "8192",
    "MAX_VALID_LIGHT_CLIENT_UPDATES": "8192",
    "SAFE_SLOTS_TO_UPDATE_JUSTIFIED": "8",
    "SECONDS_PER_ETH1_BLOCK": "14",
    "HYSTERESIS_UPWARD_MULTIPLIER": "5",
    "MIN_SEED_LOOKAHEAD": "1",
    "VALIDATOR_REGISTRY_LIMIT": "1099511627776",
    "MIN_DEPOSIT_AMOUNT": "1000000000",
    "SLOTS_PER_HISTORICAL_ROOT": "8192",
    "PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR": "2",
    "MIN_VALIDATOR_WITHDRAWABILITY_DELAY": "256",
    "DOMAIN_VOLUNTARY_EXIT": "0x04000000",
    "TARGET_COMMITTEE_SIZE": "128",
    "MAX_VALIDATORS_PER_COMMITTEE": "2048",
    "MIN_GENESIS_TIME": "1606824000",
    "HYSTERESIS_QUOTIENT": "4",
    "RANDOM_SUBNETS_PER_VALIDATOR": "1",
    "DOMAIN_DEPOSIT": "0x03000000",
    "ALTAIR_FORK_VERSION": "0x01000000",
    "DEPOSIT_CHAIN_ID": "1",
    "WHISTLEBLOWER_REWARD_QUOTIENT": "512",
    "PROPOSER_REWARD_QUOTIENT": "8",
    "DOMAIN_RANDAO": "0x02000000",
    "EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION": "256",
    "EPOCHS_PER_HISTORICAL_VECTOR": "65536",
    "MIN_PER_EPOCH_CHURN_LIMIT": "4",
    "MIN_SLASHING_PENALTY_QUOTIENT_ALTAIR": "64",
    "EPOCHS_PER_ETH1_VOTING_PERIOD": "64",
    "MAX_DEPOSITS": "16",
    "HISTORICAL_ROOTS_LIMIT": "16777216",
    "SYNC_COMMITTEE_SIZE": "1024",
    "TARGET_AGGREGATORS_PER_COMMITTEE": "16",
    "EPOCHS_PER_SLASHINGS_VECTOR": "8192",
    "MIN_SLASHING_PENALTY_QUOTIENT": "128",
    "PROPORTIONAL_SLASHING_MULTIPLIER": "1",
    "MAX_VOLUNTARY_EXITS": "16",
    "HYSTERESIS_DOWNWARD_MULTIPLIER": "1",
    "DOMAIN_BEACON_ATTESTER": "0x01000000",
    "SYNC_SUBCOMMITTEE_SIZE": "64",
    "GENESIS_DELAY": "604800",
    "EPOCHS_PER_SYNC_COMMITTEE_PERIOD": "256",
    "MAX_SEED_LOOKAHEAD": "4",
    "ETH1_FOLLOW_DISTANCE": "2048",
    "SECONDS_PER_SLOT": "12",
    "MIN_GENESIS_ACTIVE_VALIDATOR_COUNT": "16384",
    "MIN_SYNC_COMMITTEE_PARTICIPANTS": "1",
    "MAX_ATTESTATIONS": "128",
    "GENESIS_FORK_VERSION": "0x00000000",
    "DEPOSIT_NETWORK_ID": "1",
    "EJECTION_BALANCE": "16000000000",
    "MAX_COMMITTEES_PER_SLOT": "64",
    "SHARD_COMMITTEE_PERIOD": "256",
    "EFFECTIVE_BALANCE_INCREMENT": "1000000000",
    "INACTIVITY_PENALTY_QUOTIENT_ALTAIR": "50331648",
    "DOMAIN_AGGREGATE_AND_PROOF": "0x06000000",
    "MIN_EPOCHS_TO_INACTIVITY_PENALTY": "4",
    "BASE_REWARD_FACTOR": "64",
    "CONFIG_NAME": "mainnet",
    "MAX_PROPOSER_SLASHINGS": "16",
    "CHURN_LIMIT_QUOTIENT": "65536",
    "BLS_WITHDRAWAL_PREFIX": "0x00"
  }
}
```

### Versions

Teku v21.3.0

```json
{
  "data": {
    "version": "teku/v21.3.0/linux-x86_64/oracle_openjdk-java-15"
  }
}
```

Lighthouse v1.2.1

**Comment by benjaminion** [comment]
Acknowledging the issue.

Additional references:
  - Specification: https://ethereum.github.io/eth2.0-APIs/#/ValidatorRequiredApi/getSpec
  - The standard paramter list: https://github.com/ethereum/eth2.0-specs/blob/v1.0.0-rc.0/configs/mainnet/phase0.yaml

The API specification could be clearer about whether additional fields are allowable or not. I suspect that both Lighthouse and Teku are breaking [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle) in this case.

I have kicked off a conversation with Infura, but can't promise an immediate resolution. Pragmatically, making the suggested change at the Lighthouse end is likely the shortest path to getting the users up and running again.

**Comment by skmgoldin** [comment]
I'm sort of against this move, but hypothetically if we at Infura were to downgrade our Teku beacon nodes, would that break Teku validators who are running v12.3.0?

**Comment by benjaminion** [comment]
> hypothetically if we at Infura were to downgrade our Teku beacon nodes, would that break Teku validators who are running v12.3.0?

Nothing ought to break between 21.2.0 and 21.3.0, but it's an untested configuration, so I can't make absolute promises. We note in the release notes when we know of possible version incompatibilities, but there's a chance of unexpected things happening I guess.

**Comment by michaelsproul** [comment]
I've got a PR up to Lighthouse that restores compatibility: https://github.com/sigp/lighthouse/pull/2277

I'll close this issue for now, as I think we're leaning towards thinking that the current API spec is good-enough, and Lighthouse just needs to be less strict. If anyone thinks of a reason why the current API spec is inadequate we can open an issue on the specs repo.
