### ISSUE TITLE
Refactor TreeHashUtil to use Cava Convenience Methods

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#375]
### Description
As an implementer, I want the ability to calculate the hash tree root of a` java.util.List<Integer>` using Cava convenience methods so that my code is easily maintainable and does not duplicate functionality provided by our libraries. 

### Acceptance Criteria
* `TreeHashUtil.integerListHashTreeRoot` should use the native Cava convenience method writeUInt##List once support is added.

### Additional Information
Depends on https://github.com/ConsenSys/cava/issues/184

**Comment by akhila-raju** [comment]
@schroedingerscode, has this been completed or is it still an open issue?

**Comment by akhila-raju** [comment]
This needs to be updated since TreeHashUtil no longer exists.
