### ISSUE TITLE
Events API sends incorrect data

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#3750]
### Description
The API endpoint `/eth/v1/events` sends incorrect data for the 'block' topic.

### Acceptance Criteria
Data should match that described in the spec at https://ethereum.github.io/eth2.0-APIs/#/Events/eventstream

### Steps to Reproduce (Bug)
- run `curl -H "Accept: text/event-stream" 'http://localhost:5051/eth/v1/events?topics=block'`
- check output

Expect to see data of the form:
```
event:block
data:{"slot":"877361","block":"0x84bc86680b329dbf4ab1d6d0be342da47ff5a80c8ba176edc6748e4855e02bcf"}
```

however Teku returns the entire `SignedBeaconBlock` struct.

### Versions (Add all that apply)

teku/v21.3.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-14

**Comment by rolfyone** [comment]
Thanks for raising. I've put up a PR and adjusted our tests to reflect the standard api.

This is technically breaking obviously, but hopefully we can release it without too many issues.
