### ISSUE TITLE
Use atomic write for signing records

### ISSUE THREAD

**Issue by jmcruz1983** [Consensys-Incorporated/teku#3800]
### Description
As a validator, I want local slashing protection to ignore corrupted/empty signing records.

### Steps to Reproduce (Bug)
1. Having a validator running with loaded 1000 keys with local slashing protection enabled.
2. Loaded keys got reduced to 500.
3. And validator got restarted.
4. Error related to corrupted file in slashing protection directory started to appear in logs.
5. After inspecting slashing protection directory, we observed that some yaml files got 0 bytes size.

Log stack trace:
`
teku-validator-2-0 teku 13:40:41.676 ERROR - Validator   *** Failed to produce attestation  Slot: 850101 Validator: <REDACTED>
teku-validator-2-0 teku java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
teku-validator-2-0 teku  at [Source: (byte[])""; line: 1, column: 1]
teku-validator-2-0 teku 	at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecordSerialization.readRecord(ValidatorSigningRecordSerialization.java:52) ~[teku-data-signingrecord-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecord.fromBytes(ValidatorSigningRecord.java:67) ~[teku-data-signingrecord-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.Optional.map(Optional.java:258) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.core.signatures.LocalSlashingProtector.loadSigningRecord(LocalSlashingProtector.java:87) ~[teku-ethereum-core-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.core.signatures.LocalSlashingProtector.lambda$maySignAttestation$1(LocalSlashingProtector.java:61) ~[teku-ethereum-core-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:78) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.core.signatures.LocalSlashingProtector.maySignAttestation(LocalSlashingProtector.java:58) ~[teku-ethereum-core-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.core.signatures.SlashingProtectedSigner.signAttestationData(SlashingProtectedSigner.java:64) ~[teku-ethereum-core-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.signAttestationForValidator(AttestationProductionDuty.java:150) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$signAttestationsForCommittee$5(AttestationProductionDuty.java:136) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
teku-validator-2-0 teku 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
teku-validator-2-0 teku 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
teku-validator-2-0 teku 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
teku-validator-2-0 teku 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
teku-validator-2-0 teku 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
teku-validator-2-0 teku 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty$Committee.forEach(AttestationProductionDuty.java:186) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.signAttestationsForCommittee(AttestationProductionDuty.java:135) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$produceAttestationsForCommittee$2(AttestationProductionDuty.java:120) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.Optional.map(Optional.java:258) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$produceAttestationsForCommittee$4(AttestationProductionDuty.java:118) ~[teku-validator-client-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:144) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:495) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:29) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:139) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$25(SafeFuture.java:339) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:144) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2315) ~[?:?]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:495) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:29) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:139) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:236) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
teku-validator-2-0 teku 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
teku-validator-2-0 teku 	at java.lang.Thread.run(Thread.java:832) [?:?]
teku-validator-2-0 teku Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
teku-validator-2-0 teku  at [Source: (byte[])""; line: 1, column: 1]
teku-validator-2-0 teku 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.11.2.jar:2.11.2]
teku-validator-2-0 teku 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4666) ~[jackson-databind-2.11.2.jar:2.11.2]
teku-validator-2-0 teku 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4511) ~[jackson-databind-2.11.2.jar:2.11.2]
teku-validator-2-0 teku 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3527) ~[jackson-databind-2.11.2.jar:2.11.2]
teku-validator-2-0 teku 	at tech.pegasys.teku.data.yaml.YamlProvider.read(YamlProvider.java:66) ~[teku-data-yaml-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecordSerialization.readRecord(ValidatorSigningRecordSerialization.java:50) ~[teku-data-signingrecord-21.2.0.jar:21.2.0]
teku-validator-2-0 teku 	... 48 more
`

Corrupted files in _data/validator/slashprotection_:
`-rwxrwxrwx 1 root teku   0 Mar 29 13:24 <REDACTED>.yml`

`-rwxrwxrwx 1 root teku   0 Mar 29 14:22 <REDACTED>.yml`

**Frequency:** 2 files got corrupted failing to produce attestations every time these keys were used.

### Acceptance Criteria
* Slashing protection should ignore corrupted signing records.
* Validator should be able to override/fix empty file.

### Versions (Add all that apply)
* Software version: `21.2.0`
* Java version: `openjdk 15.0.2 2021-01-19`
* OS Name & Version: `Debian GNU/Linux 10 (buster)`
* Kernel Version: `Linux teku-validator-0-0 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 GNU/Linux`
* Cloud VM, type, size: `AKS v1.18.14`

**Comment by ajsutton** [comment]
We definitely don't want to ignore corrupt files as that would create opportunities to be slashed.

In your case since you're using web3signer with its slashing protection anyway, my suggestion would be to disable the inbuilt slashing protection from teku entirely with `--validators-external-signer-slashing-protection-enabled=false`.

It's interesting that the files got cleared by not written to as we do use fsync to flush the write immediately.  When the validator was restarted was it a clean shutdown or was a k8s pod just terminated?

We could potentially look at writing to a temp file then doing an atomic move to replace the existing one - it's more expensive to do though and I'm not sure if it would actually be more atomic when using a network drive.
