### ISSUE TITLE
Standardised metrics

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3843]
For discussion.

There is an initiative from Leo (Barcelona Supercomputer Centre) and a colleague to standardise the naming of a subset of metrics across clients. The idea is that this would make dashboards more portable between clients, and reduce client "lock-in" for users.

A draft proposal is [here](https://docs.google.com/spreadsheets/d/1OrToYWl-XeIfTItBM6iqEsWjynmXu0ctyOj-83qzBVM/edit#gid=0).

**Comment by rolfyone** [comment]
I've gone through and colour coded the appropriate fields, we've got some gaps that may be useful metrics...

**Comment by rolfyone** [comment]
now that this has been merged to beacon-metrics, raised a ticket #4288 to track that change. closing this ticket.
