### ISSUE TITLE
Wrong automatic epoch calculation of validator voluntary exit

### ISSUE THREAD

**Issue by gbayasgalan** [Consensys-Incorporated/teku#3862]
Description

testing voluntary-exit with more validators which are created (activated same time). 

1) Tried it with option `--epoch="current_epoch" ` on validator-1 and it works, validator-1 is exited. 
2) Tried without option `--epoch="current_epoch" ` on validator-2 (which is still active) and it doesn't work

Expected behavior: 
successfully exiting of validator with default option (without `--epoch="current_epoch"`)

Actual behavior:
```
Failed to submit exit for validator b8a7d8e
Invalid params response from Beacon Node API (url = http://beacon:5051/eth/v1/beacon/pool/voluntary_exits, response = {"status":400,"message":"Exit for validator 210225 fails process voluntary exit conditions Specified exit epoch is still in the future."}) 
```

Software version: 
OS Name & Version: Ubuntu 20.04
* Kernel Version: 
Linux eth2-test-server 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Docker Version: 
```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:01 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by rolfyone** [comment]
I'll try to replicate the problem, it's good that specifying the epoch does work, but it would be nice to not have to do that.
