### ISSUE TITLE
Failed to produce attestation

### ISSUE THREAD

**Issue by felso** [Consensys-Incorporated/teku#3866]
I'm getting an exception on 1 of my 2 validators. It's currently missing every attestation. This started after my machine filled the disk, I cleared space, and restarted.

Apr 16 09:06:11 eth2mainnet teku[2811]: 09:06:11.558 ERROR - Validator   *** Failed to produce attestation  Slot: 979529 Validator: 0x916b142397d57e0bd0dcffb4d583e039ae26b615f76d65e2a14ed5b06fd7158a24cb2ac9ada11a6cffb8ec7178f4e3a5
Apr 16 09:06:11 eth2mainnet teku[2811]: java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
Apr 16 09:06:11 eth2mainnet teku[2811]:  at [Source: (byte[])""; line: 1, column: 1]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecordSerialization.readRecord(ValidatorSigningRecordSerialization.java:52) ~[teku-data-signingrecord-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecord.fromBytes(ValidatorSigningRecord.java:67) ~[teku-data-signingrecord-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.Optional.map(Optional.java:265) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.core.signatures.LocalSlashingProtector.loadSigningRecord(LocalSlashingProtector.java:87) ~[teku-ethereum-core-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.core.signatures.LocalSlashingProtector.lambda$maySignAttestation$1(LocalSlashingProtector.java:61) ~[teku-ethereum-core-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:78) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.core.signatures.LocalSlashingProtector.maySignAttestation(LocalSlashingProtector.java:58) ~[teku-ethereum-core-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.core.signatures.SlashingProtectedSigner.signAttestationData(SlashingProtectedSigner.java:67) ~[teku-ethereum-core-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.signAttestationForValidator(AttestationProductionDuty.java:150) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$signAttestationsForCommittee$5(AttestationProductionDuty.java:136) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty$Committee.forEach(AttestationProductionDuty.java:186) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.signAttestationsForCommittee(AttestationProductionDuty.java:135) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$produceAttestationsForCommittee$2(AttestationProductionDuty.java:120) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.Optional.map(Optional.java:265) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.validator.client.duties.AttestationProductionDuty.lambda$produceAttestationsForCommittee$4(AttestationProductionDuty.java:118) ~[teku-validator-client-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:144) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:501) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:29) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:139) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$25(SafeFuture.java:339) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:144) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$11(SafeFuture.java:241) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:78) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:70) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Apr 16 09:06:11 eth2mainnet teku[2811]: Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
Apr 16 09:06:11 eth2mainnet teku[2811]:  at [Source: (byte[])""; line: 1, column: 1]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.11.2.jar:2.11.2]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4666) ~[jackson-databind-2.11.2.jar:2.11.2]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4511) ~[jackson-databind-2.11.2.jar:2.11.2]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3527) ~[jackson-databind-2.11.2.jar:2.11.2]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.data.yaml.YamlProvider.read(YamlProvider.java:66) ~[teku-data-yaml-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         at tech.pegasys.teku.data.signingrecord.ValidatorSigningRecordSerialization.readRecord(ValidatorSigningRecordSerialization.java:50) ~[teku-data-signingrecord-21.4.0.jar:21.4.0]
Apr 16 09:06:11 eth2mainnet teku[2811]:         ... 49 more

* Software version: [teku/v21.4.0/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11
* Java version: openjdk version "11.0.10" 2021-01-19
* OS Name & Version: Ubuntu 20.04
* Kernel Version: 5.8.0-49-generic

**Comment by mbaxter** [comment]
@felso - it looks like one of your slashing protection records got corrupted.  If you check the record for this validator, I suspect that file will be empty. The record should be at `<data-dir>/slashprotection/<validatorpubkey>.yml`

**Comment by mbaxter** [comment]
You generally want to be very careful with the slashing protection files.  But in this case (if you do confirm that the yml file is corrupted), since your validator has been offline for several hours, it should be fine to: stop the node, delete the corrupted file (leaving the other files untouched!), and restart.  To be extra safe, you may want to wait for a few epochs before restarting the node.

**Comment by felso** [comment]
Thank you @mbaxter. That worked. Both validators are currently working.

**Comment by mbaxter** [comment]
We're looking into making this easier to clean up in the future: https://github.com/ConsenSys/teku/issues/3868
