### ISSUE TITLE
subcommand to repair slashing protection files that are corrupted

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#3868]
as a validator, I want corrupted files to be able to be repaired
so that I don't have to manually find and delete corrupt files.

- should warn about clock skew, and once accepting the risk we can update the slashing protection files

 - update invalid files by default (files that can't be parsed, eg 0 sized files), values should be written to the next epoch

 - potentially have a `-a` option to update all the valid files as well

- potentially require a flag to cleanup lock files, and should respect file locking by default in case someone tries to run the subcommand while teku is online.

 - potentially allow user to set a (future) epoch

**Comment by ajsutton** [comment]
Yep definitely should use keystore file locking for safety. I would default to listing which valets will be updated and why and requiring confirmation of that for safety. Particularly important to confirm the epoch/slot being recorded is actually safe. 
Probably should default to picking values that are two epochs in the future for safety as well.

**Comment by rolfyone** [comment]
and flatly refuse to go 'below' whats in a file if it's already a valid file...

**Comment by rolfyone** [comment]
related to #3800
