### ISSUE TITLE
Swap-or-Not Shuffle - (Spec PR #576)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#388]
### Description
As an implementer, I want the client shuffling algorithm to use the more efficient "swap-or-not" shuffle as described in v0.2.0 of the spec [Eth2 Spec PR #576](https://github.com/ethereum/eth2.0-specs/pull/576) so that Artemis is compliant with the beacon chain specification. 

### Acceptance Criteria
* Artemis's set shuffling implementation uses the algorithm defined in the linked PR.
* Adequate test coverage of the change is maintained.

### Additional Information
* Please refer to https://github.com/ethereum/eth2.0-specs/pull/576.
* **NOTE**: See https://github.com/ethereum/eth2.0-test-generators/issues/10 for an open issue concerning updating shared tests to use the latest shuffling algorithm.

**Comment by benjaminion** [comment]
Closed by #420
