### ISSUE TITLE
Expose new metrics per validator status in validator client

### ISSUE THREAD

**Issue by joaorodrigues-consensys** [Consensys-Incorporated/teku#3892]
We currently can retrieve all validators via `validator_local_validator_count` metric. We were looking to track validators count per statuses per validator client. As we pre-allocate validator clients with a set of keys to be used in the future, there are no metrics that tell us how many pending, active and exited validators are in a given validator client.

 As an example, it could expose the following metrics (one per [ValidatorStatus](https://github.com/ConsenSys/teku/blob/master/data/serializer/src/main/java/tech/pegasys/teku/api/response/v1/beacon/ValidatorStatus.java)):
- `validator_local_validator_pending_initialized_count`
- `validator_local_validator_pending_queued_count`
- `validator_local_validator_active_ongoing_count`
- `validator_local_validator_active_exiting_count`
- `validator_local_validator_active_slashed_count`
- `validator_local_validator_exited_unslashed_count`
- `validator_local_validator_exited_slashed_count`
- `validator_local_validator_withdrawal_possible_count`
- `validator_local_validator_withdrawal_done_count`

**Comment by rolfyone** [comment]
These metrics got blocked by not having a gauge with labels in the library we're using, but I'll add this to the backlog and we'll see if we can get it unblocked...

We might also look into the standard api proposal and see if there's currently related metrics. Thanks for raising.

**Comment by rolfyone** [comment]
added a labelled gauge into besu, once that ships we'll be able to progress the teku portion of this ticket.

**Comment by rolfyone** [comment]
once besu release is out we can do teku portion.
