### ISSUE TITLE
Unsupported network string gave out generic error "Failed to load spec config"

### ISSUE THREAD

**Issue by quangld** [Consensys-Incorporated/teku#3902]
### Description
I made a mistake in config.yaml file by specified:
`network: "main"`
instead of
`network: "mainnet"`

when I started teku with --config-file, it gave me the error:
`Failed to load spec config`

I took me 5 minutes to track down the mistake.

### Suggestion:
I wish the error is more detail. Such as:
`network "main" is unsupported`

### Versions
* Software version: v21.4.1
* Java version: 14
* OS Name & Version: Ubuntu 20.04

**Comment by ajsutton** [comment]
The `--network` option takes either one of the known networks or a file or URL to a config file (matching the format in the beacon chain spec). So it really is trying to tell you that it couldn't load the spec config from "main". That's not to say the error message couldn't be improved, but it's not as simple as just saying that "main" is unsupported unfortunately.
