### ISSUE TITLE
Forks - Update Eth2GossipTopicFilter to handle multiple forks

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#3911]
### Description
Currently, `Eth2GossipTopicFilter` assumes we'll have at most 2 active forks, and calculates which topics are relevant for the current fork and next fork.  We need to update this logic to handle additional fork transitions.  

See: https://github.com/ConsenSys/teku/blob/03cad2146de627653ebef2091354874d7d488029/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/gossip/topics/Eth2GossipTopicFilter.java#L46-L47

**Comment by mbaxter** [comment]
Looks like we're only validating that the forkDigest matches currently, which is what we want: https://github.com/ConsenSys/teku/blob/b12f64fa2b3c4be0de7c2814d5146f8d6b10c352/networking/p2p/src/main/java/tech/pegasys/teku/networking/p2p/discovery/DiscoveryNetwork.java#L191-L200

**Comment by ajsutton** [comment]
Done a little while back.
