### ISSUE TITLE
Metrics for operation pool size and usage

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3917]
Add metrics to `OperationPool` to record how many items are in each type of pool. 
Also metrics for how often the `SAVE_FOR_LATER` validation reason is used for each type.

**Comment by seroze** [comment]
Hi @ajsutton , can you point to some other code  where metrics is being recorded for reference, also when I did a `grep -r  'SAVE_FOR_LATER'  .` I didn't see any results.

**Comment by ajsutton** [comment]
Hey @seroze,
Turns out I should have said `SAVE_FOR_FUTURE` sorry - it's `tech.pegasys.teku.statetransition.validation.ValidationResultCode.SAVE_FOR_FUTURE`

The `tech.pegasys.teku.statetransition.OperationPool` class will likely be the place that needs to record these metrics. Metrics are tracked through the `MetricsSystem` class (a library that comes from besu).  You can see some examples of this in the `BeaconChainMetrics` class in Teku.  For these metrics I suspect a simple `metricsSystem.createIntegerGauge` for the number of items in the pool and `metricsSystem.createLabelledCounter` for tracking validation reasons.  I'd say use a labelled counter there so we can keep track of counts for all the validation results, which will then cover SAVE_FOR_FUTURE but also allow tracking the number of rejected items which would be useful as well (and even accepted would show the rate items are added to the pool well).

**Comment by ermyas** [comment]
Hi - is anyone working on this issue at the moment? If not I'd like to take it up. Thanks

**Comment by seroze** [comment]
Hi @ermyas , was busy with my work so forgot to update here, my  code changes are done, will raise a PR today.
