### ISSUE TITLE
Update get_previous_epoch Helper - (Spec PR #565, #592)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#392]
### Description
As an implementor, I want `get_previous_epoch` to be updated so that Artemis is compliant with v0.4 of the Beacon Chain spec.

### Acceptance Criteria
* `get_previous_epoch` in `BeaconStateUtil` should use `Constants.GENESIS_EPOCH` in the comparison to cut down on duplicated code.
* Update logic in `get_previous_epoch` helper to match optimized logic in PR# 592 (linked below). 
* Changes should be adequately tested.

### Additional Information
* See https://github.com/ethereum/eth2.0-specs/pull/565
* See https://github.com/ethereum/eth2.0-specs/pull/592

**Comment by benjaminion** [comment]
Closed by #437
