### ISSUE TITLE
Apple Silicon M1 support?

### ISSUE THREAD

**Issue by Sajjon** [Consensys-Incorporated/teku#3920]
I would like to know if Teku supports Apple Silicon M1 chip?

**Comment by rolfyone** [comment]
Currently we have a number of third party libraries that need to have native support, as well as our build pipeline supporting it.

I'll add this ticket to our backlog, and we'll be able to schedule it once we have the libraries and infrastructure able to support M1.

**Comment by ajsutton** [comment]
https://github.com/ConsenSys/jblst/pull/15 adds M1 support to BLST but we'll then need either RockDB or LevelDB (preferably LevelDB) Java wrappers built for M1 before it can be natively supported and they'll be more difficult.

**Comment by paulmillr** [comment]
@rolfyone is there a list of libraries somewhere?

**Comment by ajsutton** [comment]
The two key ones are jblst (which has a PR https://github.com/ConsenSys/jblst/pull/15 that creates what appears to be a valid FAT binary for Mac x86 and ARM but doesn't appear to load it correctly when using an M1 native JVM - hopefully an easy fix for someone who can test and debug it on an actual M1 machine).  

And the other is LevelDB which is more difficult.  We're using https://github.com/fusesource/leveldbjni which has a fairly outdated build system (the autoconf version it uses doesn't appear to be available on the Linux boxes I've tried) and it needs a few tweaks to work with the latest version of LevelDB.  I have managed to get it compiling for Mac with the latest LevelDB so could share that work but I wasn't able to get it compiling on Linux, though someone more familiar with auto tools may find it easy to sort out.  I don't recall if I managed to get it cross compiling on Mac but generally once you get things building the cross compilation to create a FAT binary is fairly straight forward with the Mac toolchain.

Worth noting that Teku running on an x86 JVM does run fine on an M1 Mac via Rosetta translation.

**Comment by KaloyanTanev** [comment]
@ajsutton can you share the steps on how you managed to get leveldbjni running on Apple Silicon?

**Comment by ajsutton** [comment]
@KaloyanTanev 

> @ajsutton can you share the steps on how you managed to get leveldbjni running on Apple Silicon?

Sorry for the delay in getting back to you on this.  I'm pretty hazy on what I'd actually done as I'm not at all familiar with cmake.  I did manage to get leveldbjni compiling on Mac again and with the latest leveldb - I removed support for enabling and disabling compaction to reduce the changes required in leveldb source code.  That's at https://github.com/ajsutton/leveldbjni/pull/1 - the `build.sh` script has the steps to compile.

It doesn't look like I got it cross compiling but configure args in the pom include `<arg>--with-universal=x86_64</arg>` which looks like a good place to be able to add arm64.  Generally cross compiling on Mac is relatively straight forward like that.

The bigger issue was that I couldn't get it to compile on Linux at all as the autoconf tools appear to require an old version that I wasn't able to install.  They're probably available on older Linux versions and hopefully updating to more recent versions isn't too hard but it was getting well outside my area of knowledge by then and I ran out of time to look into it.

**Comment by KaloyanTanev** [comment]
@ajsutton 
Thanks for the reply, I have been trying to run the script for the past 2 days using JDK 11, but some issues with hawtjni-maven-plugin emerged. I will give update here as soon as I have something running, could be beneficial for somebody from the future :).

**Comment by paulmillr** [comment]
jblst now supports M1. I think the only part left is teku itself.

**Comment by ajsutton** [comment]
> jblst now supports M1. I think the only part left is teku itself.

Teku itself is java so just needs a native JVM which exist.  The remaining problem however remains LevelDB (or RocksDB), neither of which currently have an M1 build.

**Comment by paulmillr** [comment]
For reference: https://github.com/facebook/rocksdb/issues/7720

**Comment by ajsutton** [comment]
For the record, we're considering putting out a GitCoin bounty to update the LevelDB JNI wrapper and would likely either include Apple Silicon support in that or make it a follow on bounty.  Actually getting that setup on GitCoin may take a bit of time but if some funding would help anyone get LevelDB JNI updated and supporting Apple Silicon feel free to get in touch and we may be able to arrange it.

**Comment by agiletechuk** [comment]
Hi Guys, Ive been looking at getting the apache spark code building on an m1 mac and saw it also depends on leveldbjni (as does a few other projects). So I took your pr and tried to progress. I did a few small changes to get it to work on osx12 and changed the with-universal -> with-universal-archs and got the tests successfully running. When I used this library in the kvstore in spark it compiled and tested ok but then tests in higher modules are failing so not really sure if ultimately this component is actually good or not. I agree with the comments above about the state of the leveldbjni project. Its a bit hacky with generated code checked in and coppies of native libraries in multiple locations it really needs a good sorting out. Great work to reomove the patch on leveldb tho

**Comment by ajsutton** [comment]
@agiletechuk Have you seen https://github.com/ConsenSys/leveldbjni-native ? It provides fully working builds of leveldbjni with updated leveldb for Mac and Linux (including ARM support for both).

We don't currently have a Windows build for it (PRs very welcome) but you can use it with the older version of leveldb that the leveldbjni project publishes and you wind up with up to date leveldb on Mac and Linux and the older version on Windows.

Our deps wind up as:
```
    dependency 'org.fusesource.leveldbjni:leveldbjni-win64:1.8'
     dependency 'org.fusesource.leveldbjni:leveldbjni-win32:1.8'
     dependency 'tech.pegasys:leveldb-native:0.2.0'
```
