### ISSUE TITLE
Verify the convenience functions in Cava to load Bytes uses little endian byte order - (Spec PR #564)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#394]
### Description
As an implementor, I want all Cava `Bytes` types I create to be little endian, so that my implementation is compliant with the Beacon Chain spec. 

### Acceptance Criteria
* All occurrences where the Cava `Bytes` type is created in our code (i.e. `Bytes.ofUnsignedLong`, `Bytes.wrap`, `Bytes.fromHexString`, etc.) should use return a little endian bytes value.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/564

**Comment by benjaminion** [comment]
This needs to be a bit more nuanced. For example, this would seriously break the BLS stuff if applied there.

I'm happy to take this as I think I have a good handle on where little-endian is required.

**Comment by schroedingerscode** [comment]
Yeah, glad you addressed that Ben. I was a bit brief describing the issue to the point of incorrectness. Another good reference is https://github.com/ethereum/eth2.0-specs/issues/556, which is mentioned in Spec PR 564.

**Comment by benjaminion** [comment]
Closed by #447
