### ISSUE TITLE
Verify logic in update_eth1_data matches the spec - (Spec PR #561)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#397]
### Description
As an implementor, I want the per-block processing Eth1 Data update to be compliant with the spec so that Artemis performs as other clients expect. 

### Acceptance Criteria
* If there exists an `eth1_data_vote` in `states.eth1_data_votes` for which `eth1_data_vote.eth1_data == block.eth1_data` (there will be at most one), set `eth1_data_vote.vote_count += 1`.
* Otherwise, append to `state.eth1_data_votes` a new `Eth1DataVote(eth1_data=block.eth1_data, vote_count=1)`.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/561

**Comment by vitorpy** [comment]
Working on it.

**Comment by vitorpy** [comment]
I believe this was fixed by #408

**Comment by schroedingerscode** [comment]
Yup, resolved by #408.
