### ISSUE TITLE
Validate initial state fork matches ForkSchedule

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3977]
### Description
When an `--initial-state` is loaded, verify that the fork in the loaded state matches the expected fork at that epoch from `ForkSchedule`.  An incorrect fork should be treated as a fatal error and the initial state not stored to the database.

This ensures that people can't accidentally use a state from pyrmont while running mainnet configuration.  Currently the state loads and they just never find any peers because the finalized root doesn't match.

**Comment by ajsutton** [comment]
`WeakSubjectivityInitializer.validateInitialAnchor` would be a good starting point to add this validation. It would need to throw `InvalidConfigurationException` if the fork doesn't match.

**Comment by vishaljhala** [comment]
`WeakSubjectivityInitializer.validateInitialAnchor` has `initialAnchor` that can give me `ForkInfo`. How do I get `ForkInfo` from `currentSlot` to compare against?

**Comment by ajsutton** [comment]
> `WeakSubjectivityInitializer.validateInitialAnchor` has `initialAnchor` that can give me `ForkInfo`. How do I get `ForkInfo` from `currentSlot` to compare against?

You'd want to get it from `spec.getForkSchedule().getFork(initialAnchor.getEpoch())` where `spec` is an instance of `Spec` which will have to be added as a new param to the method (it's already available in `BeaconChainController.setupInitialState` where this method is called from).
