### ISSUE TITLE
Move historic block signature verification out of storage service into HistoricalBlockFetcher

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4019]
### Description
Currently verification of historic block signatures is done in `RocksDbDatabase` which means it blocks the single storage thread while performing the verification and has to load a state from the database to be able to verify against.

We should do the verification in the beacon chain service as part of `HistoricalBlockFetcher` before sending to the storage service.  It already has a finalized state in memory and won't block other operations that need to update the database.

**Comment by rolfyone** [comment]
also use batch verify service potentially
