### ISSUE TITLE
Skip Invalid Deposits, Add Deposit Index Ordering - (Spec PR #589, #594)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#404]
### Description
As an implementor, I want to add mandatory deposit index ordering so that block proposers may skip invalid blocks and Artemis is in sync with the Beacon Chain spec.

### Acceptance Criteria
* Ensure `process_deposit` logic does not fail the entire block when an invalid proof of possession is provided. (See PR 589 below.)
* Add `deposit_index` to `BeaconState`.
* Initialize `deposit_index` in `get_initial_beacon_state`.
* Verify that `deposit.index == state.deposit_index` in `processDeposits` section of per-block processing.
* Increment `state.deposit_index` after processing the deposit in deposits section of the per-block processing.

### Additional Information
* See https://github.com/ethereum/eth2.0-specs/pull/589
* See https://github.com/ethereum/eth2.0-specs/pull/594

**Comment by vitorpy** [comment]
Working on this.

**Comment by schroedingerscode** [comment]
Closed by #454
