### ISSUE TITLE
Add Support for Transfers Between Withdrawn Accounts - (Spec PR #601)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#406]
### Description
As an implementor, I want Artemis to support transfers between withdrawn accounts so that Artemis is compliant with and implements all of the functions of the Beacon Chain spec. 

### Acceptance Criteria
* Ability to process transfers is added in compliance with below linked PR.
* Functions to process transfers are adequately tested.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/601/files

**Comment by vitorpy** [comment]
Working on it.

**Comment by schroedingerscode** [comment]
Closed by #413
