### ISSUE TITLE
MultiNodeAltairAcceptanceTest is intermittently failing

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#4061]
### Description
Looks like we have an intermittent test to debug: https://app.circleci.com/pipelines/github/ConsenSys/teku/12455/workflows/9928e367-cc94-4017-a1c7-3619385edbbe/jobs/80735

**Comment by ajsutton** [comment]
I haven't seen this for a while, I suspect it's been fixed as part of the gossip changes in the spec.  Closing for now and we can reopen if it becomes a problem again in future.
