### ISSUE TITLE
Is the docker build image correct for ARM64?

### ISSUE THREAD

**Issue by outdoteth** [Consensys-Incorporated/teku#4062]
### Description

When I run `docker run consensys/teku:develop-jdk15` I get the following warning in the logs:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

This warning is unexpected given this PR here that was supposed to solve it (I think?): https://github.com/ConsenSys/teku/pull/3389

Then occasionally after stopping and starting the image a few times I will get this SIGSILL error:

![Screenshot 2021-06-06 at 21 32 41](https://user-images.githubusercontent.com/37438950/120939429-f4c63780-c70f-11eb-92d6-cbfed1b61bf8.png)

In the [openjdk](https://github.com/docker-library/openjdk/blob/master/16/jdk/slim-buster/Dockerfile) images they detect the platform on the docker image like this:

![Screenshot 2021-06-06 at 21 45 13](https://user-images.githubusercontent.com/37438950/120939572-8df54e00-c710-11eb-9a5b-3ae09715aff2.png)

So to confirm that the errors are to do with the arm64 platform, I cloned the repo, built from source and then generated a brand new jdk15 docker image on my system (apple mac M1 chip - arm64). Then after running the image I no longer get the warning or error - it's running fine here:

![Screenshot 2021-06-06 at 21 44 21](https://user-images.githubusercontent.com/37438950/120939526-60a8a000-c710-11eb-97cd-489ccd8069c7.png)

### Steps to Reproduce (Bug)
1. go on Apple mac arm64 M1 chip laptop
2. do `docker pull consensys/teku:develop-jdk15`
2. do `docker run consensys/teku:develop-jdk15`
3. see warning
4. stop container
5. start again
6. repeat step 4-5 until SIGSILL error or container becomes unresponsive (logs aren't generated)

**Expected behavior:**
jdk15 image on dockerhub image should run fine on arm64 

### Versions (Add all that apply)
* OS Name & Version: [`MacOS Big Sur 11.3.1 (20E241)`]
* Kernel Version: [`Darwin Dylans-MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64`]
* Docker Version: Docker version 20.10.6, build 370c289

### Additional Information
All errors and warnings go away after building the docker images locally from source - although the jdk14 image fails with a "platform not supported" error in the build script. So I think if the jdk15 image is to actually work on arm64 it has to be built on a arm64 machine - or maybe there is a flag to do some kind of emulation in docker.

**Comment by ajsutton** [comment]
Apologies for the delay in getting back to you on this one. It looks like you're right - whichever platform the docker image gets built on selects the jdk base image that matches that architecture and so winds up being a single-arch image. Teku itself doesn't have any particular arch dependencies, it's just ensuring the right java base image is used.

Building locally on the architecture you need is the only work around for now.  We'll have to look into what we can do in our CI setup to get the pre-built images to be multi-arch.

**Comment by ajsutton** [comment]
CircleCI now have arm executors which may make it easier to get an arm built docker image: https://circleci.com/docs/2.0/arm-resources/

I think it should be possible to build an arm docker on Linux/x86 executors but when I looked a while back I wasn't able to get it to work in CircleCI.
