### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION Crash on exit

### ISSUE THREAD

**Issue by kirillp** [Consensys-Incorporated/teku#4077]
I was running teku-21.5.0 like this

bin/teku.bat --network=pyrmont --eth1-endpoint=%eth_svc% --data-path test-data

then I exit teku by pressing Ctrl-C

**Actual behavior:** [What actually happens]

Have a native crash

**Frequency:** [What percentage of the time does it occur?]

At least once

### Versions (Add all that apply)
* Software version: [`teku --version`] 

teku/v21.5.0/windows-x86_64/oracle_openjdk-java-16

* Java version: [`java -version`]

openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)

* OS Name & Version: Windows 10 19043.1052 on i5-9600K CPU

**Comment by kirillp** [comment]
[hs_err_pid1552.log](https://github.com/ConsenSys/teku/files/6633772/hs_err_pid1552.log)

**Comment by rolfyone** [comment]
Thanks for raising this, and the log has been really helpful.

I believe this will be closely related to #4034, which will be in the next release.  The database will be fine, and on restart everything should be ok again, it's just trying to write to the database after it's been closed.

Let us know if you've got issues starting up...

**Comment by kirillp** [comment]
I updated to 21.6. Have not seen this yet

**Comment by ajsutton** [comment]
> I updated to 21.6. Have not seen this yet

Note: this fix will actually wind up in 21.6.1, not the just released 21.6.0.  There's a few days lag between the commit we choose to release and it actually going out because we do some final testing on real live nodes before releasing to users.  The crash only happens during shutdown though so won't affect stability - just creates a bit of scary noise.

**Comment by ajsutton** [comment]
This fix has now shipped in 21.6.1.
