### ISSUE TITLE
check partial_content return code when syncing on node/health

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4078]
If an archive node is syncing, the expectation is that the endpoint `/eth/v1/node/health` should return a 206 (partial content) return code.

Juan wasn't having this happen, we should investigate that a normal node syncing is returning a 206 code, and fix if it's behaving unexpectedly.

**Comment by joaorodrigues-consensys** [comment]
To give some context on our side, we are relying on kubernetes readiness probes to determine if beacon is ready or not.
The probes is just a simple HTTP GET request to `/eth/v1/node/health` that if returns other than [200, 400[ its marks it as not ready. We were also trying to make use of the query param `syncing_status` as recently introduced [here](https://github.com/ConsenSys/teku/commit/af6eea57d086c4eea44d9969df2426887bdcde76) to make the health endpoint send a 400 when syncing and mark the pod as not ready.

**Comment by rolfyone** [comment]
Had a good look, and it's clear what the issue is.

The check is currently only returning that it's syncing when its got peers and performing sync, but that doesn't allow for the period before it has peers.
current behaviour for node health
initialisation: unavailable
pre-having peers: 200 (<- should really be 206)
have peers and syncing: 206
in sync: 200

I'm tweaking the logic so that when its starting up or syncing it'll return a 206 from node/health (or custom code if that's been set).

Other impacts for this same logic are getting duties and posting blocks, which would currently potentially accept data or send duties while in startup mode.  This is similarly not great, so all of these scenarios will benefit from being turned off while not actually in an 'inSync' state.
