### ISSUE TITLE
Make sync committee signature validation subnet specific

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4079]
### Description
As per https://github.com/ethereum/eth2.0-specs/pull/2474/ ensure that duplicate sync committee signature messages on different subnets are gossiped. We don't actually need to process the duplicates in Teku though because we automatically calculate all the subnets a signature applies to.

**Comment by ajsutton** [comment]
@mbaxter Not sure if you were going to do this as part of #4067 or not so logged this to make sure it doesn't get forgotten.

**Comment by mbaxter** [comment]
Fixed via https://github.com/ConsenSys/teku/pull/4088
