### ISSUE TITLE
lmd ghost integration

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#410]
### Description
Modifications needed to integrate lmd_ghost fork choice rule into our current chain processing in onNewSlot().

### Acceptance Criteria
- in StateTreeManager:
  - List<BeaconState> fork_heads to track the current state of all possible forks within the weak subjectivity period
  - move all code inside onNewSlot to processFork(current_slot,fork_head)
  - make unprocessedBlock a priority queue (by slot)
  - onNewSlot()
       1. Does this block create a new fork?  If yes, add it to fork_heads
       2. fork_heads.map(processFork) 
            - this allows us to update all fork states for the current slot
       3.  canonical_head = lmd_ghost(store)

**Comment by cemozerr** [comment]
I updated chainProcessor function name to processFork, since that seemed more in line with function naming and more suitable to processing of a single fork.

**Comment by jrhea** [comment]
Closed by #414
