### ISSUE TITLE
Validate locally created blocks prior to gossiping

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4126]
### Description
Currently Teku gossips blocks submitted to the publish block API immediately without checking validity.  We should only publish blocks we've validated.  As part of this we will need to ensure we publish blocks that are saved for later because the slot hasn't started yet (potentially because of clock skew with the validator client) which we don't appear to do currently.

**Comment by lucassaldanha** [comment]
We need to check if this change affects the Builder flow.

**Comment by rolfyone** [comment]
curious what we need here given block v3 etc @tbenr
