### ISSUE TITLE
Profile Altair Performance

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4150]
Do an overall review of performance with Altair to ensure there's nothing silly going on.

**Comment by rolfyone** [comment]
use subscribe_all_subnets

**Comment by ajsutton** [comment]
Theory is that the increase in CPU usage seen when Altair activated on the first devnet was because of the significant increase in gossip traffic because of sync committees. Given a 10,000 validator network and running 1000 on each box, they would be subscribed to all attestation subnets all the time, but that would only give about 312 single attestations per slot.

With sync committees there are 512 validators in the committee each producing a signature every slot which are spread over 4 subnets. If you wind up on all 4 subnets which is definitely possible you wind up more than doubling the amount of gossip traffic to verify (and have to generate and sign some signatures every slot, and check if each validator in the sync committee is an aggregator every slot).

We've now included sync committee signature gossip in the batch verification which has reduced CPU usage, but the impact of sync committees will be significantly reduced on MainNet as it will be much less common to be in one at all and very unlikely to be on multiple sync subnets at the same time.

Will investigate if there are any optimisation opportunities when calculating or performing sync committee duties before closing this out.

**Comment by ajsutton** [comment]
When running 1000 validators (10% of network) we do see the majority of Cpu usage is signing - nearly 20% of Cpu usage.  There's little that can be done to optimise that but it will be significantly less load on bigger testnets because it will be much less likely that validators will be part of the sync subcommittee.

At this stage I don't see any signs of performance degradation, and we shouldn't see any significant change to CPU usage on the bigger testnets when Altair activates.
