### ISSUE TITLE
Remove unnecessary items from processedBlock (WIP)

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#416]
### Description
As an implementer, I want to remove unnecessary(finalized) blocks, i.e. blocks that I'd no longer need to reach back in lmd_ghost due to them being finalized, from memory, so that our memory doesn't grow indefinitely. 

A possible way to fix this: 
every time we finalize new blocks in epoch processing, we go in and remove finalized blocks that are no longer needed for lmd ghost.

**Comment by akhila-raju** [comment]
@cemozerr, has this been completed or is it still an open issue?

**Comment by cemozerr** [comment]
Still an open issue.

**Comment by cemozerr** [comment]
Assigned to @mankenavenkatesh
