### ISSUE TITLE
Verify attestations not included in the chain

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#418]
### Description
As an implementer, I want to verify the attestations before I use them to calculate the DAG head (with lmd ghost), so that fake attestations can't manipulate my software to follow a wrong chain. 

### Acceptance Criteria
* the verifyAttestation function, which is now only stubbed out, in AttestationUtil gets implemented with correct criteria.

**Comment by vitorpy** [comment]
@cemozerr Does this refers to https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#verify_slashable_attestation ?

**Comment by cemozerr** [comment]
I believe it doesn't. Verify slashable attestations gets used in per-block processing whereas we need a function during processing of attestations from network to decide our validator should include them in its block proposal. I think this kind of function or specification is not yet included in the main spec. I hope I'm wrong tho.

**Comment by akhila-raju** [comment]
@cemozerr, has this been completed or is it still an open issue?

**Comment by akhila-raju** [comment]
I see it hasn't been implemented, in the future let's add a TODO in the code as well

**Comment by cemozerr** [comment]
Still an open issue.
