### ISSUE TITLE
curl missing in docker image for healthcheck

### ISSUE THREAD

**Issue by sagacitysite** [Consensys-Incorporated/teku#4181]
**Description**

We're using Teku (21.6.1) in a Docker Swarm (20.10.7). We run Teku in two different settings. On is in chain-only mode and one is in validator-only mode (since the chain can be replicated and the validator can only run once). To make sure that the validator is always talking to a fully functioning chain, we perform a healthcheck, which we currently define in the docker compose file.

```
healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5051/eth/v1/node/health"]
    start_period: 10m
```

**Problem**

Unfortunately this ends in an infinite starting loop of the chain container. We figured out that `curl` is not installed in the Teku docker image. After adding it to the image, it seems to work as expected.

**Proposed solutions**

* Add `curl` to the Teku docker image
* (optionally) Include directly a healthcheck to the image

**Comment by ajsutton** [comment]
Thanks for raising this. The images are deliberately minimal but I can see how this is a problem for you. Looking into the best options to resolve it.

**Comment by ajsutton** [comment]
Looks like installing curl is going to be the best answer though it's a bit of a shame the image can't stay completely minimal.

We won't add a health check by default because by default the REST API is disabled so it would fail. Definitely want to make it easy to configure one though.
