### ISSUE TITLE
Suppress performance output when not relevant

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4213]
```
18:07:24.132 INFO  - Sync Event  *** Current slot: 1772735, Head slot: 1540800, Connected peers: 29
18:07:35.503 INFO  - Sync Event  *** Current slot: 1772736, Head slot: 1540929, Connected peers: 29
18:07:35.504 INFO  - Attestation performance: expected 0, produced 0, included 0 (0%), distance 0 / 0.00 / 0, correct target 0 (0%), correct head 0 (0%)
18:07:47.423 INFO  - Sync Event  *** Current slot: 1772737, Head slot: 1541056, Connected peers: 28
18:08:00.280 INFO  - Sync Event  *** Current slot: 1772738, Head slot: 1541163, Connected peers: 27
```

There are a couple of things not great about the above:
1. performance info is irrelevant while syncing; and
2. I am not running any validators on this instance so it is irrelevant, full stop.

Note that `--validators-performance-tracking-mode` defaults to `ALL`. I guess I could suppress this by setting it to something else (but what?? `--help` doesn't tell me what the other options are), but it should probably be always suppressed if either 1 or 2 above is true.

The simplest approach is probably to omit the performance info whenever "expected" is "0"; that ought to resolve both cases.

**Comment by ermyas** [comment]
Hi,

I can take this up. From what I gather, there are three related issues being raised here

1. `—validators-performance-tracking-mode` usage help message should list the set of options that can be specified.

2. The relationship between the `—validators-performance-tracking-enabled` and `—validators-performance-tracking-mode`, should perhaps be described in the help message. It appears the former overrides the latter if specified.

3. Performance metrics output, when not relevant, should be suppressed regardless.

**Comment by ajsutton** [comment]
> 1. `—validators-performance-tracking-mode` usage help message should list the set of options that can be specified.

Yep, note that you use something like ` (Valid values: ${COMPLETION-CANDIDATES})` and PicoCLI will automatically fill in the available options.

> 2. The relationship between the `—validators-performance-tracking-enabled` and `—validators-performance-tracking-mode`, should perhaps be described in the help message. It appears the former overrides the latter if specified.

Yes, probably worth a note in the help for `--validators-performance-tracking-mode` that it's ignored if `--validators-performance-tracking-enabled=false`

> 3. Performance metrics output, when not relevant, should be suppressed regardless.

Yep. That's probably the key change here. I'd suggest that if we didn't expect to produce any attestations in the epoch then we shouldn't log the message.  That may happen while the node is syncing, when there are no validators running locally or when the local validators aren't currently active.  All those cases will just boil down to omitting the message when "expected" is "0" as Ben says.

**Comment by ermyas** [comment]
> Yes, probably worth a note in the help for `--validators-performance-tracking-mode` that it's ignored if `--validators-performance-tracking-enabled=false`

yea, I think it is ignored even if `--validators-performance-tracking-enabled` is set to true though. [Basically, if that option is true, the mode is overridden to be `ALL` and if false the mode it is set to `NONE`](https://github.com/ConsenSys/teku/blob/master/teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java#L115-L121).

**Comment by ajsutton** [comment]
> yea, I think it is ignored even if `--validators-performance-tracking-enabled` is set to true though. [Basically, if that option is true, the mode is overridden to be `ALL` and if false the mode it is set to `NONE`](https://github.com/ConsenSys/teku/blob/master/teku/src/main/java/tech/pegasys/teku/cli/options/ValidatorOptions.java#L115-L121).

Oh yes you're right.  I remember the history here now.  Originally it was just the `-enabled` flag and then we wound up with three modes so the `-tracking-mode` option was introduced as a replacement for the `-enabled` one. `validators-performance-tracking-enabled` has been hidden for quite some time so we don't actually need to mention it in help since it doesn't appear there (the `hidden = true` attribute`.  We should add it as an upcoming breaking change in the changelog and then in a couple of releases we can just remove it.  It's pretty unlikely anyone is still using it now but always good to actually follow the deprecation process and give warning in the release notes.

**Comment by ermyas** [comment]
got it thanks. I hadn't noticed that the tracking-enabled option was hidden.
