### ISSUE TITLE
Support publishing to multiple beacon nodes

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4223]
### Description
To improve inclusion rates, allow specifying multiple beacon node endpoints that produced attestations, blocks, aggregates etc are published to.  Note that a single beacon node would still be used as the source for beacon node info (e.g getting duties, creating blocks/attestations etc) but everything the validator produces would be published to all the beacon node endpoints.

**Comment by rolfyone** [comment]
basically this didnt work so now we should revert the dev flag and logic...
