### ISSUE TITLE
Orphan BLS12381Test

### ISSUE THREAD

**Issue by asanso** [Consensys-Incorporated/teku#4240]
The `abstract` class [BLS12381Test](https://github.com/ConsenSys/teku/blob/master/bls/src/test/java/tech/pegasys/teku/bls/impl/BLS12381Test.java) doesn't contain any implementation.
It used to be implemented by Mikuli (now gone).
Ideally BLST will also run these tests.

**Comment by Nashatyrev** [comment]
Thanks @asanso !
