### ISSUE TITLE
adoptopenjdk is deprecated

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#4244]
### Description

Teku just switched to adoptopenjdk for its Docker images, from openjdk:16-slim-buster. According to https://hub.docker.com/_/adoptopenjdk?tab=description, adoptopenjdk is deprecated and will receive no further support since Aug 1st 2021.

"This image is officially deprecated in favor of the eclipse-temurin image, and will receive no further updates after 2021-08-01 (Aug 01, 2021). Please adjust your usage accordingly."

Maybe move again, to `eclipse-temurin:16-focal`, and `eclipse-temurin:16-jdk-focal` for source building inside a docker container.

**Comment by ajsutton** [comment]
Thanks for pointing this out, I've been using AdoptOpenJDK for ages and somehow missed that.  I'll get our images updated.

**Comment by ajsutton** [comment]
Probably worth noting for the record, even these AdoptOpenJDK images are actually more up to date than the OpenJDK ones we were using, including some fixes for system level vulnerabilities which, while they shouldn't affect Teku, were causing some alerts in image scans.
