### ISSUE TITLE
enable peer scoring

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4264]
need to check how it works etc, not as simple as enabling.

**Comment by zilm13** [comment]
Found this Lighthouse PR https://github.com/sigp/lighthouse/pull/1284 implementing similar feature
not a thorough description, looking at code

**Comment by zilm13** [comment]
Most logic could be understand by those links:
Scores, decay etc
https://github.com/sigp/lighthouse/blob/df40700ddd2dcc3c73859cc3f8e315eab899d87c/beacon_node/lighthouse_network/src/peer_manager/peerdb/score.rs
when and what score penalty is applied
https://github.com/sigp/lighthouse/blob/6f4102aab6a11aaf21e2f9df041343f7318fca85/beacon_node/lighthouse_network/src/peer_manager/mod.rs#L149-L165
https://github.com/sigp/lighthouse/blob/6f4102aab6a11aaf21e2f9df041343f7318fca85/beacon_node/lighthouse_network/src/peer_manager/mod.rs#L438-L518
https://github.com/sigp/lighthouse/blob/4848e531559d6b717e8431f9571a7b1b3557005b/beacon_node/network/src/beacon_processor/worker/sync_methods.rs#L269-L452
https://github.com/sigp/lighthouse/blob/9964f5afe5d810025fe6c3901674f6c92f31ce52/beacon_node/network/src/sync/manager.rs#L358-L1134
https://github.com/sigp/lighthouse/blob/9964f5afe5d810025fe6c3901674f6c92f31ce52/beacon_node/network/src/sync/backfill_sync/mod.rs#L801-L835
https://github.com/sigp/lighthouse/blob/aaa5344eab2c0bda90d0d4da3710982c05396814/beacon_node/network/src/sync/range_sync/chain.rs#L614-L646
+gossip:
https://github.com/sigp/lighthouse/blob/36fc887a40fb5a62125ccc8a9b5cd6f26d83fd7f/beacon_node/lighthouse_network/src/behaviour/mod.rs#L947-L956
https://github.com/sigp/lighthouse/blob/fc37d51e1020d20cf642ceaba4034e622e243bb8/beacon_node/network/src/beacon_processor/worker/gossip_methods.rs#L743-L2098

**Comment by rolfyone** [comment]
`GossipScoringConfigurator` `--Xp2p-gossip-scoring-enabled`
`/teku/v1/nodes/peer_scores`
