### ISSUE TITLE
Optimisation: Store VoteTracker instances in an array instead of Map

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4275]
### Description
Currently `Store.votes` is a `HashMap` with the validator index as key but access is actually sequential so it would be more efficient in both CPU and memory to store votes in an array.

**Comment by seroze** [comment]
Hi @ajsutton  can i pick this, also need clarity on the below questions. 

1) while fetching the VotedValidatorIndices  is the below code correct ? 
```java
 Set<UInt64> getVotedValidatorIndices() {
    readLock.lock();
    try {
      HashSet<UInt64> hs = new HashSet<>();
      for(int i=0;i<VOTE_TRACKER_SIZE;++i){
        if(votes[i]!=null)hs.add(UInt64.valueOf((long) i));//is this logic correct
      }
      return hs;
      //return new HashSet<>(votes.keySet());
    } finally {
      readLock.unlock();
    }
  } 
```
  
2) do we want to change the signature for votes everywhere ,  for example consider the below class. 
  
```java 
  public interface VoteUpdateChannel extends VoidReturningChannelInterface {

  void onVotesUpdated(Map<UInt64, VoteTracker> votes);
}
```

  do we want to convert  the type of this arg to VoteTracker[]

**Comment by ajsutton** [comment]
> Hi @ajsutton can i pick this, also need clarity on the below questions.

Yep, that would be great.

> 1. while fetching the VotedValidatorIndices  is the below code correct ?

I think the code you're looking at is behind master. `getVotedvalidatorIndices` was replaced with `getHighestVotedValidatorIndex` in https://github.com/ConsenSys/teku/pull/4260 

>  1. do we want to change the signature for votes everywhere ,  for example consider the below class.
> 
> ```java
>   public interface VoteUpdateChannel extends VoidReturningChannelInterface {
> 
>   void onVotesUpdated(Map<UInt64, VoteTracker> votes);
> }
> ```
> 
> do we want to convert the type of this arg to VoteTracker[]

Not necessarily everywhere.  In this case it is often only a subset of votes that are being updated and so only the changed votes wind up being passed to this method to update storage. The `Map<UInt64, VoteTracker>` API still works well for this.
