### ISSUE TITLE
Fix visibility of CLI option `--Xdata-storage-non-canonical-blocks-enabled`

### ISSUE THREAD

**Issue by ermyas** [Consensys-Incorporated/teku#4283]
### Description
As discussed [here](https://github.com/ConsenSys/teku/pull/4272#discussion_r694674049), the Teku CLI command option [`--Xdata-storage-non-canonical-blocks-enabled`](https://github.com/ConsenSys/teku/blob/master/teku/src/main/java/tech/pegasys/teku/cli/options/DataStorageOptions.java#L50) should probably be hidden or should not be tagged as an _unstable_ option with the`--X` prefix.

### Acceptance Criteria
* `teku --help` should not list the option `--Xdata-storage-non-canonical-blocks-enabled` or should instead display an option name that isn't prefixed with `--X` (e.g. `data-storage-non-canonical-blocks-enabled`)

### Versions
* Software version: teku/v21.8.1+24-gde5be55/osx-x86_64/oracle-java-16

**Comment by ajsutton** [comment]
Given we have public APIs exposed to access the non-canonical blocks I think the option should have the `X` removed so it's just a fully supported option.
