### ISSUE TITLE
Provide ws-checkpoints for prater

### ISSUE THREAD

**Issue by paulmillr** [Consensys-Incorporated/teku#4315]
I haven't found any ws-checkpoints for prater testnet. It would be great if developers were able to sync the testnet without much hassle.

I think it would be cool if the team provided those publicly. Pyrmont is shutting down, beaconscan doesn't support prater, neither does infura.

Can teku team host checkpoints for slot 1000000/1150000 (e.g.) somewhere? There is no need to update it! Would save at least a million blocks.

The documentation that would need to be updated is here:

- https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Checkpoint-Start/
- https://docs.teku.consensys.net/en/latest/Concepts/Weak-Subjectivity/

**Comment by benjaminion** [comment]
Infura does support the Prater testnet, at `eth2-beacon-prater.infura.io`, so that is probably your best source for now.

```
curl -o foo.ssz -sH 'Accept: application/octet-stream' https://<PROJECT ID>:<PROJECT SECRET>@eth2-beacon-prater.infura.io/eth/v1/debug/beacon/states/1000000
```

Eventually we will have a common approach for distributing weak subjectivity checkpoints, but it will take a while to agree and set up between teams. Meanwhile, I've put up a checkpoint for Prater slot 1150016 (needs to be an epoch boundary) on [my own site](https://benjaminion.xyz/prater_1150016.ssz) that you are welcome to use.

**Comment by paulmillr** [comment]
Thanks Benjamin, you're awesome! Is there another issue that tracks checkpoint distribution, or should we keep this one open?

**Comment by paulmillr** [comment]
(Infura didn't mention prater)

**Comment by benjaminion** [comment]
You're very welcome!

> Is there another issue that tracks checkpoint distribution, or should we keep this one open?

This is more of an ecosystem roadmap issue. Until we have agreed on a broadly trustless model across relevant stakeholders, there's not much to say. Tbh, it's going to be a while - weak subjectivity doesn't really become an issue until after withdrawals are enabled, and not all clients support the checkpoint start in any case yet.

Meanwhile, we would encourage people to use Infura to get the checkpoints for Teku. They are properly set up for this already and actually run Teku behind the scenes.

So I'd rather close this one here, if you don't mind.
