### ISSUE TITLE
Improve logging of invalid blocks

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4329]
Teku v21.7.0 on mainnet.

I occasionally get a console warning as follows:

```
Sep 08 02:55:11 metalalbert teku[2327]: 02:55:11.488 WARN  - Rejecting invalid block at slot 2020474 with root 0xcbdc592b5b4c49783a9487c05107bfd372968dff65ee0c083943adc09f7c36fd because FAILED_STATE_TRANSITION. Full block data: 0x64000000a2....
```

Questions:
1. Does this need to be at `WARN` level? If this is just junk from another client that I can't do anything about then it's a good way to DOS my logs and should probably be moved to `DEBUG`. Otoh, if this is a useful message indicating that my node might be on a wrong fork or something, then it's probably worth keeping at `WARN`.
2. Notwithstanding the above, I don't need to see the full block data (which is enormous) in my console. If it is a useful message, maybe log a one-liner up to the full stop at `WARN` level, then output the full block data at `DEBUG` level.

**Comment by rolfyone** [comment]
this logging should be disabled unless either the option: `--Xlog-include-p2p-warnings-enabled` is used, or some kind of custom logging configuration is used.
I manually tested and it appears that this CLI is functioning correctly (the invalid block warning is hidden unless this option is selected).
it could alternatively be a custom log4j config, will wait to hear if you've done either of these things..

Can you confirm whether you're using this option either in config or on your CLI @benjaminion ?

**Comment by benjaminion** [comment]
> Can you confirm whether you're using this option either in config or on your CLI

This is my entire config file. The only relevant option I'm using is `log-destination: "CONSOLE"`. I don't have any CLI options. And no `-X` options or custom logging.

```
network: "mainnet"
data-path: "/data/teku/data"
data-storage-mode: "ARCHIVE"
p2p-advertised-ip: "<redacted>"
metrics-enabled: true
metrics-interface: "0.0.0.0"
metrics-host-allowlist: ["127.0.0.1","192.168.1.203","localhost","albert"]
rest-api-enabled: true
rest-api-interface: "0.0.0.0"
rest-api-docs-enabled: true
rest-api-host-allowlist: ["127.0.0.1","192.168.1.203","localhost","albert"]
rest-api-cors-origins: "*"
p2p-peer-upper-bound: 100
p2p-peer-lower-bound: 80
validator-keys: "/var/lib/teku/keys:/var/lib/teku/keys"
eth1-endpoint: "https://mainnet.infura.io/v3/<redacted>"
log-destination: "CONSOLE"
validators-keystore-locking-enabled: false
validators-performance-tracking-enabled: true
```

I haven't had any of these `Rejecting invalid block` messages since updating to 21.8.2 a couple of days ago, having had a dozen in the previous month with the older version. I am happy to put this on hold for a week or so and I'll update if I see this again, and we can close it if not.

**Comment by benjaminion** [comment]
However, I _am_ now seeing console logs as follows:

```
Sep 10 06:05:31 metalalbert teku[2436]: 06:05:31.109 WARN  - Rejecting gossip message on topic /eth2/b5303f2a/beacon_aggregate_and_proof/ssz_snappy, reason: Rejecting aggregate because attester is not in committee. Should have been one of [113103, 179860,... <lots of stuff>
```

A couple of these today, version `teku/v21.8.2+30-gbb0c2f3/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`.

The same remarks apply to these as to the `Rejecting invalid block` messages.
