### ISSUE TITLE
[Merge] implement `TERMINAL_TOTAL_DIFFICULTY` parameter

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4345]
### Description

Refers to https://github.com/ethereum/consensus-specs/pull/2605

**Comment by mkalinin** [comment]
I am sorry for the mess. Transition logic has been implemented in another branch which is based on the `post-rayonism-merge` and catching up with it should be straightforward. So, the first step towards making this done would be bringing the transition logic into the codebase. The branch: https://github.com/txrx-research/teku/tree/transition-process

**Comment by Nashatyrev** [comment]
Fixed with #4408
