### ISSUE TITLE
[Merge] Update to interop Engine API

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4346]
### Description
Update the engine API calls to use the latest standard (at least those identified for the interop subset).

## beacon state

- [x] ExecutionPayload and ExecutionPayloadHeader

## core

- [x] engine_preparePayload
  - [x] client implementation
  - [x] api usage

- [x] engine_getPayload
  - [x] client implementation
  - [x] api usage
 
- [x] engine_executePayload
  - [x] client implementation
  - [x] api usage

- [x] engine_consensusValidated
  - [x] client implementation
  - [x] api usage
 
- [x] engine_forkchoiceUpdated
  - [x] client implementation
  - [x] api usage
 
## endpoint

- [x] introduce a new `executionEngineEndpoint` param (optional - fallback to `eth1Endpoints.get(0)`) to route there the `engine_*` APIs only. We will continue using `eth1Endpoints.get(0)` for retrieving the powHead but we may start using the new endpoint for all if it will be standardized)

**Comment by tbenr** [comment]
all PRs relative to the task list have been merged
