### ISSUE TITLE
[Merge] Sync process

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4349]
### Description
The Eth1 sync process is still largely unknown.  Will need to work with geth/besu/others to ensure it works. This is a stretch goal for the merge interop work.

**Comment by mkalinin** [comment]
- Draft proposal of the sync process design
  - https://github.com/fjl/p2p-drafts/blob/master/merge-sync/merge-sync.md
- Related section in the Engine API design doc
  - https://hackmd.io/@n0ble/consensus_api_design_space#Sync

**Comment by ajsutton** [comment]
Closing this one - we just need to implement optimistic sync and fire the various forkChoiceUpdated type events which is all covered by other tickets.
