### ISSUE TITLE
[Merge] Rebase merge implementation onto Altair

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4351]
### Description
Currently the merge implementation builds on phase0, but it has now been rebased on top of Altair which will be used for merge interop testing.

**Comment by Nashatyrev** [comment]
I didn't found anything extra to be done for rebase. 
@ajsutton @mkalinin May be do you have anything else in mind?

**Comment by ajsutton** [comment]
No I think we've basically got it. Just need to work through the reference tests now. There will probably be a fee more places we expect an Altair version and get a merge version so need to make it more generic but the ref tests will find them. 

I'd say the main thing now is the union support as that's breaking about 500 reference tests.

**Comment by Nashatyrev** [comment]
All ref tests are passing now 👍 
Closing this as fixed
