### ISSUE TITLE
Change "Skipping head block update" message to debug level

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4364]
The message `Skipping head block update as justified checkpoint was updated while loading checkpoint state. Was 64667 (0x09991b31991f434eeb0e853263039977b6ed818b3ba9212ffedb996d8a179cee) but now 64668 (0x65769cb3ae74f772e40a86360c21ae7bb6d0ae6013fd9b86b0313a766417a6b5)` can be changed to be debug level.

To do this, will be just a matter of finding "Skipping head block update as justified" in code, and changing to use `.debug` function instead of `.info`

**Comment by seroze** [comment]
@rolfyone  do have look at this when you get time.
