### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION crash on exit

### ISSUE THREAD

**Issue by kirillp** [Consensys-Incorporated/teku#4386]
Teku version: teku/v21.9.1/windows-x86_64/oracle_openjdk-java-17
Windows 11, java openjdk-17, official GA release

teku.log and app crash log attached

[teku.log](https://github.com/ConsenSys/teku/files/7184710/teku.log)
[hs_err_pid12892.log](https://github.com/ConsenSys/teku/files/7184711/hs_err_pid12892.log)

**Comment by benjaminion** [comment]
Thanks for reporting!

Just to be clear, you had terminated the Teku process independently and then it crashed as it exited - is that the right understanding? If it is a spontaneous crash that would be rather more severe. Would appreciate it if you could confirm.

The crash looks to be within LevelDB. There's probably somewhere we are not shutting it down cleanly on processing the exit. Will take a look.

**Comment by kirillp** [comment]
this is after I exit app, by Ctrl-C
