### ISSUE TITLE
Clarify documentation regarding command to run for importing slashing protection

### ISSUE THREAD

**Issue by chrishobcroft** [Consensys-Incorporated/teku#4387]
### Description

As a Validator switching to teku, I want to be able to have a low-friction process for migrating. The scariest step of the migration (for me at least), is the one about importing slashing protection data from another client. I would like t be able to read the documentation, and to feel like this is something easy to do, and that many people have passed this way before.

Currently, the documentation indicates to run the command:
```
teku slashing-protection import --data-path=/home/me/me_node --from=/home/slash/slashing-interchange-format.json
```
It further describes:

- `--data-path` specifies the location of the Teku `data` directory.`

It is not clear what this means.

![image](https://user-images.githubusercontent.com/2212651/133792589-0ef8be57-e6b3-43d7-a7e1-53bcd6f9822e.png)

### Acceptance Criteria

For it to be unambiguous as to what command to run.

**Comment by benjaminion** [comment]
We've reviewed the docs around this and have not identified any great improvements we could make here. The `--data-path` in orange is a link through to the documentation for that option which is quite comprehensive - it might not be immediately obvious that the link is there, but that's the docs style throughout. We feel that duplicating that info here would not help with overall clarity of the docs.
