### ISSUE TITLE
slashing-protection import throws an exception

### ISSUE THREAD

**Issue by kirillp** [Consensys-Incorporated/teku#4388]
the following command does not work and throws

`bin\teku.bat slashing-protection import --data-path test-data --from=slashing_protection\slashing_protection.json`

result to 
`tech.pegasys.teku.infrastructure.exceptions.InvalidConfigurationException: Cannot write to folder slashing_protection\slashing_protection.json`

Teku version: teku/v21.9.1/windows-x86_64/oracle_openjdk-java-17

**Comment by benjaminion** [comment]
Yes, apologies for this. It is a known issue in 21.9.0 and 21.9.1.  To import slashing data, please use an older release such as [21.8.2](https://github.com/ConsenSys/teku/releases/tag/21.8.2). Once the data is imported, you can then switch to the latest version without difficulty. Once again, apologies, this was a regression introduced recently.

**Comment by kirillp** [comment]
When 21.9.2 will be build?

**Comment by benjaminion** [comment]
> When 21.9.2 will be build?

It will be a week or more - the plan is for our next release to include the Altair mainnet fork, but that has not yet been agreed among devs.

Meanwhile, it's easy to [build the latest develop version](https://github.com/ConsenSys/teku#build-and-dist) from source, or use the `:develop` docker build. We don't recommend using the develop version in production settings though.
