### ISSUE TITLE
Support publishing System metrics to a remote service

### ISSUE THREAD

**Issue by regio** [Consensys-Incorporated/teku#4391]
This issue extends the previous story #3773 , which initially defines the publication framework.

The goal for this story is to implement the capability of publishing `System Metrics` to a remote service.

See the [specification document](https://docs.google.com/document/d/1qPWAVRjPCENlyAjUBwGkHMvz9qLdd_6u9DPZcNxDBpc/edit#).

This is initially driven by beaconcha.in, but I think we should ideally be service agnostic: users should supply the endpoint URL that data is pushed to.

Before we consider this story done we'll also need to add tests to ensure the Prometheus metrics we're grabbing here actually do exist (ie test should fail if we ever rename any of them). That will probably need to be an acceptance test that uses a stub external metrics service to publish to and can then check it got non-zero values for everything.

**Comment by ajsutton** [comment]
@regio Is this actually completely finished or was it incorrectly closed?

**Comment by regio** [comment]
@ajsutton, its my mistake closing it. It still need a PR with the acceptance tests.
