### ISSUE TITLE
Corrupted database is not detected and lead to loosing all connections

### ISSUE THREAD

**Issue by kirillp** [Consensys-Incorporated/teku#4393]
Sometime database can be corrupted by external events, like unexpected power shutdown and PC restarts.
In such situations number of clients in Teku decreasing to zero.

The issue (and corresponding log files) is described here: 
https://github.com/ConsenSys/teku/issues/4377

In such situations Teku can detects this and 
ideally drop the database and start it from scratch. 

Initialization using initial state this is a question of few minutes.

**Comment by ajsutton** [comment]
Going to close this one. The aim is for the database to not get corrupted even with power interruptions etc and if there is an issue a) we want it to be noticed and reported so we can fix it and b) we don't want to delete data without manual intervention - the database issue may be able to be resolved by fixing permissions, freeing up disk space etc without necessarily having to delete the existing data.
