### ISSUE TITLE
Better information logged when some eth1 endpoints are INVALID

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#4409]
### Description
As a user, I want to know which eth1 endpoint is currently active when some of the configured endpoint are reported INVALID. 

### Acceptance Criteria
* Should be clear to users which is the current used endpoint

### Steps to Reproduce
1. configure multiple eth1 endpoints
2. make one of the endpoints failing
3. when warnings similar to `13:13:30.439 WARN  - Endpoint <host>:<port> [1] is INVALID | eth1: Temporary failure in name` appear

### Solution
add information in the warnings log about the first endpoint currently VALID. Print an additional ERROR in case no endpoints are alive.

**Comment by ajsutton** [comment]
Going to close this as we're moving away from supporting multiple eth1 endpoints post-merge anyway.

**Comment by Nashatyrev** [comment]
Мм ор
