### ISSUE TITLE
Include epoch in attestation/sync committee performance logs

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4473]
### Description
When logging the attestation and sync committee performance, include the epoch it is relevant to in the log message to make it clear that it isn't reporting the current epoch (I think it lags two epochs behind to account for inclusion distance).

Should also check that block performance reports are for the current epoch since that is known immediately.

**Comment by mhechavarria** [comment]
Can I work on this, please?

**Comment by ajsutton** [comment]
> Can I work on this, please?

Yep that would be great. `DefaultPerformanceTracker` is probably the best place to start to understand the code involved.

**Comment by ajsutton** [comment]
Also I'd suggest one PR to include the epoch in the attestation report and then follow up with any changes to block performance reports if required.  We try to keep each PR as small as possible and focussed on one thing.

**Comment by mhechavarria** [comment]
Roger that. I will give it a try!

**Comment by regio** [comment]
Hi @mhechavarria, are you still working on this issue?

**Comment by mhechavarria** [comment]
Hey @regio, I didn't have the time to do it yet, but feel free to take over please.
