### ISSUE TITLE
Broken API response for block

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#4600]
The REST API response for the `/eth/v2/beacon/blocks/<blockid>` endpoint broke in 21.11.0.  The response for this with block ID 0 on prater is:

```
{
  "version": "phase0",
  "data": {
    "message": {
      "slot": "0",
      "body": {
        "randao_reveal": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "eth1_data": {
          "deposit_root": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "deposit_count": "0",
          "block_hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        "graffiti": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "proposer_slashings": [],
        "attester_slashings": [],
        "attestations": [],
        "deposits": [],
        "voluntary_exits": []
      },
      "proposerIndex": "0",
      "parentRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "stateRoot": "0x895390e92edc03df7096e9f51e51896e8dbe6e7e838180dadbfd869fdd77a659"
    },
    "signature": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  }
}
```

The issue is that this is returning `proposerIndex` rather than the standard `proposer_index`, and likewise `parentRoot` and `stateRoot`. This will cause any client that relies on this response to fail.

Note the v1 endpoint suffers the same problem, and this applies for both phase0 and altair blocks.

**Comment by ajsutton** [comment]
Thanks Jim and sorry for this. We'll get a fix up and we were already working to fix the way JSON serialisation is done to make problems like this much less likely.  We're really annoyed this got through and have a number of things we're going to improve around testing to make sure it doesn't happen again.

Going to reopen this issue until we get that extra testing in place.

**Comment by ajsutton** [comment]
For the record we're intending to release a fix for this in the next 24 hours or so.  The candidate build for that release is https://artifacts.consensys.net/public/teku/raw/names/teku.tar.gz/versions/21.11.0+develop/teku-21.11.0+develop.tar.gz

**Comment by rolfyone** [comment]
Moved the swagger documentation testing to centralise and share with validator api, so we can't easily cause this issue again in validator api:
https://github.com/ConsenSys/teku/pull/4636

Also created #4653 as a placeholder to replace the existing beacon-api implementation

**Comment by rolfyone** [comment]
Hopefully this is a good account of our response, it does look like it currently. I'm closing this ticket as resolved, but obviously there's an open ticket re. moving the rest api.
Thanks for raising this ticket, we've addressed the tech debt of it being easy to break the rest-api, and now it's just continual improvement that will be scheduled into our priorities.
