### ISSUE TITLE
Acceptance test gap

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4612]
There are certain key areas of the rest api which can cause us issues.

Notably anything around performing duties (Validator required tag) are super important that they work, and are consistently generating field names, as they're part of the standard api.

We should somehow try to improve our remote validator testing, so that we can have confidence we haven't broken cross-client compatibility with the standard api, whether that is by testing outputs, or running against a non teku beacon node...

**Comment by benjaminion** [comment]
Related to #4656?

**Comment by rolfyone** [comment]
We do have a remote validator acceptance test now.
Between that and our json testing on endpoints, we've got fairly good coverage, so I'm going to close this, and we can raise another if we find a specific problem that still needs addressing.
