### ISSUE TITLE
Find a way to remove the source bundles from our GitHub release notes

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4631]
Users are frequently downloading the source distributions rather than the binaries from our release notes on GitHub. The source bundles appear under "Assets", which draws the eye, and I've made the same mistake at least once.

Can we remove these, or rename them something like "Do Not Download", or add the binaries into the assets list, or anything to prevent this from happening?

If users actually want the source, they can easily git clone it.

**Comment by zilm13** [comment]
From my research, there is no way to remove auto-generated sources snapshot from release (moreover it will be updated if you push something to the release assigned tag in the future), we could only control its comprehensiveness and exclude, say, test folders from sources with `.gitattributes` file and something like `tests/ export-ignore` inside. What we can do is to add binaries to the assets of release. My experiment shows that user assets will appear above auto-generated sources. It sounds like a best solution.

Helpful links:
Discussions:
https://stackoverflow.com/questions/45240336/how-to-use-github-release-api-to-make-a-release-without-source-code
https://softwareengineering.stackexchange.com/questions/366771/how-do-we-avoid-development-files-in-the-release
Github Release API:
https://docs.github.com/en/rest/reference/releases#create-a-release
