### ISSUE TITLE
Flaky test: ValidatorLivenessAcceptanceTest.shouldTrackValidatorLivenessOverEpochs()

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4635]
### Description
Seeing intermittent failures from `ValidatorLivenessAcceptanceTest.shouldTrackValidatorLivenessOverEpochs()`. We should investigate and make it reliable.  e.g. https://app.circleci.com/pipelines/github/ConsenSys/teku/14808/workflows/5fbf85ec-7dad-4a8d-8e19-b123dba079c0/jobs/98178/tests#failed-test-0

**Comment by rolfyone** [comment]
not currently flakey, can re-raise if it becomes an issue again.
