### ISSUE TITLE
Include date in logs

### ISSUE THREAD

**Issue by frankisawesome** [Consensys-Incorporated/teku#4638]
### Description
As a node operator, I want to be able to see dates in my log entries - this is the standard across different clients and help debugging errors that don't come up often.

### Acceptance Criteria

- [ ] Should log the date as part of the timestamp in log entries

### Steps to Reproduce (Bug)
1. Start Teku and see logs

**Comment by benjaminion** [comment]
Some comments:
  - When using log files, by default Teku rotates them daily, with the date in the filename, so adding a date to each line would be redundant.
  - Many node operators run Teku under _systemctl_, in which case _journalctl_ can be used to view and select lines by date very flexibly. Others will send log lines to a logging server that will also do its own date stamps.
  - Custom logging is available via [log4J2 configurations](https://docs.teku.consensys.net/en/latest/HowTo/Monitor/Logging/#advanced-custom-logging) - the example in the docs shows how to prepend the date to a log line.

I am not a huge fan of adding dates to every log line by default. If we were to, maybe it should be toggled by a command line option.

**Comment by frankisawesome** [comment]
Hey @benjaminion  thanks for the detailed explanation - I didn't put too much thought into this one, just noticed that by default there's no date and I bumped into some logs that I suspected might've been days ago - but all those options sound good. Happy for you to close this one :)

**Comment by benjaminion** [comment]
Closing. Also, I missed that in the actual log files (but not on the console) the date _is_ included in the timestamp on each line.
