### ISSUE TITLE
Update shuffling reference tests to use the latest release version

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#464]
### Description
As a developer, I want Artemis to use the best available test data so that I am confident that it is performing correctly.

The [official reference test repo](https://github.com/ethereum/eth2.0-tests/) is replicated in our code base as a git submodule. The current shuffling tests do not use this as it was previously out of date. It has now been updated and we should revise the shuffling tests accordingly. The tests are new, so a rewrite is required.

### Acceptance Criteria
* Artemis passes the new reference tests

**Comment by akhila-raju** [comment]
@benjaminion, has this been completed or is it still an open issue?

**Comment by benjaminion** [comment]
Remains open.

**Comment by jrhea** [comment]
can we close this PR now?

**Comment by benjaminion** [comment]
Yep, closing.
