### ISSUE TITLE
Implement reference state-transition tests

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#465]
### Description
As a developer, I want Artemis to use the best available test data so that I am confident that it is performing correctly.

A couple of state transition tests have been added to the [testing repo](https://github.com/ethereum/eth2.0-tests/). These should be implemented alongside the other reference tests.

### Acceptance Criteria
* State transition tests run against the reference test git submodule, although they should probably avoid failing explicitly for now.
* Out of scope: debugging Artemis to make it pass the tests for now.

**Comment by akhila-raju** [comment]
@benjaminion, has this been completed or is it still an open issue?

**Comment by benjaminion** [comment]
Remains open.
