### ISSUE TITLE
Release tag 21.11.1 is not available via git repo

### ISSUE THREAD

**Issue by NessDan** [Consensys-Incorporated/teku#4661]
### Description
I'm trying to build release tag `21.11.1` in Github but it's currently not actually in the repo. Even Github is showing ["This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."](https://github.com/ConsenSys/teku/commit/f9df80c9af29dff1f9efccf32e12d5174ba5fa34)

### Acceptance Criteria
* I should be able to checkout the latest release tag `21.11.1` locally for building via source code.

### Steps to Reproduce (Bug)
1. Clone Teku repo down.
2. `git checkout 21.11.1` (This will fail)
3. `git checkout 21.11.0` (This will work)

**Expected behavior:** Line 2 should work.

**Actual behavior:** `error: pathspec '21.11.1' did not match any file(s) known to git`

**Frequency:** 100%

### Versions (Add all that apply)
* Software version: [`teku --version`]
* Java version: [`java -version`]
* OS Name & Version: 
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
* Kernel Version: `Linux 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

### Additional Information
![Screen Shot 2021-11-16 at 1 21 51 PM](https://user-images.githubusercontent.com/304269/142045837-e56d5ff6-626d-4ea6-bd45-e1fcb071bb7a.png)

**Comment by ajsutton** [comment]
The `21.11.1` release was from a release branch, not the master branch.  The tag still exists in the repo (which is why GitHub can list it and show the commit), though the branch is no longer required and has been removed.  `git fetch -t` will retrieve all tags from the upstream repo so you have the `21.11.1` tag locally.
