### ISSUE TITLE
[Merge] Update syncing messages to show optimistic and verified head

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4673]
### Description
When syncing post merge, the head block won't update if the execution client is still syncing which will make it look like Teku's sync has stalled.  We need to update the syncing log lines to include both the verified head and the optimistic head in some way to show users that Teku is progressing but we're still waiting on the execution engine to complete verification.

**Comment by tbenr** [comment]
now that #4851 is merged, the issue could also deal with "Syncing completed" currently not considering optimistic sync.

![image](https://user-images.githubusercontent.com/15999009/149335515-17dbc308-6e39-484e-9a52-3efbf8c20ca1.png)

we could have something like “Beacon chain syncing complete, waiting for execution client” kind of message followed by a “Syncing complete” when the head becomes fully verified.
