### ISSUE TITLE
[Merge] avoid calling engine_forkChoiceUpdated with payloadAttributes during optimistic sync

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#4690]
Return empty PayloadAttributes if chain head is not same as optimistic chain head in `ForkChoiceNotifier::calculatePayloadAttributes`
 Alternatively just limit how many epochs of empty slots we'll process to avoid burning CPU pointlessly during optimistic sync

**Comment by ajsutton** [comment]
The spec seems to be changing on this point to avoid a potential liveness issue so we may wind up needing to propose as long as the justified checkpoint is fully validated, even if our chain head is not (but then we should propose based on our validated head, not the optimistic head).
