### ISSUE TITLE
[Merge] call engine_forkChoiceUpdated with PayloadAttributes when current slot proposer is being prepared

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#4691]
as discussed here: https://github.com/ConsenSys/teku/pull/4678/files#r754035099

when `onUpdatePreparableProposers` is called we may receive the proposer of the current slot in the list.
So we should call forkchoiceupdated with payload attributes for the current slot if possible.

**Comment by ajsutton** [comment]
I think the one remaining case to cover here is if the current block proposer is not in our list of validators we expect to prepare for.  We should just request block preparation for whatever validator is due to propose the block we've been asked to create.

**Comment by tbenr** [comment]
> I think the one remaining case to cover here is if the current block proposer is not in our list of validators we expect to prepare for. We should just request block preparation for whatever validator is due to propose the block we've been asked to create.

I think we require a default `proposerInfo` data (fee_recipient) that must come from the beacon node config.

**Comment by ajsutton** [comment]
> I think we require a default proposerInfo data (fee_recipient) that must come from the beacon node config.

Yeah true.  Interesting choice there of whether we make it optional and only allow creating blocks for unexpected proposers if it's set or always require it. Always requiring it seems pretty messy but it's likely to be forgotten quite a lot otherwise...

**Comment by tbenr** [comment]
> Always requiring it seems pretty messy but it's likely to be forgotten quite a lot otherwise...

for the records: the recently merged pr is not strictly requiring it, but it is quite noisy in the logs when it detects that it is the case to configure it. Let's see if it is enough.
