### ISSUE TITLE
[Merge] Require merge CLI options when merge enabled

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4713]
### Description
When the merge milestone is enabled, require the ee-endpoint to be specified.

If validators are loaded when the merge milestone is enabled, require fee-recipient to be specified.

**Comment by tbenr** [comment]
> If validators are loaded when the merge milestone is enabled, require fee-recipient to be specified.

are you sure about this? fee-recipient is an optional param when calling `engine_forckChoiceUpdated`
