### ISSUE TITLE
Fix up previous epoch logic around genesis (Spec PR #672)

### ISSUE THREAD

**Issue by akhila-raju** [Consensys-Incorporated/teku#474]
### Description
1) Revert a change in `get_previous_epoch` that caused a number of separate exceptional case handling in epoch processing
2) Prevent attestations from committees/slots before genesis

See [Spec PR #672](https://github.com/ethereum/eth2.0-specs/pull/672).

**Comment by vitorpy** [comment]
Working on this.

**Comment by akhila-raju** [comment]
This is now out of date with v0.5.1 spec.
