### ISSUE TITLE
Add HistoricalBatch tuple, remove merkle_root in favor of hash_tree_root functions. - (Spec PR #739)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#476]
### Description
As an implementor, I want to use hash_tree_root everywhere and get rid of merkle_root so that hashing logic is standardized and Artemis is compliant with the beacon chain spec. 

### Acceptance Criteria
* Miscellaneous type `HistoricalBatch` is defined as a list of `block_roots` and a list of `state_roots.` This will be serialized as an SSZ tuple, with both lists bounded by `SLOTS_PER_HISTORICAL_ROOT`.
* Remove `merkle_root` function, and ensure all remaining instances of `merkle_root` in the transition logic now uses `hash_tree_root`.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/739

**Comment by cemozerr** [comment]
Is this blocked by #469?

**Comment by schroedingerscode** [comment]
This is half blocked by #469, but also by #473. There relevant parts are:

- [x] Implement HistoricalBatch data structure.
- [ ] Bound HistoricalBatch internal lists size as per spec.
_(Blocked by #469.)_
- [ ] Replace reference to merkle_root with hash_tree_root during finalize epoch step. 
_(Blocked by both above issues.)_
