### ISSUE TITLE
make attestation batching a supported option

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#4772]
```
Xvalidators-batch-attestations-enabled: True
```

this option should become a supported option, as it helps reduce the calls to external providers by a significant amount if using many validators keys on a client.

**Comment by ajsutton** [comment]
Actually we probably just want to remove this option and always send as a batch.  We've defaulted it to true for a while now and had no issues.  No real reason to support not sending as a batch.

**Comment by ajsutton** [comment]
This option is in `ValidatorOptions` and removing it will just require following the option from there through the codebase to remove everywhere its used (making sure we keep the batching enabled which is the default value). This should wind up deleting `IndividualSendingStrategy` and leaving only `BatchAttestationSendingStrategy`.
