### ISSUE TITLE
Adding `--validator-keys` command fails with `--validators-fee-recipient-address is required` but this option doesn't exist

### ISSUE THREAD

**Issue by mieubrisse** [Consensys-Incorporated/teku#4800]
### Steps to Reproduce (Bug)
1. Add the `--validator-keys` option with valid keys to `consensys/teku:latest` Docker image
2. Observe the output

**Expected behavior:** 
I'm redirected to a flag for storing validator rewards that exists

**Actual behavior:**
Using the suggested flag (`--validators-fee-recipient-address`) outputs the following:
```
Unknown option: '--validators-fee-recipient-address=0x0000000000000000000000000000000000000001'
```
The closest thing (found in the unstable API) seems to be: `--Xvalidators-suggested-fee-recipient-address`, but using this option returns:
```
Unknown option: '--Xvalidators-fee-recipient-address=0x0000000000000000000000000000000000000001'; Expected parameter for option '--validator-keys' but found '--Xvalidators-fee-recipient-address=0x0000000000000000000000000000000000000001'
```

My full args list:
```
            "--network=/kurtosis-enclave-data/services/cl-client-0_1639701278/genesis-config.yml",
            "--initial-state=/kurtosis-enclave-data/services/cl-client-0_1639701278/genesis.ssz",
            "--data-path=/opt/teku/consensus-data",
            "--data-storage-mode=PRUNE",
            "--p2p-enabled=true",
            "--eth1-endpoints=http://186.200.48.4:8545",
            "--Xee-endpoint=http://186.200.48.4:8545",
            "--p2p-advertised-ip=186.200.48.5",
            "--rest-api-enabled=true",
            "--rest-api-docs-enabled=true",
            "--rest-api-interface=0.0.0.0",
            "--rest-api-port=4000",
            "--rest-api-host-allowlist=*",
            "--data-storage-non-canonical-blocks-enabled=true",
            "--log-destination=CONSOLE",
            "--validator-keys=/kurtosis-enclave-data/services/eth-genesis-generator_1639701235/node-0-keystores/teku-keys:/kurtosis-enclave-data/services/eth-genesis-generator_1639701235/node-0-keystores/teku-secrets",
            "--Xvalidators-fee-recipient-address=0x0000000000000000000000000000000000000001"
```

**Frequency:** 100%

### Versions (Add all that apply)
Software version: teku/v21.12.2/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17

### Additional Information
Seems to originate from https://github.com/ConsenSys/teku/commit/18c457bb52838ff7f9f3ea90030e7f793ad8a546#diff-f1b125735823e6cee7e7669159c435750764c369c33fc45e2de88c0f1bf75f93R186

**Comment by ajsutton** [comment]
This is required when the merge milestone is enabled but merge support is not yet finalised so the related options are still hidden and prefixed with `--X`.  The error message is a little ahead of its time.

The correct option is `--Xvalidators-suggested-fee-recipient-address` but your second attempt was missing the `suggested` in that option.

**Comment by mieubrisse** [comment]
Oo you're right! Such is the fate of coding when tired 🤦‍♂️ Just fixed and the validator seems to be starting now
