### ISSUE TITLE
"Read the debugging wiki" link in New Issue form redirects to /teku

### ISSUE THREAD

**Issue by SeaMonkey82** [Consensys-Incorporated/teku#4828]
### Description
As an issue submitter, I want to be able to follow the rules so that I don't waste anyone's time. 

### Acceptance Criteria
* Fix the link

### Steps to Reproduce (Bug)
1. Attempt to navigate to https://github.com/ConsenSys/teku/wiki/debugging

**Expected behavior:** [What you expect to happen]
Link leads to debugging wiki

**Actual behavior:** [What actually happens]
Link redirects to teku main

**Frequency:** [What percentage of the time does it occur?]
100%

**Comment by seroze** [comment]
@SeaMonkey82  can you add a screen shot of where this link is present in READme or some other file.

**Comment by SeaMonkey82** [comment]
![image](https://user-images.githubusercontent.com/20866869/147384720-478aef33-0a53-4d73-9b4b-4f2bf71f83b7.png)
