### ISSUE TITLE
Disallow Duplicate Voluntary Exits - (Spec PR #751)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#484]
### Description
As an implementor, I want to disallow duplicate voluntary exits so that logic edge cases are eliminated and that Artemis complies with the beacon chain spec. 

### Acceptance Criteria
* The `processExits` routine in the per-block processing section is renamed `processVoluntaryExits`.
* The `processVoluntaryExits` function complies with the logic in the linked PR.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/751

**Comment by akhila-raju** [comment]
Already fixed.
