### ISSUE TITLE
Disallow Voluntary Exits Until 2048 Epochs - (Spec PR #746)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#485]
### Description
As an implementor, I want to disallow frequent voluntary exists by restricting voluntary exits until after 2048 epochs so that there is more stability in persistent committees, and so that Artemis complies with the beacon chain spec. 

### Acceptance Criteria
* Add new Constant - `PERSISTENT_COMMITTEE_PERIOD = 2^11 (=2048)`
* During `processVoluntaryExits` routine, check that `get_current_epoch(state) - validator.activation_epoch >= PERSISTENT_COMMITTEE_PERIOD`.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/746
Depends on #484

**Comment by akhila-raju** [comment]
Already fixed.
