### ISSUE TITLE
[Feature] Integrate with MEV Boost

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#4854]
Post Merge there will be an option for proposers to obtain blocks via FlashBots' MEV-Boost architecture. It is very likely to be widely used and Teku should support it.

Documentation:
  - [Overall architecture](https://ethresear.ch/t/mev-boost-merge-ready-flashbots-architecture/11177)
  - [MEV Boost middleware](https://github.com/flashbots/mev-boost) including API
  - [Implementation notes](https://hackmd.io/@paulhauner/H1XifIQ_t) from Lighthouse
  - [Milestone 1 spec](https://github.com/flashbots/mev-boost/pull/20) draft

**Comment by rolfyone** [comment]
epic created, will close this ticket

**Comment by ThomasDalla** [comment]
> epic created, will close this ticket

Could you share a link to the epic, please?

**Comment by rolfyone** [comment]
https://github.com/ConsenSys/teku/issues/5396
We're testing at the moment, should be almost done...
