### ISSUE TITLE
[Merge] Unhide merge related CLI options 

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4874]
### Description
Currently all the merge related CLI options are hidden with a `--X` prefix.  Once we're confident they've stabilised we should unhide them and remove the prefix so they become fully supported options.

**Comment by tbenr** [comment]
this are the unhidden CLI options:

`--ee-endpoint`
`--ee-jwt-secret-file`
`--validators-proposer-default-fee-recipient`
`--validators-proposer-config` 
`--validators-proposer-config-refresh-enabled`

validators-proposer options details here:
https://github.com/ConsenSys/teku/pull/4894
