### ISSUE TITLE
Fair Proposer Sampling Using Epoch Instead of Slot - (Spec PR #733)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#488]
### Description
As an implementor, I want to sample the committee using epoch instead of slot so that beacon proposer indices are hydrated correctly per beacon chain spec. 

### Acceptance Criteria
* Reference to `slot` while sampling first_committee should be replaced by `epoch`.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/733

**Comment by akhila-raju** [comment]
Already fixed.
