### ISSUE TITLE
Add commandline option constraints

### ISSUE THREAD

**Issue by jtraglia** [Consensys-Incorporated/teku#4906]
### Description

When poking around, I noticed that certain options that should only allow positive values (such as `--genesis-time` and `--validator-count` in `teku genesis mock`) will process negative values.

For negative genesis times, the `checkArgument` call will catch the problem and throw an exception.

```
$ teku genesis mock --genesis-time -1
java.lang.IllegalArgumentException: value (-1) must be >= 0
  <call stack>
```

But for most other options, it will continue as normal. For example, a negative validator count will not show any warnings. In this situation, `validatorCount` is effectively zero because `IntStream.range(0, -1)` is a range of zero. So it's not really a problem here.

Below are some other options that could benefit from constraints. I'm able to specify negative values for all of them.

```
--eth1-deposit-contract-max-request-size=<INTEGER>
--metrics-port=<INTEGER>
--p2p-advertised-port=<INTEGER>
--p2p-advertised-udp-port=<INTEGER>
--p2p-peer-lower-bound=<INTEGER>
--p2p-peer-upper-bound=<INTEGER>
--p2p-port=<INTEGER>
--p2p-udp-port=<INTEGER>
--rest-api-port=<INTEGER>
--validators-external-signer-timeout=<INTEGER>
--data-storage-archive-frequency=<FREQUENCY>
--number=<arg1>
```

### Possible Solution

Add validation constraints to some picocli options. Here is an example:

* https://picocli.info/#_jsr_380_beanvalidation

This would look like:

```java
@Min(value = 0, message = "Genesis time must be a positive value")
@Option(
    names = {"-t", "--genesis-time"},
    paramLabel = "<GENESIS_TIME>",
    description = "The genesis time")
private long genesisTime = System.currentTimeMillis() / 1000;
```

Note, another project dependency would be required.

```
implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
```

I would be happy to do this and submit a pull request if it's something we want to fix.

**Comment by ajsutton** [comment]
For simple validations like ensuring the value is positive I think those annotations make a lot of sense. We're already getting the validation-api as a dependency (transitively via swagger and jackson) so no downside to using it.

It would be great if you took this on.

**Comment by ajsutton** [comment]
Actually thinking about this - given there's a start of a programmatic API it may be better to put these checks into the various configuration builder classes for anything in the main beacon node and validator client.  Things like `genesis mock` are just debugging tools so tend to follow simpler patterns, using the annotations there would likely be a quick win without complicating things further.

But for example the `metrics-port` option could be validated in `MetricsConfig.MetricsConfigBuilder.metricsPort` and then the validation would apply to both CLI options as instantiating things programmatically.  I think throwing `IllegalArgumentException` will likely do the right thing but we could also through `InvalidConfigurationException` which is specifically designed to indicate a misconfiguration that causes Teku to exit and print the error message nicely for users (ie show only the message and not the stack trace).

**Comment by jtraglia** [comment]
That's a good point. Whatever we do should work with the programming API. I'll work on putting validation checks in the configuration builder classes and throwing an `InvalidConfigurationException`; friendly error messages are nice. I think this will be a good first issue for me.

**Comment by jtraglia** [comment]
So for the metrics port option, if add `implementation project(':infrastructure:exceptions')` as a dependency in `teku/infrastructure/metrics/gradle.build`, there is a circular dependency:
```
Circular dependency between the following tasks:
:infrastructure:async:compileJava
\--- :infrastructure:metrics:compileJava
     \--- :infrastructure:exceptions:compileJava
          \--- :infrastructure:async:compileJava (*)
```
Is there a simple way to resolve this? I would prefer to use `InvalidConfigurationException` like you suggested.

**Comment by ajsutton** [comment]
hmm, bit of yak shaving to be done on this but I think `:infrastructure:exceptions` shouldn't have the dependency on `:infrastructure:async` that it does.  That means that the `exceptionHandlingRunnable` and `exceptionHandlingConsumer` methods in `ExceptionUtil` probably need to move to somewhere in the `instrastructure:async` module. I think that's a better place for them though. I'm not exactly sure what the class name would be that they land in - maybe just `ExceptionHandlers`?

**Comment by jtraglia** [comment]
@ajsutton I can shave some yaks if you want. I don't think `:infrastructure:exceptions` should have that dependency either. Also, I started a PR just to get the ball rolling. It doesn't allow those options I mention in the issue to have negative values anymore. I also added validation checks to some other options too. I'm not sure if I should add more checks elsewhere or not. To my surprise, throwing `IllegalArgumentException` doesn't print a stack trace and doesn't look that bad, but I'm still planning on changing all of to `InvalidConfigurationException ` exceptions.

**Comment by ajsutton** [comment]
> To my surprise, throwing `IllegalArgumentException` doesn't print a stack trace and doesn't look that bad, but I'm still planning on changing all of to `InvalidConfigurationException ` exceptions.

Yeah we must have special handling for `IllegalArgumentException` when parsing the options but definitely nicer to use the more specific exception type.

Just left a comment on the PR as well. It's looking good - thanks for taking this on.
