### ISSUE TITLE
Fork Version and Signature Domain Size Changes - (Spec PR #738)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#491]
### Description
As an implementor, I want fork versions and signature domains handled consistently so that there are no unexpected type/bounds inconsistencies and so that Artemis is compliant with the beacon chain spec. 

### Acceptance Criteria
* `Fork` field `previous_version` is a `bytes4` instead of `uint64`.
* `Fork` field `current_version` is a `bytes4` instead of a `uint64`.
* `BeaconStateUtil.get_fork_version` expects `Bytes` instead of `UnsignedLong` for `epoch`.
* Ensure assignment to both `previous_version` and `current_version` in `get_genesis_beacon_state` performs `int_to_bytes4` on `GENESIS_FORK_VERSION` for type compatibility.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/738

I'm not immediately able to find where `get_genesis_beacon_state` is implemented and/or simulated in our code. @jrhea @dangerousfood

**Comment by cemozerr** [comment]
The corresponding function to `get_genesis_beacon_state` should be `DataStructureUtil.createInitialBeaconState()`. Let's actually rename the function too in this PR since we should do that sooner rather than later.
