### ISSUE TITLE
[Merge] Support authentication for the Engine API

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#4958]
### Description
Support authentication for engine API as per https://github.com/ethereum/execution-apis/pull/167

**Comment by arhamj** [comment]
If not already picked, I could pick this @ajsutton 

Sub tasks I would be splitting this into:
1. Adding a CLI command to get/generate the 256 bit key
2. Adding auth header to EL APIs

(1) is fairly straight forward. For (2) I'm looking at the following design:
1. Implementing a `TokenProvider` which takes care of the generation of the JWT token as per specs
2. Implementing a wrapper for `TokenProvider` to make it thread safe by introducing a reentrant lock
3. Adding an OkHttp client interceptor consuming an instance of the `SafeTokenProvider` to add the auth header to intercepted requests

**Comment by ajsutton** [comment]
Work hasn't started in this yet but it is next on our priority list and we'll need to get it wrapped up probably early next week. 

If you're able to start on it and ok with us taking where you're up to and finishing it off if need be next week that would be great. Might just be more of a tag team development effort than usual. That usually works well as long as we ensure we push up any work as a draft pr and merge things in as small steps as much as possible. 

You're plan for how to approach it sounds good and getting the cli args added would be a great first pr. We'd make them --X options and mark them hidden for now like the other merge options until we're ready for official merge support.
