### ISSUE TITLE
HTTP accept quality indications not respected for REST API SSZ requests

### ISSUE THREAD

**Issue by arnetheduck** [Consensys-Incorporated/teku#4978]
### Description

[`Accept` quality](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) is a useful way for a REST client to indicate that SSZ is preferred but that it'll also take JSON if forced - this allows some flexibility in requesting block data from different implementations while still choosing the most efficient format supported.

Per discussion with @ajsutton , this may be an issue in Teku (and not infura)

```
# gives SSZ as expected
curl -H "Accept: application/octet-stream" https://xxx@eth2-beacon-mainnet.infura.io/eth/v2/beacon/blocks/head
# gives JSON - should give SSZ, or error
curl -H "Accept: application/octet-stream;q=1" https://xxx@eth2-beacon-mainnet.infura.io/eth/v2/beacon/blocks/head
# gives JSON - should give SSZ, or JSON with lower priority
curl -H "Accept: application/octet-stream,application/json;q=0.9" https://@eth2-beacon-mainnet.infura.io/eth/v2/beacon/blocks/head
```

**Comment by ajsutton** [comment]
One important detail to note here is that if none of the `Accept` options match we should just return the default representation (JSON), not a 404 or error.  So `Accept: foo/foo` would return JSON.
