### ISSUE TITLE
Override constants from config.toml

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#502]
### Description
I want the ability to overwrite the constants defined in Constants.java from config.toml.  This will help us test epoch transitions and other default values defined by the beacon chain spec.

**Comment by akhila-raju** [comment]
Reference: https://gist.github.com/djrtwo/cd8250fee2d851895977627403e91401

**Comment by akhila-raju** [comment]
Static final variables can't be overrode in Java

**Comment by jrhea** [comment]
> Reference: https://gist.github.com/djrtwo/cd8250fee2d851895977627403e91401

This is our config file.  FYI:  https://github.com/PegaSysEng/artemis/blob/master/config/config.toml

**Comment by akhila-raju** [comment]
Closed by #534.
