### ISSUE TITLE
[MEV milestone 2] expose `AuthenticatedFeeRecipient` via  `consensus_getFeeRecipientsV1`

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5024]
As a validator, I want to be able to update my fee recipient to the mev_boost prior to block proposal being due, 
as I need to be able to update to a custom fee recipient.

https://hackmd.io/@paulhauner/H1XifIQ_t#Change-2-Proposal-Promises
when MEV-boost is enabled, I need to issue a proposal promise, which needs signing, and then propagating to mev_boost endpoints. It is important this is signed and propagated prior to a block proposal becoming due, and can be earlier than the slot prior to production - it could be done as soon as the duty is known possibly.

It seems it has been superseded by: https://github.com/flashbots/mev-boost/blob/fd39288869254f3e59451469a6b05ea3ce3c2322/docs/milestone-2.md
which requires VC to send `AuthenticatedFeeRecipient` to be exposed by `consensus_getFeeRecipientsV1` API from BN

**Comment by tbenr** [comment]
this will probably be changed to a "push" approach in which BN will send `AuthenticatedFeeRecipient` by calling `builder_updateFeeRecipientsV1` to mev_boost
