### ISSUE TITLE
[MEV milestone 1] produce a blind unsigned block that contains an execution payload header

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5025]
Support the production of blinded beacon blocks under bellatrix

https://hackmd.io/@paulhauner/H1XifIQ_t#Change-1-Blind-Transaction-Signing

Blinded blocks have some context but only an execution_payload_header, not a full execution payload.

Ultimately this needs to be on a new rest api endpoint, so that full blocks can still be produced from the existing endpoint, and blinded blocks can be retrieved from the new endpoint.

There are currently no rest endpoints defined for use with this feature.

**Comment by tbenr** [comment]
there is a new PR in beacon REST API to follow: https://github.com/ethereum/beacon-APIs/pull/194
applies to #5024 too
