### ISSUE TITLE
Bellatrix Acceptance Test

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#5074]
### Description
We should have acceptance tests that checks teku behaviour with Bellatrix is activated, ideally going through the transition block.
We could think about adding complexity by test several scenarios (ie. optimistic sync)

An option is to have extended AT by running a fixed besu client version capable of running as EL.

Another option is to start using kurtosis.

https://docs.kurtosistech.com/

https://github.com/kurtosis-tech/eth2-merge-kurtosis-module

Pari is already running it daily to check various client compatibility:

https://github.com/parithosh/nightly-kurtosis-test/blob/main/.github/workflows/kurtosis.yml
https://github.com/parithosh/nightly-kurtosis-test/actions

additional examples:
https://notes.ethereum.org/@ExXcnR0-SJGthjz1dwkA1A/H11OzhRAK

**Comment by ajsutton** [comment]
This would actually be an acceptance test in our terminology as it would be end-to-end.

**Comment by zilm13** [comment]
What tests could be done next:
- optimistically pass merge after safe slots, blocked with re-execution issue, 
 #5914
- switch from optimistic sync to normal, blocked by Besu bug 
https://github.com/hyperledger/besu/issues/3988

**Comment by zilm13** [comment]
Though both blockers are merged we couldn't yet finish this until https://github.com/hyperledger/besu/issues/3988 fix is included in release, so we could update Besu version used in acceptance tests. When the fix reaches release, we will need to add to `OptimisticSyncPostMergeAcceptanceTest` and `OptimisticSyncSafeSlotsAcceptanceTest` logic to enable sync with disconnected execution client and wait for non-optimistic block
