### ISSUE TITLE
"Kotlin 1.5 has a breaking change to reflection" message

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5117]
### Description

I just restarted Teku 22.3.0 and saw the following message in the log.

```
2022-03-07 09:25:01.364 WARN  - Kotlin 1.5 has a breaking change to reflection - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
```

We should fix something... either OpenAPI or the warning message.

**Comment by rolfyone** [comment]
this has been present since we upgraded to new javalin (6 months maybe?)

We can try to update again and see if we can get rid of it...

**Comment by zilm13** [comment]
We have the latest version javalin with #5235 and looking at the original issue, it was not solved yet

**Comment by benjaminion** [comment]
Still present in Teku 22.5.2; seems like no prospect of it being fixed at the Javalin end. Is there nothing we can do to suppress this message?

**Comment by rolfyone** [comment]
we could probably suppress it, my understanding was it's just during startup?
Potentially we can change how swagger is used and remove the need for the dependency once the endpoints are all migrated...

**Comment by ajsutton** [comment]
We've migrated the rest APIs now. :tada:
