### ISSUE TITLE
Error starting teku with empty public keys `

### ISSUE THREAD

**Issue by pablomendezroyo** [Consensys-Incorporated/teku#5130]
### Description
[Detailed description of the problem and the impact it has]
Starting Teku in remote signer mode with the following flags:
```
    exec /opt/teku/bin/teku \
        --network=prater \
        --data-base-path=/opt/teku/data \
        --eth1-endpoint=$HTTP_WEB3PROVIDER \
        --validators-external-signer-url=$HTTP_WEB3SIGNER \
        --validators-external-signer-public-keys=$PUBLIC_KEYS_COMMA_SEPARATED \
        --p2p-port=9000 \
        --rest-api-cors-origins="*" \
        --rest-api-interface=0.0.0.0 \
        --rest-api-port=$BEACON_API_PORT \
        --rest-api-host-allowlist="*" \
        --rest-api-enabled=true \
        --rest-api-docs-enabled=true \
        --log-destination=CONSOLE \
        --validators-graffiti=\"$GRAFFITI\" \
        $EXTRA_OPTS
``` 

The public keys loaded onto the flag `--validators-external-signer-public-keys` are obtained dynamically and parsed from the remote signer standard API https://eips.ethereum.org/EIPS/eip-3030#get-keys.

The public keys returned from the remote signer may be empty, this situation is not contemplated by teku, resulting in an error to start teku with empty public keys at `--validators-external-signer-public-keys`

I think this is not the ideal behavior, especially taking into account that the validator and beacon processes run in a monoservice process, so it does not allow to keep syncing the beacon chain if there are no validators loaded

### Steps to Reproduce (Bug)
[Please be as specific as possible]
start teku with an empty string in the flag `--validators-external-signer-public-keys`

**Expected behavior:** [What you expect to happen]
I expected teku to realize that an empty string means no validators and keep running instead of throwing errors. 

**Actual behavior:** [What actually happens]
Start teku with the flag `--validators-external-signer-public-keys` with an empty string result into an error
```
FATAL - Invalid configuration. Signer public key is invalid
```

**Frequency:** [How regularly does it occur?]
The error is thrown on startup so the process keeps in a restarting status.

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]  22.3.0
* Java version: [`java -version`]  official docker image
* OS Name & Version: [`cat /etc/*release`]   official docker image
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by rolfyone** [comment]
Thanks for raising, we'll take a look.

for fixer:
With the validators-api, its now not really invalid configuration to start without keys, we should still warn that there were no keys found to load, but not exit...

Need to check if the other key specifying mechanisms are allowing to specify effectively a 0 length list, there may be some curious details to work through...
