### ISSUE TITLE
[Merge] Generate a new JWT Auth token prior to expriy

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5160]
### Description
Currently teku uses the existing JWT Auth token for the execution Engine API right up until it expires. This means it may have expired by the time it reaches the EL and has no tolerance for clock skew. We should generate a new token a couple of seconds prior to the previous one expiring.

**Comment by zilm13** [comment]
It looks a bit strange for me.
We have an expiration of 5 seconds
https://github.com/ConsenSys/teku/blob/6e940dedce3b3cddb7da306afb6f7271c2425833/ethereum/executionlayer/src/main/java/tech/pegasys/teku/ethereum/executionlayer/client/auth/JwtConfig.java#L19
and we are setting token issuance for the current time + expiration delta, not expiration
https://github.com/ConsenSys/teku/blob/9501d743e9b0fabb35f2f30b1960e1dc952d3300/ethereum/executionlayer/src/main/java/tech/pegasys/teku/ethereum/executionlayer/client/auth/TokenProvider.java#L36
From my perspective it should be, say, 5 minutes token (so it would make a sense to update it a few seconds before, not 2-3 seconds after it's issued) and we should set its expiration to the correct number. If my understanding is correct, I could make a PR

**Comment by ajsutton** [comment]
We're correct in setting the issued at (`iat`) and not expiry in the token but I think you're right that we should be setting it to the current time not now + expiry.  So that `.setIssuedAt` line should be `.setIssuedAt(Date.from(Instant.ofEpochMilli(instantInMillis.longValue())))`.

That error actually explains why we're not seeing timed out JWT tokens more often because the EL will accept the token up to 5 seconds before or after the IAT (https://github.com/ethereum/execution-apis/blob/main/src/engine/authentication.md). So we're starting to use it at the first moment it's viable and stopping 5 seconds before it expires.

When we fix this we'll need to ensure we stop using the token a couple of seconds before the expiry (ie use it at most 3s after iat). Probably the easiest way to do that is to just reduce the `JwtConfig.EXPIRES_IN_SECONDS` to 3 since it isn't used by the actual JWT token but controls when we stop using it.  The EL will continue to recognise the JWT up to 5 seconds after IAT so we then have a 2 second buffer.

The EL is not required to support an expiry in the JWT so we can't set that to 5 minutes.  The idea is that the JWT isn't valid for long to minimise the impact if it's leaked (e.g. if it's included in logs that the user then posts publicly while asking for support those tokens would already be invalid).

**Comment by zilm13** [comment]
@ajsutton yeah but if EL has slightly smaller current time than CL, any token will fail with current bug

**Comment by ajsutton** [comment]
Yes agreed though that's less likely since we generate then send.
