### ISSUE TITLE
Use signed_root For Block ID Purposes in Blocks/State - (Spec PR #816)

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#518]
### Description
As an implementor, I want to use the `signed_root` function instead of `hash_tree_root` when calculating block root, so that block signatures are the same when producing and processing a block. 

### Acceptance Criteria
* `get_temporary_block_header` returns a block header with `signature := EMPTY_SIGNATURE`.
* `cache_state` uses `signed_root` instead of `hash_tree_root` of latest block header when storing the latest block roots.
* `process_block_header` uses `signed_root` instead of `hash_tree_root` of latest block header when verifying the previous block root.
* `build_empty_block_for_next_slot` uses `signed_root` instead of `hash_tree_root` of previous block header when storing the previous block root.

### Additional Information
See https://github.com/ethereum/eth2.0-specs/pull/816

**Comment by vitorpy** [comment]
Working on this.

**Comment by schroedingerscode** [comment]
Hey @vitorpy, it looks like this task is dependent on https://github.com/ethereum/eth2.0-specs/pull/711/, which is a task we chose not to track in Artemis. It's quite possible writing this one up was missed, because it's sandwiched between "contains no substantive changes" labels. Give me a few mins to chat with the team, and we'll get back to ya. 

**Update:** Had a quick chat, and we will track that massive Spec 711 PR, but finishing it in its entirety will take some time, probably more than it's worth you waiting on this task. Luckily, it looks like `get_temporary_block_header` can exist in isolation. So if you feel like implementing that too (probably in `BeaconStateUtil`), then you should be able to make progress on this and everything should co-exist nicely.

As always, feel free to hit us up here or on Gitter if you have any questions. `signed_root` has taken on kind of a mind of its own, because all the ways to implement it in Java are terrible.

**Comment by akhila-raju** [comment]
build_empty_block_for_next_slot is a function created in a test class which won't be implemented.
