### ISSUE TITLE
Add section headings to --help output

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5181]
### Description
PicoCLI supports adding section headings to the help text output: https://picocli.info/quick-guide.html#_section_headings

We should investigate what is actually required to do this and utilise it in teku's help text since we now have a lot of options which can be overwhelming as a single big list.

Besu has been doing this recently so it may be worth leaning from the PRs linked to issue https://github.com/hyperledger/besu/issues/2757

**Comment by whalesallaround** [comment]
Hi @ajsutton. Mind if I work on this? I can have a pull request ready within a day or two

**Comment by ajsutton** [comment]
Yep definitely that would be great.

**Comment by whalesallaround** [comment]
@ajsutton PR ready for review. Thanks :)

**Comment by benjaminion** [comment]
Looks to be resolved by #5550. Closing.
