### ISSUE TITLE
figure out the difference in standard peers interface

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5185]
We did a round of checks fairly recently so this is a little surprising, but the field 'address' in data doesn't appear to be there.
So questions:
  - was it never there and we were always incorrect?
  - did it change and we didn't do the change (has standards implications, just want yes/no though)
  - are other clients all using `address` or the new field? (if they are, we fix the spec instead)

we should probably adapt to standard, and list as a `breaking change`
https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Node/getPeers

**Comment by rolfyone** [comment]
from an initial scan it looks like this field has been the same name for a while so it's possible I just missed it in checking the definitions... may not be heavily used interface given noone has reported it?

**Comment by zilm13** [comment]
I've checked Lighthouse code, they have `last_seen_p2p_address` since 2020, looks like our bug
