### ISSUE TITLE
Report block import timings

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5188]
### Description
To improve diagnostics and aim in performance improvements, we need to establish a way to report key timings for the block import process.  This includes:

* How long after slot start the block is received
* How long between then and ForkChoice.onBlock first being called
* How long it takes to retrieve the parent state
* How long it takes to create the block post state
* How long it takes to actually import the block (ForkChoice.importBlockAndState)
* How long it takes for the transaction to commit

The aim is to get a view of what takes time for block import (in a real node).  We need to ensure that capturing the timings is extremely lightweight so it doesn't affect performance.

Reporting this data is challenging - metrics are only sampled periodically so while a gauge showing timings for the last imported block may be useful, it can also miss information between samples being taken. A histogram shows the average well but tends to hide outliers and doesn't show time periods were performance is unusually slow. Logging the data for every block is too noisy.

I'd suggest:

 1. Add a gauge to show timings for the last imported block (a labelled gauge with a label for each step and the value being the number of millis into the slot when that step was completed).
 2. If a block completes importing more than 4s into a slot (and the node is not in syncing mode), log a warning including the full timing details.

**Comment by ajsutton** [comment]
Probably worth doing the logging of a warning when the block finishes importing more than 4s into the slot as the first step - that likely gives us really useful information with lots of detail but without being overwhelming since late blocks are always noteworthy as they cause incorrect head votes.

**Comment by tbenr** [comment]
@ajsutton I was thinking to a different approach for metrics:

image we have a labeled gauge for each import stage
the label in this gauges are "0-50ms", "50-100ms", and so on with last ">1s"
and we may have an overall processing time gauge with wider time frames

so we can count blocks processing stages that fall into a particular timeframe
with the overall processing time working similarly

it is just matter of finding timeframe "bands" that make sense for each stage.

and we may activate it with a `--Xblock-processing-performance-metrics-enabled` or similar

**Comment by tbenr** [comment]
replace "gauge" with "counter"

**Comment by ajsutton** [comment]
Yeah I like that idea. If they're counters you can track the rate they  increase or just look at relative distribution between them. Might need to play with grafana dashboards to see how to best visualise it but I think we'd be able to make something work.
