### ISSUE TITLE
Issue configuring TLS communication with Web3signer

### ISSUE THREAD

**Issue by Roavill2** [Consensys-Incorporated/teku#5226]
### Description
Following the tutorial for how to configure an external signer (https://docs.teku.consensys.net/en/latest/Tutorials/Configure-External-Signer-TLS/). When trying to start Teku, it falls over with an error stating `Port 9000 (TCP) is already in use.`

There is one minute difference in that my command to start Teku doesn't include `--validators-external-signer-public-keys` which could potentially be causing the issue, but I see you closed #5130 so I'm not too sure.

Bit new to ETH staking so apologies if there are any oversights.

### Steps to Reproduce (Bug)
I've followed the above tutorial step-by-step. For testing purposes I'm trying to connect to mainnet so if that is causing the issue, relatively easy to fix. 

The command to start web3signer:

```
./web3signer \
--tls-keystore-file=/path/to/certs/web3signer_keystore.p12 \
--tls-keystore-password-file=/path/to/certs/web3signer_keystore_password.txt \
--tls-known-clients-file=/path/to/certs/knownClients.txt \
eth2 --slashing-protection-enabled=false
```

The command to start Teku:

```
./teku --network=mainnet \
--eth1-endpoint=https://mainnet.infura.io/v3/4680b6de8566466398040c5768a41436 \
--validators-external-signer-url=https://localhost:9000 \
--validators-external-signer-truststore=/path/to/certs/web3signer_truststore.p12 \
--validators-external-signer-truststore-password-file=/path/to/certs/truststore_pass.txt \
--validators-external-signer-keystore=/path/to/certs/teku_client_keystore.p12 \
--validators-external-signer-keystore-password-file=/path/to/certs/teku_keystore_password.txt
```

**Expected behavior:**
I would expect Teku to start and connect to the web3signer.

**Actual behavior:**
Web3Signer is able to be brought up no issues, however, when trying to run the command to start Teku, this error is returned:

`P2P Port 9000 (TCP) is already in use. Check for other processes using this port.`

### Versions (Add all that apply)
* Software version: `teku/v22.3.2+7-g3c443aa/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`
* Java version: `openjdk version "11.0.14" 2022-01-18`
* OS Name & Version: `Ubuntu:20.04.3 LTS (Focal Fossa)`
* Docker Version: `20.10.10`

**Comment by benjaminion** [comment]
Ah, there's a gotcha here. Both Teku and Web3Signer default to using port 9000 for networking. As per the error message Web3Signer is already running and using the port, so Teku cannot start.

The fix is to run one or the other with a different port assignment. I suggest you add `--p2p-port=9001` to the Teku configuration.

Normally Teku and Web3Signer are not run on the same machine - the intention is for W3S to be run elsewhere in a much more heavily firewalled part of the network - so this isn't usually a problem.

Let us know if this fixes things or not.

**Comment by Roavill2** [comment]
Thanks very much for the explanation! Makes sense to have them running on separate systems.

Just tried out your suggestion and it has fixed my issue!

Appreciate the speediness of your response. Much appreciated.
