### ISSUE TITLE
Incorporate a block replayer among our debugging tools

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5230]
### Description

As a client developer it would be very useful to have easy access to a tool that takes a state and replays a series of historical blocks over it so that I can more easily debug correctness and performance issues.

We have various ad hoc ways of doing this right now. I am suggesting that we add the capability to `teku debug-tools` or somewhere like that as a maintained part of the codebase. An advantage is that it would then be super easy to compare two different Teku versions for example.

### Definition of done

  - I have an easy way to obtain states and blocks in the desired format (e.g. in SSZ or JSON from an archive node/Infura)
  - The tool ingests that state and replays those blocks exactly as that version of Teku would do
  - All my usual relevant options are available, such as setting a debugging level
  - I can do all this with a vanilla Teku installation and do not need to install a separate tool

**Comment by ajsutton** [comment]
We do have `teku transition` which can take a pre state and apply either blocks or empty slots to produce the resulting post state. That assumes the state and blocks are local files - it could be quite useful to update it to support being given the URL to an archive node (or Infura) and a start and end slot then have it download the pre state and blocks itself.  If we do that it probably should save those downloaded states/blocks locally as well to make rerunning faster and make it easier to then inspect their contents.

**Comment by benjaminion** [comment]
Ah, ok. This seems to be not widely known 🙂 Happy if somebody wants to enhance this tool. But will close this for now.
