### ISSUE TITLE
Merge banner art 🐼

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5231]
Apparently it is mandatory to have an ASCII-art banner depicting pandas to appear on the console at the point of the Merge.

We could coordinate with Besu around this. Meanwhile I'll stick a good-first-issue label on this and see if any ASCII art gurus out there want to immortalise their name.

Somewhere around [here](https://github.com/ConsenSys/teku/blob/91c03c1b323c9551286bd10332624e550868f7a3/infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java#L172) might be a good starting point.

Definition of done:
  - An ASCII art banner involving pandas appears at the point when Teku confirms that the TTD has been reached on testnets and mainnet.
  - Everyone agrees that it's super cool.
  - It doesn't break anything.
  - Colour is optional but must respect the user's existing settings.

**Comment by 0xOsprey** [comment]
This could be a good base image for someone talented to go out and use: https://i.imgur.com/4vm3E8m.png

Would be good to set a reasonable expectation around character width as well.

**Comment by rolfyone** [comment]
@issanyo I got your PR running, if you're curious about how it would look:
![Screen Shot 2022-06-10 at 9.59.05 am.png](https://images.zenhubusercontent.com/5e45dddb5e32e495879572b3/ae190821-dd8f-4a5a-bc1d-6c40143a587f)

**Comment by pincente** [comment]
How about this guys...
[bannerPoS.txt](https://github.com/ConsenSys/teku/files/8874953/bannerPoS.txt)

**Comment by rolfyone** [comment]
That looks pretty good too @pincente!

**Comment by aertoria** [comment]
Is this ticket still open? Looks like should be closed.

If it's open I can take it
