### ISSUE TITLE
Feature: Multiple consensus clients for validator client

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#5237]
### Description

Analogous to the validator client option `--beacon-node-api-endpoint`, introduce `--beacon-node-api-endpoints` that takes a comma-separated list of one or more consensus client REST API endpoints. Eventually, deprecate `--beacon-node-api-endpoint`.

### Rationale

This helps with setups that use a single validator client pointed at multiple consensus clients in the backend. For example, I am running a Lighthouse validator client that fails over between Lighthouse, Teku and Nimbus. It'd be great to have more choices for the validator client.

**Comment by benjaminion** [comment]
From what you say about "failing over" I assume the rationale is for redundancy in case of BN failure. We used to have something like this, but for a different reason, and then [removed it](https://github.com/ConsenSys/teku/pull/4860) 🙂 

It's a fairly commonly requested feature, though, so we should revisit it. I think the main additional work is handling the event stream subscription in the case of fail-over.

**Comment by yorickdowne** [comment]
In case of consensus client failure or maintenance, yes. For example, the EL may need to be pruned or resynced. This would, I presume, mean the CL can no longer sync until that's completed (post-merge). Another example, the host OS gets patched and the server reboots.

I see maintenance events once or twice a month, and the Lighthouse VC I currently use just fails over to another CL when they happen.

**Comment by torfbolt** [comment]
It might be useful to add a config option so that one BC can be used exclusively for block proposals, to guard against DDOS attacks. See also [this](https://github.com/sigp/lighthouse/pull/3328) merge request from lighthouse.

**Comment by StefanBratanov** [comment]
> It might be useful to add a config option so that one BC can be used exclusively for block proposals, to guard against DDOS attacks. See also [this](https://github.com/sigp/lighthouse/pull/3328) merge request from lighthouse.

Hi, thanks for your comment. We do have an issue to track this. It is near the top of our backlog. https://github.com/ConsenSys/teku/issues/5929
