### ISSUE TITLE
Don't add states to checkpoint cache when no extra slots processed

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5245]
### Description
When a checkpoint state is requested where the slot is the same as the referenced block, the state will be added to the normal state cache so shouldn't be added to the checkpoint state cache as well.  Only states where additional empty slots were processed need to be added to the checkpoint state cache.

**Comment by rolfyone** [comment]
This should be addressed in current store, after #7359, will close.
