### ISSUE TITLE
Allow `eth1DepositContractDeployBlock` override via CLI

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#5252]
When running new testnets it is useful to allow `eth1DepositContractDeployBlock` definition by command line.
We currently default the value to 0, which than trigger a large number of `eth_getBlockByNumber` calls from `Eth1DepositManager` searching for the deposit contract. It is useful to override it even in case of baked-in configs.

**Comment by ajsutton** [comment]
Won't fix - we can now just specify a deposit snapshot which solves the same problem in a better way.
