### ISSUE TITLE
Use milliseconds for calculating slot intervals

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#5297]
### Description

Currently the validator client uses seconds to calculate slot intervals. This will cause an issue when `SECONDS_PER_SLOT` is not exactly divisible by 3 (e.g. 5 for Gnosis Beacon Chain). The problem is that the decimal points will be stripped and attestation creation and aggregation may be skipped, because it is expected to start earlier than required. 

`TimeBasedEventAdapter` should be modified to use milliseconds instead of seconds for the following scheduled events:

```
taskScheduler.scheduleRepeatingEvent(                                                       
    nextSlotStartTime.plus(oneThirdSlotSeconds),                                            
    secondsPerSlot,                                                                         
    this::onAttestationCreationDue);                                                        
taskScheduler.scheduleRepeatingEvent(                                                       
    nextSlotStartTime.plus(twoThirdSlotSeconds), secondsPerSlot, this::onAggregationDue); 
```

Also other places where slot interval calculation should be modified are:

`Duty Metrics` -> `calculateExpectedAttestationTimeInMillis`
`Fork Choice` -> `isBeforeAttestingInterval`
`Slot Processor` -> `isSlotAttestationDue`

**Comment by tbenr** [comment]
@StefanBratanov 
the trick is not use "fixes" or "resolves" prior to the issue reference :) just put "related to" or something similar

**Comment by StefanBratanov** [comment]
> @StefanBratanov the trick is not use "fixes" or "resolves" prior to the issue reference :) just put "related to" or something similar

oh great, thx for the tip
