### ISSUE TITLE
[Merge] Report on quality of execution payloads produced

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5369]
### Description
Give an indication of how good execution payloads are in blocks we produce:

 * Time between making the preparePayload call and the getPayload call (how long did we give the EL to produce the block?)
 * Gas used vs gas limit - how "full" was the produced block
 * For MEV may be able to report the rewards we were paid

Not sure if this should be a log message or metrics. May need to experiment to see what's more useful.

**Comment by rolfyone** [comment]
closing this ticket, the rest is covered in #5654
