### ISSUE TITLE
Attestation event stream always closes abruptly and can sometimes trigger an Exception

### ISSUE THREAD

**Issue by InvisibleSymbol** [Consensys-Incorporated/teku#5399]
### Description
I need a constant feed of all Attestation my node receives for a project I'm working on. The `http://node/eth/v1/events?topics=attestation` endpoint fits my needs perfectly, but is sadly unusable due to Teku constantly closing the stream. 

_This is both reproducible on my private node and with the endpoints infura provides, as they also use Teku._

### Steps to Reproduce (Bug)
`curl -X GET "http://node:5051/eth/v1/events?topics=attestation" -H 'Accept: text/event-stream'`

**Expected behavior:**
Well, nothing. I would expect an uninterrupted stream of attestation and no Exceptions being triggered.

**Actual behavior:** 
After a few seconds, the stream will simply be cut-off (sometimes in the middle of data), with no error in the node logs. Every now and then an Exception like [this](https://github.com/ConsenSys/teku/files/8577731/teku_exception.log) or [this](https://github.com/ConsenSys/teku/files/8577773/teku_exception.log) appears when the stream gets cut.

**Frequency:** 
The Exception occurs about 20% of the time, the cut-off itselfs always after varying durations (1-30 seconds).

### Versions
* Software version: teku/v22.4.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
* OS Name & Version: Ubuntu 22.04 LTS
* Docker Version: 20.10.14 Community
* Cloud VM, type, size: Hetzner AX41-NVME

**Comment by ajsutton** [comment]
Sorry, we discussed this but apparently didn't actually post a response here. The event stream will disconnect when there are too many messages backed up that haven't been delivered to a subscriber yet. That protection is really important to prevent clients from connecting but never reading any data and then having pending events queue up and use all of Teku's memory.

The problem with trying to subscribe to attestations is that when the node is subscribed to all subnets it will receive about 10,000 attestations all at once and that tends to cause the queue of messages to spike and cause the connection to be disconnected.

You can increase the maximum queue size with `--Xrest-api-max-pending-events` to better handle these spikes.  We can probably also change the disconnection to allow the maximum to be exceeded for a short period of time to better handle these kinds of spikes.
