### ISSUE TITLE
[Merge] Engine API: replace INVALID_TERMINAL_BLOCK with INVALID + lvh=0x00..00

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#5498]
this PR has been merged: https://github.com/ethereum/execution-apis/pull/217

we should check if there is something to update on our side.

**Comment by rolfyone** [comment]
It looks like we're covered here, I can't find any code that uses invalid_terminal_block, and there's a test with a json payload that has 'latestValidHash' coming in.

Is there anything else I should check to confirm @tbenr or should I close this ticket?

**Comment by tbenr** [comment]
well there is this to be removed https://github.com/ConsenSys/teku/blob/0f5b642625ff30cd5f5f590aedd918752a57acf3/ethereum/spec/src/main/java/tech/pegasys/teku/spec/executionlayer/ExecutionPayloadStatus.java#L22

I'm checking if we need to have a special handling of ZERO lastValidHash

**Comment by rolfyone** [comment]
will do this in a couple of weeks once people aren't referencing this code any more...

**Comment by tbenr** [comment]
OK. I don't think we need to do anything else.
