### ISSUE TITLE
Gossip validation: Ignore Aggregates Which Are Following the Wrong Finalized Checkpoint

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5566]
### Description
As per
https://github.com/ethereum/consensus-specs/pull/2846/

**Comment by rolfyone** [comment]
We had optimised to remove the reject rule, because by that part of the logic we can search but the aggregates are gone.
Because the rule is no longer in our code, we have nothing to update from reject to ignore.

**Comment by rolfyone** [comment]
We had optimised to remove the reject rule, because by that part of the logic we can search but the aggregates are gone.
Because the rule is no longer in our code, we have nothing to update from reject to ignore.
