### ISSUE TITLE
BeaconAPI Spec Conformance

### ISSUE THREAD

**Issue by z3n-chada** [Consensys-Incorporated/teku#5583]
### Description
Non-conformance to BeaconAPI spec.

### Steps to Reproduce (Bug)
Issues with the following endpoints:
| API Path                                              | Inputs | Issue                         |
|:----------------------------------------------------- |:------ |:----------------------------- |
| /eth/v1/beacon/states/(state)/root                    | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/fork                 | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/finality_checkpoints | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/validators           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/committees           | "head" | No execution_optimistic field |
| /eth/v1/beacon/states/{state_id}/sync_committees      | "head" | No execution_optimistic field |
| /eth/v1/beacon/headers                                | "head" | No execution_optimistic field |
### Versions (Add all that apply)
* Software version: teku/v22.5.0+65-ga583e7a/linux-x86_64/-debian-openjdk64bitservervm-java-17
* Java version: N/A
* OS Name & Version: N/A
* Docker Version: N/A
* Cloud VM, type, size: N/A

**Comment by rolfyone** [comment]
Thanks for raising this, I've had a look into it and there were definitely some missing.

I'm not sure if something had already changed, but `states/{state_id}/validators`, `states/{state_id}/committees`, `states/{state_id}/sync_committees`, `beacon/headers` do list `execution_optimistic` in their responses.

The other endpoints it as missing, they've been recently migrated to a new framework and for whatever reason it was missed.

As we transition, the documentation and code are disconnected, so I did a pass of these endpoints and the published doc does appear to include execution_optimistic, so was just a code level issue.
