### ISSUE TITLE
Update rest api endpoints using ChainDataProvider and ValidatorDataProvider

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5606]
All REST endpoints that use ChainDataProvider can potentially return a 204/503 error via the generic handler, when a `ChainDataUnavailableException` is raised, or a `ServiceUnavailableException`.
Any rest api endpoints that are affected will extend `MigratingEndpointAdapter`.

For all endpoints that use `ChainDataProvider` or `ValidatorDataProvider`, in their metadataBuilder, they should be calling `.withChainDataResponses()`, and should not be listing their own response of 204 (SC_NO_CONTENT) or 503 (SC_SERVICE_UNAVAILABLE).
The rest api handlers are located in `data/beaconrestapi/src/main/tech/pegasys/teku/handlers`. They'll all have private providers that look like one of:
`ValidatorDataProvider provider;`
`ChainDataProvider provider;`

The flow on effect is that the `MigratedOpenApiIntegrationTest` will require that files get updated to include the responses, basically the change is in output and just needs to be applied to the write resource paths for the test.

Unit tests should be added for the adapters that didn't list these return codes, they'll be basically:
```
  @Test
  void metadata_shouldHandle204() {
    verifyMetadataEmptyResponse(handler, SC_NO_CONTENT);
  }
  @Test
  void metadata_shouldHandle503() throws JsonProcessingException {
    verifyMetadataErrorResponse(handler, SC_SERVICE_UNAVAILABLE);
  }
```

**Comment by vanderheijden86** [comment]
Hi @rolfyone , is this still an open issue? If so, I am happy to pick it up.

**Comment by rolfyone** [comment]
Still open, some details have changed ever so slightly...

`MigratingEndpointAdapter` is no more, they all extend `RestApiEndpoint` now, we've finished our conversion and renamed it.
`MigratingOpenApiIntegrationTest` is now renamed to `OpenApiIntegrationTest`

The rest of the details look good :) Let me know if you need a concrete example!

**Comment by KatyaRyazantseva** [comment]
Assign me to this issue, please
