### ISSUE TITLE
Use Teku for the beaconchain explorer

### ISSUE THREAD

**Issue by skylenet** [Consensys-Incorporated/teku#5647]
I've been trying to use the Teku as the underlying beacon client for the beaconchain explorer ( https://github.com/gobitfly/eth2-beaconchain-explorer ) . Officially it only supports Prysm or Lighthouse for now.

The beaconchain explorer seems to be using a custom API from Lighthouse to get some metrics about validator inclusion per epoch : `/lighthouse/validator_inclusion/{epoch}/global`

It returns something like the following:

```json
{
    "data": {
        "current_epoch_active_gwei": 3365824000000000,
        "previous_epoch_active_gwei": 3365696000000000,
        "current_epoch_target_attesting_gwei": 3100288000000000,
        "previous_epoch_target_attesting_gwei": 3200480000000000,
        "previous_epoch_head_attesting_gwei": 2899808000000000
    }
}
```

Which the beaconchain explorer then transforms the information it needs like:

```go
return &types.ValidatorParticipation{
        Epoch: epoch,
        // technically there are rules for delayed finalization through previous epoch, applied only later. But good enough, this matches previous wonky behavior
        Finalized:               float32(parsedResponse.Data.CurrentEpochTargetAttestingGwei)/float32(parsedResponse.Data.CurrentEpochActiveGwei) > (float32(2) / float32(3)),
        GlobalParticipationRate: float32(parsedResponse.Data.PreviousEpochTargetAttestingGwei) / float32(parsedResponse.Data.CurrentEpochActiveGwei),
        VotedEther:              uint64(parsedResponse.Data.PreviousEpochTargetAttestingGwei),
        EligibleEther:           uint64(parsedResponse.Data.CurrentEpochActiveGwei),
    }
 ```
 
I was wondering if Teku has something similar, and if not, how much effort it would be to implement such APIs and if it would make any sense. This is not too important, but it would be nice to be able to use Teku for the beaconchain explorer.

**Comment by ajsutton** [comment]
Sorry for the delay in getting back to you on this.  We don't currently have an API for this but we do publish metrics like this so it should be doable to add an API for this. Might take a bit of fiddling to be able to calculate it on demand for this API but shouldn't be too bad.  We're planning the next sprint this evening so will see if we can get it onto the TODO list.
