### ISSUE TITLE
Include a recent deposit merkle tree snapashot in release

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5672]
### Description
Once #5432 is complete, we could avoid scanning a lot of Eth1 chain history by including a snapshot of the deposit Merkle tree for known networks like MainNet in the release. It can be very useful even when it's pretty old so doesn't need to be updated too regularly.

We should however add a debug-tools subcommand to create the snapshot and ensure its tested well. We should also identify how to verify the created merkle tree carefully as shipping an incorrect one would break the ability to propose blocks so it's very important it does actually line up with the real chain. Possibly can request the Merkle tree root from the deposit contract at the block we sync the snapshot up to?

**Comment by ajsutton** [comment]
This has been working reliably on our testnet nodes. Suspect we should move to enabling it by default so we can close this out as done.

**Comment by zilm13** [comment]
competed with #7039
