### ISSUE TITLE
Switch default database format back to leveldb2

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5746]
### Description
Teku currently defaults to `leveldb-tree` format which uses a lot of disk space (though queries are fast) by default. This turns out to not be what most users want even when they are doing an archive sync. We should switch the default format back to `leveldb2` which uses the snapshot based storage.

When `--data-storage-archive-frequency` is set to 1 we should automatically use `leveldb-tree` since it will then be the more space efficient storage format.

**Comment by rolfyone** [comment]
Given how efficient tree storage is, it may be something like frequency less than 100? or similar anyway... haven't tested to figure out a tipping point...
That arg (frequency) is also hidden, did we need to unhide it?

**Comment by ajsutton** [comment]
The fréquence arg shouldn't be hidden (no -X prefix and people seem to know about it).  Not sure if we should try to be clever about the cut-off - tree storage will always store every state so frequency=1 is very accurate.  It probably is more space efficient for other frequencies too but not sure if it's potentially more confusing for users if we try to be clever here.
