### ISSUE TITLE
MEV - Discrepency between error raised by Beacon node and received by Validator

### ISSUE THREAD

**Issue by nalepae** [Consensys-Incorporated/teku#5761]
### Description
After following [this document](https://hackmd.io/@StefanBratanov/BkMlo1RO9), if the Beacon node is not in sync, then:

The Beacon node raises this error (Error 503):
```
2022-06-10 10:52:27.103 ERROR - Failed to process request to URL http://kiln-teku-beacon-0-rpc.ethereum-common:5051/eth/v1/validator/duties/sync/20479
java.lang.IllegalStateException: Content required for status code 503 but not provided
at com.google.common.base.Preconditions.checkState(Preconditions.java:562) ~[guava-31.1-jre.jar:?]
at tech.pegasys.teku.infrastructure.restapi.endpoints.JavalinRestApiRequest.respondWithCode(JavalinRestApiRequest.java:133) ~[teku-infrastructure-restapi-develop.jar:22.5.2+95-gab816b2]
```

The Validator raises this error (Error 500):
```
2022-06-10 10:52:27.106 ERROR - Failed to request validator duties for epoch 20479. Retrying after delay.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unexpected response from Beacon Node API (url = http://kiln-teku-beacon-0-rpc.ethereum-common:5051/eth/v1/validator/duties/sync/20479, status = 500)
at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
```

Note no more error appears when the Beacon node is in sync.

### Steps to Reproduce (Bug)
Follow [this document](https://hackmd.io/@StefanBratanov/BkMlo1RO9)

**Expected behavior:** [What you expect to happen]
No discrepency between errors, and for UX design, maybe replace StackTrace by an Error or Warning log.

**Actual behavior:** [What actually happens]
See Description

**Frequency:** [How regularly does it occur?]
Always when beacon node is not in sync.

### Versions (Add all that apply)
* Software version: `teku/v22.5.2+89-g1687447/linux-aarch_64/-eclipseadoptium-openjdk64bitservervm-java-17` (develop)

**Comment by ajsutton** [comment]
This will be because the endpoint's metadata doesn't specify that a 503 response is possible so it doesn't know how to send one.  We'll need to add a test for this and fix the metadata.

**Comment by ajsutton** [comment]
Thank you for reporting btw. :)

**Comment by rolfyone** [comment]
i quickly checked sync duties, it's got 503 in its listing, doesn't have 400 though... should be able to replicate and see exactly whats going on by the looks, thanks for raising!

**Comment by ajsutton** [comment]
Ah, reading the error message more carefully 503 is declared, but requires content and no content was provided. But yeah, should be easy enough to reproduce in a test and go from there.

**Comment by rolfyone** [comment]
It looks like this problem also exists in `GetProposerDuties`, from framework migration - fix up shortly.
