### ISSUE TITLE
Possible sync stall on execution layer outage

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#5824]
### Description
Say, we are syncing on gossip and suddenly our execution layer goes down. We have `ReexecutingExecutionPayloadBlockManager`, which will try re-execution for next 2 slots (and we don't want to increase this number, because it could be a bad payload forcing our EL to fail). After that we will drop this block and get following chain:
    SUCCESS <- SUCCESS <-[nothing]<- UNKNOWN_PARENT <- UNKNOWN_PARENT
We are unable to pass this issue on gossip, we'll return to normal sync after `StatusMessage` exchange which is once in 5 minutes with every node. We have a lot of peers on mainnet and some `StatusMessage` always arrives in a few seconds, but in private networks or tests it could be a real problem stalling sync for up to 5 minutes.

As a solution we may need to adjust our gossip handling to ensure it retries execution when we get a new descendant of block with failed execution verification (`FAILED_EXECUTION_PAYLOAD_EXECUTION`).
### Steps to Reproduce (Bug)
Shutdown execution layer after merge when on gossip sync. Start it after more than 2 slots.

**Comment by ajsutton** [comment]
Resolving this as we've updated the way we retry executing payloads.  Have seen this working reliably now during both long sync and when following chain head via gossip.

**Comment by zilm13** [comment]
Should be fixed by #5941
