### ISSUE TITLE
Block production can fail when eth1 deposits are not current

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5836]
```
ERROR | BeaconRestApi | Failed to process request to URL ..../eth/v2/validator/blocks/....
tech.pegasys.teku.validator.coordinator.MissingDepositsException: Unable to create block because ETH1 deposits are not available. Missing deposits 410438 to 410582
```

In this case, we've failed with 500 with full stack trace.

What'd be nice is if GetNewBlock fails (v2 only is fine), and the exception is a `MissingDepositsException`, we should pass back the error message, still as a 500 error, and we won't need to fall through to the default exception handler and print the stack trace.

This will give the user a lot more context about what may be going wrong.

**Comment by sragss** [comment]
Can I take this?

**Comment by ajsutton** [comment]
@sragss Yep, happy for you to take a look at this.  Give us a yell either here or in Discord (https://discord.gg/7hPv2T6 in the #teku channel) if you have any questions. And it's always helpful to put work up as a draft as early as possible to get feedback on the general direction even if you know there's more stuff to work on.

**Comment by ajsutton** [comment]
Assigned to me so no one else takes it - apparently can't assign it to you directly.

**Comment by sragss** [comment]
Thanks! Is the idea here to catch this at the request handler level as follows?
```
  @Override
  public void handleRequest(RestApiRequest request) throws JsonProcessingException {
    final UInt64 slot =
        request.getPathParameter(SLOT_PARAMETER.withDescription(SLOT_PATH_DESCRIPTION));
    final BLSSignature randao = request.getQueryParameter(RANDAO_PARAMETER);
    final Optional<Bytes32> graffiti = request.getOptionalQueryParameter(GRAFFITI_PARAMETER);
    final SafeFuture<Optional<BeaconBlock>> result =
        provider.getUnsignedBeaconBlockAtSlot(slot, randao, graffiti, false);
    request.respondAsync(
        result
            .thenApply(
                maybeBlock ->
                    maybeBlock
                        .map(AsyncApiResponse::respondOk)
                        .orElseThrow(ChainDataUnavailableException::new))
            .exceptionally(
                err -> {
                  if (err.getCause() instanceof MissingDepositsException) {
                    return AsyncApiResponse.respondWithError(
                        SC_INTERNAL_SERVER_ERROR, err.getCause().getMessage());
                  } else {
                    // Fall through to default exception handler
                    throw (RuntimeException) err;
                  }
                }));
  }
```

 Or should this be done at the `DefaultExceptionHandler` level? Are there some similar examples that someone can point to?

I notice that other error types such as `ServiceUnavailableException` and `ChainDataUnavailableException` do not log stack traces but don't see where that is implemented.

**Comment by sragss** [comment]
Let me know if we should also check that it is a `GetNewBlock` call.
