### ISSUE TITLE
Fix code scanning alert - Insertion of sensitive information into log files

### ISSUE THREAD

**Issue by behroozreview** [Consensys-Incorporated/teku#5856]
Consider using a secure logging library for Java

Tracking issue for:
- [ ] https://github.com/ConsenSys/teku/security/code-scanning/652

**Comment by ajsutton** [comment]
Going to close this one - we already have this alert tracked through the code scanning alerts and the information being logged isn't sensitive (and is important for the user to see to be able to resolve the issue).
