### ISSUE TITLE
Fix Swagger UI issues for JsonTypeDefinitionBeaconRestApi

### ISSUE THREAD

**Issue by courtneyeh** [Consensys-Incorporated/teku#5875]
To allow the removal of the old api logic, we need to be able to instantiate swagger-ui and the swagger-docs endpoint using the new typedef based api.

Validator-api already has swagger-docs being published, but it's not loading a swagger-ui. This is probably the simpler of the 2 scenarios, as it's already a completely typedef based solution using the `RestApiBuilder`.

`RestApiBuilder.openApiDocsEnabled()` currently adds `swagger-docs` endpoint to the validator-api, so it's just the swagger-ui that's missing.

**Comment by rolfyone** [comment]
@zilm13 can you spend a bit of time (no more than a day) investigating this and writing up an idea of how we might solve this problem? It's possible that `webjars` may be the solution, but I haven't really dug into it.
If we can get an idea of the amount of work involved, we can go from there... I'll have a look over whatever you are thinking tomorrow if that works...
https://javalin.io/documentation#static-files

**Comment by rolfyone** [comment]
one thing that may not have been clear initially - javalin has a plugin, but we want to use our own webjar and manage it ourselves so that it's not coupled to the javalin version we use...
