### ISSUE TITLE
Validator Options parameters not read from `--config-file` when other params are specified via CLI args

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#5878]
Specifying via CLI an option from `ValidatorProposerOptions` (ie `--validators-proposer-config`)  or `ValidatorOptions` (ie `--validators-graffiti`) prevents params from `ValidatorKeysOptions` to be read via yaml config file specified via `--config-file`.

### Example

CLI:
```bash
./teku --config-file ./test.yaml --validators-graffiti test
```
test.yaml
```yaml
validator-keys: ["/etc/teku/keys:/etc/teku/secrets"]
```

`validator-keys` param is ignored and teku will run as it has been never specified.

by removing `--validators-graffiti test` from CLI, `validator-keys` will be read again.

### Initial thought
it seems it's related to how picocli initializes `ArgGroup` groups and how it will apply defaults values.
Since we provide config file functionality as a default value provider, it seems that specifying an argument from a `ArgGroup` causes initialization of all its sub `ArgGroup` which then are considered initialized and no default values are provided.
The same happens if you initialize a sibling group.

A solution could be to flatten all the arguments to `ValidatorOptions` but then we have rethink how to avoid duplication in `VoluntaryExitCommand`.

**Comment by ajsutton** [comment]
We may need to revert the change that added headings to our CLI options as a quick way to fix this - that's what introduced the arg group.  That said, it's probably not that quick a change since it's been a while since it went in so probably worth spending a bit of time seeing if we can find a better way to apply the config file.
