### ISSUE TITLE
remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent

### ISSUE THREAD

**Issue by come-maiz** [Consensys-Incorporated/teku#5884]
### Description

I'm testing teku + nethermind + mev-boost in kiln following this guide:
https://github.com/flashbots/mev-boost/wiki/Testing

At the end, when everything is running, Teku logs this error:
```
2022-07-02 17:59:16.856 ERROR - Merge       *** Transition Configuration error: remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent
  remote configuration: TransitionConfiguration{terminalTotalDifficulty=0x000000000000000000000000000000000000000000000000000012309ce54000, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=55127}
```

I don't know if this is a problem on nethermind or teku, or on the parameters I'm passing. I'm starting my investigation on this here, can you please guide me?

### Steps to Reproduce (Bug)

Follow the steps in:
https://github.com/flashbots/mev-boost/wiki/Testing

**Expected behavior:** Teku starts producing blocks built by the mev relay.

**Actual behavior:** This error message is logged:
```
2022-07-02 17:59:16.856 ERROR - Merge       *** Transition Configuration error: remote Execution Client TerminalBlockHash and TerminalBlockNumber are inconsistent
  remote configuration: TransitionConfiguration{terminalTotalDifficulty=0x000000000000000000000000000000000000000000000000000012309ce54000, terminalBlockHash=0x0000000000000000000000000000000000000000000000000000000000000000, terminalBlockNumber=55127}
```

Everything seems to be running anyway, so I don't know if this is problematic, or just noise.

**Frequency:** The error is logged every minute

### Versions (Add all that apply)
* Software version:
```
~/workspace/kiln/teku$ ./build/install/teku/bin/teku --version
teku/v22.6.1+21-ga046c52/linux-x86_64/-privatebuild-openjdk64bitservervm-java-11

$ java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.22.04.1, mixed mode, sharing)
```

* OS Name & Version: 
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

* Cloud VM, type, size: digital ocean

**Comment by tbenr** [comment]
Hi, the problem is the nethermind configuration. Teku is detecting a missconfiguration: as per spec, when the transition is configured to be done via TTD  the block number should be zero. Block number should be non zero when the transition is configured via block hash/epoch number (in that case TTD should be zero)

**Comment by come-maiz** [comment]
Thanks @tbenr! moving this to nethermind :point_up:
