### ISSUE TITLE
`QUANTITY` fields in ExecutionPayloadV1 are too permissive

### ISSUE THREAD

**Issue by marioevz** [Consensys-Incorporated/teku#5899]
### Description

Execution client's Engine API specifies `baseFeePerGas` as a `QUANTITY` field which has the following restrictions:

>Values of a field of QUANTITY type MUST be encoded as a hexadecimal string with a 0x prefix and the leading 0s stripped (except for the case of encoding the value 0) matching the regular expression ^0x(?:0|(?:[a-fA-F1-9][a-fA-F0-9]*))$.
> 
>Note: Byte order of encoded value having QUANTITY type is big-endian.

Currently is possible to feed Teku the following spoofed values and they will end up in the Execution payload without issues:
- `Spoofing (node 1) blockNumber, 0x34 -> 0x00000000000000034` (Overflow 64bits)
- `Spoofing (node 2) blockNumber, 0x35 -> 0x035` (Leading zero)
- `Spoofing (node 1) gasLimit, 0x1c9c380 -> 0x00000000001c9c380` (Overflow 64bits)
- `Spoofing (node 2) gasLimit, 0x1c9c380 -> 0x01c9c380` (Leading zero)
- `Spoofing (node 1) gasUsed, 0x0 -> 0x00` (Leading zero)
- `Spoofing (node 1) gasUsed, 0x0 -> 0x` (Empty hex)
- `Spoofing (node 1) timestamp, 0x62c5ec6f -> 0x00000000062c5ec6f` (Overflow 64bits)
- `Spoofing (node 2) timestamp, 0x62c5ec75 -> 0x062c5ec75` (Leading zero)
- `Spoofing (node 2) baseFeePerGas, 0x50ef0 -> 0x050ef0` (Leading zero)

### Steps to Reproduce (Bug)
Using hive branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients, run:

```
./hive --client go-ethereum,teku-bn,teku-vc --sim eth2/engine --sim.loglevel 5
```

**Expected behavior:** The payload should be rejected

**Actual behavior:** The payload is accepted and incorporated into a beacon block.

**Frequency:** Always during this test case (invalid-quantity-fields)

### Versions (Add all that apply)
* Software version: teku/v22.6.1+29-gb2bc943/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
* Java version: openjdk 17.0.3 2022-04-19
* OS Name & Version: Ubuntu 18.04.6 LTS
* Docker Version: 20.10.17

**Comment by marioevz** [comment]
I've updated the hive simulator branch, please update to the latest commit and use this command instead to run only a single test case:
```
./hive --client go-ethereum,teku-bn,teku-vc --sim eth2/engine --sim.loglevel 5 --sim.limit "/invalid-quantity-fields"
```

**Comment by ajsutton** [comment]
Thanks for logging this. We'll take a look. In general Teku follows Postel's law "Be liberal in what you accept and conservative in what you send". There's no real ambiguity in what's meant with these examples, but given we have hive tests and the JSON-RPC spec is explicit in forbidding these things it's worth enforcing it in Teku as well.

**Comment by tbenr** [comment]
@marioevz
I'm fixing this but I cant run hive tests since it brakes compiling the tests
```
INFO[07-19|10:26:52] building image                           image=hive/simulators/eth2/engine:latest dir=simulators/eth2/engine nocache=false pull=false
EROR[07-19|10:27:04] image build failed                       image=hive/simulators/eth2/engine:latest err="The command '/bin/sh -c go build -o ./sim .' returned a non-zero code: 2"
The command '/bin/sh -c go build -o ./sim .' returned a non-zero code: 2
```

**Comment by ajsutton** [comment]
I hit that today too - it doesn't seem to build on ARM architectures.
