### ISSUE TITLE
Update execution payload re-execution strategy

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#5914]
We currently have two PRs (#5840 and #5868) insisting on the same `ReexecutingExecutionPayloadBlockManager` class which handles the logic to re-execute a payload when it fails due to low level\networking exceptions, with the aim of being more resilient to short term outages.

## Current behaviour
We re-execute failing blocks every 2 seconds. We expire the re-executing when block's slot become more than 2 slot older than the current slot. It means it will re-executend for current slot and for the next 2 slots.

**Summary: blocks that arrives in time will be re-executed every 2s for 36s**

Existing bug: There is an unintended behaviour in which we are queuing for re-execution an already expired block (so it may be executed if the pruning happening `onSlot` doesn't kick-in before the 2s tick). This may happen if we hit a timeout on EL, when we may end up by re-executing it several time.

## Intents of the current PRs

#5840 wants to solve a stall problem (#5824, syncing doesn't kick-in quickly enough) by continue re-executing a block every time a descendant of that block is received. The goal is to extend the time window in which we re-execute it to be able to recover without start syncing.

#5868 wants to avoid too many re-execution by reducing slot expiry from 2 to 1 (24s likely re-execution time, 12s guaranteed)
The idea is fail fast and relay on sync process to kick-in for recovery. It also solves the bug mentioned above.

## How to proceed

Solve the mentioned bug in a dedicated pr:
- [x] #5915

We should then discuss here what are the general re-execution\retry behaviour we want to have on:

BlockImport via Gossip (currently implemented in `ReexecutingExecutionPayloadBlockManager` wrapping `BlockManager`)
BlockImport via BatchSync (nothing implemented yet)

Then we could implement a re-execution system managing both cases, or split them in two classes if the logic differs too much.

Optionally:
Improve the way we engage syncing by being more reactive (if actually needed)

**Comment by ajsutton** [comment]
Going to call this done for now.  Batch sync will automatically retry already and is only syncing a single chain so unlikely to swamp the EL.  Gossip is now handled simply but sensibly and shouldn't cause issues for the EL, while the new approach has fixed problems seen in hive tests and shown that Teku doesn't retry correctly and then carry on following the chain.
