### ISSUE TITLE
Add sentry node capability

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#5929]
Background is [here](https://hackmd.io/2KXAIkIBR9Ki_yrfRbUH4g?view#Sentry-node-approach-short-term)

In short, the IP addresses of beacon nodes can be deduced from the their attestation activity. This would allow an attacker to DDoS a node that was due to make a block proposal, in order to gain MEV or otherwise disrupt the network. Sentry nodes (Cosmos terminology [afaics](https://forum.cosmos.network/t/sentry-node-architecture-overview/454)) would only publish blocks (from a different IP) and so remain anonymous.

Even shorter: the validator sends attestations via one BN, and block proposals via a different BN.

I have no idea how this interacts with MEV-Boost.

---
**Changes required:**
- [x] Read sentry node configuration file (based on format defined [here](https://hackmd.io/0jhD6wEzQLWnE3huXLkjgg#%E2%80%9CRole-centric%E2%80%9D-config))
- [x] Support reading config from local file or URL
- [x] Implement a new `SentryValidatorApiChannel` (name not final) that extends the `ValidatorApiChannel` and encapsulates the logic of choosing the right endpoint for each method. Possibly need a new implementation of `BeaconNodeApi`.
- [x] Update `ValidatorClientService` to consume sentry config (when enabled) and instantiate the correct `ValidatorApiChannel` instance.
- [x] Update cli options with new option for sentry config file
- [x] Refactor config deserializer to use a builder

**Out of scope (for now):**
- Live reload of sentry config file
- Minimise subnet subscriptions #6112

**Comment by ajsutton** [comment]
There are quite a few options we may want to control when selecting which beacon node to use for specific activities. I've written up some thoughts at https://hackmd.io/0jhD6wEzQLWnE3huXLkjgg including a first stab at a config file that could support the required variations of configuring sentry nodes to avoid DoS attacks as well as potentially allowing us to support allocating specific beacon nodes to specific attestation subnets to avoid all nodes having to subscribe to all subnets.

**Comment by ajsutton** [comment]
We should also consider how vouch can be configured to separate duties: https://github.com/attestantio/vouch/blob/master/docs/configuration.md

At first glance it looks roughly similar but I'm not sure of the impacts of the hierarchical nature and whether that's worth considering.

**Comment by lucassaldanha** [comment]
After consideration, we have agreed to proceed with what we called "role-centric" config. More info [here](https://hackmd.io/0jhD6wEzQLWnE3huXLkjgg#%E2%80%9CRole-centric%E2%80%9D-config).

I have updated the description with a brief description of the changes required to implement this functionality.

**Comment by lucassaldanha** [comment]
A limitation when using blinded block means that we will need to ensure that we use the same beacon node for creating and publishing blocks. 

Some consequences are:
- Slightly less shielded as malicious actors can try to trace your node IP based on your the blocks you gossip. However, given this happens less frequent than attestations, it should be less of an issue. (and we will support having a pull of block creator/publisher nodes what should make it even harder)
- When using MEV-boost, it will need to be paired with the block creator/publisher node.
- Maybe people will end-up using the 2-node deployment approach, which is fully supported in our model.

**Comment by lucassaldanha** [comment]
This feature has been released as experimental. Preliminary documentation on how to use it can be found here: https://github.com/ConsenSys/doc.teku/pull/397
