### ISSUE TITLE
check non-canonical block storage when using blinded blocks

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5955]
While doing database upgrade, I noticed something peculiar...

I have a database I'm updating, and have non-canonical block storage enabled.

While syncing, I get non-canonical blocks added, by the end of the update I seem to have quite a number.

Before turning on blinded block storage there's no non-canonical blocks, and by the end of syncing to get to head, I have a whole bunch, and syncing to get to head should not be importing non-canonical blocks...

I suspect that `storeNonCanonicalBlocks` is not functioning correctly when in blinded mode currently...

**Comment by rolfyone** [comment]
I'm fairly sure the fix is to add a check in the for loop in `BlindedKvStoreDatabase.storeNonCanonicalBlocks`, but it needs to be tested
```
        if (finalizedChildToParentMap.containsKey(blockRoot)) {
          continue;
        }
```
The initial problem of non-canonical indices being added is resolved by this snippet, but we need automated tests to ensure that problem doesn't happen again.

**Comment by ajsutton** [comment]
We removed the blinded block support so can close this.
