### ISSUE TITLE
Remove old feature toggles

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5965]
### Description
Review feature toggles that have been enabled by default for a number of releases and remove them.  Probably best to review the `--X` options teku has (`teku -X` will list them) to find the feature toggles.

**Comment by StefanBratanov** [comment]
I had a look at the `--X` options and the following look like potential candidates for removing:

- --Xfork-choice-equivocating-indices-enabled
- --Xfork-choice-proposer-boost-enabled
- --Xfork-choice-update-head-on-block-import-enabled

**Comment by ajsutton** [comment]
`--Xfork-choice-update-head-on-block-import-enabled` is a new one we need to keep. It's just "backwards" in that we're investigating the consequences of not doing it anymore.  Probably worth a comment on it to explain that actually.

**Comment by ajsutton** [comment]
The other two can definitely be removed now.
