### ISSUE TITLE
Automatically add path to finalized state when --initial-state given domain root

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5978]
### Description
To make it easier for users to use checkpoint sync, automatically detect when the URL given to --initial-state is the root of a beacon node REST API and automatically append `/eth/v2/debug/beacon/states/finalized`

The right approach here is probably to request the root URL and if it is an error response or not application/octet-stream then log an info message and try with the additional path.

I'd be tempted to restrict this to when the supplied URL has no path (or just `/`) to avoid having it kick in because of a typo in the provided URL or something like that.  So `https://example.com` and `https://example.com/` would have the path added but `https://example.com/someting/` wouldn't.

**Comment by mehdi-aouadi** [comment]
@ajsutton Does the initial state file url always end with `/eth/v2/debug/beacon/states/finalized`?
I am trying to understand if we could simply append it to the end of the url if it doesn't exist or if we must check the provided url first

**Comment by ajsutton** [comment]
No it doesn't always end with that. That's the most common path because that's the path to get the latest finalized state in the standard REST API.  But I could put a state file anywhere and point to it - it doesn't have to come directly from the standard REST API.  For example before Infura provided an endpoint, I used to periodically shove states in https://github.com/ajsutton/eth2-states so people could use them for checkpoint sync.
