### ISSUE TITLE
invalid options in yaml result in shutdown with no message

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5984]

**Comment by rolfyone** [comment]
practical example, if i change `initial-state` on my prater to have a typo in it like `xinitial-state`

```
➜  build/install/teku/bin/teku --config-file ~/Library/teku/prater.yaml
➜  echo $?
1
```
Also nothing since a couple of days ago in the teku.log.

We need to report that there was something that couldn't be read, so that the user is able to figure out what's invalid.
similar happens for `data-path` -> `datapath`, `rest-api-enabled` -> `restapi-enabled`, so i think any key that is incorrect.
It would be sufficient for some kind of log message like
`Unknown configuration option "datapath", cannot load configuration.`
It doesn't have to be that exact message, but does indicate my expectation - let the user know what's broken so that they can take corrective actions without having to guess.

For example, if I was to put `--datapath test` on the CLI, I get:
```
➜ build/install/teku/bin/teku --config-file ~/Library/teku/prater.yaml --datapath test
Unknown options: '--datapath', 'test'
Possible solutions: --data-base-path, --data-path, --data-validator-path, --data-beacon-path, --data-storage-mode, --data-storage-archive-frequency, --data-storage-non-canonical-blocks-enabled

To display full help:
teku [COMMAND] --help
```

Which helps me understand what went wrong.

**Comment by jimmygchen** [comment]
@rolfyone looks like most of the code is already there and just needs to be logged. Please see #6000
