### ISSUE TITLE
Remove legacy metrics in `MetricRecordingValidatorApiChannel`

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#5996]
As part of [#5977](https://github.com/ConsenSys/teku/pull/5977) few of the metrics which are used in our official grafana dashboard were changed. These metrics were brought back to achieve compatibility with older versions of the dashboard.

This issue is to remove those metrics all together as well as add a note in the changelog about the removal.

**Comment by StefanBratanov** [comment]
As part of https://github.com/ConsenSys/teku/pull/5977 few of the metrics which are used in our official grafana dashboard were changed. These metrics were brought back to achieve compatibility with older versions of the dashboard. 

This issue is to remove those metrics all together as well as add a note in the changelog about this change.

**Comment by ajsutton** [comment]
The metrics for compatibility were re-added in https://github.com/ConsenSys/teku/pull/5997 - with some luck we could revert that commit and be done, might get a bunch of conflicts and have to unpick by hand though.
