### ISSUE TITLE
Flag to define headers in engine API requests

### ISSUE THREAD

**Issue by pablomendezroyo** [Consensys-Incorporated/teku#6011]
### Description
[Detailed description of the problem and the impact it has]

With the upcoming merge, 1 EL node cannot receive the head chain from multiple CL nodes due to subjectivity. For this reason, makes sense to look for ways to restrict the use of the engine API in the EL, so it is used by one CL at a time.

### Describe the solution you'd like

In addition to the `auth-token` would be nice to add headers to the EL endpoint (`--ee-endpoint`) requests, to indicate the Host who is requesting. This could be used in conjunction with the host whitelist in Geth `--authrpc.vhosts value`, see [geth docs](https://geth.ethereum.org/docs/interface/command-line-options).

**Comment by ajsutton** [comment]
I'm not entirely sure I see the need for this given that `auth-token` is a full authentication method which is significantly stronger than a custom header.  The Geth `--authrpc.vhosts` setting controls what domains Geth will accept requests on, not a list of suitable sources of requests.  For example if you accessed Geth via `http://geth-node.com/` you would need to add `geth-node.com` to the vhosts list or Geth would reject the request. It doesn't matter where the request comes from.

The way to ensure that only a single CL is able to update the EL is to ensure that the auth token is only known by that CL - in the same way that you'd make sure the CL is configured with the correct custom header in the proposed scheme.

If you really wanted source based permissioning, that's a feature the EL would need to support and it can determine the source of a request without custom headers by looking at the source of the TCP connection (or possibly a `X-Forwarded-For` header if there's a trusted reverse proxy being used).
