### ISSUE TITLE
No guarantee to finalize DepositTree in absence of Eth1Data cached block height

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#6102]
### Description
Since #6095 updating the structure of `DepositTreeSnapshot` block height is included in it and we may fail to finalize deposit tree in absence of execution block data referenced in finalized state's `Eth1Data`. We use height from `Eth1Data` cache, but in some cases, especially when finalization is delayed for many epochs, this data will not be available from the cache.

So, if this data is not found in the cache, we should call EL client to get it and finalize tree when the response is received. This will add an extra complexity to the deposit tree finalization for the side feature. Plus, in active network, we shouldn't ever fall into this, it could be more common for test networks. 
Overall it looks like we could miss several `DepositTreeSnapshot` in test networks relying only on cache, but shouldn't have any issues in mainnet, so we may not need any improvements on this side.

**Comment by ajsutton** [comment]
Closing this - it's extremely unlikely to happen in real networks and just means we'll reload deposits from the EL on the next restart so isn't a big issue.
