### ISSUE TITLE
Don't make first descendant of head the new chain head

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6105]
### Description
Way back, we implemented an optimisation for long sync where if the imported block is the child of the current canonical chain head, it would be set as the new head without having to run fork choice.

While this still holds, during normal operation we run fork choice more often and there is more complexity around it. There is also a potential for race conditions as updating the chain head is an async operation - while they resolve themselves it leads to unnecessary reorgs.

We should investigate not automatically updating the chain head when a block is imported and leave it to be done when fork choice is next triggered to run.

We need to check if there are any async operations like retrieving a new justified/finalized state that should be preached to avoid delays.
Also need to ensure that the chain head gets updated often enough during a long sync and that performance isn't negatively affected.

**Comment by zilm13** [comment]
Did I understand correctly that by optimization you mean not running explicitly [this method](https://github.com/ConsenSys/teku/blob/c3da1c9326ffe7aa6b7d7948db9b6217a7e0e473/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java#L177), so I need to:
- remove setting a head on block import, it should be set by `processHead` when it's run (separately)
- check when we run `processHead`, is there a potential for race but more likely reorgs, we should avoid it
- check what could be cached there
- check that during long sync head is not updated too rarely after changes
- ensure performance isn't negatively affected

**Comment by ajsutton** [comment]
The key thing is that we want to remove the logic that automatically makes a new block the chain head if it descends from the current head block (https://github.com/ConsenSys/teku/blob/c3da1c9326ffe7aa6b7d7948db9b6217a7e0e473/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoice.java#L475-L486).

> remove setting a head on block import, it should be set by processHead when it's run (separately)

Yes, I'm suggesting we think through what would happen if we didn't have `ForkChoice.updateForkChoiceForImportedBlock` which is updating the chain head as soon as we import the block. We would still be calling the `ForkChoice.processHead` method at the same times - that's the "normal" fork choice runs.

The first problem I can see is that we use the block import event to remove included operations from the pool if it's on the canonical chain but will now have to trigger that when we update the chain head, even if it's not strictly a reorg (ie if it just picks a new head further along the same fork).

> check when we run processHead, is there a potential for race but more likely reorgs, we should avoid it

I don't think this is an issue because we already have a bunch of controls around when `processHead` runs and it can handle if there are multiple updates in flight. We're just investigating not updating the head when a new block is imported.

> check what could be cached there
> check that during long sync head is not updated too rarely after changes
> ensure performance isn't negatively affected

Yep to all these.

**Comment by rolfyone** [comment]
code complete behind a feature toggle, need to test this, back to bottom of current for now.

**Comment by lucassaldanha** [comment]
@rolfyone can we finish testing this and close the ticket?

**Comment by rolfyone** [comment]
feature toggle is `--Xfork-choice-first-descendent-as-head-enabled=false` (true by default), does need to be tested.

**Comment by rolfyone** [comment]
once I toggled that on on goerli, our teku detailed board showed 'correct signatures' going from high 90's to mid 20's success, so reverting that for now, need to investigate why.

Formula is : 
```
clamp_max(avg((validator_performance_correct_sync_committee_messages{instance=~"$system"} / validator_performance_produced_sync_committee_messages{instance=~"$system"}) >= 0), 1)
```

need to ensure the fork choice completes before sync committee messages are produced so that we're producing correct duties...

**Comment by rolfyone** [comment]
This has been running on goerli for a couple of weeks ok, have pushed to mainnet-nightly02.

**Comment by rolfyone** [comment]
The PR making this default is #7387, which will merge shortly and fix this issue. Closing.
