### ISSUE TITLE
Feature: add milestone option to transition command

### ISSUE THREAD

**Issue by jtraglia** [Consensys-Incorporated/teku#6114]
### Description

When debugging a transition problem from a fuzzed state, I found that the `teku transition` command was unable to read the pre-state because it started as a Bellatrix state (_i.e.,_ `altairForkEpoch=0` and `bellatrixForkEpoch=0`). I needed to modify some things to get it working. I would have appreciated an option for this. Thoughts?

**Comment by ajsutton** [comment]
You can achieve this by using the `--network` option and pointing to a custom network config file (https://github.com/ConsenSys/teku/blob/eedecbfb66a397fd3dabe2b9375d9f62990af951/ethereum/spec/src/main/resources/tech/pegasys/teku/spec/config/configs/mainnet.yaml is the mainnet one - should be pretty much identical to what the spec has).

You can also override them with the `--Xnetwork-bellatrix-fork-epoch` and `--Xnetwork-altair-fork-epoch` options. Everything in `Eth2NetworkOptions` (https://github.com/ConsenSys/teku/blob/3e0a11f84dea4eb98fbf35fe1abf9d309cf30269/teku/src/main/java/tech/pegasys/teku/cli/options/Eth2NetworkOptions.java) can be used with the transition commands.

Does that cover what you need?

**Comment by jtraglia** [comment]
Ah yes, perfect. Thank you!
