### ISSUE TITLE
Service unavailable when fetching validator duties

### ISSUE THREAD

**Issue by alrevuelta** [Consensys-Incorporated/teku#6144]
### Description

When fetching the validator duties for a given epoch (a recent one close to the head) I get that the service is not available. Note that the endpoint I'm using is `eth/v1/validator/duties/proposer/xxx` and that the node is working properly (i.e. `curl http://localhost:5051/eth/v1/beacon/genesis` works)

```
{"code":503,"message":"Service unavailable"}
```

Note also that I started synching the node with an Infura provided `initial-state` several hours before, so perhaps the node hasn't downloaded the whole beacon chain. However, I'm fetching the duties of very recent epochs so it shouldn't be related.

### Steps to Reproduce

```
curl localhost:5051/eth/v1/validator/duties/proposer/143159
```

**Expected behavior:** Get the duties of this given epoch

**Actual behavior:** Return a "Service unavailable" error

**Frequency:** Always

### Versions (Add all that apply)
* Software version: `consensys/teku:22.8.1`
* Java version: NA
* OS Name & Version: NA
* Docker Version: NA
* Cloud VM, type, size: NA

**Comment by ajsutton** [comment]
The 503 response code indicates that the beacon node is still syncing.  Using initial-state it should have been in sync very quickly, but only if there wasn't already an existing database.  What do the beacon node logs show?

**Comment by alrevuelta** [comment]
Adding the flags I'm using:
```console
- --data-path=/opt/teku/data
- --network=mainnet
- --ee-endpoint=http://geth:8551
- --ee-jwt-secret-file=/consensus/jwtsecret
- --metrics-enabled=true
- --rest-api-enabled=true
- --rest-api-host-allowlist=*
- --initial-state=https://xxx:yyy@zzz.io/eth/v2/debug/beacon/states/finalized
```

Related to the logs:
* I see no errors
* These are the last lines. Note that at the time of writing the head epoch is 143298 (as per beaconcha.in) so my node appears to be in sync.
```
Epoch Event *** Epoch: 143298, Justified checkpoint: 143297, Finalized checkpoint: 143296, Finalized root: 4beff9e039a80bcfd51836a8f1f815fa9fce62e9a183f9776b25964fa138656a

Slot Event  *** Slot: 4585536, Block: 9b3175327a1e239a9287a370a7836a6f75c9149909ab6f982aed78d430a80584, Justified: 143297, Finalized: 143296, Peers: 100

...

Slot Event  *** Slot: 4585551, Block: 761bc6967d62c0c4f87a63801401b5dd99e7f31f7c002ce2defce6c607a28d49, Justified: 143297, Finalized: 143296, Peers: 97
```

The node is not syncing, so already in sync.
```console
$ curl localhost:5051/eth/v1/node/syncing
{"data":{"head_slot":"4585552","sync_distance":"0","is_syncing":false,"is_optimistic":false}}
```

And I have discovered a very weird behaviour. The endpoint `/eth/v1/validator/duties/proposer/xxx` works from `epoch=head` to `epoch=head-4` but it acts as a sliding window:
* For example, let's say head is epoch = 143302
* All epochs: 143302, 143301, 143300, 143299 work
* Epoch 143298 does not work
* When epoch++, epoch 143299 (which previously worked) stops working
* When epoch++ again, epoch 143300 (which used to work) stops working

When `head=143302`
curl localhost:5051/eth/v1/validator/duties/proposer/143302 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143301 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143300 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143299 OK      **<- This used to work!**
curl localhost:5051/eth/v1/validator/duties/proposer/143298 NOK

When `head=143303`
curl localhost:5051/eth/v1/validator/duties/proposer/143303 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143302 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143301 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143300 OK
curl localhost:5051/eth/v1/validator/duties/proposer/143299 NOK. **<- Now it doesn't!**

More NOK examples in case it helps (`head=143303`)
curl localhost:5051/eth/v1/validator/duties/proposer/1 NOK
curl localhost:5051/eth/v1/validator/duties/proposer/50000 NOK
curl localhost:5051/eth/v1/validator/duties/proposer/140000 NOK
curl localhost:5051/eth/v1/validator/duties/proposer/143000 NOK
curl localhost:5051/eth/v1/validator/duties/proposer/143250 NOK

I have checked my setup multiple times and I can't find anything wrong. Note that I'm using docker-compose mounting `/opt/teku/data` in a local folder.

**Comment by alrevuelta** [comment]
> The 503 response code indicates that the beacon node is still syncing

Some more information related to this.

Note that this example uses a different setup than the one described above. It uses a Teku node without any `initial-state` that was just launched.

Using the endpoint I was using in an unsynced node I get this error, which is expected:
```console
$ curl localhost:5051/eth/v1/validator/duties/proposer/1
{"code":503,"message":"Beacon node is currently syncing and not serving requests"}
```

But in my case its "**Service unavailable**" which is different from "**Beacon node is currently syncing and not serving requests**", but still a 503 error.

Perhaps the issue is related to the `initial-state`?

**Comment by ajsutton** [comment]
Ah, calculating proposer duties requires access to a BeaconState from within that epoch.  By default Teku using prune storage mode which doesn't store any states prior to the finalized checkpoint so when you're requesting proposer duties for a historic state the service is unavailable because that state has been pruned and the information is no longer available.  We should provide a more useful reason here though.

So you'd need to set `--data-archive-mode=archive` to get Teku to retain older states but it still wouldn't have information from before you first enable that or before the initial state you sync from.  To get the entire history you'd have to sync from genesis.

Alternatively you could try out the experimental support for reconstructing historic states which lets you using initial-state to get in sync quickly but then backfills the historic beacon states. It will still take quite a while to get through them all but would be faster than syncing from genesis as we don't need to revalidate signatures.  You can enable it with `--Xreconstruct-historic-states`.

**Comment by alrevuelta** [comment]
Thanks! I see, great explanation!

Closing, since it's expected behavior. I solved my problem by just removing the `initial-state` flag and syncing the node from genesis since the suggested alternatives, `archive` doesn't fully solve my issue and I don't want to rely on experimental stuff.
