### ISSUE TITLE
mac OS ， Cannot start normally and exit

### ISSUE THREAD

**Issue by nocb** [Consensys-Incorporated/teku#6154]
### Description
mac OS ， Cannot start normally and exit。 
---------------  T H R E A D  ---------------

Current thread (0x00007fa1f4012800):  JavaThread "main" [_thread_in_native, id=5891, stack(0x0000700004e7d000,0x0000700004f7d000)]

Stack: [0x0000700004e7d000,0x0000700004f7d000],  sp=0x0000700004f776c8,  free space=1001k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnetty_resolver_dns_native_macos_x86_6415947397140365464687.dylib+0x6504]  netty_jni_util_JNI_OnUnload+0x84
C  [libjava.dylib+0x20eb]  Java_java_lang_ClassLoader_00024NativeLibrary_load0+0xd1
j  java.lang.ClassLoader$NativeLibrary.load0(Ljava/lang/String;Z)Z+0 java.base@11.0.9
j  java.lang.ClassLoader$NativeLibrary.load()Z+53 java.base@11.0.9
j  java.lang.ClassLoader$NativeLibrary.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Z+216 java.base@11.0.9
j  java.lang.ClassLoader.loadLibrary0(Ljava/lang/Class;Ljava/io/File;)Z+46 java.base@11.0.9
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)V+48 java.base@11.0.9
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+57 java.base@11.0.9
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@11.0.9
j  io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x69f97a]  _ZL6invokeP13InstanceKlassRK12methodHandle6Handleb14objArrayHandle9BasicTypeS5_bP6Thread+0x4e9
V  [libjvm.dylib+0x69f447]  _ZN10Reflection13invoke_methodEP7oopDesc6Handle14objArrayHandleP6Thread+0xf5
V  [libjvm.dylib+0x424f1a]  JVM_InvokeMethod+0x20a
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@11.0.9
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+100 java.base@11.0.9
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@11.0.9
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@11.0.9
j  io.netty.util.internal.NativeLibraryLoader$1.run()Ljava/lang/Object;+53
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x418911]  JVM_DoPrivileged+0x6d3
J 1717  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.9 (0 bytes) @ 0x000000011c435612 [0x000000011c435540+0x00000000000000d2]
j  io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(Ljava/lang/Class;Ljava/lang/String;Z)V+10
j  io.netty.util.internal.NativeLibraryLoader.loadLibrary(Ljava/lang/ClassLoader;Ljava/lang/String;Z)V+15
j  io.netty.util.internal.NativeLibraryLoader.load(Ljava/lang/String;Ljava/lang/ClassLoader;)V+352
j  io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.loadNativeLibrary()V+53
j  io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider.<clinit>()V+51
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x3855ab]  _ZN13InstanceKlass22call_class_initializerEP6Thread+0x19f
V  [libjvm.dylib+0x384eeb]  _ZN13InstanceKlass15initialize_implEP6Thread+0x49f
V  [libjvm.dylib+0x41649b]  _Z28find_class_from_class_loaderP7JNIEnv_P6Symbolh6HandleS3_hP6Thread+0x58
V  [libjvm.dylib+0x41639f]  JVM_FindClassFromCaller+0x1f9
C  [libjava.dylib+0x1a97]  Java_java_lang_Class_forName0+0x129
J 1817  java.lang.Class.forName0(Ljava/lang/String;ZLjava/lang/ClassLoader;Ljava/lang/Class;)Ljava/lang/Class; java.base@11.0.9 (0 bytes) @ 0x000000011c445347 [0x000000011c445240+0x0000000000000107]
J 1834 c1 java.lang.Class.forName(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class; java.base@11.0.9 (47 bytes) @ 0x00000001151cc434 [0x00000001151cc100+0x0000000000000334]
j  io.netty.resolver.dns.DnsServerAddressStreamProviders$1.run()Ljava/lang/Object;+8
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x418911]  JVM_DoPrivileged+0x6d3
J 1717  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.9 (0 bytes) @ 0x000000011c435612 [0x000000011c435540+0x00000000000000d2]
j  io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>()V+23
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x3855ab]  _ZN13InstanceKlass22call_class_initializerEP6Thread+0x19f
V  [libjvm.dylib+0x384eeb]  _ZN13InstanceKlass15initialize_implEP6Thread+0x49f
V  [libjvm.dylib+0x53b4af]  _ZN12LinkResolver19resolve_static_callER8CallInfoRK8LinkInfobP6Thread+0x6b
V  [libjvm.dylib+0x53cf59]  _ZN12LinkResolver20resolve_invokestaticER8CallInfoRK18constantPoolHandleiP6Thread+0x35
V  [libjvm.dylib+0x397a61]  _ZN18InterpreterRuntime14resolve_invokeEP10JavaThreadN9Bytecodes4CodeE+0x22b
V  [libjvm.dylib+0x39807d]  _ZN18InterpreterRuntime18resolve_from_cacheEP10JavaThreadN9Bytecodes4CodeE+0x37
j  io.netty.resolver.dns.DnsNameResolverBuilder.<init>()V+48
j  io.vertx.core.impl.resolver.DnsResolverProvider.<init>(Lio/vertx/core/impl/VertxImpl;Lio/vertx/core/dns/AddressResolverOptions;)V+495
j  io.vertx.core.spi.resolver.ResolverProvider.factory(Lio/vertx/core/Vertx;Lio/vertx/core/dns/AddressResolverOptions;)Lio/vertx/core/spi/resolver/ResolverProvider;+17
j  io.vertx.core.impl.AddressResolver.<init>(Lio/vertx/core/Vertx;Lio/vertx/core/dns/AddressResolverOptions;)V+7
j  io.vertx.core.impl.VertxImpl.<init>(Lio/vertx/core/VertxOptions;Lio/vertx/core/spi/cluster/ClusterManager;Lio/vertx/core/spi/cluster/NodeSelector;Lio/vertx/core/spi/metrics/VertxMetrics;Lio/vertx/core/spi/tracing/VertxTracer;Lio/vertx/core/net/impl/transport/Transport;Lio/vertx/core/spi/file/FileResolver;Lio/vertx/core/spi/VertxThreadFactory;Lio/vertx/core/spi/ExecutorServiceFactory;)V+472
j  io.vertx.core.impl.VertxBuilder.vertx()Lio/vertx/core/Vertx;+38
j  io.vertx.core.Vertx.vertx(Lio/vertx/core/VertxOptions;)Lio/vertx/core/Vertx;+11
j  io.vertx.core.Vertx.vertx()Lio/vertx/core/Vertx;+7
j  tech.pegasys.teku.AbstractNode.<init>(Ltech/pegasys/teku/config/TekuConfiguration;)V+5
j  tech.pegasys.teku.BeaconNode.<init>(Ltech/pegasys/teku/config/TekuConfiguration;)V+2
j  tech.pegasys.teku.Teku.start(Ltech/pegasys/teku/config/TekuConfiguration;Z)Ltech/pegasys/teku/Node;+21
j  tech.pegasys.teku.Teku.lambda$startFromCLIArgs$2(Ljava/util/concurrent/atomic/AtomicReference;Ltech/pegasys/teku/config/TekuConfiguration;Z)V+3
j  tech.pegasys.teku.Teku$$Lambda$96.start(Ltech/pegasys/teku/config/TekuConfiguration;Z)V+6
j  tech.pegasys.teku.cli.BeaconNodeCommand.call()Ljava/lang/Integer;+15
j  tech.pegasys.teku.cli.BeaconNodeCommand.call()Ljava/lang/Object;+1
j  picocli.CommandLine.executeUserObject(Lpicocli/CommandLine;Ljava/util/List;)Ljava/util/List;+94
j  picocli.CommandLine.access$1300(Lpicocli/CommandLine;Ljava/util/List;)Ljava/util/List;+2
j  picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(Ljava/util/List;)Ljava/util/List;+36
j  picocli.CommandLine$RunLast.handle(Lpicocli/CommandLine$ParseResult;)Ljava/util/List;+4
j  picocli.CommandLine$RunLast.handle(Lpicocli/CommandLine$ParseResult;)Ljava/lang/Object;+2
j  picocli.CommandLine$AbstractParseResultHandler.execute(Lpicocli/CommandLine$ParseResult;)I+16
j  picocli.CommandLine$RunLast.execute(Lpicocli/CommandLine$ParseResult;)I+2
j  picocli.CommandLine.execute([Ljava/lang/String;)I+31
j  tech.pegasys.teku.cli.BeaconNodeCommand.parse([Ljava/lang/String;)I+238
j  tech.pegasys.teku.Teku.start(Ltech/pegasys/teku/cli/BeaconNodeCommand$StartAction;[Ljava/lang/String;)I+55
j  tech.pegasys.teku.Teku.startFromCLIArgs([Ljava/lang/String;)Ljava/util/Optional;+15
j  tech.pegasys.teku.Teku.main([Ljava/lang/String;)V+11
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x39cfa8]  _ZN9JavaCalls11call_helperEP9JavaValueRK12methodHandleP17JavaCallArgumentsP6Thread+0x21c
V  [libjvm.dylib+0x3e1daf]  _ZL17jni_invoke_staticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread+0x11c
V  [libjvm.dylib+0x3e557a]  jni_CallStaticVoidMethod+0x1d1
C  [libjli.dylib+0x4a6e]  JavaMain+0xab5
C  [libsystem_pthread.dylib+0x5e65]  _pthread_start+0x94
C  [libsystem_pthread.dylib+0x183b]  thread_start+0xf
### Steps to Reproduce (Bug)
[Please be as specific as possible]

**Expected behavior:** [What you expect to happen]
normal startup
**Actual behavior:** [What actually happens]
Cannot start normally and exit

**Frequency:** [How regularly does it occur?]

every time

### Versions (Add all that apply)
* Software version: [teku/v22.9.0/osx-x86_64/oracle-java-11]
* Java version: 
 java version  "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

* OS:uname:Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
rlimit: STACK 8192k, CORE 0k, NPROC 1392, NOFILE 10240, AS infinity, DATA infinity, FSIZE infinity
load average:2.36 2.17 2.11

CPU:total 4 (initial active 4) (2 cores per cpu, 2 threads per core) family 6 model 69 stepping 1, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, fma

Memory: 4k page, physical 8388608k(656416k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (11.0.9+7-LTS) for bsd-amd64 JRE (11.0.9+7-LTS), built on Sep 15 2020 15:57:40 by "mach5one" with gcc 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)

**Comment by ajsutton** [comment]
Is that the entire output you get when running teku? It seems to be just the debug info after a JVM crash that lists the running threads but doesn't include the actual reason for the crash which is what we need to be able to help.

**Comment by tbenr** [comment]
It also seems that you are running on a system with 8gb of RAM, so I think you shouldn't give more than 3GB to the JVM.
Refer to: https://docs.teku.consensys.net/en/latest/HowTo/Get-Started/Manage-Memory/

**Comment by ajsutton** [comment]
Going to close this one as we don't have a full error to go on.  Please feel free to reopen if you can provide the requested information.
