### ISSUE TITLE
Support reading blocks as hex data in transition subcommand

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6164]
### Description
To make it easier to replay invalid blocks, add the ability to parse blocks that are stored as hex strings in a file rather than binary ssz to the `teku transition blocks` subcommand.

Specifically we want to be able to create the block file by just copying from our invalid gossip log and pasting it into a file. Can probably autodetect this if the file fails to parse as binary SSZ, try to load it via `Bytes.fromHexString` and then parse that as SSZ.

**Comment by mehdi-aouadi** [comment]
I implemented a hex deserialisation fallback when ssz fails.
The good thing is that the blocks can have mixed format but that makes the code less elegant.
I was thinking of adding a command option to choose the blocks format (which default to ssz if not present) and keep things separate.
