### ISSUE TITLE
Add option to detect which signature is invalid in a block

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6165]
### Description
For performance reasons we do verification of all signatures (except deposits) in a block as a single batch. If any of the signatures are invalid we just reject the block with "Invalid signature" but there's no way to tell which signature was invalid.  We should provide a `--X` option to both teku and the `teku transition blocks` subcommand (most importantly the transition subcommand) to identify exactly which signature is invalid and provide a more useful rejection message.

One way to do this would be to use a non-batching signature verifier though it will be slower.

**Comment by lucassaldanha** [comment]
`TransitionCommand` is already using the non-batch verifier when running.
