### ISSUE TITLE
Modification of agent version for Lodestar

### ISSUE THREAD

**Issue by philknows** [Consensys-Incorporated/teku#6177]
### Description
Reference: https://github.com/ChainSafe/lodestar/issues/4465

Lodestar is looking to modify the agent version gossiped from the default libp2p string `js-libp2p/0.36.2` to `lodestar/version`. We are requesting an update to your client on how you identify Lodestar nodes for better tracking and referencing of Lodestar peers on the network for debug purposes. We will not implement until it has been completed between all the various clients on the network.

### Steps to Reproduce (Bug)
N/A

### Versions (Add all that apply)
N/A

**Comment by ajsutton** [comment]
Currently we don't identify lodestar because I never got around to adding special case code to handle the fact that it doesn't just put `lodestar` at the start of its agent string like every other client. So I'm a big fan of this change. Will start adding detection for the new string.
