### ISSUE TITLE
Make BLS API more consistent

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6204]
### Description
To make it easier to safely work with our BLS APIs we should refactor the APIs and add tests to ensure the behaviour is consistent across in all particular.

In particular the handling of a public key being unparsable should be consistent (throw exception or return false) regardless of which verification method is used, size of batch etc. There are likely a number of variations of this such as signatures being unparsable, keys or signatures not being on the correct curve etc.

We likely also have too many entry points into the BLS verification API and should investigate options for reducing those (e.g always using the `BLSSignatureVerifier` and never `BLS` directly).

Writing comprehensive tests to prove the consistency in all cases is a crucial part of this task. Errorpone rules to enforce lower levels of the BLS API aren't used directly may also be appropriate.

**Comment by lucassaldanha** [comment]
Probably a good idea but will be done as part of a refactor on the BLS modules.
