### ISSUE TITLE
Beacon node fails at a random time soon after starting

### ISSUE THREAD

**Issue by AntoBrajkovic** [Consensys-Incorporated/teku#6206]
### Description
Beacon node fails to sync. Tried with and without the metrics. Assigned different amounts of memory, lifted the amount of open files. The node connects to the execution client. I might have missed something obvious

### Steps to Reproduce (Bug)
run command: otna@ethValidator:~/teku/teku-22.9.0$ JAVA_OPTS=-Xmx20G ./bin/teku --rest-api-enabled=true --rest-api-docs-enabled=true --metrics-enabled=true --metrics-categories=BEACON,PROCESS,LIBP2P,JVM,NETWORK --ee-endpoint=http://localhost:8551 --ee-jwt-secret-file=/home/otna/token.txt

**Expected behavior:** Beacon node should sync to the latest slot
**Actual behavior:** [Beacon node fails at a random time soon after starting 
**Frequency:** Evey time I start the sync process

### Versions (Add all that apply)
Kubuntu 22.04 
jdk18
teku-22.9.0
besu-22.7.2
## the command and log:
otna@ethValidator:~/teku/teku-22.9.0$ JAVA_OPTS=-Xmx20G ./bin/teku --rest-api-enabled=true --rest-api-docs-enabled=true --metrics-enabled=true --metrics-categories=BEACON,PROCESS,LIBP2P,JVM,NETWORK --ee-endpoint=http://localhost:8551 --ee-jwt-secret-file=/home/otna/token.txt
2022-09-15 17:14:19,529 main INFO Configuring logging for destination: console and file
2022-09-15 17:14:19,535 main INFO Logging file location: /home/otna/.local/share/teku/logs/teku.log
2022-09-15 17:14:19,535 main INFO Logging includes events: true
2022-09-15 17:14:19,535 main INFO Logging includes validator duties: true
2022-09-15 17:14:19,536 main INFO Logging includes color: true
2022-09-15 17:14:19,599 main INFO Include P2P warnings set to: false
17:14:19.910 INFO  - Teku version: teku/v22.9.0/linux-x86_64/oracle-java-18
17:14:19.912 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
17:14:20.073 INFO  - Storing beacon chain data in: /home/otna/.local/share/teku/beacon
17:14:20.074 INFO  - Loading 0 validator keys...
17:14:20.076 INFO  - Loaded 0 Validators: 
17:14:20.095 INFO  - Using optimized BLST library
17:14:20.276 INFO  - Initializing storage
17:14:20.803 INFO  - Storage initialization complete
17:14:20.806 WARN  - No default proposer fee recipient has been specified and rest API is enabled. If a Validator Client is going to use this node it is strongly recommended to configure it to avoid possible block production failures
17:14:21.509 INFO  - Loading generated p2p private key from: generated-node-key
17:14:21.690 INFO  - PreGenesis Local ENR: enr:-Iu4QCDWFACW993dYWQeZEhhUmMNPT6KK_J8D8o0VulqYS0bBllvjzq06gZV3A0yk2MzT3g51FeSrGa7D_21FHoMxHM5hGV0aDKQ9aX9QgAAAAD__________4JpZIJ2NIlzZWNwMjU2azGhAsYIJXwNlu4HItcK4CyvxKwNVXfDOn8u3MB1bxFj7yim
17:14:24.458 INFO  - Listening for connections on: /ip4/127.0.1.1/tcp/9000/p2p/16Uiu2HAm8khufnK6dQLfuN1uye4rf4ShTd8NcvdnP2uCZJm5amnV
17:14:24.489 INFO  - Syncing     *** Target slot: 4702570, Head slot: 180398, Remaining slots: 4522172, Connected peers: 0
17:14:24.525 INFO  - Local ENR: enr:-Iu4QBEHlXyat8-p5J6txFiSI3Su3cGbSXiCtiVcNwwAJfYeTzY0p_6j7HNKHz-T81JQXBxmlxugVMs_gJEdowqlMw06hGV0aDKQSibFiwIAAAD__________4JpZIJ2NIlzZWNwMjU2azGhAsYIJXwNlu4HItcK4CyvxKwNVXfDOn8u3MB1bxFj7yim
17:14:24.835 INFO  - Loading deposits up to Eth1 block 0
17:14:35.476 INFO  - Syncing     *** Target slot: 4702571, Head slot: 180398, Remaining slots: 4522173, Connected peers: 0
17:14:47.476 INFO  - Syncing     *** Target slot: 4702572, Head slot: 180398, Remaining slots: 4522174, Connected peers: 0
17:14:59.476 INFO  - Syncing     *** Target slot: 4702573, Head slot: 180398, Remaining slots: 4522175, Connected peers: 0
17:15:06.560 INFO  - Syncing started
17:15:11.529 INFO  - Syncing     *** Target slot: 4702574, Head slot: 180509, Remaining slots: 4522065, Connected peers: 2
17:15:23.509 INFO  - Syncing     *** Target slot: 4702575, Head slot: 180905, Remaining slots: 4521670, Connected peers: 1
17:15:24.486 INFO  - Execution Client is online
17:15:35.525 INFO  - Syncing     *** Target slot: 4702576, Head slot: 181070, Remaining slots: 4521506, Connected peers: 4
17:15:47.477 INFO  - Syncing     *** Target slot: 4702577, Head slot: 181070, Remaining slots: 4521507, Connected peers: 7
17:15:59.477 INFO  - Syncing     *** Target slot: 4702578, Head slot: 181070, Remaining slots: 4521508, Connected peers: 4
17:16:11.474 INFO  - Syncing     *** Target slot: 4702579, Head slot: 181070, Remaining slots: 4521509, Connected peers: 4
17:16:23.506 INFO  - Syncing     *** Target slot: 4702580, Head slot: 181336, Remaining slots: 4521244, Connected peers: 4
17:16:35.513 INFO  - Syncing     *** Target slot: 4702581, Head slot: 181759, Remaining slots: 4520822, Connected peers: 4
17:16:47.518 INFO  - Syncing     *** Target slot: 4702582, Head slot: 181870, Remaining slots: 4520712, Connected peers: 4
17:16:59.476 INFO  - Syncing     *** Target slot: 4702583, Head slot: 181870, Remaining slots: 4520713, Connected peers: 4
17:17:11.476 INFO  - Syncing     *** Target slot: 4702584, Head slot: 181870, Remaining slots: 4520714, Connected peers: 5
17:17:23.509 INFO  - Syncing     *** Target slot: 4702585, Head slot: 181983, Remaining slots: 4520602, Connected peers: 5
17:17:35.524 INFO  - Syncing     *** Target slot: 4702586, Head slot: 182431, Remaining slots: 4520155, Connected peers: 5
17:17:47.560 INFO  - Syncing     *** Target slot: 4702587, Head slot: 182871, Remaining slots: 4519716, Connected peers: 8
17:17:59.547 INFO  - Syncing     *** Target slot: 4702588, Head slot: 183170, Remaining slots: 4519418, Connected peers: 8
17:18:11.476 INFO  - Syncing     *** Target slot: 4702589, Head slot: 183170, Remaining slots: 4519419, Connected peers: 8
17:18:23.508 INFO  - Syncing     *** Target slot: 4702590, Head slot: 183438, Remaining slots: 4519152, Connected peers: 5
17:18:24.475 ERROR - Execution Client is offline java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8551 (See log file for full stack trace)
17:18:35.507 INFO  - Syncing     *** Target slot: 4702591, Head slot: 183879, Remaining slots: 4518712, Connected peers: 8
17:18:40.725 WARN  - Eth1 service down or still syncing for 30s, retrying
17:18:47.514 INFO  - Syncing     *** Target slot: 4702592, Head slot: 184337, Remaining slots: 4518255, Connected peers: 8
#
#A fatal error has been detected by the Java Runtime Environment:
#
#SIGSEGV (0xb) at pc=0x00007fc3ac8aa8da, pid=35315, tid=35359
#
#JRE version: Java(TM) SE Runtime Environment (18.0.2.1+1) (build 18.0.2.1+1-1)
#Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.2.1+1-1, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
#Problematic frame:
#V  [libjvm.so+0x71c8da]  G1ParScanThreadState::trim_queue_to_threshold(unsigned int)+0x141a
#
#Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/otna/teku/teku-22.9.0/core.35315)
#
#An error report file with more information is saved as:
#/home/otna/teku/teku-22.9.0/hs_err_pid35315.log
#
#If you would like to submit a bug report, please visit:
#https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)

**Comment by AntoBrajkovic** [comment]
docker fails as well 
## the command and log
otna@ethValidator:~/teku/teku-22.9.0$ sudo docker run --network="host" -p 9000:9000/tcp -p 9000:9000/udp -p 30304:30303/tcp -p 30304:30303/udp -p 5051:5051 --user 1000:1000 --mount type=bind,source=/home/otna/.local/share/teku,target=/var/lib/teku consensys/teku:latest --data-base-path=/var/lib/teku --ee-endpoint=http://localhost:8551 --ee-jwt-secret-file=/var/lib/teku/token.txt
WARNING: Published ports are discarded when using host network mode
2022-09-15 19:36:37,941 main INFO Configuring logging for destination: console and file
2022-09-15 19:36:37,951 main INFO Logging file location: /var/lib/teku/logs/teku.log
2022-09-15 19:36:37,951 main INFO Logging includes events: true
2022-09-15 19:36:37,951 main INFO Logging includes validator duties: true
2022-09-15 19:36:37,951 main INFO Logging includes color: true
2022-09-15 19:36:38,010 main INFO Include P2P warnings set to: false
19:36:38.344 INFO  - Teku version: teku/v22.9.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
19:36:38.346 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
19:36:38.562 INFO  - Storing beacon chain data in: /var/lib/teku/beacon
19:36:38.564 INFO  - Loading 0 validator keys...
19:36:38.566 INFO  - Loaded 0 Validators: 
19:36:38.588 INFO  - Using optimized BLST library
19:36:38.698 INFO  - Initializing storage
19:36:39.237 INFO  - Storage initialization complete
19:36:40.019 INFO  - Loading generated p2p private key from: generated-node-key
19:36:40.218 INFO  - PreGenesis Local ENR: enr:-Iu4QFpJ-HJTNmxOeVwTC3nTE-c5fMZqmE0XSufKfFl4prQjSvKPKMrWDAzO3icPO31wLzenGM7kZa3ceZpZpgFNBBhFhGV0aDKQ9aX9QgAAAAD__________4JpZIJ2NIlzZWNwMjU2azGhAsYIJXwNlu4HItcK4CyvxKwNVXfDOn8u3MB1bxFj7yim
19:36:40.373 INFO  - Listening for connections on: /ip4/127.0.1.1/tcp/9000/p2p/16Uiu2HAm8khufnK6dQLfuN1uye4rf4ShTd8NcvdnP2uCZJm5amnV
19:36:40.410 INFO  - Syncing     *** Target slot: 4703881, Head slot: 215388, Remaining slots: 4488493, Connected peers: 0
19:36:40.453 INFO  - Local ENR: enr:-Iu4QBk5HQjM0bqVhjieTZ4SwUwO2MWJt8a6r91j_05CgFdQUJWIkRdSKcOzLTWXZAlAySKjaQxinrEgzKkxRbqMGhBGhGV0aDKQSibFiwIAAAD__________4JpZIJ2NIlzZWNwMjU2azGhAsYIJXwNlu4HItcK4CyvxKwNVXfDOn8u3MB1bxFj7yim
19:36:40.500 INFO  - Loading deposits up to Eth1 block 0
19:36:47.396 INFO  - Syncing     *** Target slot: 4703882, Head slot: 215388, Remaining slots: 4488494, Connected peers: 0
19:36:59.392 INFO  - Syncing     *** Target slot: 4703883, Head slot: 215388, Remaining slots: 4488495, Connected peers: 0
19:37:11.392 INFO  - Syncing     *** Target slot: 4703884, Head slot: 215388, Remaining slots: 4488496, Connected peers: 0
19:37:23.392 INFO  - Syncing     *** Target slot: 4703885, Head slot: 215388, Remaining slots: 4488497, Connected peers: 0
19:37:35.393 INFO  - Syncing     *** Target slot: 4703886, Head slot: 215388, Remaining slots: 4488498, Connected peers: 0
19:37:40.440 INFO  - Execution Client is online
19:37:47.391 INFO  - Syncing     *** Target slot: 4703887, Head slot: 215388, Remaining slots: 4488499, Connected peers: 0
19:37:51.271 INFO  - Syncing started
19:37:59.424 INFO  - Syncing     *** Target slot: 4703888, Head slot: 215604, Remaining slots: 4488284, Connected peers: 3
19:38:11.429 INFO  - Syncing     *** Target slot: 4703889, Head slot: 215996, Remaining slots: 4487893, Connected peers: 3
19:38:23.424 INFO  - Syncing     *** Target slot: 4703890, Head slot: 216379, Remaining slots: 4487511, Connected peers: 1
19:38:35.450 INFO  - Syncing     *** Target slot: 4703891, Head slot: 216628, Remaining slots: 4487263, Connected peers: 2
19:38:47.391 INFO  - Syncing     *** Target slot: 4703892, Head slot: 216628, Remaining slots: 4487264, Connected peers: 2
19:38:59.393 INFO  - Syncing     *** Target slot: 4703893, Head slot: 216628, Remaining slots: 4487265, Connected peers: 1
19:39:11.423 INFO  - Syncing     *** Target slot: 4703894, Head slot: 216728, Remaining slots: 4487166, Connected peers: 1
19:39:23.445 INFO  - Syncing     *** Target slot: 4703895, Head slot: 216907, Remaining slots: 4486988, Connected peers: 1
19:39:35.460 INFO  - Syncing     *** Target slot: 4703896, Head slot: 216978, Remaining slots: 4486918, Connected peers: 1
19:39:47.391 INFO  - Syncing     *** Target slot: 4703897, Head slot: 216978, Remaining slots: 4486919, Connected peers: 0
19:39:59.426 INFO  - Syncing     *** Target slot: 4703898, Head slot: 217215, Remaining slots: 4486683, Connected peers: 4
19:40:11.459 INFO  - Syncing     *** Target slot: 4703899, Head slot: 217622, Remaining slots: 4486277, Connected peers: 4
19:40:23.455 INFO  - Syncing     *** Target slot: 4703900, Head slot: 217778, Remaining slots: 4486122, Connected peers: 3
19:40:35.391 INFO  - Syncing     *** Target slot: 4703901, Head slot: 217778, Remaining slots: 4486123, Connected peers: 8
19:40:47.391 INFO  - Syncing     *** Target slot: 4703902, Head slot: 217778, Remaining slots: 4486124, Connected peers: 8
19:40:59.427 INFO  - Syncing     *** Target slot: 4703903, Head slot: 217963, Remaining slots: 4485940, Connected peers: 5
19:40:59.891 INFO  - Epoch Event *** Epoch: 146997, Justified checkpoint: 6811, Finalized checkpoint: 6810, Finalized root: f922bf74d45d520dd45be0d15271ab948d9699a47d8e99758c3c954e66720637
19:41:11.426 INFO  - Syncing     *** Target slot: 4703904, Head slot: 218362, Remaining slots: 4485542, Connected peers: 6
19:41:23.437 INFO  - Syncing     *** Target slot: 4703905, Head slot: 218763, Remaining slots: 4485142, Connected peers: 6
19:41:35.426 INFO  - Syncing     *** Target slot: 4703906, Head slot: 219167, Remaining slots: 4484739, Connected peers: 5
19:41:47.446 INFO  - Syncing     *** Target slot: 4703907, Head slot: 219428, Remaining slots: 4484479, Connected peers: 5
19:41:59.392 INFO  - Syncing     *** Target slot: 4703908, Head slot: 219428, Remaining slots: 4484480, Connected peers: 5
19:42:11.391 INFO  - Syncing     *** Target slot: 4703909, Head slot: 219428, Remaining slots: 4484481, Connected peers: 6
19:42:23.438 INFO  - Syncing     *** Target slot: 4703910, Head slot: 219695, Remaining slots: 4484215, Connected peers: 6
19:42:35.443 INFO  - Syncing     *** Target slot: 4703911, Head slot: 220089, Remaining slots: 4483822, Connected peers: 6
19:42:47.428 INFO  - Syncing     *** Target slot: 4703912, Head slot: 220488, Remaining slots: 4483424, Connected peers: 5
19:42:59.465 INFO  - Syncing     *** Target slot: 4703913, Head slot: 220528, Remaining slots: 4483385, Connected peers: 5
19:43:11.391 INFO  - Syncing     *** Target slot: 4703914, Head slot: 220528, Remaining slots: 4483386, Connected peers: 10
19:43:23.426 INFO  - Syncing     *** Target slot: 4703915, Head slot: 220576, Remaining slots: 4483339, Connected peers: 10
19:43:35.426 INFO  - Syncing     *** Target slot: 4703916, Head slot: 220982, Remaining slots: 4482934, Connected peers: 7
19:43:47.424 INFO  - Syncing     *** Target slot: 4703917, Head slot: 221376, Remaining slots: 4482541, Connected peers: 6
19:43:59.452 INFO  - Syncing     *** Target slot: 4703918, Head slot: 221786, Remaining slots: 4482132, Connected peers: 5
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f84a8771a24, pid=1, tid=22
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.4.1+1 (17.0.4.1+1) (build 17.0.4.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (17.0.4.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xb5ea24]  markWord::displaced_mark_helper() const+0x14
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /opt/teku/core.1)
#
# An error report file with more information is saved as:
# /opt/teku/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#

[error occurred during error reporting (), id 0xb, SIGSEGV (0xb) at pc=0x00007f84a8f73941]

**Comment by AntoBrajkovic** [comment]
docker with the jdk16 runtime same issue

**Comment by ajsutton** [comment]
This looks a lot like there's faulty memory or some other hardware issue. It's quite unusual to be getting a SIGSEGV in libjvm.so since that would be a bug in the JVM and we'd likely see very widespread reports of that given how much the JVM is used, whereas this is the only report we've had of Teku crashing. It's fairly common that the machine runs correctly most of the time but crashes when starting a java process because quite often the heap size is large and so the machine then starts using the full memory space - often activating a new memory stick for the first time.

I'd suggest doing a long running memory test on the box to identify any potential issues. Even if it starts running these memory issues tend to lead to database corruption at various points as well.

**Comment by tbenr** [comment]
We close it for the moment. Feel free to reopen it if you have more info to share.

**Comment by AntoBrajkovic** [comment]
Got bogged down by work. @ajsutton was right, my RAM was faulty
