### ISSUE TITLE
event stream disconnects periodically

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6210]
When listening for chain_reorg, sometimes the event stream seems to disconnect periodically.

It doesn't appear to be the keep alive, but haven't got the raw stream data to look at currently.

**Comment by tbenr** [comment]
it should be related to the error:
`Sep 20, 2022 @ 09:40:18.601	Connection unexpectedly closed`

**Comment by courtneyeh** [comment]
Tried to replicate the issue without success. Will close the issue for now, and reopen if and when more information is made available.
