### ISSUE TITLE
async runner names need to be validated

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6211]
when we create an async runner (`serviceConfig.createAsyncRunner` for example), metrics are created on the name given, and if the name contains certain characters like '-' it breaks metrics.

We need a test so that when we create this kind of thing, we can validate the metric name and not get into a situation where we break metrics.

**Comment by mehdi-aouadi** [comment]
Isn't this the same as [check metric names are valid#11](https://app.zenhub.com/workspaces/team-centaur-5ec772b542883ab933e51688/issues/consensys/teku-internal/11)?

**Comment by rolfyone** [comment]
https://github.com/ConsenSys/teku/pull/6209
fixing a metric name found when trying to push a dev build... concrete example we talked about

**Comment by rolfyone** [comment]
Possibly, I thought the other was resolved, would have to check…
