### ISSUE TITLE
Make `VALIDATOR_REGISTRATION_EXPIRATION_EPOCHS` configurable

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6238]
With regard to #6237 it might be useful for some deployment to configure the latency in which builder usage for a given public key is actually deactivated on BN.
In case users are using proposer config file refresh option (and in future with an additional VC rest API), they could dynamically set `builder.enabled` to `false`.

`VALIDATOR_REGISTRATION_EXPIRATION_EPOCHS` is currently governing how quickly BN reacts to that by expiring he validator registration.

Making it configurable with a BN parameter users can have adjust it if they want to.

**Comment by ajsutton** [comment]
We haven't had any requests for this that I'm aware of so probably best to stick with the simple hard coded option.
