### ISSUE TITLE
enable\disable builder via validator rest APIs

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6239]
We can currently set `feeRecipient` and `gasLimit` via validator rest APIs. I think it makes sense to be able to toggle builder flag too. This will complete all operations that can be currently done by having proposer config file refresh enabled.

**Comment by ThomasDalla** [comment]
Side question on that topic: when we set the `feeRecipient` and `gasLimit` via the validator REST APIs, does it update the `proposerConfig.json` file as well? Or is it just "in-memory" and lost on restart?

**Comment by tbenr** [comment]
`proposerConfig.json` is not changed but the new values are persisted in a local json file. So they are reloaded upon restart.

**Comment by tbenr** [comment]
We can close it for now. We haven't received any specific request for this feature. If we will, we will reopen it.
