### ISSUE TITLE
Default behavior should not send packets to RFC1918 addresses

### ISSUE THREAD

**Issue by dtto** [Consensys-Incorporated/teku#6242]
### Description
Normal operation should not send traffic to rfc1918 addresses.

### Steps to Reproduce (Bug)
Run teku. Watch for traffic on rfc1918 addresses, e.g. 

```
# while ! ss -p state syn-sent | grep 192.168; do sleep .1; done
tcp   0      1      [::ffff:XXXX]:51566 [::ffff:192.168.0.158]:13000 users:(("java",pid=16341,fd=429))
```

**Expected behavior:** [What you expect to happen]
No traffic is sent to rfc1918.
I suggest to add a flag to enable sending traffic to rfc1918 as needed.

**Actual behavior:** [What actually happens]
On occasion, traffic (likely p2p discovery?) is sent to RFC1918 addresses. 

**Frequency:** [How regularly does it occur?]
Varies.

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
```
$ ./teku --version
teku/v22.9.1+3-g3d7dd4f/linux-x86_64/-debian-openjdk64bitservervm-java-17
```
* Java version: [`java -version`]
```
$ java --version
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)
```
* OS Name & Version: [`cat /etc/*release`]

Debian 11

* Docker Version: [`docker version`]

N/A

* Cloud VM, type, size: [Amazon Web Services I3-large]
N/A

**Comment by taggart** [comment]
I am seeing this too. It would be good if these were off by default.

**Comment by ajsutton** [comment]
For the record, these ranges to avoid map to `InetAddress.isSiteLocalAddress` in Java. https://www.rfc-editor.org/rfc/rfc1918 

```
   The Internet Assigned Numbers Authority (IANA) has reserved the
   following three blocks of the IP address space for private internets:

     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
```

**Comment by ajsutton** [comment]
Finishing this off will require:
* getting #6631 merged
* deploying and monitoring a box with this enabled to check there aren't other places that need filtering
* Enabling it by default (will likely have to allow site local addresses in ATs and things like the docker test network)

**Comment by zilm13** [comment]
Docs are added https://github.com/ConsenSys/doc.teku/pull/442
next: Teku upcoming release comes with --p2p-discovery-site-local-addresses-enabled defaults to `true`
next: Teku subsequent release comes with --p2p-discovery-site-local-addresses-enabled defaults to `false`and we close this issue as resolved
