### ISSUE TITLE
Augment the ChainStoreServer

### ISSUE THREAD

**Issue by jalextowle** [Consensys-Incorporated/teku#629]
### Description
As a future user of the Artemis client, I want the `ChainStorageServer` class to be implemented in several ways that will allow state to be stored in different protocols. 

### Acceptance Criteria
* An interface that will be sufficient to store data to arbitrary protocols
* An `ChainStoreServer` that sends data to the disk to be stored
* An `ChainStoreServer` that sends data to be stored in IPFS.
* [Optional] A subclass is created that sends data to a git repository to be stored.

**Comment by jrhea** [comment]
@jalextowle to start with.  Just subscribe to this event:

```java
  @Subscribe
  public void onDataEvent(RawRecord record) {
      // TODO: storage logic
  }
```
