### ISSUE TITLE
Improve `validatorRegistration` signing process by excluding unknown validators

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6290]
We currently sign `validatorRegistration` objects for all loaded keys, without excluding validators that are currently unknown (yet without an associated index)

**Comment by ajsutton** [comment]
@tbenr Have we already added this filtering or have we only filtered what we send and are still signing for all validators?

**Comment by tbenr** [comment]
We added the filtering on the Beacon Node side. Yes, we are currently signing all vaildator registrations.
