### ISSUE TITLE
Filter validators with all post-exit statuses when registering against builder endpoint

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6312]
we already filtering out `exited_slashed` and `exited_unslashed` but we have to filter `withdrawal_*` too

**Comment by ajsutton** [comment]
Would it be easier to only allow `active_*` explicitly (ie opt in statuses instead of opt out)?

**Comment by tbenr** [comment]
I thought about that but we probably would like to register validators in advance prior to activation... Well this concept is actually in the spec now.
