### ISSUE TITLE
Extend existing containers for Capella

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#6317]
https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/beacon-chain.md#extended-containers

- [x] ExecutionPayload @StefanBratanov 
- [x] ExecutionPayloadHeader @StefanBratanov 
- [x] BeconBlockBody @lucassaldanha (Will be done as part of https://github.com/ConsenSys/teku/issues/6370)
- [x] BeaconState @rolfyone

**Comment by lucassaldanha** [comment]
I'll start working on `BeaconBlockBody` changes

**Comment by StefanBratanov** [comment]
`ExecutionPayload` and `ExecutionPayloadHeader` done as part of  https://github.com/ConsenSys/teku/pull/6369
