### ISSUE TITLE
Would it be possible to have a metric showing time to next duty

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6326]
https://discord.com/channels/694822223575384095/782670046736285697/1030814583771889724

To be able to plan times to restart, it might be useful to have a metric that displays a countdown in seconds to the next duty ... or something similar...

The idea is that you'd then be able to potentially restart teku while you have a gap, but we also had a discussion about how timings may be fairly tight on a VC...

Created this ticket as a placeholder for discussion of this option.

**Comment by tbenr** [comment]
Yes I think it is a good thing. Exposing a different metrics for duty type would be also good. There are also usecases in which you may want to build scripts that change machine configuration in preparation of duty (ie setting more aggressive scaling governor or blocking new incoming connections in preparation of block production)

**Comment by zilm13** [comment]
It reminds me this NO MERGE PR which I made a year ago https://github.com/ConsenSys/teku/pull/5343
Do we really need it? In what form exactly?

**Comment by rolfyone** [comment]
just a gauge? If we have duties in slot 3,4,5, then its just the slot time of slot 3 that would be the metric....

Also, if one duty is due at the end of the epoch (only scheduled duty), and we're in slot 1 of the epoch, then you'll be setting the next duty time as that slot 31 time...

I'm pretty sure we won't have periods with no duties, maybe at startup... Maybe just letting it be set once a duty comes in would be fine in that scenario...

What i don't want is a bunch of numbers, that would defeat the purpose... i think just 1 value, and if we can somehow have it be able to be on a dashboard as a time? that might inform the direction of if this would even work...

**Comment by rolfyone** [comment]
or maybe the slot number of the duty would be sufficient?

**Comment by zilm13** [comment]
> just a gauge? If we have duties in slot 3,4,5, then its just the slot time of slot 3 that would be the metric....

so we update the metric only once in epoch?
btw could we just proxy it when validator requests its duties?

**Comment by tbenr** [comment]
https://github.com/TobiWo/eth-duties

**Comment by lucassaldanha** [comment]
After talking to some people about this, the idea of using a metric does not seem to be very helpful (even less helpful when running multiple validators).

A recommended approach would be to poll the Duties API and use the information about proposers to decide a good time to upgrade. Missing attestations during an upgrade should be fine. Even sync committee duties are not a bit deal. The only duty that a validator definitely does not want to miss is a block proposal.

Solutions like https://github.com/TobiWo/eth-duties could be helpful for those that don't want to implement their own script.
