### ISSUE TITLE
Support block value in `engineGetPayload`

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6327]
https://github.com/ethereum/execution-apis/issues/307

We could start comparing locally produced payloads with bids coming from builder endpoint and prefer local one if it has higher or similar value of the received bid. We could add percentage diff as well, so if let's say bid isn't at least 50% more valuable than local we fallback to local.

**Comment by benjaminion** [comment]
I think this is a duplicate of #6140. Also see #6344.

General view seems to be that this is better done in MEV-Boost than in the consensus client. But happy to consider other views.

**Comment by tbenr** [comment]
Well, not exactly. This will enable the a value comparison between local el block and builder bid. Previous issues where about applying an absolute cutoff\threshold on bids (which indeed has been recently implemented in mev-boost). The motivation behind that is to enable\encourage to choose locally produced payloads when there is "not enough rewards difference" to choose the bid. Moreover, non censored local blocks censored tx can start competing with censoring builder bids.
In the current sidecar model, mev-boost can't "see" local produced block and so the only place where it can happen is in CL.

**Comment by benjaminion** [comment]
Ah, ok. Got it.

**Comment by tbenr** [comment]
We can start working on this since we have #6614
