### ISSUE TITLE
Sync committee messages not created when failing over to secondary beacon node

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6345]
### Description
When a vc is configured with multiple beacon node endpoints and the primary beacon node is online but syncing, the vc fails to produce sync committee messages when it should have been able to via the fallback:

```
{"@timestamp":"2022-10-26T20:15:16,005","level":"WARN","thread":"ValidatorTimingChannel-1","class":"teku-validator-log","message":"Validator   *** Skipped producing sync_signature while node is syncing  Count: 1, Slot: 4192276","throwable":""}
```

It is producing attestations and aggregates correctly.

**Comment by StefanBratanov** [comment]
The issue is happening because `ChainHeadTracker` tracks the current head via the event stream and the event stream failover functionality has a bug when the primary BN is syncing.
