### ISSUE TITLE
Improve the CI

### ISSUE THREAD

**Issue by jalextowle** [Consensys-Incorporated/teku#635]
### Description
As a future user of the Artemis client, I would like the CI to be enhanced so that changes that result in errors in the test suite are not considered passing builds. This enhancement would increase the safety of pulling the current HEAD of the Artemis client, and it will also make development easier for the Artemis team. 

### Acceptance Criteria
* Fails builds that have stack traces logged during testing

### Additional Information
It's possible that the general form for stack traces will match strings that should be logged during testing and builds. If this is the case, a less general enhancement should be pursued that will still catch several types of Exception and Error logs. With things like this, a solution that works 90% of the time can be really nice 👍

**Comment by jrhea** [comment]
@jalextowle In case you didn't notice.  The CI script is called from the Jenkinsfile and this is the line that calls it:

```
                stage('Test') {
                    sh './gradlew --no-daemon --parallel test'
                    sh './artemis/src/main/resources/artemisTestScript.sh'
                }
```

since we have a scripts folder, you can move it there.  Also, feel free to modify it however you feel is necessary

**Comment by jrhea** [comment]
outdated
