### ISSUE TITLE
Move commandline arguments to toml config file

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#636]
Currently JSON output formatting is defined using the following parameters:

```
  -o, --output=<FILENAME>   Path/filename of the output file. Path can be followed
                            by events the user wishes to output example:
                            -o=artemis.json Eth2Genesis TimeSeriesRecord
  -p, --provider=<PROVIDER TYPE>
                            Output provider types: CSV, JSON (default: JSON).
  -s, --sim                 PoW simulation flag, w/ optional input file
```

Those parameters are the passed to `BeaconNode.class` which instantiates a `FileProvider.class` and an `EventHandler.class` to subscribe and output events specified in the `-o` or `--output`. ie: `-o=artemis.json Eth2Genesis TimeSeriesRecord`.

Those parameters should be removed as configurable commandline arguments and added as arguments to the `toml` file. Doing so should maintain the same current application behavior.

**Comment by jrhea** [comment]
@mankenavenkatesh for some reason it isn't finding your github id when i try to assign this issue to you; however, i did tag it as in progress
