### ISSUE TITLE
Validator registration failure after updating to latest besu+teku releases.

### ISSUE THREAD

**Issue by nhlroyrocks** [Consensys-Incorporated/teku#6366]
Nov 03 03:03:11 ogserver teku[3322209]: 03:03:11.008 ERROR - Validator   *** Failed to send validator registrations to the builder network via the Beacon Node java.util.concurrent.CompletionException: tech.pegasys.teku.api.exceptions.RemoteServiceNotAvailableException: Server error from Beacon Node API (url = http://127.0.0.1:5051/eth/v1/validator/register_validator, status = 500, message = java.lang.RuntimeException: Unable to register validators: builder not available) (See log file for full stack trace)

I went digging through the journalctl log for Teku and actually found a few occurrences of this error as far back as the 27th but nothing changed on my end until today. I versioned up Teku and Besu and removed 1 of my 2 MEV relays today.

**Comment by StefanBratanov** [comment]
Closing this after a discussion on Discord: https://discord.com/channels/697535391594446898/697539289042649190/1037882402120421406 . The issue ended up being a bloxroute relay timeout issue. I suggested to the user to follow up with them.
