### ISSUE TITLE
Slow sync with high load

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#6381]
### Description
High load and slow import on sync (15 slots per minute on fast desktop). Teku restart solved the issue
Heap dump shows unusual number of `SSZUInt64` objects (1.7GB total)
Thread dump attached: [teku_thread_dump_huge_load.txt](https://github.com/ConsenSys/teku/files/9943720/teku_thread_dump_huge_load.txt)
![image](https://user-images.githubusercontent.com/6196452/200119012-775c2c55-1f4f-484e-8bdd-051c0bfe8c07.png)

**Frequency:** [How regularly does it occur?]
Once. It's possible that this is a hardware related issue (memory or whatever).

### Versions (Add all that apply)
22.10.2+gb4edaf50

**Comment by benjaminion** [comment]
Not seen again. Closing for now.
