### ISSUE TITLE
Add\update containers

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6383]
### New SSZ containers

[p2p containers](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/p2p-interface.md#containers)

- [ ] `BlobsSidecar`
- [ ] `SignedBeaconBlockAndBlobsSidecar`

### Updated SSZ containers
[beacon containers](https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/beacon-chain.md#containers)
- [ ] `BeaconBlockBody`
  - [ ] `BeaconBlockBodyBuilder`
- [ ] `ExecutionPayload`
- [ ] `ExecutionPayloadHeader`

**Comment by zilm13** [comment]
Looks like validator containers are no more actual with this PR merged 
https://github.com/ethereum/consensus-specs/pull/3038
one of the goals was to close this issue https://github.com/ethereum/consensus-specs/issues/3026

we may need structure for this tuple, but it doesn't have a name at the moment https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md?plain=1#L48

**Comment by tbenr** [comment]
> we may need structure for this tuple, but it doesn't have a name at the moment https://github.com/ethereum/consensus-specs/blob/dev/specs/eip4844/validator.md?plain=1#L48

That's implementation specific. I currently think we will pass around the "internal" version of [blobsbundlev1](https://github.com/ethereum/execution-apis/blob/main/src/engine/blob-extension.md#blobsbundlev1) which I don't think it will be an ssz container.

> Looks like validator containers ...

yeah, I haven't updated the issue after that pr was merged
