### ISSUE TITLE
Create java binding for c-kzg library

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6389]
We need to have a java binding for the official c-kzg library.
Currently the library is here https://github.com/dankrad/c-kzg/tree/4844 but will be probably migrated to a dedicated repo.

There are two options:
1. Make a PR to add a java binding in the repo itself (it already contains a binding dir with other bindings)
2. create a dedicated binding repo (similar to `jc-kzg`)

the interface is quite simple: https://github.com/dankrad/c-kzg/blob/4844/src/c_kzg_4844.h so we could skip using swig if makes things easier\faster to implement

**Comment by StefanBratanov** [comment]
Created a repo of the binding with a publishable artifact - https://github.com/ConsenSys/jc-kzg-4844
