### ISSUE TITLE
beacon-apis - add rewards endpoints

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6442]
https://github.com/ethereum/beacon-APIs/pull/260
https://github.com/ethereum/beacon-APIs/pull/262

**Comment by lucassaldanha** [comment]
sync_committee_rewards ticket https://github.com/ConsenSys/teku/issues/6701

**Comment by lucassaldanha** [comment]
block rewards ticket https://github.com/ConsenSys/teku/issues/6702

**Comment by lucassaldanha** [comment]
Attestation rewards ticket https://github.com/ConsenSys/teku/issues/6703

**Comment by lucassaldanha** [comment]
Closing this ticket in favour of individual tickets (see comments)
