### ISSUE TITLE
upgrade POW besu to POS teku

### ISSUE THREAD

**Issue by puneet166** [Consensys-Incorporated/teku#6469]
HI Team,

Please help
i have my already running private network with chain id 2344 using besu execution client.
I want to upgrade my POW network into POS (beacan) using teku.

My questions - 
1. can i upgrade my private network in POS using teku?
  if yes , what to do for it?

**Comment by puneet166** [comment]
@ajsutton @robzajac @mbaxter

**Comment by ajsutton** [comment]
It is possible to do but relatively complex. You'd need to start a new beacon chain with Teku (separate to your PoW network) running the Bellatrix milestone with a custom network configuration and then schedule the merge by setting a total difficultly on both the beacon chain and your existing PoW chain.

However this is not recommended. All the security in PoS comes from the ETH in the network having a significant amount of value which is almost never the case for private networks.  It's almost always better to use one of the Proof of Authority (PoA) systems like QBFT which besu supports.
