### ISSUE TITLE
Potential issue with voluntary exit command not gracefully exiting

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6498]
Had a talk with someone while testing capella devnet, and they submitted an exit and it hung, we should see if we can submit some exits and that we haven't broken it...

I had a vague memory of this being in acceptance tests, so it would be interesting to see if that's not using the CLI version...

docs reference for convenience: https://docs.teku.consensys.net/en/latest/HowTo/Voluntary-Exit/

> 
> When manually triggering a teku exit, it's hanging
> 
> ```
> Loading configuration...
> Exits are going to be generated for validators:
> ad2e4b8
> Epoch: 18
> 
> These validators won't be able to be re-activated, and withdrawals aren't likely to be possible until Phase 2 of eth2 Mainnet.
> Are you sure you wish to continue (yes/no)?
> yes
> Exit for validator ad2e4b8 submitted.
> 
> 
> ^C
> ```
> and I have to escape
>

**Comment by tbenr** [comment]
First test in ropsten mev.
I exited only one key using this command line:

```shell
sudo -u teku ./teku voluntary-exit --beacon-node-api-endpoint=http://127.0.0.1:5051 --validator-keys "/etc/teku/keys:/etc/teku/secrets" --validator-public-keys "0x9975b3bf26f6727dbc201cc202a1e04c7d478bebaef0435f11e8f8cb6ccdc68c39fd67b036e13cb5ccfa39525cb43cfa"
```

it hanged for a couple of minutes after printing:
```
Loading configuration...
Exits are going to be generated for validators:
9975b3b
Epoch: 42482

These validators won't be able to be re-activated, and withdrawals aren't likely to be possible until Phase 2 of eth2 Mainnet.
Are you sure you wish to continue (yes/no)?
yes
Exit for validator 9975b3b submitted.
```
and then exited correctly (RC seems to be 0)

<img width="919" alt="image" src="https://user-images.githubusercontent.com/15999009/205616810-4d8820ec-5081-49db-a57c-64a90d94a09b.png">

**Comment by tbenr** [comment]
then I exited 4 keys together:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/15999009/205617601-4590ca32-882c-4506-973c-8f86d96f360d.png">

hanged for the same amount of time (2m ish) after printing the submission messages for all of them.
So it seems a constant time independent by the amount of keys exiting.

**Comment by tbenr** [comment]
I exited them all (2500).
I correctly got `Exit is not the first one for validator <idx>.` for the 6 previously exited validator.
The same amount of time waited before getting the prompt back.
Error code: 0

**Comment by tbenr** [comment]
randomly picking keys and they are effectively exiting:
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/15999009/205623134-8fbd01a9-2481-4c24-97a4-424de7396e74.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/15999009/205624261-1fd98abe-c173-4805-a105-bed4003760c0.png">

**Comment by ajsutton** [comment]
If I had to guess I'd say the 2 min delay before shutdown is something like waiting for OkHttp to terminate the background threads it creates.  If they aren't marked as daemon that would stop the jvm from exiting until they exited and I think they do stay around for a period of time before being stopped.  We can probably grab a thread dump in the period we're waiting for it to stop to confirm that.

**Comment by tbenr** [comment]
> If I had to guess ...

I had the same thought
