### ISSUE TITLE
Ingest a JSON file of voluntary exits

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#6515]
The below feature request from a large Teku user.

Assuming we might have 100s of exits, how could we easily pass these into teku.

```
teku voluntary-exit --validator-keys=<KEY_DIR>:<PASS_DIR> | <KEY_FILE>:<PASS_FILE>[,<KEY_DIR>:<PASS_DIR> | <KEY_FILE>:<PASS_FILE>...]
```

We were wondering if there is the possibility to pass a json file into the command `teku voluntary-exit`. The json file would include all the vals.

**Comment by rolfyone** [comment]
As an alternative here that's already implemented, it's possible to pass --config-file to voluntary exit...

So you could, for example, have the config file that specifies a bunch of files, and work that way to accomplish what's in this ticket.

For example
```
network: "minimal"
validator-keys: ["a.json:a.txt",
                 "b.json:b.txt"
                ]
```
any other configuration such as the beacon rest endpoint to submit the exit can be added to the file also, or configured on command line...

**Comment by benjaminion** [comment]
The configuration file approach seems like a reasonable workaround. Closing.
