### ISSUE TITLE
allow bls_to_execution_changes with capella fork prior to capella start

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6535]

**Comment by ajsutton** [comment]
Need to think through all the corner cases for validation just before and after forks, including submitting via gossip or via REST API.

 - Can't sign changes with Bellatrix fork
 - Can sign with capella fork even before head state transitions to Capella
 - How do we handle the fork after capella?

**Comment by rolfyone** [comment]
We're just going to reject pre-capella bls_to_execution changes, they'll have to wait until capella is active to add to the operation pool.
