### ISSUE TITLE
`shouldPassMergeTransitionUsingWebsocketsEngine` breaking very often

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6563]
The shouldPassMergeTransitionUsingWebsocketsEngine AT is breaking quite often currently, we need to have a look and see if there's an actual problem, or if its related to using `swift` now.

**Comment by ajsutton** [comment]
This is caused by a web3j bug: https://github.com/web3j/web3j/pull/1826
Sadly trying to work around it on the Teku side would make ATs significantly slower as we'd have to synchronously send each deposit transaction.

**Comment by ajsutton** [comment]
Finishing this off will require getting web3j/web3j#1826 merged and into a new web3j release then pulling that into Teku.

**Comment by benjaminion** [comment]
Web3j PR now merged. Waiting for release.
