### ISSUE TITLE
Support pruning old blocks

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6576]
### Description
Now that checkpoint sync is supported by all clients, we can start moving away from storing the full block history back to genesis.

Add a (initially hidden, --X) option to specify the maximum retention period for historic block data. This should be specified in number of epochs to retain.  The minimum allowed value is [`MIN_EPOCHS_FOR_BLOCK_REQUESTS`](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/p2p-interface.md#configuration). If the value is set to less than this, log a warning and use `MIN_EPOCHS_FOR_BLOCK_REQUESTS` as the retention period.

If the retention period is set to 0, retain all blocks back to genesis.  Q: Should we instead have a separate `--block-pruning-enabled` option to disable?

Also ensure that the historic block fetcher never attempts to fetch blocks prior to this retention period. It will also not be possible to rebuild historic states when block data is pruned (since it requires blocks all the way back to genesis).

**Comment by benjaminion** [comment]
Would we auto-prune existing databases that have existing data back to genesis? (2 years' worth now.) Or would this apply only to newly-checkpoint-synced nodes?

I can see arguments for both, but we should choose by default whichever is least surprising to users - probably the latter. Maybe supply a tool option to prune old DBs. (Users could manually delete an old DB and do a checkpoint sync, but this comes at the cost of re-downloading 5 months worth of blocks, which is non-trivial.)

**Comment by ajsutton** [comment]
Good question - ideally for existing databases the current behaviour of keeping all blocks back to genesis would be preserved so there are no surprises.  But I think we want to make it easy to enable this and just have it prune old data in the background rather than having to run a separate tool. So I think we'd just want to make the default enabled/disabled value dependent on the database so it defaults to disabled for any database created before this feature that hasn't enabled it at some point.

But the initial implementation would be disabled by default and I think we'd leave this as an opt-in feature for a fair while anyway.

**Comment by ajsutton** [comment]
For initial implementation I've wound up with just a block-pruning-enabled flag and no option to customise the number of epochs it keeps. We could make it configurable if needed but it added complexity and given the spec requires about 5 months of storage, I'm not really sure why you'd want somewhere between that and everything. Maybe tax reporting but seems very very niche...

**Comment by ajsutton** [comment]
Initial implementation done, there's a few remaining things to get to done:

1. Check that switching this on with a fully sync'd node works smoothly. Currently it deletes all historic blocks in a single transaction but that may explode memory usage.
2. Make the flag visible and documented

If we want to change the default to be enabled, we also need to work out how to deal with existing databases as per the discussion above. It would likely need to remain disabled by default for existing databases and should be disabled when in archive mode.

**Comment by ajsutton** [comment]
Actually one possibility would be to change this to be a third `--data-storage-mode` so we'd have `ARCHIVE`, `PRUNE` and `PRUNE_ALL` or something like that.  Shame `PRUNE` isn't `PRUNE_STATES`...

**Comment by ajsutton** [comment]
Moved over to `--data-storage-mode` with ARCHIVE, PRUNE and the new MINIMAL option that also prunes blocks.  Have spun up a new node on mainnet that's currently backfilling all blocks so that we can test performance when first switching to MINIMAL.

Also worth noting that if you switch from MINIMAL to PRUNE, Teku will automatically backfill the blocks again which is kind of cool.
