### ISSUE TITLE
Create CLI option for minimum persistent attestation subnet subscriptions

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#6580]
Currently, Teku has two modes to choose how many attestation subnets it is subscribed to:
- Validator based (validator att subnet + 1 random)
- All subnets (all 64 att subnets)

We want a 3rd mode that creates a minimum number of attestation subnets subscriptions. Keep in mind that if the minimum number is lower than the number of validators, we need to ensure we don't end up subscribing to fewer subnets than we need to.

Example:
- If a node has 10 validators, it is expected to subscribe to 20 subnets. If `min_att_subscriptions = 10`, we should have 20 subscriptions (10 needed + 10 random).
- If a node has 10 validators, it is expected to subscribe to 20 subnets. If `min_att_subscriptions = 30`, we should have 30 subscriptions (10 needed + 20 random)
- If a node has 0 validators, it is expected to subscribe to 0 subnets. If `min_att_subscriptions = 20`, we should have 20 subscriptions (20 random)

**Comment by ajsutton** [comment]
Added as a hidden option and closing as there's no plan to make this a supported thing.
