### ISSUE TITLE
Improve checkpoint sync process and logging

### ISSUE THREAD

**Issue by remyroy** [Consensys-Incorporated/teku#6594]
### Description
Teku hangs during initial state loading with a checkpoint sync.

### Steps to Reproduce (Bug)
Launch Teku on Goerli with `--initial-state=https://prater.checkpoint.sigp.io/eth/v2/debug/beacon/states/finalized` option.

### Output logs

```
2022-12-13 10:16:55,341 main INFO Configuring logging for destination: console and file
2022-12-13 10:16:55,419 main INFO Logging file location: c:\ethereum\var\lib\teku\logs\teku.log
2022-12-13 10:16:55,419 main INFO Logging includes events: true
2022-12-13 10:16:55,419 main INFO Logging includes validator duties: true
2022-12-13 10:16:55,434 main INFO Logging includes color: false
2022-12-13 10:16:55,872 main INFO Include P2P warnings set to: false
10:16:57.466 INFO  - Teku version: teku/v22.12.0/windows-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
10:16:57.466 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
10:16:58.388 INFO  - Using portable BLST library.
10:16:58.887 INFO  - Loading 1 validator keys...
10:17:00.154 INFO  - Loaded 1 Validators: a830c39
10:17:00.169 INFO  - Storing beacon chain data in: c:\ethereum\var\lib\teku\beacon
10:17:00.169 INFO  - Loading 0 validator keys...
10:17:00.169 INFO  - Loaded 0 Validators: 
10:17:01.768 INFO  - Initializing storage
10:17:01.768 INFO  - Storage initialization complete
10:17:01.768 INFO  - Loading initial state from https://prater.checkpoint.sigp.io/eth/v2/debug/beacon/states/finalized
```

**Expected behavior:** More information being logged if the download takes a long time, some form of retry if there is an HTTP request issue or some sort of timeout if the checkpoint sync endpoint does not reply in time or does not behave as expected.

**Actual behavior:** Teku just hangs in there for more than 15 minutes.

**Frequency:** Sometimes when the checkpoint sync endpoint is misbehaving. This does not happen with all the checkpoint sync endpoints from https://eth-clients.github.io/checkpoint-sync-endpoints/ . Some are behaving better than others.

### Versions
* Software version: teku/v22.12.0/windows-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
* Java version: eclipseadoptium-openjdk64bitservervm-java-17 (Adoptium 17.0.5_8)
* OS Name & Version: Windows 10 Version 10.0.19045.2251

**Comment by ajsutton** [comment]
Yeah we should check we have a reasonable timeout applied.  It's working for me now so likely was an issue with the server at the time.
