### ISSUE TITLE
Default storage mode to MINIMAL for new databases

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#6615]
### Description
Currently, Teku's default storage mode is `PRUNE` which downloads all historic blocks but prunes finalized states. Ultimately we want the default to become `MINIMAL` without unnecessarily surprising users.

Requirements:

* for any existing database, the default storage mode should be `PRUNE`.
* for new databases the default storage mode should be `MINIMAL`
* for any database the user can override the default by explicitly setting `--data-storage-mode`
* once the user has switched an existing database to `MINIMAL` mode, the default storage mode should be `MINIMAL`

One option worth considering is to make the default storage mode always whatever storage mode was last used for that database.

Also, we should add a log with the database mode being used (if Teku does not do this).

This follows on from #6576

**Comment by lucassaldanha** [comment]
If we don't log the database mode being used we should add this.

**Comment by lucassaldanha** [comment]
Also, do we have logs when pruning blocks?

**Comment by rolfyone** [comment]
released in 23.9.0
