### ISSUE TITLE
Invalid SNI between web3signer and teku client

### ISSUE THREAD

**Issue by tropicar** [Consensys-Incorporated/teku#6620]
### Description
With the latest version of Teku client, the validator can't communicate in a proper way with the remote signer. We have the client and the web3signer in the same machine but in separate dockers containers.  There are a warning message in the client and an error message in the web3signer. I have created the certificates with the hostname we use but that does not solve the problem. 

### Steps to Reproduce (Bug)
[Please be as specific as possible]
This is the entrypoint we use for the web3signer https://github.com/dappnode/DAppNodePackage-web3signer-prater/blob/master/web3signer/entrypoint.sh
This is the entrypoint of the teku client: https://github.com/dappnode/DAppNodePackage-teku-prater/blob/master/validator/entrypoint.sh

--validator-api-keystore-file=/cert/teku_client_keystore.p12 \ this certificate i tried to create with the next command to solve the issue:
```
```keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias web3signer -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=localhost, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext san=dns:web3signer.web3signer-prater.dappnode,ip:127.0.0.1```
```
Adding the hostname web3signer.web3signer-prater 

**Expected behaviour:** [What you expect to happen]
The validator connects with the web3signer and works.
**Actual behaviour:** [What actually happens]
In the validator service logs appears this warning 
```
2022-12-16 06:46:01.731 WARN  - handleException /eth/v1/remotekeys org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI
```
The validator stopped of working.
In the websigner logs you can see:
```
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Invalid SNI</title>
</head>
<body><h2>HTTP ERROR 400 Invalid SNI</h2>
<table>
<tr><th>URI:</th><td>/eth/v1/remotekeys</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Invalid SNI</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:267)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:208)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
	at java.base/java.lang.Thread.run(Unknown Source)
</pre>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 11.0.12</a><hr/>

</body>
</html>, HTTP code 400
```

**Frequency:** [How regularly does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Docker Version: [`docker version`]
* Web3signer: v22.11.0
* Teku: v22.12.0

Extra:
I have tried to create the certificates with the followed commands according to the teku documentation:
```keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias web3signer -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=localhost, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext san=dns:web3signer.web3signer-prater.dappnode,ip:127.0.0.1```
Adding the hostname web3signer.web3signer-prater 

In this thread https://github.com/ConsenSys/teku/issues/5386 was discussed how to connect it in dappnode environment.

**Comment by ajsutton** [comment]
I'm not sure I understand what's going on here. The Teku update changes _Teku's_ key manager API to check that it's server certificate (specified via the `--validator-api-keystore-file` option) matches the host name used to access the key manager API.  That doesn't have anything to do with web3signer though.

The endpoint you mention (`/eth/v1/remotekeys`) is part of Teku's key manager API.  Web3Signer doesn't expose that endpoint at all. But you say web signer logs are showing the error? Web3Signer wouldn't normally call that API. So I'm really not sure what is calling the api and failing.

In terms of the keystone though, you've specified `CN=localhost` which means that whatever is calling the api would need to be using `https://localhost` (on whatever port) or it won't work.  Given the use of docker, that's unlikely to be the case and the certificate probably should be generated with CN set to the name of the docker container (ie the DNS name used to access that docker container).

**Comment by tropicar** [comment]
I have created the keystore, adding the DNS of the web3signer container:
```
keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias web3signer -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=web3signer.web3signer-prater.dappnode, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext san=dns:web3signer.web3signer-prater.dappnode,ip:127.0.0.1
```
Now I dont see any error or warning in the teku client but it seems the web3signer can connect with the validator service, it appears this warning:
`[ WARN ] teku-prater.dnp.dappnode.eth is not available, make sure the server is listening: , HTTP code 000`

**Comment by ajsutton** [comment]
But web3signer doesn't connect to the validator client. It's the other way around, the validator client connects to web3signer. That's why I'm finding it hard to understand what the actual problem is here. That error message isn't coming from Teku or Web3Signer though as far as I can tell - I'm guessing it's something that DAppNode is logging? But then there should be more information in the other log files.

It would be really helpful if you could provide full logs from each service so I have a better idea of what's actually going on with each component.

**Comment by tropicar** [comment]
Full logs of the web3signer
[logs-dappnode-package-DAppNodePackage-web3signer.web3signer-prater.dnp.dappnode.eth.txt](https://github.com/ConsenSys/teku/files/10256862/logs-dappnode-package-DAppNodePackage-web3signer.web3signer-prater.dnp.dappnode.eth.txt)

Full logs of the validator service of teku client
[logs-dappnode-package-DAppNodePackage-validator.teku-prater.dnp.dappnode.eth.txt](https://github.com/ConsenSys/teku/files/10256863/logs-dappnode-package-DAppNodePackage-validator.teku-prater.dnp.dappnode.eth.txt)

Full logs of the beacon.chain service of teku client
[logs-dappnode-package-DAppNodePackage-beacon-chain.teku-prater.dnp.dappnode.eth.txt](https://github.com/ConsenSys/teku/files/10256953/logs-dappnode-package-DAppNodePackage-beacon-chain.teku-prater.dnp.dappnode.eth.txt)

**Comment by ajsutton** [comment]
Ok so the validator client is able to connect to the beacon node - it initially couldn't, likely because the beacon node was still starting up but the reported:

```
2022-12-19 07:09:48.119 INFO  - Validator   *** Successfully connected to beacon node event stream
2022-12-19 07:09:56.010 WARN  - Validator   *** The beacon node is not ready to accept requests (offline or not in sync). Future requests to it are likely to fail.
2022-12-19 07:10:08.014 INFO  - Validator   *** The beacon node is back in sync and ready to accept requests now
```

The validator client is also successfully connecting to web3signer.  From the validator logs:
```
External signer is reachable at http://web3signer.web3signer-prater.dappnode:9000
```

But DappNode appears to have configured some kind of cron job in the web3signer instance which is failing to connect properly:
```
[ DEBUG ] starting cron
[ DEBUG ] success response from beacon-chain: {"data":{"head_slot":"4577265","sync_distance":"0","is_syncing":false,"is_optimistic":false}}, HTTP code 200
[ DEBUG ] beacon node syncing status: false
[ DEBUG ] success response from web3signer: OK, HTTP code 200
[ DEBUG ] web3signer status: OK
[ DEBUG ] success response from web3signer: {"data":[{"validating_pubkey":"0x86865a5ce92b75d928c0c7bce1af3f2a1c801dd16ea13361d761c7ba5c4f2b24da324328ae1e64834acb933d5a87c308","derivation_path":"m/12381/3600/0/0/0","readonly":false},{"validating_pubkey":"0x8fbfd1af3ab95560dbaf75bb43dd12fa402bf4313c95017a3d375ee6e8817a6cfc4c4a9db3dd3bab3fdb3e3b1658f82a","derivation_path":"m/12381/3600/1/0/0","readonly":false}]}, HTTP code 200
[ DEBUG ] web3signer public keys: 0x86865a5ce92b75d928c0c7bce1af3f2a1c801dd16ea13361d761c7ba5c4f2b24da324328ae1e64834acb933d5a87c308 0x8fbfd1af3ab95560dbaf75bb43dd12fa402bf4313c95017a3d375ee6e8817a6cfc4c4a9db3dd3bab3fdb3e3b1658f82a
[ DEBUG ] token: cd4892ca35d2f5d3e2301a65fc7aa660
[ WARN ] teku-prater.dnp.dappnode.eth is not available, make sure the server is listening: , HTTP code 000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```

That looks like it's using curl to connect something and it's not functionality that's built into either Teku or Web3Signer.  I'm guessing it's the script to reload keys (https://github.com/dappnode/DAppNodePackage-web3signer-prater/blob/master/web3signer/reload-keys.sh#L125) which I think it trying to connect back to the validator client's rest api which would have SSL enabled.   You said you generated the certificate file with the web3signer host name, but if the cert is being used by the validator client it should have the validator client's host name instead. That said there are no SNI errors being reported so the problem doesn't appear to be to do with certificate host names currently.

The host in the warning (`teku-prater.dnp.dappnode.eth`) doesn't match up with the log file names - I'd have thought it should be trying to connect to `validator.teku-prater.dnp.dappnode.eth`. I'm really not sure though as this is pretty deep into DAppNode specific setup.

**Comment by tropicar** [comment]
We want to create a self-signed certificate, the DNS address of the web3signer and the validator teku service are:
- `validator.teku-prater.dappnode`
- `web3signer.web3signer-prater.dappnode`

How should we create the certificate?
When we create with the next command:
`keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias web3signer -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=validator.teku-prater.dappnode, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU"`
We see an error related to javalin in teku validator service
[Uploading logs-dappnode-package-DAppNodePackage-validator.teku-prater.dnp.dappnode.eth.txt…]()

**Comment by ajsutton** [comment]
Web3signer and the validator client are two separate bits of software with two separate host names so should have two separate SSL certificates in a normal setup, each with its appropriate domain name.

That said, if you really want to use the same certificate for both, you can create one with openssl.  https://docs.teku.consensys.net/en/latest/HowTo/External-Signer/Manage-keys/ has instructions on doing that.

**Comment by tropicar** [comment]
I have followed that steps to create the SSL certificate but i have the same issue,
In the conf file i have these dns:
`[alt_names]
DNS.1 = validator.teku-prater.dappnode
DNS.2 = web3signer.web3signer-prater.dappnode`
And i am using these commands
```
openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -config openssl.cnf | openssl pkcs12 -export -out teku_client_keystore.p12 -passout file:teku_keystore_password.txt
```

**Comment by mehdi-aouadi** [comment]
Can you try creating separate certificates (One for the web3signer and another for the validator)?
Otherwise I would suggest to check with the dappnode team since the API calls from the web3signer back to the validator are out of our control.

**Comment by tbenr** [comment]
Closing for now due to low activity. Please open back if you have other information to share.

**Comment by dsimog01** [comment]
I am continuing Tropicar's work on this issue. As seen above, in DAppNode we have a cron job in the Web3Signer that ensures the keys are properly loaded in the validator (this is temporary as we are working on a new component). The thing is that the only element that will communicate to the Teku validator container for managing the validator keys is the web3signer container. Can you clarify how to create the .p12 certificates so that we are able to do this?

**Comment by dsimog01** [comment]
@tbenr Can you reopen the issue?

**Comment by dsimog01** [comment]
We need to fix this ASAP as the Teku package running in DAppNode is outdated due to this error.

I will summarize the issue:
1. I need to perform requests to the validator API
2. Both the validator and the requester are running in different docker containers that belong to the same network
3. I created an SSL certificate file using `keytool`: 
```keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass dappnode -alias requester -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=requester, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext "SAN=IP:172.24.0.3,DNS:requester"```
4. I set the keystore and the password in the validator container using the flags
5. I perform requests from the requester using the .p12 file that I generated
6. I still get "Invalid SNI" error

Note that "requester" is the docker alias for the requester container in this network, so it should be resolved to the IP of the command

**Comment by dsimog01** [comment]
I also tried with the binary of Teku, running it on localhost, and I was able to perform the requests properly, so there must be a problem when resolving the IP address inside the docker container or something similar. To create the keys in this case I executed: 
```
keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass dappnode -alias localhost -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=localhost, OU=PegaSys, O=ConsenSys, L=Brisbane, ST=QLD, C=AU" -ext "SAN=IP:127.0.0.1,DNS:localhost"
```

**Comment by dsimog01** [comment]
I think I already fixed the issue. It can be closed. The proper command was: `keytool -genkeypair -keystore teku_client_keystore.p12 -storetype PKCS12 -storepass changeit -alias localhost -keyalg RSA -keysize 2048 -validity 109500 -dname "CN=validator.teku-prater.dappnode"`

**Comment by mehdi-aouadi** [comment]
Solved
