### ISSUE TITLE
Segfault in blobToKzgCommitment

### ISSUE THREAD

**Issue by jtraglia** [Consensys-Incorporated/teku#6622]
### Description

Encountered another segmentation fault, but this time in `blobToKzgCommitment`:

```
CKZG4844PropertyTest > fuzzBlobToKzgCommitment STANDARD_OUT
    2022-12-16 15:53:01.934+00:00 | Test worker | DEBUG | CKZG4844 | Loaded trusted setup from /tmp/trusted_setup1663048493037019535.tmp
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9ceaac6880, pid=455, tid=457
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libckzg4844jni.so+0x1c880]  blst_lendian_from_scalar+0x10
#
```

Which was caught here (needed to scroll up about 100 lines to see it):

* https://app.circleci.com/pipelines/github/ConsenSys/teku/22710/workflows/ee035a90-d007-4c93-9fc2-40d110067e89/jobs/163972

This is very similar to the original issue mentioned in here:

* https://github.com/ConsenSys/teku/pull/6596

Then it was a problem in `blst_scalar_from_lendian`, now it's `blst_lendian_from_scalar`.

**Comment by StefanBratanov** [comment]
Interesting. Need to update the binding library with the latest commits. I hope it gets fixed from this commit:
https://github.com/ethereum/c-kzg-4844/commit/cfa36097a3d0c85cebeb7c19b3789b6454589cae

**Comment by jtraglia** [comment]
Hmm I wish there were more information. Because it was a segfault jqwik doesn't provide a seed. I'm having trouble reproducing it, running a billion iterations locally, haven't encountered it yet. Also, I'm having trouble finding where in the stack `blob_to_kzg_commitment ` calls `blst_lendian_from_scalar`... checking `libckzg` and `blst`. It would be nice if that crash file (`/home/circleci/project/ethereum/spec/hs_err_pid455.log`) were available.

**Comment by StefanBratanov** [comment]
It happened again.

https://app.circleci.com/pipelines/github/ConsenSys/teku/22714/workflows/6f15c709-04f5-40b4-9fbe-5e23ad2934fc/jobs/163995/

I could consider disabling that test until we find out what is happening.

**Comment by jtraglia** [comment]
I got a crash log (though it's not that useful). I had a hunch that panned out.

* [hs_err_pid1112105.log](https://github.com/ConsenSys/teku/files/10249499/hs_err_pid1112105.log)

Had to run the fuzzer on amd64 for this. I ran 16 instances of the fuzzer for 4 hours with zero crashes on arm64.

I'll try to get the input blob now.

**Comment by StefanBratanov** [comment]
Thanks. Got one as well. The CI seems to fail often, so just raised a PR and printed out every blob. This one fails:

```
0x7c748addf4e969f60bfc1e15f80a7e2d945f942016a4c9a60bc1ff8179f34de8d27e87bae656f8fdfb1925f90496e4f9727bfbfc1f75f5d9ff0f016900cccd8500530222540d0745df061cf8daf40b026eff02811a918023f8e747b3fad26e8fee0271a8ee0abcc0d8f96c02f5c80cdcdfd0f501f50d46e16d7ceef215b1f924f49cfea505495eb1ede0c290f31a05e40ff300e667c1f60c221a00f3e8f5031dfbe60d4e0a0bfaf3f2fa042602ad150112feae0946f6006a6583f9d60bebf720f1057ef3fd01faf3daf5f759e1d6130f1e9bd8ee450c068af5
```

**Comment by StefanBratanov** [comment]
It seems to pass with latest version of `c-kzg`. Will release a new version of the `jc-kzg` library and this should fix it.

**Comment by StefanBratanov** [comment]
Hmm something is happening. Getting segfault rarely for the following blobs (with new version of the library) for example:

- 0xc976fb2001e84207
- 0xfd82d8
- 0x1fdaf40901c4ff011c03dac22608410467f28253270809

It works most of the time with C_KZG_BADARGS error but if I ran them 100_000 times in a loop, I  always get segfault error at some point.

**Comment by jtraglia** [comment]
Interesting. I have also been trying to figure it out, but to no avail. It doesn't seem to be reproducible with a certain blob. In the test, I would append each blob to a file before calling `blobToKzgCommitment` on it. When it would eventually crash, I would try again with that blob and it works fine. I would run the last 10, 100, 1000, 10000 blobs and it would still work. I'm starting to think it has less to do with a particular blob and more to do with the number of calls. Maybe there's an underlying memory issue; like it's allocating space for something, never freeing it, and eventually running out.

**Comment by benjaminion** [comment]
I suspect some memory issue in the base ckzg lib.

Running even a very minimal test looks like it leaks some bytes.

```
#include <stdio.h>
#include "c_kzg_4844.h"

FILE *fp;
KZGSettings s;

int main() {
    fp = fopen("trusted_setup.txt", "rb");

    load_trusted_setup_file(&s, fp);
    free_trusted_setup(&s);

    fclose(fp);
    return 0;
}
```

The Valgrind result is not quite clean:

```
==3738== Memcheck, a memory error detector
==3738== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3738== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==3738== Command: ./a.out
==3738== 
==3738== 
==3738== HEAP SUMMARY:
==3738==     in use at exit: 32 bytes in 1 blocks
==3738==   total heap usage: 9 allocs, 8 frees, 1,596,248 bytes allocated
==3738== 
==3738== LEAK SUMMARY:
==3738==    definitely lost: 0 bytes in 0 blocks
==3738==    indirectly lost: 0 bytes in 0 blocks
==3738==      possibly lost: 0 bytes in 0 blocks
==3738==    still reachable: 32 bytes in 1 blocks
==3738==         suppressed: 0 bytes in 0 blocks
```

The number of allocs and frees should match, and there should be zero bytes lef tover.

I'll take a proper look into this a bit later.

**Comment by benjaminion** [comment]
[This](https://github.com/ethereum/c-kzg-4844/pull/38) might help. I'll do some more extensive memory leak testing shortly.

**Comment by StefanBratanov** [comment]
> [This](https://github.com/ethereum/c-kzg-4844/pull/38) might help. I'll do some more extensive memory leak testing shortly.

Thanks Ben 🙂 I will give it a test

**Comment by jtraglia** [comment]
Maybe worth mentioning that the fuzzing test only loads the trusted setup once per property test and reuses that instance for all 1000 iterations, so I wouldn't expect that particular fix to solve the issue.

**Comment by benjaminion** [comment]
Yes, agreed, except that memory can be fickle. I didn't find any other memory issue in the `blob_to_kzg_commitment()` primitive. I'll take a look at the Java bindings and see what's there.

**Comment by StefanBratanov** [comment]
This issue has been fixed in https://github.com/ethereum/c-kzg-4844/commit/d06df97716a47bbec2ed83f488e6bc60bead6517 . Thanks to @benjaminion for the help. After releasing a new version of the library, will re-enable the property test and close this issue.
