### ISSUE TITLE
cant find fork schedule for capella in ethdo

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6648]
We should check if we can clean this up... basically when we're running ethdo to prepare for offline withdrawal credential changes, currently teku users need to provide `--fork-version`, but ideally it would be found in api calls...

steps to reproduce:
 - capella enabled (doesnt have to be active) network
 - run the command: `./ethdo validator credentials set --prepare-offline`

output:
```
Error: failed to process: beacon node not providing capella fork schedule; provide manually with --fork-version
```

expected: should be able to generate the offline-preparation.json file without supplying the fork-version, as it should be detected. This likely means an api call (possibly `/eth/v1/config/fork_schedule` isn't providing it, but have asked on ethrnd discord in apis https://discord.com/channels/595666850260713488/710831784991916072/1055231161397415986)

You'll probably need to build ethdo to run the actual command, but any network (minimal with interop eth1 and capella enabled for instance) should suffice to generate the offline file ...

**Comment by ajsutton** [comment]
After discussion in the discord channel, it looks like Teku's APIs are doing the right thing, just the standard APIs aren't particularly well designed and make finding the fork info for capella a bit tricky.

**Comment by lucassaldanha** [comment]
It is worth checking if other clients are enforcing this ordering on `/eth/v1/config/fork_schedule`.
We should also check what we are doing in Teku.

Ultimately, it might be worth raising this with the Ethdo team. On our side, if we create a documentation page with an Ethdo example, we must ensure it has a working example.

**Comment by rolfyone** [comment]
confirmed with lighthouse, we can just list all the schedules, even if only a subset will effectively be active...

So if phase0, altair, bellatrix all start at 0, we can add them in order, and then the fork schedule output is more consistent with other clients.

Currently if we start on bellatrix, we'd only add bellatrix and capella (if active), but this makes consuming the api difficult without looking at the config spec.
