### ISSUE TITLE
VC failover when EL is offline

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#6655]
VC should failover when the EL connected to a BN is offline

**Background** 

Question from user on Discord (obfuscate):

`Hi there, I am currently experimenting with fail over scenarios in my system. I have the Teku Beacon Node and Validator clients split out into separate processes. I have a primary BN connected to Besu and a secondary BN connected to Nethermind. I have configured the two BN endpoints in the VCs to examine the fail over behaviour. When I bring the primart BN down it fails over to the secondary BN almost instantly which is great! However, when I bring my primary EL client (Besu) down, the VC doesn't seem to failing over the secondary BN (with the healthy Nethermind node connected it).`

https://discord.com/channels/697535391594446898/697539289042649190/1058317129805484082

**Comment by spenot09** [comment]
Hi there I've also noticed on the flip side I am seeing a failover happening under the hood it seems. As when the primary EL is down, blocks are still being produced and only when the secondary EL is down do block production failures start creeping in
