### ISSUE TITLE
Resolving local address returns IP starting with 0.

### ISSUE THREAD

**Issue by courtneyeh** [Consensys-Incorporated/teku#6711]
### Description
When running integration tests locally, many fail due to local address being resolved to address starting with 0.

### Temporary Solution

```
NetworkConfig.java

127    String hostAddress = InetAddress.getLocalHost().getHostAddress();
128    return hostAddress.startsWith("0.")  ? "127.0.0.1" : hostAddress;
```

**Comment by tbenr** [comment]
Sam here. I have this ready to pick from the shelf when needed.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/15999009/213646010-d04db0d2-f06b-4798-b596-d4ff10971a51.png">
