### ISSUE TITLE
Docker image for 23.1 fails to run as non-root user

### ISSUE THREAD

**Issue by overholts** [Consensys-Incorporated/teku#6741]
### Description
Docker image for [`23.1`](https://hub.docker.com/layers/consensys/teku/23.1/images/sha256-0a9cee1315990aaaa0706bae3b297d1cb253ed10d7685cd3ba6935d93272ddbc?context=explore) fails to start when running as non-root user.

`22.x` and prior images work fine with no other change to my config.

### Steps to Reproduce (Bug)
Docker compose config (or equivalent `--user` param) like:
```
user: "999:1001"
```
**Expected behavior:**
Teku docker image runs.

```
 ⠿ Container teku-goerli        Started
```

**Actual behavior:**
```
 ⠿ Container teku-goerli        Starting
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/teku/bin/teku": stat /opt/teku/bin/teku: permission denied: unknown
```

### Versions (Add all that apply)
* Software version: 23.1
* Java version: 17
* OS Name & Version: Debian 11
* Docker Version: 20.10.23
* Cloud VM, type, size: N/A (NUC10i7)

**Comment by lucassaldanha** [comment]
Hi @overholts ,

Thanks for reporting this bug. We have just pushed 23.1.1 exclusively with a fix for the docker user permission. Would you please let us know if it solves your problem?

**Comment by lucassaldanha** [comment]
From Discord:
>  Seeing permission issues on docker since upgrading: stat /opt/teku/bin/teku: permission denied: unknown
Running as a different user --user UID:GID and it worked fine until the last version?
Runs fine if I change the data directory owners to the current user (1000) and reruns without the user mapping.
(just caught up on the permission differences in adduser in Ubuntu 22.04 -- looking forward to seeing the fix, thanks!)

Waiting on their feedback if the fix works for them.

**Comment by overholts** [comment]
Yep that fixed it for me, thanks!

**Comment by tbenr** [comment]
fixed by https://github.com/ConsenSys/teku/pull/6743
