### ISSUE TITLE
Empty BlobsSidecar Handling

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6767]
These PRs given:

https://github.com/ethereum/consensus-specs/pull/3174
https://github.com/ethereum/consensus-specs/pull/3242

Given that we respond "Resource Unavailable" when we fail the test on`checkBlobsSidecarsAreAvailable`.

Problem 1:
If we have an entyre epoch of empty blobs sidecars, we will not store anything on DB. If this epoch is the oldest epoch in DA window, we return "Resource Unavailable" even if it it's the case.

Options are:
- we should start writing empty blobs sidecars on DB when we do not receive them when syncing.
- Move away from tracking DA window from earliest blobsSidecar slot in DB and explicitly tracking it via a DB variable.

Problem 2:
Captured by #6788

**Comment by zilm13** [comment]
Fixed with #7295 and #7128
