### ISSUE TITLE
Print EL configuration at startup

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6820]
in a similar way to #6539 we should print configuration of the EL during startup.

**Comment by l646505418** [comment]
Hi,rolfyone,would mind explaining what is the EL stands for? @rolfyone

**Comment by rolfyone** [comment]
WOW I missed this in May! So sorry about that!

EL is execution layer, basically the consensus layer client relies on execution layer to process blocks on the EVM, so it's helpful to know what execution layer is connected. This is configured via the `--ee-endpoint` parameter in teku.

It looks like we now print
`Using Execution engine at {}` in the log, so I'll close this now as it's been completed elsewhere...
