### ISSUE TITLE
BNs failover mechanism improvement

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#6847]
In some cases, the request keep being sent to an optimistic node even though there could be a non optimistic and synced one (See point 1). That could lead to failed attestations production first before falling back to a non optimistic node if present. In the next call, the same behaviour will be observed (even though we could already have concluded from the first attempt that there is a "better" alternative).
In this case there is not enough logs to investigate this behaviour too (See point 2). The errors are reported as metrics without printing any logs.

The following improvements could be implemented:

1. Prefer non optimistic nodes: The readiness check could prioritise non optimistic nodes over optimistic ones. The order of preference would be: non optimistic and in sync -> optimistic and in sync -> not in sync
2. Add some logs when the requests fail: When the requests fail, the exceptions are captured but never logged. They are reported as metrics only.

**Comment by mehdi-aouadi** [comment]
Logs improvement is done in #6902

**Comment by rolfyone** [comment]
> Prefer non optimistic nodes: The readiness check could prioritise the optimistic nodes over non optimistic and synced ones. It would be better to change this behaviour.

This seems to contradict itself slightly...
My understanding is (highest to lowest priority)
 - Node in sync and non optimistic
 - Node in sync and optimistic
 - node not in sync

I guess my reasoning is the top one gives us the best chance of performing successful duties...
Is this the precedence order we want @mehdi-aouadi ?

**Comment by mehdi-aouadi** [comment]
> > Prefer non optimistic nodes: The readiness check could prioritise the optimistic nodes over non optimistic and synced ones. It would be better to change this behaviour.
> 
> This seems to contradict itself slightly... My understanding is (highest to lowest priority)
> 
> * Node in sync and non optimistic
> * Node in sync and optimistic
> * node not in sync
> 
> I guess my reasoning is the top one gives us the best chance of performing successful duties... Is this the precedence order we want @mehdi-aouadi ?

Yes, that's exactly what I meant, thank you for clarifying it. The description was ambiguous.
