### ISSUE TITLE
Peers rate limiting

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#6874]
In the `ThrottlingSyncSource` we're supposed to consider the `peerRateLimit` more accurately:
Currently we just check if `wantToRequestObjects(count.longValue()) > 0` and proceed with the request.
A more accurate behaviour would be to respond with `min(count, wantToRequestObjects(count.longValue()))`

**Comment by zilm13** [comment]
Also the same with answer. Currently if we are allowed to answer with at least 1 object we provide full response whatever size is it. It would be more precise to provide only objects left in throttle allowance

**Comment by zilm13** [comment]
Plus I'd refactor `wantToSmth` names. It's now clear. Something like `allowedToSmth` or similar could be better
