### ISSUE TITLE
Refactor blob sidecars slot and indices iteration

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#6881]
Anther approche to iterate through slots and indices to retrieve the blob sidecars could be by using a data structure.
Proposal: https://github.com/zilm13/teku/commit/208e424ba40c56c9ad9074c1309e6e4e168b5ae5
For more details check: https://github.com/ConsenSys/teku/pull/6835#discussion_r1118112561

**Comment by zilm13** [comment]
btw I did #6880 in it too
