### ISSUE TITLE
Gossip validation improvements

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#6893]
1. when we validate signature in blocks (and blobSidecar) we add them to the validity set in this way:
```java
private boolean blockSignatureIsValidWithRespectToProposerIndex(
....

return signatureValid && receivedValidBlockInfoSet.add(new SlotAndProposer(block));
```
which cause the check to fail and triggers a `reject` like the signature was invalid

2. in blobSidecar gossip validation we haven't added the check we do on block, which is:
```java
    if (gossipValidationHelper.isBlockAvailable(block.getRoot())) {
      LOG.trace("Block is already imported");
      return completedFuture(InternalValidationResult.IGNORE);
    }
```
This should be always caught by `blockIsFirstBlockWithValidSignatureForSlot`. The only exception is when the limited cache doesn't contain it anymore because has been evicted (flooded). Should we remove it from block validation?

**Comment by tbenr** [comment]
related to #6864

**Comment by rolfyone** [comment]
is this Deneb specific?

**Comment by tbenr** [comment]
No, it isn't. Should be a quick one though. I'll prepare a PR today

**Comment by rolfyone** [comment]
The 1k item synchronized set will purge periodically, where as the store only prunes on finalization... I guess in theory during long running finalization may be when you want that second check...

It's a cheap check I would expect, maybe we just leave it in case an edge case occurs, or we could potentially improve the log message and let it run at warn level or something so we see if it actually gets into that code ever?

The down side of being incorrect is it'd lead to blocks actually being rejected ...

**Comment by tbenr** [comment]
I think it is ok to check the `add` return, but I'd act accordingly. A clearer approach is to separate the signature verification with the `add` in the set, which will better reflect the method name (`blockSignatureIsValidWithRespectToProposerIndex` doesn't say anything about the "seen infoSet")

so it could be something like:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/15999009/234593531-e66e2894-d120-4cdf-8d2f-85e389152fec.png">

<img width="933" alt="image" src="https://user-images.githubusercontent.com/15999009/234593618-1c2f14c8-c81e-46ff-b540-5aca021af72a.png">

**Comment by rolfyone** [comment]
Yep that cleanup I do agree with, but removing the initial check does cause a bunch more validation, so I think we should leave that check in place. I'll have a PR up shortly.
