### ISSUE TITLE
Check how limits are applied to blocksByRange requests

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6928]
- how many requests can a node make for blocks by range? Do we have any logic around that?

 - if a lot of nodes are all requesting at the same time, what protections do we have in place?

**Comment by mehdi-aouadi** [comment]
Already started reviewing the RPC limits in #6788, #6874 and #6870

**Comment by rolfyone** [comment]
Ok it sounds like these are in progress, should we close this as duplicate?

**Comment by mehdi-aouadi** [comment]
Yes. I close this one then
