### ISSUE TITLE
SPIKE: what's next for storage?

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6943]
- Leveldb seems to be not supported any longer
 - Rocksdb wasn't very stable previously which is why we moved to leveldb

Moving forward we need to decide what we're doing in this area, we need to get a good idea of a direction.

**Comment by zilm13** [comment]
For the record: we've halted updates of RocksDB at `7.7.3` after #6930, while it's regularly updated.
We may consider to begin updating it again once we are sure we have some testing for it

**Comment by tbenr** [comment]
I did another search session and I found this https://github.com/jankotek/mapdb/

Update: seems like storage isn't mature enough: https://mapdb.org/blog/mapdb_storage_and_design_change/
Pure java implementation would have been interesting though.

**Comment by tbenr** [comment]
there are interesting java projects referenced here:
https://stackoverflow.com/questions/260804/alternative-to-berkeleydb

**Comment by tbenr** [comment]
https://www.speedb.io/
seems like an alternative to rocksdb. We should check with besu guys if they had a chance to evaluate, since it is data-file compatible.

**Comment by tbenr** [comment]
for the records, Besu has integrated the use of BlobDB which is part of RocksDB. They put static data in blobs to reduce compactions.

https://github.com/hyperledger/besu/pull/5471
https://github.com/hyperledger/besu/pull/5475

resources:
https://github.com/facebook/rocksdb/wiki/BlobDB
https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html

**Comment by rolfyone** [comment]
- articulate state of where we're at (problem statement)

**Comment by rolfyone** [comment]
@tbenr close?

**Comment by tbenr** [comment]
ok let's close it for now
