### ISSUE TITLE
Example data in Teku's SwaggerUI needs updating

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#7035]
Version 23.3.1

For example, visiting `http://host:5051/swagger-ui#/Beacon/getBlockV2` in a browser shows example return data that does not include `execution_payload`, `withdrawals`, or `bls_to_execution_changes` although the actual returned data now contains all of these.

Nice to have:
- Examples should use latest active milestone (Capella)?

**Comment by rolfyone** [comment]
wont fix.
