### ISSUE TITLE
Teku 23.3.1 docker container crashes immediately on start

### ISSUE THREAD

**Issue by j4ys0n** [Consensys-Incorporated/teku#7036]
### Description
Teku 23.3.1 docker container crashes immediately on start
```
[0.035s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /opt/teku/hs_err_pid1.log
[0.025s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```
v22.x worked fine, exact same environment, runtime flags

### Steps to Reproduce (Bug)
Since this environment is not the most common - here's how to set it up.

On a separate machine, 
- Install Proxmox https://www.proxmox.com/en/downloads/category/iso-images-pve
- Set up an LXC with docker. helper script: https://tteck.github.io/Proxmox/ - click on "Docker - Kubernetes" > "Docker LXC"
- Start LXC
- `docker run -it --rm consensys/teku:23.3.1`

**Expected behavior:** container should run

**Actual behavior:** container crashes

**Frequency:** every time

### Versions (Add all that apply)
* Software version: 23.3.1
* Java version: OpenJDK 16, OpenJDK 17
* OS Name & Version: Ubuntu 22.04 LXC on Proxmox 7.4
* Docker Version: Docker version 20.10.7, build f0df350
* Cloud VM, type, size: LXC with 16 cores and 32GB allocated

[hs_err_pid1.log](https://github.com/ConsenSys/teku/files/11240223/teku-jvm-error.txt)

**Comment by rolfyone** [comment]
Thanks for raising...

```
-XX:SoftMaxHeapSize=2g -Xms5g -Xmx5g
```

I'd suggest removing softMaxHeapSize, and Xms... although Xms may be useful in this instance since it's showing you a lack of memory available up front.  either-way, softMaxHeap won't be required...

Are there a lot of other processes running (outside of this container)? The message suggests there's no physical memory left on the machine to satisfy allocating 5G swap upfront...

I did start this docker instance the other day on my machine and it was working for a different reason, so believe it is going to be configuration, just trying to narrow down in what way... sorry to ask more questions than I answered...

**Comment by j4ys0n** [comment]
Thanks for the suggestion. I've tried that actually. Among other variations, I tried running the container with no arguments and the result is the same. The run command I wrote in the original issue description has the same result. `docker run -it --rm consensys/teku:23.3.1`

To answer your other questions - 
In this specific LXC, there are other things running, with docker. everything here: https://github.com/j4ys0n/eth-validator-stack/blob/main/docker-compose.yml

But I have many LXCs running on this specific server. The LXCs are running on Proxmox, which is an open source hypervisor.

I am using this same docker-compose on an AWS EC2 instance and it runs fine, so the issue seems to be with running this image in a linux container.

**Comment by rolfyone** [comment]
fairly useless example, but just for context:
```
docker run -it --rm consensys/teku:23.3.1 --network minimal --Xinterop-enabled=true
INFO StatusConsoleListener Configuring logging for destination: console and file
INFO StatusConsoleListener Logging file location: /opt/teku/.local/share/teku/logs/teku.log
INFO StatusConsoleListener Logging includes events: true
INFO StatusConsoleListener Logging includes validator duties: true
INFO StatusConsoleListener Logging includes color: true
INFO StatusConsoleListener Include P2P warnings set to: false
00:37:47.244 INFO  - Teku version: teku/v23.3.1/linux-aarch_64/-eclipseadoptium-openjdk64bitservervm-java-17
00:37:47.246 INFO  - This software is licensed under the Apache License, Version 2.0 (the "License"); you may not use this software except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
00:37:47.309 INFO  - Configuration | Network: minimal, Storage Mode: PRUNE
00:37:47.309 INFO  - Host Configuration | Maximum Heap Size: 1.92 GB, Total Memory: 7.67 GB, CPU Cores: 6
00:37:47.310 INFO  - Rest Api Configuration | Enabled: false
00:37:47.310 INFO  - Validator Api Configuration | Listen Address: 0.0.0.0, Port 5052, Allow: [127.0.0.1, localhost]
00:37:47.459 INFO  - Storing beacon chain data in: /opt/teku/.local/share/teku/beacon
00:37:47.460 INFO  - Loading 0 validator keys...
00:37:47.462 INFO  - Loaded 0 Validators:
00:37:47.464 INFO  - Using portable BLST library.
00:37:47.588 INFO  - Initializing storage
00:37:47.590 INFO  - Storage initialization complete
00:37:47.604 INFO  - Starting with mocked start interoperability mode with genesis time 2023-04-17 12:37:52 and 64 validators
00:37:47.763 INFO  - Genesis Event ***
Genesis state root: 0x458c86dc2f811dddef03805fb2535896c30f213a253768bd663df5add366f4de
Genesis block root: 0x9bb6be93aabbc78ff60b964272a8a8d5cd1bc2fbd30cb5125b2e2d19a0b29c4f
Genesis time: 2023-04-17 00:37:52 GMT
00:37:47.948 INFO  - Generated new p2p private key and storing in: generated-node-key
00:37:48.142 INFO  - PreGenesis Local ENR: enr:-Iu4QK-FvfPcsJ8ZAmPvpLZJjEzXIoxGCxtgTSjiALCjH0apYAk_HhBFCAuSpzR39ONuoWgjIK74Jq0E3KJ80AXu-oUChGV0aDKQGK5MywAAAAH__________4JpZIJ2NIlzZWNwMjU2azGhAjuFsKjhIU9PJLUyFutWEq78iG2fLPbqPvbY2XY5Hj0l
00:37:48.187 INFO  - 4 seconds until genesis time is reached. Peers: 0
00:37:48.231 INFO  - Listening for connections on: /ip4/172.17.0.2/tcp/9000/p2p/16Uiu2HAkyS2GdiM1X2BtbFPWt3oJ5z7QgAWH1EKv9uM2VQAbL4Z2
00:37:48.252 INFO  - Local ENR: enr:-Iu4QOFSokYLIb0VP2lB1wXWcfU0wyeiRywLolufexND8ECQZkEqQPNsSZEi0Ddq-4tJ-H_4UPHW9jbN4FFppivpwsgDhGV0aDKQUmfZxgAAAAH__________4JpZIJ2NIlzZWNwMjU2azGhAjuFsKjhIU9PJLUyFutWEq78iG2fLPbqPvbY2XY5Hj0l
00:37:52.007 INFO  - Epoch Event *** Epoch: 0, Justified checkpoint: 0, Finalized checkpoint: 0, Finalized root: 9bb6be93aabbc78ff60b964272a8a8d5cd1bc2fbd30cb5125b2e2d19a0b29c4f
^CTeku is shutting down
```

Because this is interop, a lot of things don't happen, but it does start, and I'd expect it to not start if it was a broken image...

**Comment by j4ys0n** [comment]
It does not start on the LXC.

```
docker run -it --rm consensys/teku:23.3.1 --network minimal --Xinterop-enabled=true
[0.014s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /opt/teku/hs_err_pid1.log
```

there's plenty of memory available on the server and the LXC that's provisioned on it.

![image](https://user-images.githubusercontent.com/979576/232353616-077264c8-6d56-495f-b598-a574ea7ff933.png)

**Comment by rolfyone** [comment]
There's a few references online to a similar issue around random docker images, but the only answer seems to be 'update docker'.
I'm guessing you've already tried that?

**Comment by j4ys0n** [comment]
Ah - that was it! Thank you sir. I was searching for teku specific issues, not necessarily java/docker issues.

There is another issue though. The container starts up but then teku doesn't start.

```
2023-04-17 00:59:02.839 INFO  - Using default implementation for ThreadExecutor
2023-04-17 00:59:02.844 INFO  - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2023-04-17 00:59:02.845 INFO  - Quartz Scheduler v.2.3.2 created.
2023-04-17 00:59:02.845 INFO  - RAMJobStore initialized.
2023-04-17 00:59:02.845 INFO  - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2023-04-17 00:59:02.845 INFO  - Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
2023-04-17 00:59:02.845 INFO  - Quartz scheduler version: 2.3.2
2023-04-17 00:59:02.855 INFO  - Initializing storage
2023-04-17 00:59:03.324 FATAL - Failed to initialize storage. Check the existing database matches the current network configuration. Set log level to debug for more information.
2023-04-17 00:59:03.325 FATAL - Teku failed to start
java.util.concurrent.CompletionException: tech.pegasys.teku.infrastructure.ssz.sos.SszDeserializeException: First variable element offset doesn't match the end of fixed part
```

I'm not sure why it would fail to initialize storage.

**Comment by rolfyone** [comment]
ok this one is probably less severe in a way, thats basically because it was running pre 23.3.1 during the capella fork and now it's confused.

If you're an archive node you probably want to keep history so you'll want to do something like:
```
teku debug-tools db delete-hot-blocks
```

if you're running prune or minimal, it's probably not a huge issue to just re-initialise your database, it would just have to re-download blocks... This would mean deleting the data folder and re-initialising from `initial-state`. I usually just google `checkpointz beaconcha.in` and use the initial state they offer, but if you have a trusted node internally you could equally use an initial-state from that...

**Comment by j4ys0n** [comment]
ah - ok - i will try that. i run this at home for dev and stuff like that and forgot to update in time. thanks again!
i do have an archive, but that's actually offline temporarily, awaiting a replacement nvme drive.

**Comment by rolfyone** [comment]
Ok, I'll close this, but feel free to ask further questions on this ticket or in discord if you need more help :)
