### ISSUE TITLE
update java minimum supported?

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7047]
With a dependency on besu, who now supports minimum java 17, we're going to have to probably follow suit, as we include besu libraries which we can no longer update, because we support java 11.

**Comment by lucassaldanha** [comment]
Just pointing out some of the changes in Besu that could be similar to ours:
- https://github.com/hyperledger/besu/pull/3953
- https://github.com/hyperledger/besu/pull/4532
- https://github.com/hyperledger/besu/pull/4977

Don't be disheartened by the number of changes on https://github.com/hyperledger/besu/pull/4977 as most of them are related to PKI infrastructure support in Besu so it does not relate to Teku.

Here is the tracking ticket in Besu: https://github.com/hyperledger/besu/issues/3320
