### ISSUE TITLE
Make `execution_optimistic` required field in GetProposerDuties

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#7053]
Currently, if `execution_optimistic` is false, It is not included in the json response. To make it consistent with the attester and sync duties endpoints, It would be preferred to include it.

https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/ValidatorRequiredApi/getProposerDuties

**Comment by mehdi-aouadi** [comment]
As you mentioned and according to the [spec](https://github.com/ethereum/beacon-APIs/blob/f087fbf2764e657578a6c29bdf0261b36ee8db1e/types/primitive.yaml#L50) the `ExecutionOptimistic` is assumed to be false when not present. So not really an issue on our side but on the caller side... 
Being consistent with the other endpoints could be considered a good reason so I guess it's ok to include it in any case

**Comment by StefanBratanov** [comment]
> As you mentioned and according to the [spec](https://github.com/ethereum/beacon-APIs/blob/f087fbf2764e657578a6c29bdf0261b36ee8db1e/types/primitive.yaml#L50) the `ExecutionOptimistic` is assumed to be false when not present. So not really an issue on our side but on the caller side... Being consistent with the other endpoints could be considered a good reason so I guess it's ok to include it in any case

Yup, I agree. I wouldn't have changed it, but then saw for the other endpoints is required field so decided to be consistent.
