### ISSUE TITLE
Validator top up not valid 

### ISSUE THREAD

**Issue by DynamoLED** [Consensys-Incorporated/teku#7060]
Please can somebody help?

I suddenly found myself under 32 ETH on my validator and tried to top up through the top up facility on the launchpad but although the transaction was successful the top up is not valid…

![5B49D6B5-0E08-4127-A996-21A1EF1BFBD8](https://user-images.githubusercontent.com/109997884/232951922-62bf0cbf-11f2-4e00-a285-6ca85de52aa6.jpeg)

Transaction 
[(https://etherscan.io/tx/0x3e68702566edee0061344eb99c484b4fac8800db082980bb6027d1dca09f5812)](https://etherscan.io/tx/0x3e68702566edee0061344eb99c484b4fac8800db082980bb6027d1dca09f5812)

**Comment by benjaminion** [comment]
I suspect Etherscan is incorrect about this and that you will be fine. Top-up transactions for existing validators do not need to have valid signatures.

It will be another 12 hours or more before the consensus layer processes this transaction. I'd give it a day and check your validator then. If it's not successful there isn't much we can do from the Teku side - the Ethstaker community would be a good place to ask. But I think you'll find it will go through ok.

Closing as not really a Teku issue.

**Comment by benjaminion** [comment]
I'll just add that your validator's effective balance was still 32 ETH even though the actual balance had dropped below that. That's the maximum effective balance, so the top up was unnecessary. You will probably get almost all of it sent back to you via the withdrawals process within the next few days (assuming it is processed successfully).

**Comment by DynamoLED** [comment]
Thanks Ben, really appreciate you help.

**Comment by benjaminion** [comment]
Looks like your deposit [has been credited](https://beaconcha.in/validator/b132a4235ceade9a3809c776e3a7312eb1fed984973ca28e4a6fabe9d59ccb3db15ca5abd9c78e0f0af81e07af7125d2#deposits) now, so we can all relax 😅  As I mentioned, you should be getting most of that back in a few days when the current withdrawals sweep reaches you.

I must say that both beaconcha.in and etherscan are most unhelpful in displaying the top-up as invalid. Might be worth bug reports to them if you feel like sparing anyone else the angst in future. You can refer them to this issue.
