### ISSUE TITLE
Implement epoch metrics

### ISSUE THREAD

**Issue by atoulme** [Consensys-Incorporated/teku#707]
# Description
See https://github.com/ethereum/eth2.0-metrics/blob/master/metrics.md
Implement the epoch related metrics: beaconchain_current_justified_epoch, beaconchain_current_finalized_epoch, beaconchain_current_prev_justified_epoch, beaconchain_current_epoch_live_validators, beaconchain_previous_epoch_live_validators, beaconchain_pending_exits, beaconchain_previous_epoch_stale_blocks

For metrics that would store a hash, transform the Bytes32 hash into a double, using the sign bit.

## Acceptance Criteria
Prometheus reports all those metrics.

**Comment by arash009** [comment]
Closing this issue and will be tracking individual metrics as separate items based on most recent spec
