### ISSUE TITLE
P2P lower/upper bound options erasure

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#7074]
When `p2p-peer-upper-bound` > `p2p-peer-lower-bound` (default value: 64) without explicitly setting the lower bound option, the lower bound is set to the upper bound value but on the `DiscoveryConfig` builder only. Then the upper bound is compared to the default lower bound (64) and hence set to 64. We end up with p2p-peer-upper-bound == p2p-peer-lower-bound == 64

Check:
```
d.isDiscoveryEnabled(p2pDiscoveryEnabled)
                  .staticPeers(p2pStaticPeers)
                  .minPeers(getP2pLowerBound())
                  .maxPeers(getP2pUpperBound())
                  .siteLocalAddressesEnabled(siteLocalAddressesEnabled);
```
in `P2POptions`

[Reported on Discord](https://discord.com/channels/697535391594446898/697539289042649190/1100124015529578660)

**Comment by StefanBratanov** [comment]
This looks related to https://github.com/ConsenSys/teku/issues/6992

**Comment by mehdi-aouadi** [comment]
Duplicate of #6992
