### ISSUE TITLE
Implement eth1 processing metrics

### ISSUE THREAD

**Issue by atoulme** [Consensys-Incorporated/teku#708]
# Description
See https://github.com/ethereum/eth2.0-metrics/blob/master/metrics.md
Implement the eth1 processing related metrics: beaconchain_pending_deposits, beaconchain_total_deposits

# Acceptance Criteria
Prometheus reports beaconchain_pending_deposit and beaconchain_total_deposits.

**Comment by arash009** [comment]
Closing this issue and will be tracking individual metrics as separate items based on most recent spec
