### ISSUE TITLE
Why do blocks not always make it to all nodes

### ISSUE THREAD

**Issue by jrhea** [Consensys-Incorporated/teku#710]
### Description
If the beacon chain is running long enough, eventually one (or more) of the nodes will never receive a block.  Why?

![image](https://user-images.githubusercontent.com/5555162/59176220-09ba6100-8b1e-11e9-9f43-a87b741b8038.png)

**Comment by atoulme** [comment]
There is no code to reconnect a peer that lost connection, and I'm not sure keep alive is turned on on both sides. I would start there. There is probably a glaring bug in plumtree as well.

**Comment by jrhea** [comment]
<img width="1590" alt="Untitled" src="https://user-images.githubusercontent.com/5555162/59236502-1ab9af80-8bbc-11e9-9122-7d630048a036.png">

**Comment by cemozerr** [comment]
This has been fixed right? Since we're running with no problems nearly indefinitely now.
