### ISSUE TITLE
Unable to register remote key with keymanager API

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7113]
### Description

When attempting to register a remote key as per https://ethereum.github.io/keymanager-APIs/?urls.primaryName=v1.0.0#/Remote%20Key%20Manager/importRemoteKeys , Teku returns code `200`, and a json result with status `error` and message `Not able to add validator`

### Steps to Reproduce (Bug)

`curl -k -m 60 -s --show-error -o /tmp/result.txt -w '%{http_code}' -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer mybearertoken' --data @/tmp/apidata.txt https://consensus:7500/eth/v1/remotekeys`

With apidata.txt for example

```
{
  "remote_keys": [
    {
      "pubkey": "0xb69d83500fd0b171e4af7fa41890af7a6d1658fdd9df28d2fe98d652d74a069a8882dc81aedd484e0e738dc142547ec7",
      "url": "http://web3signer:9000"
    }
  ]
}
```

### Versions

* Software version: `teku/v23.4.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17`

**Comment by rolfyone** [comment]
Hey there! Thanks for raising.
I did a quick test of this and it does appear to be working, just wondering if your key is available on web3signer?

Specifically what I did was kind of cheating a little I guess, I ran web3signer with key-manager:
```
docker run -p 19000:9000 \
    consensys/web3signer:develop eth2 \
    --slashing-protection-enabled=false \
    --key-manager-api-enabled=true \
```
then i loaded some interop keys and posted 
```
curl -X 'POST' \
  'http://localhost:5052/eth/v1/remotekeys' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer myBearer' \
  -H 'Content-Type: application/json' \
  -d '{
  "remote_keys": [
    {
      "pubkey": "0xb6c8c112c7802a29579e14b228ae6a33fd7f0a3d33d06708b0f07cf7ec18f48e5ed7d5c47e7942c2aea2d1f4dd95557b",
      "url": "http://localhost:19000"
    }
  ]
}'
```

and teku was running with 
```
build/install/teku/bin/teku \
    --network minimal \
    --data-path tmp/minimal-keys \
    --data-storage-mode archive \
    --validators-external-signer-url http://localhost:19000 \
    --validator-api-enabled \
    --Xvalidator-api-ssl-enabled=false \
    --initial-state genesis-256.bin \
    --validator-api-docs-enabled
```

I guess one potential might be that the signer-url was listed and known to teku?  Was your web3signer url known to teku?

**Comment by yorickdowne** [comment]
Ah that’s the difference, I am not passing the signer url through in parameters, as it’s in the registration. Let me change that, that should do it.

**Comment by yorickdowne** [comment]
That did the trick. Thanks for the help!

**Comment by rolfyone** [comment]
awesome! Glad we could figure it out :)
