### ISSUE TITLE
Teku consumes 100% CPU during Ethereum consensus issues event

### ISSUE THREAD

**Issue by kernelpanic9** [Consensys-Incorporated/teku#7138]
### Description
Teku consumes 100% CPU during Ethereum consensus issues on May 11-12, 2023

### Steps to Reproduce (Bug)
Java heap was set to 8GB.
Teku crashing on Java heap and consumes 100%.
Not syncing during consensus issues.

Attaching log.
[teku_log_20230512.tar.gz](https://github.com/ConsenSys/teku/files/11466811/teku_log_20230512.tar.gz)

### Versions (Add all that apply)
* Software version: 2.4.0
* Java version: 17.0.6
* OS Name & Version: Ubuntu 22.04.1 LTS
* Docker Version: N/A
* Cloud VM, type, size: Dedicated server 73F3

**Comment by benjaminion** [comment]
Thanks. Yes, this is widespread. Related: https://github.com/ConsenSys/teku/pull/7137

**Comment by xiaoxinxiashan** [comment]
I have encountered the same problem. When can this issue be fixed?

**Comment by benjaminion** [comment]
This should be fixed by [release 23.5.0](https://github.com/ConsenSys/teku/releases/tag/23.5.0).

Closing for now, but if you find the issue recurs after upgrading to 23.5.0 then add a follow-up and we will re-open.
