### ISSUE TITLE
Teku takes longer than expected to query block headers by root

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7144]
from customer:

I created a python script which starts off by querying the head block of a client and uses the parent hash to iterate down the chain until the genesis block. The purpose of this was so that we can calculate the actual chain created and see if there are forks between clients. The api requests for each client was conducted serially.

I noticed that it would take substantially longer to query teku compared to other clients as seen by the difference in time between fetch requests (note: the time was recorded at the start of fetching)

This was the endpoint I used to construct the data:
/eth/v1/beacon/headers/{block_id}
https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockHeader 

my thoughts:

something funky might be happening with the way data is queried:
```
> time curl http://localhost:5051/eth/v1/beacon/headers/0x4b1018549c3d6db84fb736bdf8a478b5c9a789ae64de37ad496aa05fdadebee4
 <.. snip>
real	0m0.324s
user	0m0.005s
sys	0m0.000s
> time curl http://localhost:5051/eth/v1/beacon/headers/6441471
 <.. snip>
real	0m0.083s
user	0m0.000s
sys	0m0.005s
```

Not sure if it's just because of the way search by root works, or if we're doing something unusual when searching by root, but worth taking a look at how it all works on finalized blocks

**Comment by zilm13** [comment]
I did some measurement with finalized data. I don't have hot data locally and assume we will pass hot slot/roots fast if we want to check the whole chain. At least 1000 slots were measured for each run. I've checked fresh finalized data and old assuming db compaction or something like this could have impact on the result. p2p was turned off to disable its impact on the result
```
Fresh finalized by root:
50th percentile (median): 0.004
90th percentile: 0.005
99th percentile: 0.006
Old finalized by root:
50th percentile (median): 0.003
90th percentile: 0.004
99th percentile: 0.012

Fresh finalized by slot:
50th percentile (median): 0.032
90th percentile: 0.084
99th percentile: 0.088
Old finalized by slot:
50th percentile (median): 0.003
90th percentile: 0.004
99th percentile: 0.005
```
The only misfit I see here is "Fresh finalized by slot", which become even worse while writing this, which is opposite to the user results, I will try to understand the reason of such result and try to get also results for hot data, as user query could affect hot data.

**Comment by zilm13** [comment]
Funny thing after restart both fresh and old by slot is even worse:
```
50th percentile (median): 0.045
90th percentile: 0.124
99th percentile: 0.131
```
Changing https://github.com/ConsenSys/teku/blob/1ed6a09a561fdc89f4d1a21d529c21b2aa0950f1/storage/src/main/java/tech/pegasys/teku/storage/server/kvstore/dataaccess/CombinedKvStoreDao.java#L275 `getFloorEntry` to `get` makes time on par with by root:
```
50th percentile (median): 0.004
90th percentile: 0.005
99th percentile: 0.006
```
One seek is 40-64ms always [(this line)](https://github.com/ConsenSys/teku/blob/a9f0099bf7daadfc3ea89e06f37b337d2c323662/storage/src/main/java/tech/pegasys/teku/storage/server/leveldb/LevelDbInstance.java#L146), when block is missed in slot, next slot lookup adds the same amount of time to the result (which is, to be honest, very strange).

**Comment by zilm13** [comment]
I would check all usages of `getFloorEntry` whether we really need it or not in every case plus I'd also check all `withIterator` usages if first and last column entry seek is slow too, just interesting

**Comment by zilm13** [comment]
I did some measurements on our nodes and while Goerli measurements matches my local findings, Mainnet data varies a lot. So I'm not sure now. Please note, these measurements where taken with network on, which could affect the result.
```
Goerli finalized by slot 1
50th percentile (median): 0.089
90th percentile: 0.296
99th percentile: 1.009
Goerli by finalized slot 2
50th percentile (median): 0.086
90th percentile: 0.240
99th percentile: 0.318
Goerli by slot from head
50th percentile (median): 0.086
90th percentile: 0.241
99th percentile: 0.313

Goerli finalized by root 1
50th percentile (median): 0.008
90th percentile: 0.013
99th percentile: 0.045
Goerli finalized by root 2
50th percentile (median): 0.007
90th percentile: 0.010
99th percentile: 0.017
Goerli by root from head
50th percentile (median): 0.007
90th percentile: 0.013
99th percentile: 0.116

Mainnet finalized by slot 1
50th percentile (median): 0.006
90th percentile: 0.008
99th percentile: 1.457
Mainnet finalized by slot 2
50th percentile (median): 0.208
90th percentile: 0.397
99th percentile: 1.881
Mainnet finalized by slot 3
50th percentile (median): 0.005
90th percentile: 0.006
99th percentile: 0.010
Mainnet from head by slot 1
50th percentile (median): 0.010
90th percentile: 0.020
99th percentile: 1.539
Mainnet from head by slot 2
50th percentile (median): 0.009
90th percentile: 0.013
99th percentile: 1.509

Mainnet finalized by root 1
50th percentile (median): 0.007
90th percentile: 0.021
99th percentile: 1.552
Mainnet finalized by root 2
50th percentile (median): 0.009
90th percentile: 0.21
99th percentile: 0.402
Mainnet finalized by root 3
50th percentile (median): 0.007
90th percentile: 0.21
99th percentile: 1.43116
Mainnet from head by root 1
50th percentile (median): 0.008
90th percentile: 0.012
99th percentile: 1.293
Mainnet from head by root 2
50th percentile (median): 0.009
90th percentile: 0.213
99th percentile: 0.409
```

**Comment by zilm13** [comment]
Performed measurement on another mainnet and goerli nodes and it doesn't add a light to the issue
```
Goerli archive finalized by slot 1
50th percentile (median): 0.009
90th percentile: 0.015
99th percentile: 1.204
Goerli archive finalized by slot 2
50th percentile (median): 0.007
90th percentile: 0.011
99th percentile: 1.109
Goerli archive finalized by slot 3
50th percentile (median): 0.010
90th percentile: 0.016
99th percentile: 1.384
Goerli archive from head by slot
50th percentile (median): 0.010
90th percentile: 0.023
99th percentile: 0.153

Goerli archive finalized by root 1
50th percentile (median): 0.008
90th percentile: 0.012
99th percentile: 0.065
Goerli archive finalized by root 2
50th percentile (median): 0.006
90th percentile: 0.010
99th percentile: 0.058
Goerli archive finalized by root 3
50th percentile (median): 0.007
90th percentile: 0.127
99th percentile: 0.183
Goerli archive from head by root
50th percentile (median): 0.009
90th percentile: 0.020
99th percentile: 1.189

Mainnet non-archive finalized by slot 1
50th percentile (median): 0.007
90th percentile: 0.011
99th percentile: 0.020
Mainnet non-archive finalized by slot 2
50th percentile (median): 0.008
90th percentile: 0.014
99th percentile: 0.551
Mainnet non-archive finalized by slot 3
50th percentile (median): 0.010
90th percentile: 0.013
99th percentile: 0.027
Mainnet non-archive from head by slot
50th percentile (median): 0.204
90th percentile: 0.273
99th percentile: 0.514

Mainnet non-archive finalized by root 1
50th percentile (median): 0.009
90th percentile: 0.014
99th percentile: 0.027
Mainnet non-archive finalized by root 2
50th percentile (median): 0.008
90th percentile: 0.011
99th percentile: 0.018
Mainnet non-archive finalized by root 3
50th percentile (median): 0.009
90th percentile: 0.220
99th percentile: 0.332
Mainnet non-archive finalized by root 4
50th percentile (median): 0.009
90th percentile: 0.015
99th percentile: 0.206
Mainnet non-archive from head by root
50th percentile (median): 0.011
90th percentile: 0.017
99th percentile: 0.051
```

**Comment by zilm13** [comment]
So it looks like there is a case when iterator is slow but I'm not sure in what occasion. Locally the main time in these cases were consumed by atomic db operations. Overall both requests took similar time and sometimes are dramatically slower than usual.
Looking at the code, I don't see anything bad on each side except the fact we call `getFloorEntry` with by slot query and if slot is missed we look for the previous entry and drop it before response, so using `getFloorEntry` functionality looks useless in this case but I cannot be confident it's slower than `get`, at least not on all nodes.

**Comment by zilm13** [comment]
I'd suggest to close this, because
- it was not confirmed
- we've switched from iterator to atomic get in #7471 and I guess we want to keep this as it looks safer on slow DB
