### ISSUE TITLE
BLS verify bug

### ISSUE THREAD

**Issue by mpetrunic** [Consensys-Incorporated/teku#717]
### Description
Bls spec tests does not include inputs for `verify` methods but in block processing operations spec tests there is a lot of bls signatures to be verified. It seems that your `bls.verify` does not work. That said, it seems that with same private key it produces different signature than py_ecc which lead me to believe that hash_to_g2 implementation doesn't work always.
We used similar implementation in Lodestar which also seems to have similar issue.

### Steps to Reproduce (Bug)
Inputs from `test_process_deposit.test_new_deposit` spec tests which passes in py_ecc. Do note, domain in hex is `0000000003000000` (not really sure why do you use long).
```java
  @Test
  void succeedsWhenAMessageSignsAndVerifies() throws BLSException {
    assertTrue(
      BLSSignature
              .fromBytes(
                      Bytes.fromHexString(
                              "a61b0de0d96c0f7a99874ba327e0ed4715e2bbe125ee0148e43179ea508c84e3c7aaf0a3248e414d13f28e7c9eed568a15f58373f8d49c595008d67ebfa5b5536b46b05f840f83931fd5730c88e4c4876175623453d2087d616302941010534f"
                      )
              ).checkSignature(
              BLSPublicKey.fromBytesCompressed(Bytes.fromHexString("b4ea54b24c3dae4c5d072e75299096f9c3d4c6902112bdb45ef18281bfc4143b240662d454316092acebafdc7fb427cb")),
              Bytes.fromHexString("2ae827264d2182d3a9c4d5c2e8b09b85ca9daf499771cf4200bd67cd3bfcdf25"),
              12884901888L
      )

    );
  }
```

**Expected behavior:** [What you expect to happen]
true
**Actual behavior:** [What actually happens]
false
**Frequency:** [What percentage of the time does it occur?]
100%

**Comment by benjaminion** [comment]
Thanks for this. The failure is because we are still using keccak256 in `hash_to_g2`. When I swap that out for SHA256, this test passes fine.

Appreciate your time for looking into this.
