### ISSUE TITLE
Order Validators in Shuffling Test by Index

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#718]
Order Validators in Shuffling Test by Index

### Acceptance Criteria
* Validators defined in the `input` of both `test_vector_shuffling.yml` and `shuffling_set_size.yml` should be ordered according to their `original_index`, and not just what position they are in the YAML file.

### Steps to Reproduce (Bug)
1. Notice that validators are added to the validator registry in order of their position in the YAML file, not their `original_index` parameter.

**Comment by jrhea** [comment]
Is this issue still unresolved?

**Comment by ajsutton** [comment]
We don't have those files anymore so closing.
