### ISSUE TITLE
Choosing a Generation path that doesn't end in `sedge-data` breaks `sedge`

### ISSUE THREAD

**Issue by Pablosan** [Consensys-Incorporated/teku#7192]
### Description
`sedge` commands fail if a Generation path is specified that does NOT end in `sedge-data`. Error:

```
2023-05-29 19:55:19 -- [INFO] [Logger Init] Log level: info
2023-05-29 19:55:20 -- [INFO] You are running the latest version of sedge. Version:  v1.1.0
2023-05-29 19:55:20 -- [FATA] docker-compose file not found
```

### Steps to Reproduce (Bug)
Run `sedge-cli`
When asked for `Generation path` enter `/User/<username>/src/sedge-goerli`
When asked to `Run services now?` answer `n`
Enter `sedge run` or any other `sedge` command that requires the docker-compose file and you'll see an error similar to the one posted above

**Expected behavior:**
`sedge` should honor the Generation path that was entered

**Actual behavior:** [What actually happens]
`sedge` throws error `docker-compose file not found`

**Frequency:** [How regularly does it occur?]
Every time

### Versions (Add all that apply)
* Software version: sedge version 1.1.0 (any version of any client)
* OS Name & Version: Mac OS 13.4 running on Apple Silicon
* Docker Version: Docker Desktop 4.19.0 (106363)

**Comment by tbenr** [comment]
I don't see any teku related logs or errors. Can you clarify how can we help?

**Comment by tbenr** [comment]
We close this. Feel free to reopen the issue if you provide more info.
