### ISSUE TITLE
Add an option to disable syncing the deposit contract logs for non-validator nodes

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#7240]
### Description
It would be useful to have a option to disable syncing the deposit contract logs. This is useful if running an execution node for a purpose other than staking. It should not be used for staking nodes as it will cause missed block proposals.
For users who doesn't run a validator it's useful because they could turn off transaction receipts and other storage consuming data on execution layer side.

**Comment by tbenr** [comment]
This may become irrelevant when new deposit handling will be adopted.
