### ISSUE TITLE
Improve Historical Sync to speed up backfill

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7244]
related to #7243 

since the node cannot perform duties until it has validated the entire Data Availability window, we must evolve the historical sync to be multi-peer (similarly to forward sync) to be able to download and validate as quick as possible the whole DA and start performing duties.

**Comment by rolfyone** [comment]
wow this seems like a huge step backwards... why is that a requirement??

**Comment by tbenr** [comment]
It's a forkchoice requirement in spec. Was a bit unclear to me and I asked for confirmation in yesterday's ACDC

**Comment by tbenr** [comment]
After per latest 4844 implementers call I'm going to close these tickets.
