### ISSUE TITLE
Teku 23.6.0 having issues with GNOSIS chain

### ISSUE THREAD

**Issue by phd2018eth** [Consensys-Incorporated/teku#7285]
### Description
[Detailed description of the problem and the impact it has]
Significant reduction in effectiveness caused by periodical low counts (0-70%）of correct target and head.
Sometimes with "ERROR - Refusing to sign attestation" 
### Steps to Reproduce (Bug)
[Please be as specific as possible]
Upgrade TEKU from 23.4.0 to 23.6.0 using eth-docker stack.
Downgrade back to 23.4.0 or 23.5.0 both behave normally.
**Expected behavior:** [What you expect to happen]
No change in the validation process
**Actual behavior:** [What actually happens]
ERROR log：[message.1.txt](https://github.com/ConsenSys/teku/files/11814721/message.1.txt)

**Frequency:** [How regularly does it occur?]
Always with bad attestation performance but only log ERROR after running for a while (an hour also). 
### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`] 23.6.0
* Java version: [`java -version`] java-17
* OS Name & Version: [`cat /etc/*release`] Ubuntu 22.04
* Docker Version: [`docker version`] 24.0.2
* Cloud VM, type, size: [Amazon Web Services I3-large] N/A
* Nethermind version: 1.19.2
* eth-docker version: 2.2.9.2

**Comment by StefanBratanov** [comment]
Hi, thanks for raising the issue. Will look into it. Can you confirm that downgrading helps and these issues are not there and when upgrading you see these issues periodically?

**Comment by zilm13** [comment]
@phd2018eth could you please provide logs since the start of the epoch (since around 2023-06-16 16:02 your time) both for Teku and Nethermind. It may help in investigation

**Comment by phd2018eth** [comment]
> Hi, thanks for raising the issue. Will look into it. Can you confirm that downgrading helps and these issues are not there and when upgrading you see these issues periodically?

confirm

**Comment by phd2018eth** [comment]
> @phd2018eth could you please provide logs since the start of the epoch (since around 2023-06-16 16:02 your time) both for Teku and Nethermind. It may help in investigation

Sorry, the older containers are removed when I relaunched the services. I only have that part of the logs saved.

**Comment by StefanBratanov** [comment]
Hi @phd2018eth , are you sure you are not running two validator clients simulatenously somehow when upgrading? Have you performed upgrades using `eth-docker` before?

```
2023-06-16 16:03:20.576 ERROR - Refusing to sign attestation:  source epoch (599224) is safe, target epoch (599225) is unsafe.  Previously signed source epoch 599222, target epoch 599225
```

This error basically means you have already signed an attestation for a validator for the given target epoch. It is a definite no-no to do double signing, since this could result in slashing.

**Comment by StefanBratanov** [comment]
Also @phd2018eth this could potentially happen in case of long reorgs or state regenerations when running low on resources. What `-Xmx` parameter you run Teku with? `6g` is advised for mainnet, but for Gnosis, it could be better to run with `7g` because of the faster slot times.

**Comment by phd2018eth** [comment]
> Hi @phd2018eth , are you sure you are not running two validator clients simulatenously somehow when upgrading? Have you performed upgrades using `eth-docker` before?
> 
> ```
> 2023-06-16 16:03:20.576 ERROR - Refusing to sign attestation:  source epoch (599224) is safe, target epoch (599225) is unsafe.  Previously signed source epoch 599222, target epoch 599225
> ```
> 
> This error basically means you have already signed an attestation for a validator for the given target epoch. It is a definite no-no to do double signing, since this could result in slashing.

No question about it. It seemed failing to follow the chain then try to catch up then conflicts happen. As I have detailed in the original report, the exception won't happen right away after upgrading. It will run appearing normal initially, then attestation performance deteriorates for some time. Then the exception would occur after an hour.

**Comment by phd2018eth** [comment]
> Also @phd2018eth this could potentially happen in case of long reorgs or state regenerations when running low on resources. What `-Xmx` parameter you run Teku with? `6g` is advised for mainnet, but for Gnosis, it could be better to run with `7g` because of the faster slot times.

8g, but it's indeed a slow machine with an old 4-core cpu.  Does 23.6.0 require significantly more resources?

**Comment by phd2018eth** [comment]
Just tried to upgrade to 23.6.1 with -Xmx10g. This time the exception appeared earlier on, but then recovered and works fine so far.  Then later on again after some empty blocks. The complete log file is attached.
 
[gnosis_teku23.6.1.log](https://github.com/Consensys/teku/files/11999901/gnosis_teku23.6.1.log)

**Comment by StefanBratanov** [comment]
> Just tried to upgrade to 23.6.1 with -Xmx10g. This time the exception appeared earlier on, but then recovered and works fine so far. The complete log file is attached. [gnosis_teku23.6.1.log](https://github.com/Consensys/teku/files/11999674/gnosis_teku23.6.1.log)

Thank you. I can see one of the errors `java.lang.IllegalArgumentException: Committee information must be derived from a state no older than the previous epoch.` comes from a code path that was changed, so will see what could be the effect.

**Comment by phd2018eth** [comment]
Just updated with more logs with another exception later on.  But unlike the previous run with 23.6.0 and 8g heap, it is able to recover and perform decent, so I will keep it running in this mode. Thanks for looking into it.

**Comment by rolfyone** [comment]
how is Gnosis on 23.8.0? It should improve further...

**Comment by rolfyone** [comment]
Closing due to no follow up comments - please feel free to re-raise or re-open...
