### ISSUE TITLE
Failed to load public keys from Web3Signer URL when TLS enabled

### ISSUE THREAD

**Issue by jleeh** [Consensys-Incorporated/teku#7301]
### Description
When using the Web3Signer with Teku and specifying a URL to load public keys from, when TLS is enabled Teku will fail to load the public keys due to a SSL exception:
```
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

When the public keys are explicitly defined in the argument rather than the URL, Teku will correctly boot. As seen in the attached logs, Teku will state that the external signer is reachable but throw an exception upon the retrieval of public keys.

[validator.log](https://github.com/ConsenSys/teku/files/11848741/validator.log)

### Steps to Reproduce (Bug)
- Run Web3Signer with TLS enabled
- Run Teku with Web3Signer enabled and `--validators-external-signer-public-keys` set to a https URL 

**Expected behavior:** Teku will fetch all public keys from Web3Signer

**Actual behavior:** Exception is thrown

**Frequency:** Always, at boot

### Versions (Add all that apply)
* Software version: Teku 23.5.0 & 23.6.0, Web3Signer 23.5.0 & 23.6.0
* Java version: Java version built into container `consensys/teku:23.6.0`

**Comment by tbenr** [comment]
Hi @jleeh , this seems like a misconfiguration to correctly establish a TLS connection toward `https://eth-goerli-web3signer.eth-goerli-web3signer.svc.cluster.local:9000`

In particular what is missing is the trust store where to look for certificates to trust CA root\intermediaries of the certificate exposed by your `eth-goerli-web3signer.eth-goerli-web3signer.svc.cluster.local`.

you need to specify a trusted store via `--validators-external-signer-truststore`  and `--validators-external-signer-truststore-password-file` (https://docs.teku.consensys.net/reference/cli/subcommands/voluntary-exit#validators-external-signer-truststore) 

a full tutorial on how to configure TLS to operate with an external signer is here:
https://docs.teku.consensys.net/tutorials/configure-external-signer-tls

**Comment by jleeh** [comment]
Hey @tbenr, thanks for the response.

Both ` --validators-external-signer-truststore` and `--validators-external-signer-truststore-password-file` are specified. To be specific, external signing works when the public keys are literally defined in `--validators-external-signer-public-keys`, but not when the URL is given.

For example, this validator is from the Teku using web3signer but with the keys defined:
https://goerli.beaconcha.in/validator/0xabc21bf57dfc4cab9f31cd6924b82d89aa102c88deb0b56dafaf5642c3532639d02531b84427eca41036e09bd483d0ba#attestations

Working:
```
--validators-external-signer-public-keys=0xabc21bf57dfc4cab9f31cd6924b82d89aa102c88deb0b56dafaf5642c3532639d02531b84427eca41036e09bd483d0ba,0xab6e5323bf76d6cd36d7cb1c4eac5d309bf92c04ae50ebb95cf642a70d2fc7e9900cb265f3973fa8965d9c631e7c3a72,0x8ea38b64bbfdc81e0eaf8fa80c21db76c1546567598d9eba55fc729a12f3cc752f4f35398caf0ed80baa7d0099367a46,0xb0baa498ae3fe6b0201d074748575d4d71f6109ba7ef1a51d8ce18b10f6cfccbcbe001818fa046ba701907fff43cdfc4,0x993cde4d1e15d1428041a0bbceb0a499cfdaf46be47aee8bd0d710270ddd1344104a67e916d765f5e7b860ff8c28e3c0,0xaab0b1a353901c910753038153e628a78caa14b1aba2d04cc1a235010a3c2f12b5a3463c82cb70bf51b17bec381de4cc,0xb7663fc1f8ce9f2c7087cdc81e646106b54de2d7e311c0e58afef79488a68f677b4da220c99dff8b53f5392f2bcf9332,0x85d84349118ef30b6bd589c116320d085246572832f01253e1b0a1b2ea5046a13f1739619130c4c54b2921c0d6568b9e,0xaf1e65ad026e2f7d8db7bc09f8592dc84d892c698e94dacea4a0db9dd353dd308ceb8ba1c2bd5e29e8746a847347837a,0x91f58f1065c9b6e66e3de59f6663265e392a23736490b3b50db4b9acc82e697319337dbcd422ecc01d9e2a8c3fb335f6
```

Not working:
```
--validators-external-signer-public-keys=https://eth-goerli-web3signer.eth-goerli-web3signer.svc.cluster.local:9000/api/v1/eth2/publicKeys
```

**Comment by jleeh** [comment]
I haven't looked at Java for a long time, but it appears to me that the public key loader is calling the URL directly with a plain Jackson ObjectMapper, outside of the ExternalSigner client:
https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/PublicKeyLoader.java#L64

So that won't have context of any of the specified certificates unlike the instantiated [ExternalSigner](https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/signer/ExternalSigner.java) client.

**Comment by tbenr** [comment]
@jleeh I see your point now. And seems like you're right.

Could you try as a workaround to set the default JVM trust store by setting this environment variable in the VC context?
```bash
TEKU_OPTS='-Djavax.net.ssl.trustStore=/path/to/truststore -Djavax.net.ssl.trustStorePassword=<password>'
```
Please specify the same trust store you are referring with `--validators-external-signer-truststore` and set the password like the content of the file pointed by `--validators-external-signer-truststore-password-file`

**Comment by tbenr** [comment]
to be more exact:
```bash
TEKU_OPTS='"-Djavax.net.ssl.trustStore=/path/to/truststore" "-Djavax.net.ssl.trustStorePassword=<password>"'
```

**Comment by jleeh** [comment]
@tbenr I just rolled that change but it unfortunately broke TLS with the beaconchain endpoint as that's also https:
```
Failed to retrieve network spec from beacon node endpoint 'https://<sensitive>/'.
Details: Error communicating with Beacon Node API: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by tbenr** [comment]
@jleeh ouch. I'm working on a fix. I'll keep you posted.

**Comment by tbenr** [comment]
@jleeh our CI is currently building and about to deploy a new docker `develop` image. It would be nice if you could test it in your environment.
You have to essentially set `--validators-external-signer-public-keys=external-signer`

**Comment by jleeh** [comment]
Thanks for the quick fix @tbenr, can confirm that it's working!

I'm sure this is known already, but I had to update the beaconclient node to the same develop version as there seems to be a breaking change that was causing the validator to error with:
```
Failed to retrieve network spec from beacon node endpoint 'https://<sensitive>/'.
Details: Missing value for spec constant 'MAX_REQUEST_BLOCKS'
```

Will keep an eye out for a new release with the fix for this issue. Thanks again.

**Comment by tbenr** [comment]
@jleeh Great. Thanks for testing it out!

Yes the 23.6.1 VC requires BN version 23.6.1 too. It is mentioned in the release notes.
