### ISSUE TITLE
/expected_withdrawals endpoint timing out

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#7316]
### Description

We have had some report of `/expected_withdrawals` method timing out.

From Reddit:

> I am making a series of calls to the /expected_withdrawals endpoint on my teku full node. I've noticed that this endpoint works less than 50% of the time, often timing out before returning any results. The more recent the stateroot I try, the worse the performance. Has anyone else encountered this? What would be some potential causes. My node is fully managed by an institutional grade service and sees no issues with other RPC endpoints. Are there any other implementations of the beacon chain client that have this endpoint? I know lighthouse has yet to integrate it yet.

**Comment by rolfyone** [comment]
do we have more context about what's being queried for this to time out? eg. is it head+1 etc?

**Comment by rolfyone** [comment]
no information to go on, closing.
