### ISSUE TITLE
Prevent inactivity leak info log to burst multiple messages

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7329]
I noticed during some interop tests that it is possible that teku prints  several inactivity logs:

<img width="1116" alt="image" src="https://github.com/Consensys/teku/assets/15999009/fc939e2e-1c5e-4bbb-a8cd-cfc40335d336">

I restarted an interop network after keeping it down for a while. I think It processed several (empty) epochs in a row.

We should have logic to print this message within a certain interval to avoid spamming logs.

**Comment by rolfyone** [comment]
there's a throttling logger i believe...
