### ISSUE TITLE
Update the teku-detailed grafana and release

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7367]
- need to add `storage_memory_epoch_states_cache_size{instance=~"$system"}` to `In memory storage` objects
 
any other issues to address while we're looking at the board?

Need to make sure we're basing it on the last release, not what's currently in grafana, as I believe we've lost the BLS queue...

**Comment by lucassaldanha** [comment]
I have created the following page with information on the process to update our dashboards and to publish a dashboard to Grafana: https://consensyssoftware.atlassian.net/wiki/spaces/PEG/pages/398948598128/Teku+Grafana+Dashboards

**Comment by lucassaldanha** [comment]
Added new metric to panel: https://github.com/Consensys/observability-tenants/pull/468

And published new version of panel to Grafana.
