### ISSUE TITLE
Add LRU cache for `BlobSidecars`

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7369]
This is for discussing the opportunity to have a BlobSidecars cache. Since recent blocks are cached in Store, we don't have anything like that for blobs.

At the moment `RecentChainData` exposes retrieveBlobSidecars only for testing purpose, and serves all blobs on disk, not only a "recent" set. Which is a bit counterintuitive.

Currently in `CombinedChainDataClient` we tap into historicalChainData (storage channel) without querying recentChanData first (like we do for blocks, to get the recent cached or hot blocks).

Since blobs have no distinction between hot and finalized storage, we could in any case follow the same flow of blocks, but tapping into recentChainData just for accessing the LRU cache and fallback to `historicalChainData` access storage.

We could also feed this LRU cache when when we store blobs on block import (fc::onBlock) these recent blobs are more likely to be requested byroot via RPC (and even queried via beacon endpoint). Not sure if we should feed this cache every time we access Storage querying Blobs (beacon API, RPC requests).

**Comment by zilm13** [comment]
fixed (implemented) with #7593
