### ISSUE TITLE
rewards api change for attestations

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7414]
https://github.com/ethereum/beacon-APIs/pull/340

**Comment by rolfyone** [comment]
we should flag this as breaking given we've no longer got the rewards api under experimental.

**Comment by courtneyeh** [comment]
The `total_rewards` change does not appear to be a massive change. This will require changing how the response is aggregated. The inactivity seems to be included in the `RewardComponent`, meaning it should not be too hard to get. I expect this task should take 1 or 2 days assuming no surprises.

The `ideal_rewards` change appears to be a bit more complex. It will also require more investigation and will need changes in the ideal calculation. This may take a couple of days and potentially an extra day for texting.

Estimate is a week for completing all. Could be broken up into two tickets for the two different tasks.

**Comment by rolfyone** [comment]
just to clarify, the api PR said 
```
This PR adds the following fields to the AttestationsRewards response:

A inactivity field to both ideal_rewards and total_rewards.
A inclusion_delay field to ideal_rewards
```
so we're saying the update to `total_rewards` is relatively easy meaning the inactivity field in just total_rewards? which bridges both the items in part 1 of ticket
And the bulk of unknowns is the changes (inactivity in ideal rewards, and inclusion_delay in ideal_rewards)

Is that correct?

**Comment by courtneyeh** [comment]
That is what I expect based on the previous investigation.

**Comment by courtneyeh** [comment]
This issue has been broken down into #7553 and #7554
