### ISSUE TITLE
Deposit Data Object Deviation from v0.7.1 spec

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#742]
The `UnsignedLong merkle_tree_index` value is added to the `Deposit` object. The index i9s used to order the `Deposit` object in the `MerkleTree`.

Long term this value should be removed.

**Comment by cemozerr** [comment]
I think the variable is named `index`. Similar to BeaconState (a spec data structure) and BeaconStateWithCache (client specific data structure we have to keep information such as cache), here we can make another class that inherits Deposit (spec data structure) class, and keeps extra information such as `index`. This way it would be less confusing going forward to know what's inside a Deposit class object.
