### ISSUE TITLE
Teku Maven artifacts issues when including as dependency

### ISSUE THREAD

**Issue by Nashatyrev** [Consensys-Incorporated/teku#7444]
### Description

When using different versions of `io.spring.dependency-management` gradle plugin including any Teku module artifact as a maven dependency to a gradle build the following error may occur:

- version `1.1.0`: no errors
- version `1.1.1`: build fails with the following error (plugin issue [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/365))
```
> Task :startScripts FAILED
2 actionable tasks: 1 executed, 1 up-to-date
Errors occurred while build effective model from C:\Users\Admin\.gradle\caches\modules-2\files-2.1\tech.pegasys.teku.internal\unsigned\23.8.0\c0e66a134880efb10f2882a13b6cfd8d69b2fe7f\unsigned-23.8.0.pom:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':startScripts'.
> Error while evaluating property 'relativeClasspath' of task ':startScripts'
   > Cannot invoke "io.spring.gradle.dependencymanagement.org.apache.maven.model.Model.getGroupId()" because "effectiveModel" is null
```
- version `1.1.3`: build succeeds bu the the following error(s) are printed:
```
Errors occurred while building effective model from C:\Users\Admin\.gradle\caches\modules-2\files-2.1\tech.pegasys.teku.internal\unsigned\23.8.0\c0e66a134880efb10f2882a13b6cfd8d69b2fe7f\unsigned-23.8.0.pom:
	'dependencies.dependency[tech.pegasys.teku.internal:unsigned:23.8.0]' for tech.pegasys.teku.internal:unsigned:23.8.0 is referencing itself. in tech.pegasys.teku.internal:unsigned:23.8.0
```

The above errors indicate another problem: all dependencies of `test-fixture` scope are also picked up when only module runtime dependencies are required. Here is some more insights: https://stackoverflow.com/questions/69877418/why-does-every-pom-file-published-by-gradle-has-a-self-referential-dependency

### Steps to Reproduce (Bug)
run `gradle build` for the following `build.gradle`

```gradle
plugins {
    id 'io.spring.dependency-management' version '1.1.1'
    id "java"
    id "application"
}

repositories {
        mavenCentral()
        maven { url "https://artifacts.consensys.net/public/teku/maven/" }
}

dependencies {
    implementation 'tech.pegasys.teku.internal:unsigned:23.8.0'
}
```

**Expected behavior:** 

Successful build
Only required artifacts are imported

**Actual behavior:** 

Build fails with the errors described above (depending on the plugin version)

**Frequency:** Always

### Versions (Add all that apply)
* Software version: 23.8.0
* Java version: 17
* OS Name & Version: Windows

### Related issues:
Libp2p PR: https://github.com/libp2p/jvm-libp2p/pull/306

**Comment by Nashatyrev** [comment]
CC @StefanBratanov

**Comment by tbenr** [comment]
The fix should be something like https://github.com/Consensys/teku/commit/c91265d55379e82a380e006ea6301ed85c5d3005

I tested it against a local maven repo and I now get:

``` text
Execution failed for task ':startScripts'.
> Error while evaluating property 'relativeClasspath' of task ':startScripts'.
   > Could not resolve all files for configuration ':runtimeClasspath'.
      > Could not find com.google.code.findbugs:jsr305:.
        Required by:
            project : > tech.pegasys.teku.internal:unsigned:develop > com.google.guava:guava:32.1.2-jre
      > Could not find org.checkerframework:checker-qual:.
        Required by:
            project : > tech.pegasys.teku.internal:unsigned:develop > com.google.guava:guava:32.1.2-jre
      > Could not find com.google.errorprone:error_prone_annotations:.
        Required by:
            project : > tech.pegasys.teku.internal:unsigned:develop > com.google.guava:guava:32.1.2-jre
```

@Nashatyrev might be good enough?

**Comment by tbenr** [comment]
sorry @courtneyeh I was curious about this and I ended up spending a bit on it so I wanted to share what I did.

on my local teku i run
```
./gradlew publishToMavenLocal
```

and on a test project i used:

```
plugins {
    id 'io.spring.dependency-management' version '1.1.1'
    id 'java'
    id "application"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.9.1')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'tech.pegasys.teku.internal:unsigned:develop'
}

test {
    useJUnitPlatform()
}
```

**Comment by tbenr** [comment]
using version `1.1.3` it builds

**Comment by courtneyeh** [comment]
Thanks @tbenr is this okay to close now?

**Comment by tbenr** [comment]
@courtneyeh I did additional checks and seems to work, at least locally.
Opened a PR: https://github.com/Consensys/teku/pull/7468
