### ISSUE TITLE
Public keys not loading from URL warning

### ISSUE THREAD

**Issue by courtneyeh** [Consensys-Incorporated/teku#7462]
### Description
Set command line option `validators-external-signer-public-keys` as a valid link, get a warning in the logs. 

```
WARN  | ValidatorClientService | Failed to load public keys from URL http://localhost:19000
```

But still says the external signer is reachable. So the link must be working.

```
INFO  | teku-status-log | External signer is reachable at http://localhost:19000
```

### Steps to Reproduce (Bug)

**Expected behavior:** No warning and for the public keys to load.

**Actual behavior:** Fails to load public keys from URL.

**Frequency:** 100%

**Comment by rolfyone** [comment]
we should keep digging into this one further to get a better understanding and hopefully resolve this issue

**Comment by courtneyeh** [comment]
Wording around command line option --validators-external-signer-public-keys=http://localhost:9900/publicKeys was misleading due to not having the correct format /api/v1/eth2/publicKeys. Referring to the endpoint as /publicKeys instead of the public keys endpoint also furthered the confusion around what the endpoint should look like.

The issue began when Teku logged that http://localhost:9900/ is reachable, however the user was unable to debug why the validators-external-signer-public-keys was invalid because it was the same format as the example given.

The Teku docs have been updated to help fix this.
