### ISSUE TITLE
Remove unnecessary items from memory

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#747]
As an implementer, I want to remove unnecessary items from memory so that our memory pool doesn't grow indefinitely. These include:

- [x] Processed blocks before the finalized block.

- [x] Processed states before the finalized block.

- [x] Processed attestations that are older than an epoch.

**Comment by jrhea** [comment]
@cemozerr is this complete?

**Comment by cemozerr** [comment]
Attestations are the only part that we haven't implemented due to uncertainty around AttesterSlashings.
