### ISSUE TITLE
/eth/v1/node/peers endpoint does not include ENR

### ISSUE THREAD

**Issue by angusscott** [Consensys-Incorporated/teku#7473]
### Description
The /eth/v1/node/peers endpoint does not include the optional ENR field as part of the response. This is available on other consensus consensus clients (Prysm). 

https://github.com/Consensys/teku/blob/23.8.0/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/node/GetPeers.java#L60

### Steps to Reproduce (Bug)
Perform a curl request to /eth/v1/node/peers endpoint

### Versions (Add all that apply)
* Software version: 23.8.0

**Comment by angusscott** [comment]
@tbenr as requested

**Comment by tbenr** [comment]
@angusscott thanks for rising!

**Comment by rolfyone** [comment]
This will ultimately need to be thought out a bit.
ENR comes from the discovery library, which is fairly easy to get, but we need to make a link between our libp2p peers and the ENR data we're receiving. We haven't really built this out, so while we might get to it at some stage, it's likely to be a bit of a job, and we would only really be using that field for the peers endpoint, so we'll have to weigh this up against other priorities.
We had a go at it and it got messy so we're having to shelve it for a while and will revisit at some point.
