### ISSUE TITLE
CLI option rest-api-host-allowlist not working properly.

### ISSUE THREAD

**Issue by cheatfate** [Consensys-Incorporated/teku#7507]
### Description

`curl` (`192.168.1.10`) unable to get response from `Teku` beacon node (`192.168.1.100`) which was started with `--rest-api-host-allowlist=192.168.1.10, 127.0.0.1, localhost`.

But 

`curl` (`192.168.1.10`) was able to receive response from `Teku` beacon node (`192.168.1.100`) which was started with `--rest-api-host-allowlist=192.168.1.100, 127.0.0.1, localhost`.

I think filter which sits inside `Teku` beacon node incorrectly compares local address with `allow-list` instead of comparing remote address.

### Versions
* Software version:
```
teku/v23.9.0/linux-x86_64/-na-openjdk64bitservervm-java-17
```
* Java version:
```
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1, mixed mode)
```
* OS Name & Version:
```
ArchLinux
```

**Comment by tbenr** [comment]
Hi @cheatfate 
the allowlist is a feature to validate the host header variable coming with the request. it is not suppose to validate source ip\host.

https://portswigger.net/web-security/host-header

see the `Validate the Host header` section.
