### ISSUE TITLE
[API] create the state endpoint under beacon

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7525]
https://github.com/ethereum/beacon-APIs/pull/353

currently the initial-state is read from debug/state, but we're moving it.

The old one should only be deprecated, but the new one is basically identical.

**Comment by courtneyeh** [comment]
**Estimate: 1 day**

**Involved:**
* Create new `/eth/v1/beacon/states/{state_id}` based on old `/eth/v2/debug/beacon/states/{state_id}` API
* Deprecate the old `debug` API
* Add unit testing
* Likely add an acceptance test and update some integration testing

**Comment by lucassaldanha** [comment]
Waiting for resolution on https://github.com/ethereum/beacon-APIs/pull/357
