### ISSUE TITLE
Research: CrosslinkCommittee Data Structure Does Not Exist in the Spec

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#755]
### Description
As an implementor, I want to know what the CrosslinkCommittee data structure is used for in Artemis, as it does not exist in the Beacon Chain spec. Having documentation explaining the data structures that exist in Artemis that are not mentioned in the spec is beneficial in maintaining the client.

### Acceptance Criteria
* The usage of CrosslinkCommittee is understood, and the name is updated as appropriate for the v0.7.1 version of the spec.

**Comment by jrhea** [comment]
Is this still an issue @schroedingerscode ?

**Comment by ajsutton** [comment]
Thankfully CrosslinkCommittee was nixed from the spec.
