### ISSUE TITLE
`23.9.1` minor release introduces a breaking change in LevelDB dependency

### ISSUE THREAD

**Issue by Neurone** [Consensys-Incorporated/teku#7552]
### Description
Using Ubuntu 20.04, when upgrading from `23.9.0.` to `23.9.1`, Teku reports a LevelDB error and stops.

If I run from scratch, without using an existing DB, Teku reports the same error and starts a new DB with RocksDB instead of using the existing LevelDB database.

```sh
Teku failed to start: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [Can't load library: /tmp/leveldbjni@14976013304512060760/libleveldbjni-1.8.so, /tmp/leveldbjni@14976013304512060760/libleveldbjni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/leveldbjni@14976013304512060760/libleveldbjni.so), no leveldbjni64-1.8 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib, no leveldbjni-1.8 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib, no leveldbjni in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
```

Updating Ubuntu to the latest updates from the official repos does not solve the problem.

I searched online, and having `GLIBC 2.33` on Ubuntu 20.04 seems complex. The current repo seems stuck to `GLIBC 2.31`.

I noticed the LevelDB native library in the Teku repo was updated from `0.2.0` to `0.3.0` in the `23.9.1` release with PR #7504

Using `23.9.1`, I downgraded that native library back to `0.2.0`, and everything seems to work fine - both unit tests and the execution of Teku on an existing DB.

```sh
❯ ./gradlew
...
BUILD SUCCESSFUL in 9m 13s
539 actionable tasks: 537 executed, 2 up-to-date
```

### Steps to Reproduce (Bug)

- Use Ubuntu `20.04`
- Run Teku `23.9.0`, and stop it
- Run Teku `23.9.1` on the same DB

**Expected behavior:**

Teku continues to work as expected before the upgrade.

**Actual behavior:**

Teku reports the following error and stops.

```sh
Teku failed to start: java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [Can't load library: /tmp/leveldbjni@14976013304512060760/libleveldbjni-1.8.so, /tmp/leveldbjni@14976013304512060760/libleveldbjni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/leveldbjni@14976013304512060760/libleveldbjni.so), no leveldbjni64-1.8 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib, no leveldbjni-1.8 in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib, no leveldbjni in java.library.path: /usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
```

**Frequency:**

Always

### Versions (Add all that apply)
* Software version: `teku/v23.9.1/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17`
* Java version: `openjdk version "17.0.8.1" 2023-08-24 - OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu120.04) - OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu120.04, mixed mode, sharing)`
* OS Name & Version: `Ubuntu 20.04.3 LTS (Focal Fossa)`
* Docker Version: `N/A`
* Cloud VM, type, size: `N/A`

**Comment by tbenr** [comment]
Thanks @Neurone for opening! We realized the issue today as well.
We are in the process of releasing a new leveldb lib moving back GLIBC requirements.
Reference to https://github.com/Consensys/leveldbjni-native/pull/12 for the upcoming version.

**Comment by tbenr** [comment]
@Neurone do you have the chance to compile https://github.com/Consensys/teku/pull/7557 so we can double-check that the problem is solved?

**Comment by Neurone** [comment]
Hi @tbenr , yep, it works. I tried that branch and tests pass and also Teku starts correctly over the old LevelDB.
