### ISSUE TITLE
Holesky Needed

### ISSUE THREAD

**Issue by yagolgmesol** [Consensys-Incorporated/teku#7582]
Hello, I want to test validator creation and funding using custom made smart contract, for that purpose I need 9600 ETH if possible

0x3F7521340a9eC62eA20f74eEE75A0C0C4e581ec7
As soon as everything works!

**Comment by rolfyone** [comment]
https://holesky.ethpandaops.io/
There's a faucet listed, but we don't really have 9600 eth, and the faucet will only give a small amount of eth at a time.
It might be worth asking on ethereum discord on the testnets channel as a starting point...

**Comment by rolfyone** [comment]
closing for now as we don't have the funds to assist.
