### ISSUE TITLE
Execution client considered syncing even though eth_syncing is false

### ISSUE THREAD

**Issue by RatanRSur** [Consensys-Incorporated/teku#7592]
### Description
I believe teku isn't performing attestation duties because it's still in the `AWAITING_EL` state. See screenshot for `eth_syncing` result, endless `Syncing`, and `NewPayload` behavior.

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
  * teku/v23.10.0/linux-x86_64/-na-openjdk64bitservervm-java-21
* EL version
  * erigon version 2.52.1-13fa1297
<img width="1726" alt="Screenshot 2023-10-13 at 12 31 39 PM" src="https://github.com/Consensys/teku/assets/4733314/11855b63-3fc7-4fac-ac8d-a3ff2ec2935e">

**Comment by tbenr** [comment]
Hello @RatanRSur, thanks for opening the issue.
I'd like to double-check node is not responding SYNCING when in the engine apis call. Hitting the `eth_syncing` API is not a guarantee of this.

If your node is still in that state, could you enable tracing on teku via: 

```
curl -X 'PUT' \
  'http://localhost:5051/teku/v1/admin/log_level' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "level": "TRACE",
  "log_filter": [
    "tech.pegasys.teku.ethereum.executionclient.methods.EngineForkChoiceUpdatedV2",
    "tech.pegasys.teku.ethereum.executionclient.methods.EngineNewPayloadV2"
  ]
}'
```
?

In the meantime I'll check if there is a race condition that could leave teku in a "always-waiting-el" state.

**Comment by tbenr** [comment]
It would be nice to double check the response to 
```
curl -X 'GET' \
  'http://localhost:5051/eth/v1/beacon/headers/head' \
  -H 'accept: application/json'
```

I'm interested to check the metadata `execution_optimistic` value.

<img width="722" alt="image" src="https://github.com/Consensys/teku/assets/15999009/33a06aed-8b78-4a37-8d12-3cdd901feb7c">

**Comment by RatanRSur** [comment]
```
{
  "data": {
    "root": "0x3dd7a44f5f8a7c24379d1a28579d39cda8b50c0439f2c5c5ab923fde579912e3",
    "canonical": true,
    "header": {
      "message": {
        "slot": "7553963",
        "proposer_index": "604961",
        "parent_root": "0xffa770b3b70566b47fdd03e4956b590a6af342ef9603bb2bd547190b23232773",
        "state_root": "0x4c1aec0c7cd0b79e695f5740c6c1877c1bef0a71ade3f0f3c22fa5a7a9fc84c4",
        "body_root": "0x161d6e9a774bc18deef70673df12ecdf9867a422c3767fd8861520820cb802f7"
      },
      "signature": "0x824fd665e846f53f81a998a6f1adc7314ba39c7607f2dae2521e756bef84ba5be6f8f4d9dfdfe5e7a4143b2cef935227141c3ae27730cc6377eee92cfa91585a9da940af141b54e21488e818948ae70153da9188290bf5aac3f607515d5e6326"
    }
  },
  "execution_optimistic": true,
  "finalized": false
}
```

**Comment by RatanRSur** [comment]
[fork-trace.log](https://github.com/Consensys/teku/files/12919077/fork-trace.log)
some logs after enabling tracing

**Comment by tbenr** [comment]
@RatanRSur 
EL is returning `SYNCING` to forkChoice calls.

```
2023-10-16 11:55:37.597-04:00 | pool-4-thread-2981 | TRACE | EngineForkChoiceUpdatedV2 | Response engine_forkchoiceUpdatedV2(forkChoiceState=ForkChoiceState{headBlockRoot=0x4516e00f2bf14d4b0d8ca5e508a220f9ba1e273b90c11a41593839c10a8b1ea7, headBlockSlot=7553976, headExecutionBlockHash=0x4c793d4e109c9a4ccd50c8ebd7f4fa093b04c4e8d3b5d07c5796d010a3fda1aa, safeExecutionBlockHash=0xa2f971f757382a053b1eb98a93df955b59899e742e5071aeb360ffec66b17506, finalizedExecutionBlockHash=0x38b7b85d1db9391158bbbac8d3a54cbb2c095fe9025b989c91b0e7e614d26544, isHeadOptimistic=true}, payloadAttributes=Optional.empty) -> ForkChoiceUpdatedResult{payloadStatus=PayloadStatus{status=Optional[SYNCING], latestValidHash=Optional.empty, validationError=Optional.empty, failureCause=Optional.empty}, payloadId=Optional.empty}
```

and the newPayload are `ACCEPTED` and not `VALID`. So consistent with the EL in syncing state.

So to me Teku is working as expected, also showing `"execution_optimistic": true,` which is consistent.

**Comment by RatanRSur** [comment]
Ok, must be an erigon issue then. Closing unless something new comes up.
