### ISSUE TITLE
Teku does not import slots on startup if EL is offline

### ISSUE THREAD

**Issue by quickchase** [Consensys-Incorporated/teku#7600]
### Description
Teku does not import any slots if started when EL is stopped. I don't think Teku should just completely stop importing slot data and fall further and further behind just because the EL is currently stopped?

I believe that in the case of Lighthouse they still import slots they just change it to "Optimistic"

The reason this is a problem for my particular setup is that I have tasks that during the upgrade process ensure that the CL and EL are importing slots/blocks after upgrade. In the case of the EL, it will not import new blocks without a CL, so I have to start the CL first. In the case of Teku it hangs/fails because Teku appears "stuck"

### Steps to Reproduce (Bug)
Stop EL and Teku
Start Teku

**Expected behavior:** [What you expect to happen]
Teku should import slots regardless of the EL status

**Actual behavior:** [What actually happens]
Teku just stops importing slots

```text
16:39:21.295 ERROR - Execution Client request failed. Make sure the Execution Client is online and can respond to requests.
16:39:24.001 INFO  - Syncing     *** Target slot: 3478397, Head slot: 3478320, Remaining slots: 77, Connected peers: 64
16:39:36.001 INFO  - Syncing     *** Target slot: 3478398, Head slot: 3478320, Remaining slots: 78, Connected peers: 65
16:39:48.001 INFO  - Syncing     *** Target slot: 3478399, Head slot: 3478320, Remaining slots: 79, Connected peers: 65
16:39:51.336 ERROR - Execution Client request failed. Make sure the Execution Client is online and can respond to requests.
16:40:00.001 INFO  - Syncing     *** Target slot: 3478400, Head slot: 3478320, Remaining slots: 80, Connected peers: 65
16:40:12.001 INFO  - Syncing     *** Target slot: 3478401, Head slot: 3478320, Remaining slots: 81, Connected peers: 66
16:40:21.381 ERROR - Execution Client request failed. Make sure the Execution Client is online and can respond to requests.
16:40:24.001 INFO  - Syncing     *** Target slot: 3478402, Head slot: 3478320, Remaining slots: 82, Connected peers: 66
16:40:36.001 INFO  - Syncing     *** Target slot: 3478403, Head slot: 3478320, Remaining slots: 83, Connected peers: 65
16:40:39.100 INFO  - Loading deposits up to Eth1 block 4499840
16:40:41.622 INFO  - Execution Client is responding to requests again after a previous failure
16:40:41.644 INFO  - Execution Client syncing complete. Continuing to sync beacon chain blocks
16:40:48.006 INFO  - Syncing     *** Target slot: 3478404, Head slot: 3478369, Remaining slots: 35, Connected peers: 65
16:40:49.931 INFO  - Syncing completed
16:40:55.676 WARN  - Request for eth1 deposit logs from 10000 blocks failed. Retrying with a smaller block range.
16:41:04.007 INFO  - Slot Event  *** Slot: 3478405, Block: a546514e17d0e3a1a4099a36d701d78f93d25961527c58da928841db3fbafab3, Justified: 108699, Finalized: 108698, Peers: 67
```

As you can see from the above, Head slot is stuck, until I start the EL then it starts importing slots.

**Frequency:** [How regularly does it occur?]
Always

### Versions (Add all that apply)
* Software version: [23.10.0](https://github.com/Consensys/teku/releases/tag/23.10.0)
* Java version: [`openjdk 17.0.8.1 2023-08-24`]
* OS Name & Version: [`Ubuntu 22.04.3 LTS`]

**Comment by tbenr** [comment]
Hi @quickchase, thanks for opening the issue.

This is the intended behaviour. Optimistic sync can be activated only if EL is online and actively responding `SYNCING` to the consensus client forkchoice calls. The reason why this is the case is that, even if the EL is syncing it will do some basic validation to the execution payloads and returning `ACCEPTED` (instead of `VALID`) during its syncing process.

So I think you should adapt your deployment assuming this behaviour.
