### ISSUE TITLE
Investigate regular failure of BlobSidecarsByRangeIntegrationTest

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#7617]
As part of https://github.com/Consensys/teku/pull/7609 `BlobSidecarsByRangeIntegrationTest.requestBlobSidecars_shouldReturnCanonicalBlobSidecarsOnDenebMilestone()` was failing regularly on the line `assertThat(peer.getOutstandingRequests()).isEqualTo(0);`. 

That line was commented out in order for the test to pass on CI and the condition afterwards were still passing but it needs to be investigated why this assertion fails. It would be most likely related to the increase of the size of the blobs given that minimal uses the same FIELD_ELEMENTS_PER_BLOB as mainnet.

**Comment by mehdi-aouadi** [comment]
@StefanBratanov This is normally fixed, right? Should we close it?

**Comment by StefanBratanov** [comment]
Ah yes, thanks. Closing that now. It has been fixed as part of https://github.com/Consensys/teku/pull/7627
