### ISSUE TITLE
FR: Enable checkpoint-sync-url and initial-state=genesis.ssz defined in the same process

### ISSUE THREAD

**Issue by barnabasbusa** [Consensys-Incorporated/teku#7643]
### Description
[Detailed description of the problem and the impact it has]

It would be great to have an additional flag created for checkpoint syncing, instead of reusing the --initial-state flag that is used for bootstrapping a custom network. 

When I want to enable checkpoint sync for a teku node, I always have to make sure that the original init-state flag is removed. 

It would be great to be able to define both: 

```sh
--initial-state=genesis.ssz
--checkpoint-sync-url=https://checkpoint-sync-endpoint
```

Where it would use the initial state only if there is no checkpoint sync endpoint is defined, or if checkpoint sync endpoint flag is not present.

**Comment by lucassaldanha** [comment]
The desired behaviour can be achieved using `--genesis-state` and `--initial-state` flags.

When only `initial-state` is defined, Teku will try to load that as checkpoint sync and, if it fails to load the state, an error will be thrown.

When both `initial-state` and `genesis-state` are defined, Teku will try checkpoint sync from `initial-state` first, but if this fails it will fallback into the genesis defined at `genesis-state`.

When only `genesis-state` is used, Teku will try to load that as a custom genesis state and, if it fails, an error will be thrown.

References:
- https://docs.teku.consensys.net/reference/cli#genesis-state
- https://docs.teku.consensys.net/reference/cli#initial-state
