### ISSUE TITLE
Enable VC crashing on 0 keys loaded

### ISSUE THREAD

**Issue by jmcruz1983** [Consensys-Incorporated/teku#7647]
Regarding PR [5145](https://github.com/Consensys/teku/pull/5145) validators are allow to run with 0 loaded keys,
Could you add an CLI argument to enable the previous behaviour of crashing / restarting when 0 keys loaded?
Thanks

Logs:
```
023-11-02 12:46:03.668 WARN  - Failed to load public keys from URL http://blabla
```

**Comment by rolfyone** [comment]
Thanks for raising, will put it on the list.

**Comment by courtneyeh** [comment]
Hey @jmcruz1983

That PR refers to treating an empty string `””` as an empty list `[]`, and filtering out the empty strings from the list. Validators have always been able to run with no keys loaded, or an empty list.

Were you referring to wanting to ensure that keys have been loaded from the endpoint? This has not been an option up yet, however, just trying to understand what you were meaning.

Let us know, thanks!

**Comment by courtneyeh** [comment]
As a team we should decide whether an empty string should be treated as a valid empty list. And if by accepting it here, we should also be accepting it everywhere else in the CLI array options for consistency.

**Comment by jmcruz1983** [comment]
> Hey @jmcruz1983
> 
> That PR refers to treating an empty string `””` as an empty list `[]`, and filtering out the empty strings from the list. Validators have always been able to run with no keys loaded, or an empty list.
> 
> Were you referring to wanting to ensure that keys have been loaded from the endpoint? This has not been an option up yet, however, just trying to understand what you were meaning.
> 
> Let us know, thanks!

Hi @courtneyeh 
we do load keys from external signer with `--validators-external-signer-public-keys` argument.

About CLI argument, i was thinking about having something like `--crash-on-zero-keys-loaded` or similar argument, 
that would exit the validator when zero keys loaded (with return code different to zero) and that would allow the validator to restart and retry loading then key in next runtime,

In addition to `--crash-on-zero-keys-loaded` argument, you could even provide something like `--empty-key-delimiter` with default to `""` to be able to configure what to understand as an empty list (this would be optional to keep things simpler).

Thanks
