### ISSUE TITLE
Holesky `fork_schedule` endpoint problem

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7675]
Reported by an user on discord.

It seems like there is a small bug in teku `23.10.0` beacon node. When running on holesky, the fork schedule endpoint (/eth/v1/config/fork_schedule) gives the following response:

```json
{
   "data":[
      {
         "previous_version":"0x01017000",
         "current_version":"0x01017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x02017000",
         "current_version":"0x02017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x03017000",
         "current_version":"0x03017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x03017000",
         "current_version":"0x04017000", 
         "epoch":"256"
      }
   ]
}
```

While it should be:
```json
{
   "data":[
      {
         "previous_version":"0x01017000",
         "current_version":"0x01017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x01017000",
         "current_version":"0x02017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x02017000",
         "current_version":"0x03017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x03017000",
         "current_version":"0x04017000", 
         "epoch":"256"
      }
   ]
}
```

**Comment by rolfyone** [comment]
i can double check but i think this is how the ref tests require the fork_schedule... i vaguely recall something in this area and trying to make it better, then breaking reftests....

**Comment by rolfyone** [comment]
this is basically because 
https://github.com/ConsenSys/teku/commit/93ddfe9ff98cee3701b57c9417b1d2279358cdd8

thoughts @tbenr ?

**Comment by tbenr** [comment]
So I can confirm that I did that to pass reference tests: https://github.com/Consensys/teku/pull/7693

Let me try to ask the question: should the response be instead the following?

```json
{
   "data":[
      {
         "previous_version":"0x03017000",
         "current_version":"0x03017000",
         "epoch":"0"
      },
      {
         "previous_version":"0x03017000",
         "current_version":"0x04017000", 
         "epoch":"256"
      }
   ]
}
```

EDIT: thinking twice, it won't reflect the actual config in which we specify all the previous forks at epoch 0..

looks like reference tests are consistent with this idea while API are not.

**Comment by tbenr** [comment]
This is a [spike](https://github.com/Consensys/teku/pull/7693) with a potential fix, WDYT @rolfyone?

**Comment by rolfyone** [comment]
we got specifically asked by a previous ticket to list all forks, not just active forks...

potentially this one: https://github.com/Consensys/teku/issues/6648

**Comment by tbenr** [comment]
Ah I see. Btw the spike doesn't change that.
