### ISSUE TITLE
Update the block production workflow to use the block V3 API by default

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#7779]
### Description
Currently the block production have two APIs: block v2 and block v3. In the current block V3 flow, the `blinded` param (similar to the block V2 API) is hard coded and set to true. The following changes are required to make the block V3 API the default:
- [x] #7889
  - [x] #7835
  - [x] Remove the hard coded blinded param in block V3
- [x] Enabled block V3 as the default
- [x] Test compatibility among CLs
- For next release:
- [x] Remove the deprecated block V2 methods - done via (#8508 and #8504)
- [x] Remove the `--Xblock-v3-enabled` option which is used to use block V3 apis (#8511)

These are the last steps of https://github.com/Consensys/teku/issues/7390

**Comment by gfukushima** [comment]
Closing this as last PR was merged today.
