### ISSUE TITLE
Support Basic Auth credentials in Web3signer URL

### ISSUE THREAD

**Issue by ArchiFleKs** [Consensys-Incorporated/teku#7796]
### Description
currently using Web3signer with TLS + http basic auth. This work fine with Lighthouse and Prysm when using an URL format of https://user:pass@web3signer_url but in TEKU it seems that the HTTP lib used does not support passing the basic auth credentials. 

```
2023-12-07 09:10:36.137 ERROR - External signer is currently not reachable at https://w3s:PASSWORD@web3signer.sepolia.domain.com
```

When logged into the pod I can query it fine.

Is there any way to support this easily in TEKU ? Or am I missing something ? Right now I'm passing this as en ENV var, I could try via config or args but not sure it would change anything.

### Steps to Reproduce (Bug)
Set the env vars TEKU_VALIDATORS_EXTERNAL_SIGNER_URL.

**Expected behavior:** [What you expect to happen]

Connection is successful

**Actual behavior:** 

Unable to connect

**Frequency:** 

Constant

### Versions (Add all that apply)
* Software version: 23.08
* Java version: jdk17
* OS Name & Version: Ubuntu 22.04 but running in Kubernetes via Docker image
* Docker Version: No docker but containerd
* Cloud VM, type, size: Bare metal

**Comment by StefanBratanov** [comment]
Hi, thanks for raising an issue. I looked at the code and it looks like we don't support basic auth for the external signer. We will look into adding that functionality.

**Comment by ArchiFleKs** [comment]
Could you point to where it is in the code ?

**Comment by StefanBratanov** [comment]
> Could you point to where it is in the code ?

Yeah, it's here -> https://github.com/Consensys/teku/blob/master/validator/client/src/main/java/tech/pegasys/teku/validator/client/loader/HttpClientExternalSignerFactory.java
