### ISSUE TITLE
23.12.0 cannot sync Holesky from genesis

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7822]
### Description

Attempting to sync Holesky from genesis with `--ignore-weak-subjectivity-period-enabled=true` will nonetheless load a checkpoint. I believe this makes it impossible to use Teku as an archive node on Holesky.

On mainnet, it does not show this behavior.

### Steps to Reproduce (Bug)

Run without `--checkpoint-sync-url` and with `--ignore-weak-subjectivity-period-enabled=true` on Holesky

Logs:
```
eth-docker-devel-consensus-1  | 2023-12-13 09:24:25.485 INFO  - Initializing storage
eth-docker-devel-consensus-1  | 2023-12-13 09:24:25.493 INFO  - Storage initialization complete
eth-docker-devel-consensus-1  | 2023-12-13 09:24:25.495 WARN  - Ignoring weak subjectivity period check (--ignore-weak-subjectivity-period-enabled). Syncing from outside of the weak subjectivity period is considered UNSAFE.
eth-docker-devel-consensus-1  | 2023-12-13 09:24:25.497 INFO  - Loading initial state from https://checkpoint-sync.holesky.ethpandaops.io/eth/v2/debug/beacon/states/finalized
eth-docker-devel-consensus-1  | 2023-12-13 09:24:54.706 INFO  - Loaded initial state at epoch 17073 (state root = 0x30d76b13a970d8dbc31f64b2e45452e74ca9a4ef4a89933c6a92bd93a59f5980, block root = 0x835305d6f02a0c1ab069f9d7a845c8a547c543ca03d819ed86a85831c069fa36, block slot = 546336).  Please ensure that the supplied initial state corresponds to the latest finalized block as of the start of epoch 17073 (slot 546336).
```

### Versions (Add all that apply)
* Software version: 23.12.0

**Comment by rolfyone** [comment]
You could definitely do it, just need to specify `--initial-state` and pass in `https://checkpoint-sync.holesky.ethpandaops.io/eth/v2/debug/beacon/states/genesis`... Holesky has been starting at finalized by default so you'd need to manually specify both flags.

**Comment by yorickdowne** [comment]
You’re saying this is by design? Teku doesn’t ship with the Holesky genesis state included? That makes it kinda tough to run an archive node there, unless I’m missing something

**Comment by rolfyone** [comment]
genesis route is served by checkpointz, and teku points to the github repo for its reference, but we're moving away from suggesting syncing from genesis as a rule (weak subjectivity). 

If we have weak-subjectivity is on and we have sync from genesis by default, then you'd *always* get an error unless you specify to sync from finalized which would be significantly impacting most users when they try to initialise...

Mainnet still has initial-state genesis, so if you do try to startup on mainnet now, it'll fail unless you specify to ignore weak-subjectivity, which I don't love the UX of...

**Comment by yorickdowne** [comment]
Yes that’s what I compared it to, mainnet.

What is your recommended way to sync a Teku archive node? On mainnet I have the built-in genesis, but on Holesky you’d recommend to load the state from the URL you showed?

**Comment by rolfyone** [comment]
so on mainnet it looks like:
```
teku \
    --ignore-weak-subjectivity-period-enabled \
    --data-storage-mode archive \
    --initial-state=https://sync-mainnet.beaconcha.in/eth/v2/debug/beacon/states/genesis \
    --network=mainnet
```
could optionally specify `--initial-state=https://sync-mainnet.beaconcha.in/eth/v2/debug/beacon/states/genesis
`, but equally its default so you could strike that out.
equally with --network - defaults to mainnet so implicit...
so ultimately this simplifies to 
```
teku \
    --ignore-weak-subjectivity-period-enabled \
    --data-storage-mode archive
```

On holesky, its got a version from github of the genesis state still, but its initial state doesn't default to genesis, so you'd basically be going:
```
teku \
    --ignore-weak-subjectivity-period-enabled \
    --data-storage-mode archive \
    --network holesky \
    --initial-state=https://checkpoint-sync.holesky.ethpandaops.io/eth/v2/debug/beacon/states/genesis
```
and all these options aren't defaulting so they'll all be specified.

Sometimes we just start an archive node from normal finalized state, which means it's not back to genesis, and then we can not bother specifying the ignore or the initial state, but equally we can't query states earlier than when we initialized in this scenario... In that case it's just:
```
teku \
    --data-storage-mode archive \
    --network holesky
```
Again though, just to reemphasise, this is an archive node that doesn't go back to genesis, so this may not be what some (most?) people would desire from an archive node... The first holesky example is closer to what you're asking...

**Comment by yorickdowne** [comment]
Thank you. I have some special-casing to do then, so this works.

I assume Sepolia is similar, with an initial state needed? Where is that kept?

**Comment by rolfyone** [comment]
Sepolia defaults its initial state to genesis, as does goerli...

So both would need that ignore-weak-subjectivity flag if you wanted an archive from genesis...

We could change holesky to be consistent, or think outside the box... do you think holesky having a default intial-state of finalized is a bad idea? It just seems we spend a lot of time adivising people syncing from genesis isn't a great plan, then we go and make it default... Unfortunately currently for most networks we don't have a truly 'independent' checkpointz so we werent sure about enshrining specific checkpointz in, it's a hard topic weirdly.

**Comment by yorickdowne** [comment]
Archive nodes are a niche use case. I can special-case this for Holesky. Thanks! Closing this issue. I’ll use it for reference and make the change.
