### ISSUE TITLE
`--checkpoint-sync-url` missing from `--help`

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#7823]
### Description

23.12.0 does not have `--help` text for `--checkpoint-sync-url`

Log:
```
ubuntu@eth-testing:~/eth-docker-devel$ docker run --rm teku:local --help | grep url
      --validators-external-signer-url=<NETWORK>
```

### Versions (Add all that apply)
* Software version: 23.12.0

**Comment by rolfyone** [comment]
Hey thanks for raising - a trivial fix but annoying, sorry about the inconvenience!

Usage can be found at : https://docs.teku.consensys.io/get-started/checkpoint-start

**Comment by RogerHKW** [comment]
Dear Consensys team,

What is the difference between
`--checkpoint-sync-url` and `--initial-state`? The documentation is unclear, at least to non-experts like me.

**Comment by rolfyone** [comment]
Very little.
If you set checkpoint-sync-url, you override initial-state and genesis-state flags.

Equally, you could set `--initial-state=checkpointz.url` and it would be basically equivalent.

The `checkpoint-sync-url` flag is used by several clients, and ultimately will end up loading the deposit-snapshot-url (we reverted that change in 23.12.1).

The initial-state flag won't be removed most likely, so if you're using it that will be fine to continue to use (it only does anything on initialization of the database anyway, same as checkpoint-sync-url for the most part).
