### ISSUE TITLE
Add `builder_boost_factor` to blockV3 validator API

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#7851]
### Description
See appropriate blockV3 API section: https://github.com/ethereum/beacon-APIs/blob/master/apis/validator/block.v3.yaml#L46-L78
The feature is similar to our [validators-builder-bid-challenge-percentage](https://github.com/Consensys/teku/pull/6878) but since the change validator will be able to set it via blockV3 call for any block production request. 
We should also decide whether blockV3 overrides BN settings (if any).

**Comment by tbenr** [comment]
related to https://github.com/Consensys/teku/issues/7779

**Comment by tbenr** [comment]
@zilm13 I think values coming from VC should override BN value, which I consider it as a default.
VC represents the staker, which have the ultimate right to decide how the flow should behave.
