### ISSUE TITLE
Teku 23.12.0 crashes on stop after ~2 weeks of uptime

### ISSUE THREAD

**Issue by daichuanwu21** [Consensys-Incorporated/teku#7854]
### Description
Stopping the Teku client version 23.12.0 after more than 1 week of uptime can sometimes result in a coredump.

```
Dec 31 12:21:36 server systemd[1]: Stopping Teku Consensus Layer Client service...
Dec 31 12:21:36 server teku[791]: Teku is shutting down
Dec 31 12:21:36 server teku[791]: 2023-12-31 12:21:36.649 INFO  - Stopping Javalin ...
Dec 31 12:21:36 server teku[791]: 2023-12-31 12:21:36.661 INFO  - Stopped Server@4d629976{STOPPING}[11.0.17,sto=0]
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: # A fatal error has been detected by the Java Runtime Environment:
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: #  SIGSEGV (0xb) at pc=0x00007fcd450ec2dc, pid=791, tid=1361266
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: # JRE version: OpenJDK Runtime Environment Zulu17.46+19-CA (17.0.9+8) (build 17.0.9+8-LTS)
Dec 31 12:21:36 server teku[791]: # Java VM: OpenJDK 64-Bit Server VM Zulu17.46+19-CA (17.0.9+8-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Dec 31 12:21:36 server teku[791]: # Problematic frame:
Dec 31 12:21:36 server teku[791]: # C  [libleveldbjni.so+0x502dc]
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to //core.791)
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: # An error report file with more information is saved as:
Dec 31 12:21:36 server teku[791]: # /var/opt/ethereum/teku/hs_err_pidteku.log
Dec 31 12:21:36 server teku[791]: 2023-12-31 12:21:36.778 INFO  - Stopped ServerConnector@312a2402{HTTP/1.1, (http/1.1)}{127.0.0.1:5051}
Dec 31 12:21:36 server teku[791]: 2023-12-31 12:21:36.831 INFO  - Stopped i.j.j.@463669fb{/,null,STOPPED}
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server teku[791]: # If you would like to submit a bug report, please visit:
Dec 31 12:21:36 server teku[791]: #   http://www.azul.com/support/
Dec 31 12:21:36 server teku[791]: # The crash happened outside the Java Virtual Machine in native code.
Dec 31 12:21:36 server teku[791]: # See problematic frame for where to report the bug.
Dec 31 12:21:36 server teku[791]: #
Dec 31 12:21:36 server systemd-coredump[1361301]: Process 791 (java) of user 980 dumped core.
Dec 31 12:21:37 server systemd[1]: teku.service: Main process exited, code=dumped, status=6/ABRT
Dec 31 12:21:37 server systemd[1]: teku.service: Failed with result 'core-dump'.
Dec 31 12:21:37 server systemd[1]: Stopped Teku Consensus Layer Client service.
Dec 31 12:21:37 server systemd[1]: teku.service: Consumed 2w 4d 9h 35min 26.261s CPU time.
```

The uptime for Teku in this case was actually 2w 3d 22h 47min 39.514s, a little lower than the consumed CPU time systemd is reporting in the logs.

Since it seems like a database issue, I've checked the SMART logs on my SSD and found that it claims to have had no read failures so far. Just in case its worth mentioning, the underlying filesystem Teku is running on is XFS, and my kernel version is `5.14.0-362.13.1.el9_3.x86_64`.

### Steps to Reproduce (Bug)
I am running the Teku client through systemd with 5G of memory allocated. I've also configured it to use jemalloc 5.2.1 through LD_PRELOAD.

**Expected behavior:**
Teku shuts down without reporting any errors or crashing.

**Actual behavior:**
Teku crashes complaining about what appears to be an issue with the database library.

**Frequency:**
Very rare. I've never seen Teku crash like this on shutdown through 6 months of upgrades.

### Versions (Add all that apply)
* Software version: `teku/v23.12.0/linux-x86_64/zulu-java-17`
* Java version:
```
openjdk 17.0.9 2023-10-17 LTS
OpenJDK Runtime Environment Zulu17.46+19-CA (build 17.0.9+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.46+19-CA (build 17.0.9+8-LTS, mixed mode, sharing)
```
* OS Name & Version:
```
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
Red Hat Enterprise Linux release 9.3 (Plow)
Red Hat Enterprise Linux release 9.3 (Plow)
```
* Docker Version: N/A
* Bare metal (my own hardware)

**Comment by StefanBratanov** [comment]
Hi thanks for reporting, by any chance, would you have access to the error report file? /var/opt/ethereum/teku/hs_err_pidteku.log

**Comment by daichuanwu21** [comment]
Sure! Here it is:

~~[hs_err_pidteku.log](http://redacted)~~

I hope I didn't upload anything sensitive, please let me know if I did and I'll remove this comment. I could email the crash log to you folks if necessary.

**Comment by StefanBratanov** [comment]
Thank you. It's not sensitive. No worries. We will investigate. Initial thought is some rare hardware incompatibility with the database we use (leveldb), but will get back to you.

**Comment by daichuanwu21** [comment]
Thanks for looking into it! Since we're considering hardware issues, I should mention that the server I run Teku on does not have ECC RAM, so we can't rule out the possibility that this could be some kind of single-event upset.

**Comment by rolfyone** [comment]
I'd probably suggest running a memtest and seeing if it flags an error. It's very unusual to get core dumps in this way but I've seen it from faulty memory modules...

**Comment by tbenr** [comment]
Hi, we are closing this. Please reopen if you can share something more.
