### ISSUE TITLE
Disable Peer Exchange in PRUNE message

### ISSUE THREAD

**Issue by diegomrsantos** [Consensys-Incorporated/teku#7860]
### Description
As described here https://github.com/ethereum/consensus-specs/issues/3500, Peer Exchange isn't relevant to the Ethereum Network and `PRUNE` messages sent by Teku can have up to 9 KB and 210 peer IDs due to Peer Exchange.

The options to limit the number of peers sent and accepted in `PRUNE` messages have been fixed and improved in this PR https://github.com/libp2p/jvm-libp2p/pull/336.

We suggest 2 phases for the implementation:

1. A new jvm-libp2p version containing the mentioned PR is released. Teku is updated to use this version and set `maxPeersSentInPruneMsg` to `zero`. For compatibility reasons, `maxPeersAcceptedInPruneMsg` is set to a high value, potentially to the max Integer value.
2. After some time has passed and all Teku nodes are expected to have been updated, `maxPeersAcceptedInPruneMsg` is also set `zero`.

### Steps to Reproduce (Bug)
Inspect `PRUNE` messages sent by Teku over time.

**Expected behavior:** 
Phases:
1. Teku doesn't send peer IDs in `PRUNE` messages, but accept it from other peers.
2. Teku doesn't send peer IDs in `PRUNE` messages and doesn't accept it from other peers.

**Actual behavior:** 
Teku sends peer IDs in `PRUNE` messages and accept it from other peers.

**Frequency:** 
Often

### Versions (Add all that apply)
* Software version: Not sure, but probably the latest and previous ones.
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by StefanBratanov** [comment]
Thank you @diegomrsantos for raising this.:) We will look into releasing a new version of the `libp2p` and will take it from there.

**Comment by StefanBratanov** [comment]
@diegomrsantos just to confirm both phases have been implemented

**Comment by diegomrsantos** [comment]
@StefanBratanov thank you for that.
