### ISSUE TITLE
[Feature]Support GraalVM native

### ISSUE THREAD

**Issue by GrapeBaBa** [Consensys-Incorporated/teku#7935]
### Description
Is there a plan to support graalvm native？

**Comment by rolfyone** [comment]
We don't have a current plan to support GraalVM. Is there a reason we should add this to our plan that we're not aware of? Feel free to pitch it...

**Comment by lucassaldanha** [comment]
Closing as not planned.

**Comment by totoCZ** [comment]
in case anyone finds this, here is a Dockerfile to run under GraalVM (JVM mode)
I haven't noticed any performance benefits in this mode, but compiled could be better.
Maybe I will try to see how hard it is to build in the future.

```
FROM container-registry.oracle.com/graalvm/jdk:23 as graalvm

RUN $JAVA_HOME/bin/jlink \
         --add-modules ALL-MODULE-PATH \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /javaruntime


FROM consensys/teku:latest

USER root
RUN rm -rf /opt/java/openjdk
COPY --from=graalvm /javaruntime $JAVA_HOME
USER teku

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
```
