### ISSUE TITLE
Setup nightly acceptance tests

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#7954]
### Description
Acceptance tests step time increases with each new test added and it's going uncomfortable to run it on every commit. So we'd better limit acceptance tests number which are run on every commit to most important and run others once in every day.
So, we need:
- separate folder for nightly acceptance tests, which are not run in CI acceptance-test task
- gradle task to run tests from this folder
- add it to CI flow for nightly runs
- configure some reporting, so we don't miss when it fails
- have a way to run them on CI explicitly or automatically for release candidate

First candidates for these tests will be:
`CapellaUpgradeAcceptanceTest`, `DenebUpgradeAcceptanceTest`, disabled test cases from `ValidatorSlashingDetectionAcceptanceTest`

**Comment by rolfyone** [comment]
prefer not to do a 'nightly' kind of AT unless we have to.
