### ISSUE TITLE
We should be able to start a node with a non-finalized checkpoint

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#7961]
In period of non finalization, to recover from bad situation we should be able to support that.

**Comment by tbenr** [comment]
When deneb activates, if network is not finalizing for more than the DA window (18 days), the node could not be able to retrieve blobs and won't be able to sync from that old finalized state.

**Comment by lucassaldanha** [comment]
@tbenr after team discussion do you think we still need this?

**Comment by tbenr** [comment]
Double-checked and we are good. We won't try to retrieve any blobs outside DA when starting from an older finalized state.
Closing.
