### ISSUE TITLE
java.util.concurrent.CompletionException: org.iq80.leveldb.DBException: Corruption: corrupted compressed block contents

### ISSUE THREAD

**Issue by wga22** [Consensys-Incorporated/teku#7973]
### Description
Teku stopped consensus and node validation activities on 2024-02-11 15:51:36.393-05:00

### Steps to Reproduce (Bug)
Unknown. - logs attached.

**Expected behavior:** [What you expect to happen]
Teku to gracefully attempt to work around the issue; perhaps by restarting or working around the issue by restoring data to new DB nodes from a peer.

**Actual behavior:** [What actually happens]
System goes into failure mode and never recovers without restart (reboot)

**Frequency:** [How regularly does it occur?]
The issue occurred repeatedly with each "systemctl service restart", however was resolved by a reset/reboot of the server.

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
24.1.0
* Java version: 
 openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-123.10)
OpenJDK 64-Bit Server VM (build 17.0.9+9-Ubuntu-123.10, mixed mode, sharing)
* OS Name & Version: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=23.10
DISTRIB_CODENAME=mantic
DISTRIB_DESCRIPTION="Ubuntu 23.10"
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
* Docker Version: NA
* Cloud VM, type, size: NA
[teku_2024-02-11.log](https://github.com/Consensys/teku/files/14238959/teku_2024-02-11.log)

**Comment by tbenr** [comment]
@wga22  Thanks for opening the issue.
This is appears to be a low level issue (in particular, related to compression library used by levelDB library to compact data on disk) that could be also triggered by some hardware issues.
Did teku recovered from this after restarting? Has this occurred again?
Have you tried to check memory health using tools like `memtest86`?
I'm not sure if this could be triggered by a malfunction on IO (SSD).
Can you also check system logs if there are signs of issues?

**Comment by wga22** [comment]
The issue occurred repeatedly with each "systemctl service restart", however was resolved by a reset/reboot of the server.  I do not see evidence of a hardware error, and the NVME drive is relatively new, however I cannot rule it out.

**Comment by tbenr** [comment]
@wga22 which CPU architecture are you running on?

**Comment by wga22** [comment]
-cpu
          description: CPU
          product: AMD Ryzen 5 5560U with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: 10
          bus info: cpu@0
          version: 25.80.0
          serial: Unknown
          slot: FP6
          size: 4042MHz
          capacity: 4062MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pa              t pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good               nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe               popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefet              ch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pst              ate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clf              lushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero               irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid deco              deassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid               overflow_recov succor smca fsrm cpufreq
          configuration: cores=6 enabledcores=6 microcode=173015053 threads=12




description: Mini PC
    product: SER (Default string)
    vendor: AZW
    version: Default string
    serial: D55603JF80285
    width: 64 bits
    capabilities: smbios-3.3.0 dmi-3.3.0 smp vsyscall32
    configuration: boot=normal chassis=mini family=Default string sku=Default string uuid=03000200-0400-0500              -0006-000700080009
  *-core
       description: Motherboard
       product: SER
       vendor: AZW
       physical id: 0
       version: V2.0
       serial: Default string
       slot: Default string
     *-firmware
          description: BIOS
          vendor: American Megatrends International, LLC.
          physical id: 0
          version: FP655U508
          date: 03/31/2023
          size: 64KiB
          capacity: 16MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppynec int13floppyto              shiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int14serial int17printer               int10video acpi usb biosbootspecification uefi
     *-memory
          description: System Memory
          physical id: b
          slot: System board or motherboard
          size: 64GiB

**Comment by tbenr** [comment]
@wga22 Is the issue happened again? Thinking about closing the issue for now.

**Comment by wga22** [comment]
I have moved to a hosted solution.  I was unable to get the Nethermind / Teku combo stable on 64GB AMD Ryzen 5 5560U setup. Issue can be closed.
