### ISSUE TITLE
Update Javalin to version 6

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#7982]
Javalin has been updated to a new major version 6

Migration guide: https://javalin.io/migration-guide-javalin-5-to-6

**Comment by lucassaldanha** [comment]
It looks like they are considering releasing v7 this fall (Sep 2024). So we better upgrade this to v6 soon otherwise the migration path v5 -> v7 might be harder :)

btw they will continue to support v5 with security fixes.
