### ISSUE TITLE
Reference Test Implementation for BLS

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#803]
Using `artemis/eth-reference-tests/src/test/java/pegasys/artemis/reference/ssz_static/core/ssz_minimal_zero.java` as a style template implement the following reference tests.

Changes should be made in the `v0.8.0-integration` branch. Failing tests are ok, as long as the implementation is made. Some code changes may be necessary for tests to pass which is out of scope.

- [x] `bls`

   - [x] `bls/aggregate_pubkeys/aggregate_pubkeys.java`

   - [x] `bls/aggregate_sigs/aggregate_sigs.java`

   - [x] `bls/msg_hash_g2_compressed/g2_compressed.java`

   - [x] `bls/msg_hash_g2_uncompressed/g2_uncompressed.java`

   - [x] `bls/priv_to_pub/priv_to_pub.java`

   - [x] `bls/sign_msg/sign_msg.java`

**Comment by shahankhatch** [comment]
#835
