### ISSUE TITLE
Upgrade `it.unimi.dsi:fastutil`

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#8038]
When upgrading `it.unimi.dsi:fastutil` from 8.5.12 to 8.5.13, there are failing tests in `AggregateAttestationValidatorTest`. Need to investigate what causes those failings and fix them and only then upgrade.

Captured while working on https://github.com/Consensys/teku/pull/8037

**Comment by tbenr** [comment]
maybe due to this https://github.com/vigna/fastutil/commit/0f5313322a701e20a4268ec1bf6406addcf696cb ?

**Comment by tbenr** [comment]
seems like we need to wait 8.5.14, which seems to be on the way

**Comment by StefanBratanov** [comment]
Good catch. Looks like it.
