### ISSUE TITLE
Occasional failure to public blocks with `/eth/v2/beacon/blocks`

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#8039]
### Description

When publishing blocks via the `/eth/v2/beacon/blocks` endpoint on holesky I occasionally see the following error:

```
2024-03-01 19:43:03.420 WARN  - Block (and blob sidecars) publishing skipped due to broadcast validation result GOSSIP_FAILURE for slot 1118315
```

Other consensus nodes publish the block without issue.

**Frequency:**

Intermittent.  

### Versions

`teku/v24.2.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17`

**Comment by tbenr** [comment]
Thanks @mcdee for opening.
This happens because the API is defined to apply GOSSIP validation rules, and in that case seems like the relay published the block significantly earlier than returning the payload via getPayload to the teku node. So early that teku received the block via p2p before obtaining the response, so the GOSSIP equivocation check failed.

Is my analysis compatible with your logs?

In my opinion we should have a `broadcast_validation` to `none` and default to it instead of defaulting to `gossip`.

Connects to the discussion happening here: https://discord.com/channels/595666850260713488/710831784991916072

**Comment by mcdee** [comment]
When you say "GOSSIP equivocation", surely there would be no equivocation check to fail because the blocks would have the same data.  Or am I misunderstanding here?

**Comment by tbenr** [comment]
No, I'm talking about the exact same data. When teku sends the signed blinded block to the relay (https://ethereum.github.io/builder-specs/#/Builder/submitBlindedBlock), the relay reconstruct the full block and it will (in parallel?):
1. gossip it
2. returning it as a response

so teku can "see" the full block via p2p before receiving it from the response.

**Comment by mcdee** [comment]
Sure, but in that situation which gossip rule is causing a REJECT?

**Comment by tbenr** [comment]
We consider IGNORE as a validation failure (equivocation check is an IGNORE). And I think this matches the builder use-case, but not exactly a "normal" validating node.

**Comment by mcdee** [comment]
I don't think that other consensus nodes do this, and I'm not sure why IGNORE would translate to a rejection.  It seems reasonable to return a 200 in this situation.

I imagine that this is the same situation for MEV relays, as it's possible for one relay to broadcast a block ahead of time of another.  And the actual equivocation checks should catch the situation where there are multiple different blocks for the same slot.

**Comment by tbenr** [comment]
I see what you mean.
We never considered the block root in the implementation of this rule:

```
- _[IGNORE]_ The block is the first block with valid signature received for the proposer for the slot, `signed_beacon_block.message.slot`.
```

Which is what we do as "equivocation check", and we always have consider slot-proposerIndex pair to apply the check.

**Comment by mcdee** [comment]
Yeah, you could argue that seeing the same block twice means that the block is _still_ "the first block with valid signature received for the proposer..." and so this check should pass in this situation.

But the practical reality is that with the current setup you're going to have a number of "failed to publish block" messages show up in the logs, and likely a number of people flagging this as an issue.

**Comment by tbenr** [comment]
I always thought that it was more an issue for normal validators, but as you previously said, it could be an issue for builders too. I'll give another round of thoughts tomorrow.

**Comment by tbenr** [comment]
Hey @mcdee, I merged a PR that should solve the problem. We should start a release today\tomorrow so it will be in a release pretty soon.
Thanks for bringing this up.
