### ISSUE TITLE
Reference Test Implementation for Epoch Processing

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#804]
Using `artemis/eth-reference-tests/src/test/java/pegasys/artemis/reference/ssz_static/core/ssz_minimal_zero.java` as a style template implement the following reference tests.

Changes should be made in the `v0.8.0-integration` branch. Failing tests are ok, as long as the implementation is made. Some code changes may be necessary for tests to pass which is out of scope.

- [ ] `epoch_processing`

   - [ ] `crosslinks/crosslinks_mainnet.java`

   - [ ] `crosslinks/crosslinks_minimal.java`

   - [ ] `final_updates/final_updates_mainnet.java`

   - [ ] `final_updates/final_updates_minimal.java`

   - [ ] `justification_and_finalization/justification_and_finalization_mainnet.java`

   - [ ] `justification_and_finalization/justification_and_finalization_minimal.java`

   - [ ] `registry_updates/registry_updates_mainnet.java`

   - [ ] `registry_updates/registry_updates_minimal.java`

   - [ ] `slashings/slashings_mainnet.java`

   - [ ] `slashings/slashings_minimal.java`

**Comment by shahankhatch** [comment]
#835
