### ISSUE TITLE
[SPIKE] Add MEV support for Obol distributed validators

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#8059]
The registration of a validator in the Builder API required its public key. When using Obol DVT, each validator node has a share of the public key.

To be able to register successfully using the Builder API, we need a way to configure the aggregate public key (what the network sees).

Related to #6851

For reference: https://github.com/sigp/lighthouse/issues/3444

**Comment by rolfyone** [comment]
resolved @lucassaldanha ?

**Comment by lucassaldanha** [comment]
Yes, so far we haven't had an issue with it.
