### ISSUE TITLE
Reference Test Implementation for Operations

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#806]
Using `artemis/eth-reference-tests/src/test/java/pegasys/artemis/reference/ssz_static/core/ssz_minimal_zero.java` as a style template implement the following reference tests.

Changes should be made in the `v0.8.0-integration` branch. Failing tests are ok, as long as the implementation is made. Some code changes may be necessary for tests to pass which is out of scope.

- [ ] `operations`

   - [ ] `attestation/attestation_mainnet.java`

   - [ ] `attestation/attestation_minimal.java`

   - [ ] `attester_slashing/attester_slashing_mainnet.java`

   - [ ] `attester_slashing/attester_slashing_minimal.java`

   - [ ] `block_header/block_header_mainnet.java`

   - [ ] `block_header/block_header_minimal.java`

   - [ ] `deposit/deposit_mainnet.java`

   - [ ] `deposit/deposit_minimal.java`

   - [ ] `proposer_slashing/proposer_slashing_mainnet.java`

   - [ ] `proposer_slashing/proposer_slashing_minimal.java`

   - [ ] `transfer/transfer_minimal.java`

   - [ ] `voluntary_exit/voluntary_exit_mainnet.java`

   - [ ] `voluntary_exit/voluntary_exit_minimal.java`

**Comment by shahankhatch** [comment]
#835
