### ISSUE TITLE
POST to `/eth/v1/builder/blinded_blocks` missing header

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#8061]
### Description

When teku calls the endpoint `/eth/v1/builder/blinded_blocks` it does not supply an `Eth-Consensus-Version` header, as per the specs at https://ethereum.github.io/builder-specs/#/Builder/submitBlindedBlock

### Versions (Add all that apply)

```
teku/v24.2.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17
```

**Comment by rolfyone** [comment]
Thanks, we'll have a look.
