### ISSUE TITLE
Reference Test Implementation for Sanity

### ISSUE THREAD

**Issue by dangerousfood** [Consensys-Incorporated/teku#807]
Using `artemis/eth-reference-tests/src/test/java/pegasys/artemis/reference/ssz_static/core/ssz_minimal_zero.java` as a style template implement the following reference tests.

Changes should be made in the `v0.8.0-integration` branch. Failing tests are ok, as long as the implementation is made. Some code changes may be necessary for tests to pass which is out of scope.

- [ ] `sanity`

   - [ ] `blocks/sanity_blocks_mainnet.java`

   - [ ] `blocks/sanity_blocks_minimal.java`

   - [ ] `slots/sanity_slots_mainnet.java`

   - [ ] `slots/sanity_slots_minimal.java`

**Comment by shahankhatch** [comment]
#835
