### ISSUE TITLE
Append EL/CL information to user-defined graffiti

### ISSUE THREAD

**Issue by StefanBratanov** [Consensys-Incorporated/teku#8074]
In addition to #7930 even if user has specified a graffiti we can attempt to append EL/CL information if the space permits it. This will be `opt-in` feature defaulted to false e.g. `append-client-versions-to-validators-graffiti`

Some implementation ideas: https://github.com/ethereum/execution-apis/pull/517#issuecomment-1920549999

Add a graffiti versioning "mode" (single CLI option):
Example:
- CL + CL_VERSION + EL + EL_VERSION (enabled by default)
- Only CL + EL
- Nothing

If not enough space, try other modes (e.g. if adding the version does not fit, add at least CL and EL).

Padding?? (need to adjust spec)

**Comment by zilm13** [comment]
I'm thinking on
`--validators-graffitti-client-append-format`
AUTO_PADDED (default): no user graffitti - full size (20 chars), user graffitti + space + 4-20 characters of whatever left
AUTO: same without space
NAME_PADDED:  space (if user graffitti defined) + 4 chars TKBU, client names dropped if more than 32 chars
NAME: same without space
NONE: doesn't touch
Print info status line at startup which graffitti was compiled.
