### ISSUE TITLE
There is no deserializer for SszBitvector

### ISSUE THREAD

**Issue by emosamastudio** [Consensys-Incorporated/teku#8076]
### Description
I am trying to deserialize BeaconState by jsonProvider.jsonToObject. 
But it gets failed because there is no deserializer for SszBitvector.
code link: https://github.com/Consensys/teku/blob/be4dfc0e167b95fafe7aa1ed2afc605a9ddf7a72/data/serializer/src/main/java/tech/pegasys/teku/provider/JsonProvider.java#L61

**Comment by emosamastudio** [comment]
The type SszBitvector only has a serialization method, without a corresponding deserialization method. Since the justification_bits field in BeaconState is SszBitvector, an error occurs when trying to deserialize BeaconState using JsonProvider.jsonToObject(). The error message is "com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `tech.pegasys.teku.infrastructure.ssz.collections.SszBitvector` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: tech.pegasys.teku.api.schema.capella.BeaconStateCapella["justification_bits"])"

By the way, the GetStateResponseV2 seems only support verion phase0 and altair.

**Comment by rolfyone** [comment]
We've actually moved away from that provider completely and are using type definitions - Are you trying to use the JsonProvider in your project as a permanent thing? we might be better off finding a good reference for typedefs...

**Comment by emosamastudio** [comment]
Thanks for your relay, but I am still kind of confused. 
I am trying to get beacon state by "/eth/v2/debug/beacon/states/" and mapping it into BeaconSatate object by JsonProvidoer.jsonToObject(). Is there any other way I can achieve it?
Currently, I have added a deserializer for SszBitvector into JsonProvidoer and it works.
```
public class SszBitvectorDeserializer extends JsonDeserializer<SszBitvector> {
    private final int length;

    public SszBitvectorDeserializer(int length) {
        this.length = length;
    }

    public SszBitvector deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException {
        SszBitvector sszBitvector = SszBitvectorSchema.create(length).fromBytes(Bytes.fromHexString(jp.getValueAsString()));
        return sszBitvector;
    }
}
```

**Comment by rolfyone** [comment]
As an example, if you take a look at `GetStateIntegrationTest`, theres instances using `JsonUtil.parse` and parsing to state...

This is more the declarative style we're using now, rather than relying on the JsonProvider which uses a bunch of duplicated objects, as it was getting difficult to maintain a couple of years ago, so we updated our model to not require separate object definitions...

The old JsonProvider logic will be disappearing at some point, once we remove the last few references...

**Comment by rolfyone** [comment]
Assuming this context has helped, I'll close given no further information - please feel free to either reach out here or in discord if we can assist further.
