### ISSUE TITLE
deprecation warnings loading current grafana board into the latest grafana

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8091]
we should take a look at the warnings, it's probably graphs or similar that we need to update.

**Comment by lucassaldanha** [comment]
These are the panels we need to migrate:

Validator
- Attestation Performance
- Attestation Inclusion Distance (slots)
- Included Blocks


Beacon Chain
- Trailing Distance
- Participation Rate
- Peer Client Software

System
- Memory Usage
- GC Time

Queues, Executors and Caches
- Batch Signature Verification Queue Size
- Signature Verification Batch Size
- Signature Verification Batch Size

**Comment by lucassaldanha** [comment]
Panels have been updated. Will run a sanity check before a release.
