### ISSUE TITLE
 Gnosis chain got errpr: Cannot sync outside of weak subjectivity period

### ISSUE THREAD

**Issue by wetezos** [Consensys-Incorporated/teku#8120]
### Description
[Detailed description of the problem and the impact it has]
My node was originally running normally, but suddenly stopped data synchronization. 

Command:
`teku -c /home/gnosis/teku-node/teku.yaml `

I see this error message:
`02:40:37.815 INFO  - Host Configuration | Maximum Heap Size: 29.97 GB, Total Memory: 125.71 GB, CPU Cores: 32
02:40:37.815 INFO  - Rest Api Configuration | Enabled: true, Listen Address: 127.0.0.1, Port: 5053, Allow: [127.0.0.1, localhost]
02:40:37.815 INFO  - Validator Api Configuration | Listen Address: 127.0.0.1, Port 5052, Allow: [127.0.0.1, localhost]
02:40:37.987 INFO  - Storing beacon chain data in: /home/gnosis/teku-node/beacon
02:40:37.987 INFO  - Loading 0 validator keys...
02:40:37.989 INFO  - Loaded 0 Validators: 
02:40:38.445 INFO  - Initializing storage
02:40:39.720 INFO  - Storage initialization complete
02:40:39.720 WARN  - Not loading specified initial state as chain data already exists.
Teku failed to start: java.lang.IllegalStateException: Cannot sync outside of weak subjectivity period. Consider re-syncing your node using --checkpoint-sync-url or use --ignore-weak-subjectivity-period-enabled to ignore this check.

To display full help:
teku [COMMAND] --help`

### Steps to Reproduce (Bug)
[Please be as specific as possible]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [How regularly does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
`teku/v24.3.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17`
* Java version: [`java -version`]
`openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-120.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-120.04.1, mixed mode, sharing)`

* OS Name & Version: [`cat /etc/*release`]
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal`
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

**Comment by wetezos** [comment]
<img width="693" alt="image" src="https://github.com/Consensys/teku/assets/40154568/69985f66-1c06-4c99-8ba6-86ee58c41fda">

**Comment by tbenr** [comment]
Hey @wetezos , have you left the node shut down for a while? The behaviour you described is the way is intended.
For security reason, if your node remain offline for longer than the WeekSubjectivityPeriod (which varies between networks and networks conditions) you have two options:

1. wipe your database and let the node sync again from a recent checkpoint.
OR
2. add --ignore-weak-subjectivity-period-enabled and let the node sync despite the WSP.
