### ISSUE TITLE
Switch to publishBlockV2

### ISSUE THREAD

**Issue by zilm13** [Consensys-Incorporated/teku#8126]
### Description
[publishBlockV2](https://github.com/ethereum/beacon-APIs/blob/master/apis/beacon/blocks/blocks.v2.yaml) is mature enough API and we could consider switching to it on our VC if we don't need to keep V1 fallback. Otherwise we will get a lot of legacy code on switch.

There are several things worth to check before switching:
- are all BNs compatible with it? Prysm is working only with Prysm, Grandine doesn't have separate BN, so Lighthouse, Nimbus, Lodestar should be checked. Users cannot use versions prior first mainnet-deneb required release, so compatibility should be tested on this version for each BN. [Kurtosis](https://github.com/kurtosis-tech/ethereum-package) tool could help to do this. 
- required GOSSIP validation on V2. Currently we publish block in any case. Unless it's the only block published, there is no risk for validator to do this. But any bug or whatever in GOSSIP validation will prevent node from publishing block. Also there could be delay added.

**Comment by StefanBratanov** [comment]
Fixed by https://github.com/Consensys/teku/pull/8352
