### ISSUE TITLE
Invalid configuration. --ee-endpoint parameter is mandatory when Bellatrix milestone is enabled

### ISSUE THREAD

**Issue by srvint** [Consensys-Incorporated/teku#8167]
### Description
New install, followed latest setup instructions. Installed Java 17 then followed up with Teku install.

Result, Teku will not start, terminates with error:
2024-04-03 09:59:24.881-05:00 | main | FATAL | BeaconNodeCommand | Invalid configuration. --ee-endpoint parameter is mandatory when Bellatrix milestone is enabled

### Steps to Reproduce (Bug)
Run
./teku --network=mainnet --data-path=/mnt/raid0/teku --data-beacon-path=/mnt/raid0/beacon

**Expected behavior:** I expect teku to start

**Actual behavior:** Teku does not start

**Frequency:** Always

### Versions (Add all that apply)
* Software version: teku/v24.3.1+13-g9962cae259/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17
* Java version: openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)

* OS Name & Version: DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

* Docker Version: Not installed
* Cloud VM, type, size: None

**Comment by rolfyone** [comment]
Thanks for raising - can you share the guide you were following to start?

**Comment by StefanBratanov** [comment]
Hi @srvint you need to specify your execution client engine endpoint (Besu/Geth/etc...) in order to follow the chain. As @rolfyone asked, which guide did you use, because it most certainly should mention this important point?

**Comment by srvint** [comment]
I used the build instructions on the main page. https://github.com/Consensys/teku

Solved by adding the following flags.

--ee-endpoint http://localhost:8551/ --ignore-weak-subjectivity-period-enabled

**Comment by StefanBratanov** [comment]
> I used the build instructions on the main page. https://github.com/Consensys/teku
> 
> Solved by adding the following flags.
> 
> --ee-endpoint http://localhost:8551/ --ignore-weak-subjectivity-period-enabled

Got it. On the main page, there are no instructions how to start Teku (only to build it). The documentation is a better and more concise place: https://docs.teku.consensys.io/get-started/start-teku . Will close this issue. Feel free to open new one if having any further issues.
