### ISSUE TITLE
Artemis SSZ v0.8.+ Does Not Correctly Merkleize Empty Lists

### ISSUE THREAD

**Issue by schroedingerscode** [Consensys-Incorporated/teku#817]
### Description
While empty SSZ vectors are illegal types, empty SSZ lists are valid, and can be encountered in the Beacon Chain spec. As currently implemented, empty SSZ lists are not merkleized at all.

### Acceptance Criteria
* Empty SSZ lists should be merkleized per the v0.8.+ SSZ spec, instead of being skipped. This will likely require multiple static functions to handle merkleizing List<UnsignedLong>, List<SimpleOffsetSerializable>, etc. instead of the more generic implementation as currently exists.

**Expected behavior:** Hash tree root of an empty list should return the merkle root according to the algorithm in the SSZ spec.

**Actual behavior:** Hash tree root of an empty list fails to return a merkle root at all, and instead returns an empty byte array (Bytes.EMPTY/byte[0]).

### Additional Information
See https://github.com/ethereum/eth2.0-specs/blob/v0.8.1/specs/simple-serialize.md#merkleization

**Comment by schroedingerscode** [comment]
Fix is implemented in IndexedAttestation. The fix still needs to be applied in CompactCommittee, BeaconStateUtil, and EpochProcessorUtil. There are no other observed occurrences of a List of Basic types as of v0.8.1.

**Comment by jrhea** [comment]
ok let's add this to Sprint 2

**Comment by ajsutton** [comment]
All the SSZ that matters now appears to be serialised correctly.  Suspect this was fixed quite a while back.
