### ISSUE TITLE
[beacon api] check if we need to fix anything in our definitions

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8223]
https://github.com/ethereum/beacon-APIs/pull/444

I haven't read this closely, but if someone can take a look... its probably worth testing the query parameter.

**Comment by gfukushima** [comment]
Just double checking before executing on something that we don't want. 
The PR mentioned above changes the type of the field `skip_randao_verification`. 
In Teku we only have `skip_randao_verification` in the BlockV3. My understanding is that the type change is all we want to do in Teku. 
We don't want to add this field to blinded_block, correct? 
Same applies for BlockV2  which seems to be deprecated.
