### ISSUE TITLE
Release new Grafana dashboard version

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#8253]
Now that we have removed the deprecation warnings #8091 we should release a new version of the monitoring dashboards.

We might need to wait until they Grafana fix the issue with versions. Or just release it anyway. Need to decide.

**Comment by gfukushima** [comment]
I've just found this issue, just letting you know that `Teku - Detailed` has been published as of 8th of June.

**Comment by lucassaldanha** [comment]
We need to decide what dashboards we want to support from now on.
