### ISSUE TITLE
Incorrect error message on voluntary exit command failure

### ISSUE THREAD

**Issue by courtneyeh** [Consensys-Incorporated/teku#8292]
### Description
It is common for the voluntary exit command to show an incorrect error message on failure when the error is related to not being able to connect to a URL.

The error message returned is the following:
```
Failed to connect to beacon node. Check that http://127.0.0.1:5051 is available.
```

### Reproduce
In the following cases, the error message on failure is the same as above. This is not expected for these cases.
1. Fail to load `validators-external-signer-public-keys` from URL
2. Fail to load keys from URL when `validators-external-signer-url` is unreachable and the `validators-external-signer-public-keys` option has been used with `external-signer`.

Other scenarios would have to be fully investigated to identify the issue.

Found in testing for #8289

**Comment by rolfyone** [comment]
fairly happy with error messages now that i've proven the behaviour in testing.
