### ISSUE TITLE
create and test `fromHexString` for `SszBitList`

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8505]
As a developer using the `SszBitList` class, 
it would be convenient to have `fromHexString` and `fromBytes` defined,
So that I can create an `SszBitList` from a hex or bytes payload.

Basically, `fromBytes` would do the heavy lifting, `fromHexString` would convert to bytes then call `fromBytes`.

I'd suggest following how `ofBits` is done basically.

The implementation will likely be in `SszBitListImpl` where `ofBits` is defined currently. and would be on the `SszBitListSchema`

Testing will be in SszBitListTest.

**Comment by oceans404** [comment]
hey @rolfyone! you can assign this to me

**Comment by oceans404** [comment]
Solved by PR #8611

**Comment by rolfyone** [comment]
closing - fixed.
