### ISSUE TITLE
create and test `fromHexString` for `SszBitVector`

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8506]
As a developer using the `SszBitVector` class, 
it would be convenient to have `fromHexString` and `fromBytes` defined,
So that I can create an `SszBitVector` from a hex or bytes payload.

Basically, `fromBytes` would do the heavy lifting, `fromHexString` would convert to bytes then call `fromBytes`.

I'd suggest following how `ofBits` is done basically.

The implementation will likely be in `SszBitVectorImpl` where `ofBits` is defined currently. and would be on the `SszBitVectorSchema`

Testing will be in SszBitVectorTest.

**Comment by gconnect** [comment]
Hello @rolfyone please assign this issue to me
