### ISSUE TITLE
Teku:Nethermind on gnosis: Nethermind returned twice the block for the same slot

### ISSUE THREAD

**Issue by galaxy-mario** [Consensys-Incorporated/teku#8530]
**Description**
Nethermind returned a block from the same slot twice, with a 3s delay. Teku clearly knows/shows in logs the block is empty.

We are not sure if this is an issue on Teku or Nethermind, we'd like to understand what happened and whether there is anything that can be done to improve it.

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
- Debian 12
- eth-docker
- Nethermind/v1.28.0+9c4816c2/linux-x64/dotnet8.0.8
- teku/v24.8.0/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-21

**Additional context**
This is on the gnosis chain, where the time to get a block in is 1.66s max.

**Logs**
https://gnosischa.in/slot/17052573

```
consensus-1  | 2024-08-21 16:03:20.413 INFO  - Calling local execution layer to start block production (block slot: 17052573)
consensus-1  | 2024-08-21 16:03:22.000 INFO  - ESC[37mSlot Event  *** Slot: 17052572, Block: 16ae7cca982b24cb7276ef61ec80084b6597f20eba9df4251be0df4638ef75a3, Justified: 1065784, Finalized: 1065783, Peers: 110ESC[0m
consensus-1  | 2024-08-21 16:03:27.001 INFO  - ESC[37mSlot Event  *** Slot: 17052573, Block:                                                        ... empty, Justified: 1065784, Finalized: 1065783, Peers: 110ESC[0m
consensus-1  | 2024-08-21 16:03:32.000 INFO  - ESC[37mSlot Event  *** Slot: 17052574, Block: fbc06d932b621859b8e63a60d20729d7882b4da8f3c0c4fe3b2c9e660aad27d8, Justified: 1065784, Finalized: 1065783, Peers: 110ESC[0m
consensus-1  | 2024-08-21 16:03:37.001 INFO  - ESC[37mSlot Event  *** Slot: 17052575, Block: 9d452f290922d5e747fb3a3f5a16bc49629f12192997d1b249821ee2f039c3ee, Justified: 1065784, Finalized: 1065783, Peers: 110ESC[0m
consensus-1  | 2024-08-21 16:03:40.001 INFO  - ESC[32mEpoch Event *** Epoch: 1065786, Justified checkpoint: 1065785, Finalized checkpoint: 1065784, Finalized root: 9a5c72a4f4c33f66206af288b3e9c281b0d8fa23b790b81aeadc6325a6a61597ESC[0m
consensus-1  | 2024-08-21 16:03:40.090 INFO  - Attestation performance: epoch 1065784, expected 15364, produced 15327, included 15326 (100%), distance 1 / 1.00 / 4, correct target 15327 (100%), correct head 15297 (100%)
consensus-1  | 2024-08-21 16:03:40.090 INFO  - Block performance: epoch 1065785, expected 1, produced 1, included 1 (100%)
consensus-1  | 2024-08-21 16:03:40.090 INFO  - Sync committee performance: epoch 1065785, expected 448, produced 352, correct 352, included 334 (95%)
```

```
execution-1  | 21 Aug 16:03:20 | Produced block 35596759 (0xd8ced6...15e666), diff: 0, tx count: 1 
execution-1  | 21 Aug 16:03:20 | Improved post-merge block 35596759 (0xd8ced6...15e666), diff: 0, tx count: 1 
execution-1  | 21 Aug 16:03:23 | Produced block 35596759 (0x823107...0f014b), diff: 0, tx count: 7 
execution-1  | 21 Aug 16:03:23 | Improved post-merge block 35596759 (0x823107...0f014b), diff: 0, tx count: 7
```

**Comment by tbenr** [comment]
Hi, thanks for reaching us.
Checking the logs it seems a pretty standard behaviour on the EL side: when CL asks for a block production (execution payload) the EL immediately prepare a block and then starts improving it over time (`Improved post-merge block ..`) several times before CL asks for the final one when it's time to propose.

What happened instead is that it seems that the block production has been slow (or failed for some reason but there is no evidence in logs) and you missed it. 

looking at the history of your validator it seems to perform well overall. Are you experiencing similar issues often?

**Comment by galaxy-mario** [comment]
Hi @tbenr, thanks for your feedback!

The validator performs well, but we did miss that block and we're not clear why. Should we probably enable DEBUG logs everywhere to get a better idea?

Another couple of questions would be:

- Why does Teku think the block was included when it clearly wasn't?
- Is Teku using the same timing in Gnosis as in Ethereum? Consider that gnosis timing is considerably shorter

**Comment by tbenr** [comment]
> Why does Teku think the block was included when it clearly wasn't?

that's a good question, I'll log an issue so we can take a look when we find the time.

> Is Teku using the same timing in Gnosis as in Ethereum? Consider that gnosis timing is considerably shorter

no, Gnosis has a 5s slot time and it wouldn't be possible to follow the chain using Ethereum timings.

**Comment by tbenr** [comment]
Going to close this. Opened https://github.com/Consensys/teku/issues/8552

**Comment by gfukushima** [comment]
Hi @galaxy-mario would you be able to change this class to use debug log so if it happens again we can track the state and blocks you had as you canonical? 
After starting teku you can run the following command on a terminal to change the log level for a specific class.
```
curl --location --request PUT 'http://127.0.0.1:5051/teku/v1/admin/log_level' \
--header 'Content-Type: application/json' \
--data '{
  "level": "DEBUG",
  "log_filter": [
    "tech.pegasys.teku.validator.coordinator.performance.DefaultPerformanceTracker"
  ]
}'
```

Note: Additional logs have been introduced in 24.10.0. 
127.0.0.1 refers to the localhost ip and 5051 is the default port of the REST API. You might need to change those according to the way your clients is setup
