### ISSUE TITLE
Add Native Support for Ephemery Testnet and Config Files

### ISSUE THREAD

**Issue by gconnect** [Consensys-Incorporated/teku#8537]
### Description
There is currently no native support for [Ephemery](https://ephemery.dev/) using the --network=ephemery flag.
We also need to include the Ephemery config to connect to the Ephemery Testnet easily.

For context Ephemery Testnet was initiated by @taxmeifyoucan. Ephemery testnet is a network that rolls back to the genesis after a set period of time. It is focused on short term and heavy testing usecases. This is also to avoid problems like insufficient testnet funds, inactive validators, state bloat, and similar issues faced by long-running testnets.

**Expected behavior:** [What you expect to happen]
We want to be able to connect to Ephemery like other supported networks like this
```bash
teku \
    --network=ephemery                             \
    --ee-endpoint=http://localhost:8551          \
    --ee-jwt-secret-file=<path to jwtsecret.hex> \
    --metrics-enabled=true                       \
    --rest-api-enabled=true                      \
    --checkpoint-sync-url=<checkpoint sync URL>
```

**Actual behavior:** [What actually happens]
Currently to connect to Ephmery network it has to be done manually.

```bash
teku \
--genesis-state=ephemery/besu.json  \
--ee-endpoint=http://localhost:8551/  \
--ee-jwt-secret-file=<path to jwtsecret.hex> \
--metrics-enabled=true \
--rest-api-enabled=true  \
--p2p-discovery-bootnodes=$BOOTNODE_ENR_LIST   \
--checkpoint-sync-url=<checkpoint sync URL>

```
**Frequency:** [How regularly does it occur?]
Whenever, we need to start an Ephemery Testnet

### Versions (Add all that apply)
* Software version: [`teku --version` or look for log lines starting with `Teku version:`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

As part of my contribution for my Ethereum Protocol Fellowship (EPF) project, I would like this issue to be assigned to me.

**Comment by taxmeifyoucan** [comment]
For the context, ephemery is an implementation of [eip-6916](https://eips.ethereum.org/EIPS/eip-6916). The specification for CL client support is defined there.
