### ISSUE TITLE
Do not create deserializable type definition at each request

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#8538]
Some type def client requests create the required deserializable type definition at each request (Examples: `ProduceBlockRequest` and `SendAggregateAndProofsRequest`). 
This could be avoided by creating the deserializable type definition in advance and getting the correct one based on the request.

**Comment by rolfyone** [comment]
This is an advantage of the old model where we didnt create an object per request. Ideally we can make use of `SchemaDefinitionCache`, or use the schema definitions from the request objects themselves... I'll have a quick look at the two listed.
