### ISSUE TITLE
Erroneous warning in logs

### ISSUE THREAD

**Issue by mcdee** [Consensys-Incorporated/teku#8562]
### Description

teku is generating warnings when blocks are requested via the v3 endpoint that appear to be erroneous.

### Steps to Reproduce (Bug)

Request a block via the v3 endpoint https://ethereum.github.io/beacon-APIs/#/Validator/produceBlockV3

Check the logs, e.g.:

```
2024-09-04 11:45:13.001 INFO  - Creating unsigned block for slot 2462326
2024-09-04 11:45:13.850 WARN  - Builder endpoint is available but a non-blinded block has been requested
```

It appears that this warning will always be generated for the v3 endpoint as by the specification of this call teku will always fetch both blinded and non-blinded payloads to compare values.  The warning should not be generated for a call to the v3 endpoint.

### Versions (Add all that apply)

```
teku --version
teku/v24.8.0/linux-x86_64/-ubuntu-openjdk64bitservervm-java-21
```

**Comment by rolfyone** [comment]
Hey - thanks - seems like a quick win. I'll clean that up.
