### ISSUE TITLE
Standardise the Engine Json RPC error codes

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#8671]
The json RPC error codes are standard: [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification#error_object)
It would be better to handle the errors in the `Web3JClient::doRequest` based on their codes and avoid logging the whole stack trace.
Example: error code `-32601` -> 	Method not found

**Comment by Malaydewangan18** [comment]
Hey @mehdi-aouadi, is this issue still open? 
Can I start working on it? 
Thanks!

**Comment by Malaydewangan09** [comment]
Hey @mehdi-aouadi , is this issue still open? 
Can I start working on it? 
Thanks!

**Comment by mehdi-aouadi** [comment]
Hi @Malaydewangan09, yes it's open. Feel free to raise a PR and don't hesitate to reach out to our [discord contributors channel](https://discord.com/channels/697535391594446898/1050616638497640548) if you have any question

**Comment by Malaydewangan09** [comment]
@mehdi-aouadi 
Thanks!
