### ISSUE TITLE
Investigate failures with EL withdrawal requests sanity blocks ref tests

### ISSUE THREAD

**Issue by lucassaldanha** [Consensys-Incorporated/teku#8680]
The following tests are failing on reference tests `v1.5.0-alpha.7`"
- ~~sanity/blocks - basic_el_withdrawal_request~~
- ~~sanity/blocks - cl_exit_and_el_withdrawal_requests_in_same_block~~
- sanity/blocks - basic_btec_and_el_withdrawal_request_in_same_block

They are being ignored on `SanityBlocksTestExecutor`

**Comment by jtraglia** [comment]
Just to double check, are you sure that `basic_btec_and_el_withdrawal_request_in_same_block` was failing?

That would be unexpected. We merged a fix for the other two though.

**Comment by lucassaldanha** [comment]
> Just to double check, are you sure that `basic_btec_and_el_withdrawal_request_in_same_block` was failing?

It was, but I haven't looked at the reason yet. It could be a problem with our code :)
