### ISSUE TITLE
Add a proposer config file to our release testing nodes

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#8688]
We'd want at least one of our nodes to be using a proposer config file in order to make sure that it loads it correctly and is working as expected when a new teku version is released.

**Comment by tbenr** [comment]
Fixed here: https://github.com/Consensys/protocols-azure-inventories/commit/9c8c3ac96aee13b99835f240165445658261f0ff

**Comment by iceton** [comment]
@tbenr Is this related to the error I'm getting with 24.10.0?
```
teku: Failed to load proposer config from 'file:/.../proposer_config.json' - Cannot find a (Map) Key deserializer for type [simple type, class org.apache.tuweni.bytes.Bytes48] at line: 1, column: 1
```
