### ISSUE TITLE
jemalloc library not found

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#8705]
### Description

On starting my Teku it reports

```
2024-10-10 15:01:32.267 INFO  - jemalloc library not found.
```

However, `jemalloc` is installed (and Besu is using it):

```
$ apt list 'libjemalloc-dev'
Listing... Done
libjemalloc-dev/jammy,now 5.2.1-4ubuntu1 amd64 [installed]
```

I really don't remember whether this matters or not. Just reporting in case it does.

### Versions (Add all that apply)
* Software version: `teku/v24.10.1/linux-x86_64/-ubuntu-openjdk64bitservervm-java-21`
* Java version: [`java -version`]

```
openjdk version "21.0.4" 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

* OS Name & Version: [`cat /etc/*release`]

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by lucassaldanha** [comment]
Thanks for the report!

Looks like this was [recently introduced](https://github.com/Consensys/teku/commit/91a17a59ed6dc60331cf37cf97ae6541e0dec6ee) as part of updates related to RocksDB. I'll take a guess and say that it should not affect normal operation, and there is nothing to worry about. We'll take a look into it!

**Comment by gfukushima** [comment]
It doesn't affect operation at all. It is just an informative log. I'll have a look to see why it isn't detecting its presence.
