### ISSUE TITLE
Update Attestation APIs with SingleAttestation

### ISSUE THREAD

**Issue by mehdi-aouadi** [Consensys-Incorporated/teku#8768]
Update the Attestation APIs to handle the new SingleAttestation
Spec PR: https://github.com/ethereum/beacon-APIs/pull/472

**Comment by tbenr** [comment]
It is not sure we will go in that direction. Depends by how much we want to minimize the impacts when introducing `SingleAttestation`.

**Comment by mehdi-aouadi** [comment]
> It is not sure we will go in that direction. Depends by how much we want to minimize the impacts when introducing `SingleAttestation`.

Yes, agree. Just logged this issue to keep track and not forget about it in case it gets merged

**Comment by rolfyone** [comment]
i believe this is done now

**Comment by tbenr** [comment]
fixed via #8893 and #8873
