### ISSUE TITLE
Remove delay when looking up blobs via local EL

### ISSUE THREAD

**Issue by tbenr** [Consensys-Incorporated/teku#8796]
Once there is enough adoption of `engine_getBlobs` we can remove the delay and do the local lookup of the missing blobs immediately once we receive the block.
RPC delay should remain unchanged.

**Comment by samr874** [comment]
Any update about this issue?? who is taking over @tbenr ?

**Comment by tbenr** [comment]
some informations:
1. we should not try to lookup the block via RPC too fast when we first see a blob sidecar. The process when we receive a blob first could be
  - store it
  - wait (maybe with the same "elastic" logic but with different params)
  - fetch block RPC if not received yet.
2. I think we can remove the attempt to recover blobs when we still don't have a block. Currently we try to download all max blobs (6). In Electra it will be even 9. I think we could be less aggressive now that we have local EL option. 
3. the process when we receive a block could be
  - immediately lookup for blobs via local EL
  - (not sure we should add a delay here, currently we don't)
  - broadcast reconstructed blobs
  - (delay here?)
  - lookup still missing blobs via RPC
