### ISSUE TITLE
logging noise with local blob fetch failure

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#8827]
From customer:
---
Getting these errors in teku beaconchain service when syncing along with  `Geth/v1.14.11-stable-f3c696fa`. 

Teku version: `teku/v24.10.3/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-21`

error1 (beaconchain):
`2024-11-06 14:55:50.642 WARN  - Local EL blobs lookup failed: InvalidRemoteResponseException: Invalid remote response from the execution client: JSON-RPC error: Method not found (-32601): the method engine_getBlobsV1 does not exist/is not available`

error2 (beaconchain):
`2024-11-06 14:59:13.182 ERROR - An error occurred while attempting to fetch blobs via local EL`

geth:
```
 WARN [11-06|14:59:55.675] Unexpected bytecode packet               peer=6b36f791 reqid=8,460,901,486,704,953,336
WARN [11-06|15:00:38.569] Served engine_getBlobsV1                 conn=xxxxx:xxx reqid=1393 duration="11.828µs" err="the method engine_getBlobsV1 does not exist/is not available"
```

from me:
---
It looks like this isn't rate limited logging, and I wasn't able to find an `enabled` flag, so we may need to think about the logging noise in this... If this is every block (unconfirmed) the logs would be hard to read...

**Comment by rolfyone** [comment]
actually it looks like #8826 may resolve this issue

**Comment by tbenr** [comment]
yes i fixed yesterday cose i'm running the same setup and I noticed this two types of error logs. I would not bother with suppression cose you can get a sequence of those only during startup. During normal operation you'll get one of them every now and then. Moreover geth will include the api support in the upcoming release

**Comment by tbenr** [comment]
fixed via https://github.com/Consensys/teku/pull/8826
