### ISSUE TITLE
Downloading historical blocks?

### ISSUE THREAD

**Issue by totoCZ** [Consensys-Incorporated/teku#8950]
![Screenshot 2024-12-21 at 04 17 39](https://github.com/user-attachments/assets/311bba76-a1cc-4d7e-9331-88bcc595ec2f)
The way I understand this minimal config should not be downloading any historical blocks?
24.12.1

Dec 20 19:50:25 systemd-teku[16980]: 2024-12-20 19:50:25.310 INFO  - Begin historical sync of blocks from slot 9843828 to slot 9601375
Dec 20 19:48:48 systemd-teku[16980]: 2024-12-20 19:48:48.697 INFO  - Configuration | Network: mainnet, Storage Mode: MINIMAL

**Comment by totoCZ** [comment]
https://github.com/grandinetech/grandine/issues/27

“Ethereum consensus nodes are required to keep a minimum of 5 months of historical block data ensuring the health of the network.”

I also think keeping 1 block is too little and the full chain too much.

**Comment by totoCZ** [comment]
It stopped at this block
https://beaconcha.in/block/9602749
I don't really undestand it :D

**Comment by rolfyone** [comment]
minimal needs to keep about 5 months of history of blocks to follow the honest validator spec...

from initial state, we'll download to head (about 128 blocks ish) then once we're in sync, a service will start that downloads historical blocks... It can take a while to get started, typically within a couple of days you should have all the history you need. It's visible in metrics...

**Comment by rolfyone** [comment]
Im fairly sure this is answered completely, will close but feel free to message in our discord or here if you need further explanation.
