### ISSUE TITLE
Creating a license notice and giving copyright credit

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#938]
### Description
As an implementer, I want Artemis to have a license notice file that indicates the copyright notice of software used, especially ones with EPL and EDL licenses, so that Artemis can legally use these software in a safe manner. 

An example on how to include a copyright notice in our license notice file:

> Artemis contains mapdb, licensed under apache 2 (link to their license file)
> Artemis contains Eclipse Collections, licensed under EDL (link to their license file)
> but Artemis is licensed under Apache 2.0
> and have our apache 2.0 license

**Comment by arash009** [comment]
Should contain 2 license files:

- The Apache 2.0 license under which Teku is being developed and distributed
- A license-dependency file that lists out each dependency and their license information and link to the relevant license.
