### ISSUE TITLE
Start from deposits don't set the actual Store in ChainStorageClient

### ISSUE THREAD

**Issue by cemozerr** [Consensys-Incorporated/teku#983]
### Description
As an implementer, when Artemis is started using any (PoW) deposit mode, I want to set the `ChainStorageClient`'s `Store` variable to the `Store` object generated using a `BeaconState` that was generated using the deposits, so that the genesis state reflects the actual deposits and genesis time rather than the ones that were mocked in `BeaconChainController`'s `initStorage()`.

**Comment by ajsutton** [comment]
Fixed.
